#!/usr/bin/env python3
"""Generate fortran/test/ecp_num_check.F90 from PySCF's compiled ECP routines.

    python3 fortran/test/gen_ecp_num_check.py

The ECP modules are translated from PySCF's pyscf/lib/gto/nr_ecp.c rather than
from libcint, which has no ECP code.  So the reference for them is PySCF, and
the sharpest form of that reference is PySCF's own compiled functions rather
than numbers copied out of a paper: `libcgto` exports `ECPsph_ine` and
`ECPgauss_chebyshev`, and calling them through ctypes compares the translation
against the exact thing it was translated from.

Generated rather than hand-written for the same reason gen_catalogue_check.py
is: ninety-six reference values typed by hand is ninety-six chances to move a
digit, and a wrong reference that the port happens to match is worse than no
test at all.

The output is committed, so a build needs neither Python nor PySCF.  Re-run
this only when the sampled points change.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

# Straddling both branch boundaries in ECPsph_ine (1e-7 and 16) from each
# side.  A test that sampled only the interiors would pass through a `<`
# written for a `<=`, which is the most likely way to mistranslate this.
ZS = [1e-9, 5e-8, 1e-7, 1e-6, 0.25, 1.0, 4.0, 15.999, 16.0, 16.001, 40.0, 300.0]
ORDER = 7

# The three grid sizes an ECP evaluation actually asks for: LEVEL0 = 5 gives
# 31 points, and the refinement doubles to LEVEL_MAX = 11 at 2047.
NS = [31, 127, 2047]


def fortran_real(x):
    """A double literal that round-trips exactly."""
    return "%.17e_dp" % x


def wrap(values, indent, per_line=3):
    out, line = [], []
    for i, v in enumerate(values):
        line.append(v)
        if len(line) == per_line or i == len(values) - 1:
            out.append(indent + ", ".join(line))
            line = []
    return ", &\n".join(out)


def main():
    import ctypes
    import numpy as np
    from pyscf import lib

    c = lib.load_library("libcgto")

    ine = []
    for z in ZS:
        out = np.zeros(ORDER + 1)
        c.ECPsph_ine(out.ctypes.data_as(ctypes.c_void_p),
                     ctypes.c_int(ORDER), ctypes.c_double(z))
        ine.append(out.copy())

    # For the grid, comparing all 2047 points would bloat the source for no
    # extra coverage: the first, middle and last pin the map's two ends and
    # its interior, and the weight sum pins every point at once.
    grid = []
    for n in NS:
        rs = np.zeros(n)
        ws = np.zeros(n)
        c.ECPgauss_chebyshev(rs.ctypes.data_as(ctypes.c_void_p),
                             ws.ctypes.data_as(ctypes.c_void_p), ctypes.c_int(n))
        grid.append((n, rs[0], ws[0], rs[n // 2], ws[n // 2],
                     rs[n - 1], ws[n - 1], ws.sum()))

    ine_flat = [fortran_real(v) for row in ine for v in row]
    zs_lit = [fortran_real(z) for z in ZS]
    ns_lit = [str(n) for n in NS]
    grid_flat = [fortran_real(v) for g in grid for v in g[1:]]

    src = TEMPLATE % {
        "nz": len(ZS),
        "order": ORDER,
        "ngrid": len(NS),
        "zs": wrap(zs_lit, " " * 6),
        "ine": wrap(ine_flat, " " * 6),
        "ns": ", ".join(ns_lit),
        "grid": wrap(grid_flat, " " * 6),
        "pyscf_version": __import__("pyscf").__version__,
    }
    path = os.path.join(HERE, "ecp_num_check.F90")
    with open(path, "w") as fh:
        fh.write(src)
    print("%d Bessel rows, %d grids -> ecp_num_check.F90" % (len(ZS), len(NS)))


TEMPLATE = '''!
! The ECP numerical primitives against PySCF's own compiled routines.
!
! GENERATED by fortran/test/gen_ecp_num_check.py -- do not edit.
! Reference values from PySCF %(pyscf_version)s, libcgto.
!
! The reference here is PySCF and not libcint, because libcint has no ECP
! code: cint_ecp_num is translated from pyscf/lib/gto/nr_ecp.c, so the thing
! it has to agree with is that file as compiled.  These values came out of
! `ECPsph_ine` and `ECPgauss_chebyshev` through ctypes, which makes this a
! comparison against the source of the translation rather than against a
! second implementation of the same mathematics.  A disagreement is therefore
! a porting mistake, which is the only kind a translation can make.
!
! The bar is bit-identical and it is reachable: both routines are closed
! expressions in double precision, with nothing a compiler may reassociate.
! The Bessel series terminates on `next == s`, which is exact, so even the
! iteration count carries across.
!
! The z values straddle both of the C's branch boundaries, 1e-7 and 16, from
! each side. Sampling only the interiors would pass a `<` written for a `<=`.
!
program ecp_num_check
   use cint_const, only: dp
   use cint_ecp_num, only: ecp_sph_ine, ecp_gauss_chebyshev
   implicit none

   integer, parameter :: ORDER = %(order)d
   integer, parameter :: NZ = %(nz)d
   integer, parameter :: NGRID = %(ngrid)d

   real(dp), parameter :: ZS(NZ) = [ &
%(zs)s]

   real(dp), parameter :: INE_REF(0:ORDER, NZ) = reshape([ &
%(ine)s], [ORDER + 1, NZ])

   integer, parameter :: NS(NGRID) = [%(ns)s]

   ! Per grid: r(1), w(1), r(mid), w(mid), r(n), w(n), sum(w)
   real(dp), parameter :: GRID_REF(7, NGRID) = reshape([ &
%(grid)s], [7, NGRID])

   real(dp), allocatable :: rs(:), ws(:)
   real(dp) :: out(0:ORDER)
   integer :: iz, ig, l, n, bad

   bad = 0

   do iz = 1, NZ
      call ecp_sph_ine(out, ORDER, ZS(iz))
      do l = 0, ORDER
         if (out(l) /= INE_REF(l, iz)) then
            write (*, '(a,i0,a,es24.17,a,i0)') &
               "FAIL sph_ine  z#", iz, " z=", ZS(iz), " l=", l
            write (*, '(a,es26.17,a,es26.17)') &
               "      got ", out(l), "   want ", INE_REF(l, iz)
            bad = bad + 1
         end if
      end do
   end do

   do ig = 1, NGRID
      n = NS(ig)
      allocate (rs(0:n - 1), ws(0:n - 1))
      call ecp_gauss_chebyshev(rs, ws, n)
      call same("r(1)   ", rs(0), GRID_REF(1, ig), n, bad)
      call same("w(1)   ", ws(0), GRID_REF(2, ig), n, bad)
      call same("r(mid) ", rs(n/2), GRID_REF(3, ig), n, bad)
      call same("w(mid) ", ws(n/2), GRID_REF(4, ig), n, bad)
      call same("r(n)   ", rs(n - 1), GRID_REF(5, ig), n, bad)
      call same("w(n)   ", ws(n - 1), GRID_REF(6, ig), n, bad)
      ! The sum pins every point at once, where the three samples above pin
      ! only the ends and the middle.
      call same("sum(w) ", sum(ws), GRID_REF(7, ig), n, bad)
      deallocate (rs, ws)
   end do

   if (bad == 0) then
      write (*, '(a,i0,a,i0,a)') "ecp_num_check: OK -- ", &
         NZ*(ORDER + 1), " Bessel values and ", NGRID, " grids, bit-identical"
   else
      write (*, '(a,i0,a)') "ecp_num_check: ", bad, " mismatch(es)"
      stop 1
   end if

contains

   subroutine same(label, got, want, n, bad)
      character(len=*), intent(in) :: label
      real(dp), intent(in) :: got, want
      integer, intent(in) :: n
      integer, intent(inout) :: bad
      ! The weight sum is a sum of n doubles, so it is the one quantity here
      ! a compiler may legally reassociate; everything else is compared exact.
      if (got /= want) then
         if (label == "sum(w) " .and. abs(got - want) <= 1.0e-13_dp*abs(want)) return
         write (*, '(a,a,a,i0)') "FAIL gauss_chebyshev ", label, " n=", n
         write (*, '(a,es26.17,a,es26.17)') "      got ", got, "   want ", want
         bad = bad + 1
      end if
   end subroutine same

end program ecp_num_check
'''


if __name__ == "__main__":
    sys.exit(main())
