! GENERATED by scripts/hgp -- do not edit.
! sssd: vrr=55 carried=40x2 hrr=93 in 1 block(s) comps=18
module hgp_grad_sssd_m
   use cint_const, only: dp
   use cint_rotaxis_boys, only: boys
   implicit none
   private
   public :: hgp_grad_sssd
   real(dp), parameter :: PI = 3.14159265358979323846_dp
   real(dp), parameter :: TWO_PI_52 = 2.0_dp*PI**2*sqrt(PI)
contains
   ! d/dA (ss|sd)  sssd: vrr=55 carried=40x2 hrr=93 in 1 block(s) comps=18
   subroutine hgp_grad_sssd(nbra, ncb, bp, kab, nket, nck, kp, kcd, ab, cd, cutoff, res, any)
      integer,  intent(in)  :: nbra, ncb, nket, nck
      real(dp), intent(in)  :: bp(11, nbra), kab(1*ncb, nbra)
      real(dp), intent(in)  :: kp(11, nket), kcd(1*nck, nket)
      real(dp), intent(in)  :: ab(3), cd(3), cutoff
      real(dp), intent(out) :: res(18, ncb*nck)
      logical,  intent(out) :: any
      ! TWO contracted sets: plain, and weighted by 2a.  d/dA
      ! raises the bra with the bra exponent, which varies per
      ! primitive while the transfers run once per contracted
      ! quartet -- so the exponent is folded in here, the last
      ! stage that still has it.
      real(dp) :: c(40, 2, 1*ncb, 1*nck)
      real(dp) :: cb(40, 2, 1*ncb)
      real(dp) :: t(55), tv(40), f(0:3), b(0:3)
      real(dp) :: h(93)
      real(dp) :: p, q, pq, rho, oo2p, oo2q, oo2pq, rp, rq, tt, w, eab, ecd, ea
      real(dp) :: PA0, PA1, PA2, QC0, QC1, QC2, WP0, WP1, WP2, WQ0, WQ1, WQ2
      real(dp) :: PQ0, PQ1, PQ2, AB0, AB1, AB2, CD0, CD1, CD2, wq_, wp_
      logical  :: hit
      integer  :: kq, bq, bc, kc, cc, ck, n, col

      AB0 = ab(1); AB1 = ab(2); AB2 = ab(3)
      CD0 = cd(1); CD1 = cd(2); CD2 = cd(3)
      any = .false.
      c = 0.0_dp
      do kq = 1, nket
         q = kp(1,kq); oo2q = kp(2,kq)
         QC0 = kp(3,kq); QC1 = kp(4,kq); QC2 = kp(5,kq)
         ecd = kp(10,kq)
         cb = 0.0_dp
         hit = .false.
         do bq = 1, nbra
            eab = bp(10,bq)
            if (eab + ecd > cutoff) cycle
            hit = .true.
            p = bp(1,bq); oo2p = bp(2,bq); ea = bp(11,bq)
            PA0 = bp(3,bq); PA1 = bp(4,bq); PA2 = bp(5,bq)
            PQ0 = bp(6,bq) - kp(6,kq)
            PQ1 = bp(7,bq) - kp(7,kq)
            PQ2 = bp(8,bq) - kp(8,kq)
            pq = p + q
            rho = p*q/pq
            oo2pq = 0.5_dp/pq
            rp = rho/p; rq = rho/q
            wp_ = -q/pq; wq_ = p/pq
            WP0 = wp_*PQ0; WP1 = wp_*PQ1; WP2 = wp_*PQ2
            WQ0 = wq_*PQ0; WQ1 = wq_*PQ1; WQ2 = wq_*PQ2
            tt = rho*(PQ0*PQ0 + PQ1*PQ1 + PQ2*PQ2)
            call boys(f, tt, 3)
            w = TWO_PI_52*bp(9,bq)*kp(9,kq)/sqrt(pq)
            do n = 0, 3
               b(n) = w*f(n)
            end do
            call vrr_001()
            tv(1) = t(1)
            tv(2) = t(3)
            tv(3) = t(4)
            tv(4) = t(5)
            tv(5) = t(8)
            tv(6) = t(10)
            tv(7) = t(12)
            tv(8) = t(13)
            tv(9) = t(14)
            tv(10) = t(15)
            tv(11) = t(16)
            tv(12) = t(17)
            tv(13) = t(18)
            tv(14) = t(19)
            tv(15) = t(20)
            tv(16) = t(21)
            tv(17) = t(22)
            tv(18) = t(23)
            tv(19) = t(24)
            tv(20) = t(25)
            tv(21) = t(26)
            tv(22) = t(27)
            tv(23) = t(31)
            tv(24) = t(34)
            tv(25) = t(37)
            tv(26) = t(39)
            tv(27) = t(41)
            tv(28) = t(43)
            tv(29) = t(44)
            tv(30) = t(45)
            tv(31) = t(46)
            tv(32) = t(47)
            tv(33) = t(48)
            tv(34) = t(49)
            tv(35) = t(50)
            tv(36) = t(51)
            tv(37) = t(52)
            tv(38) = t(53)
            tv(39) = t(54)
            tv(40) = t(55)
            do bc = 1, 1*ncb
               cb(1:40,1,bc) = cb(1:40,1,bc) + kab(bc,bq)*tv(1:40)
               cb(1:40,2,bc) = cb(1:40,2,bc) + (2.0_dp*ea)*kab(bc,bq)*tv(1:40)
            end do
         end do
         if (.not. hit) cycle
         any = .true.
         do kc = 1, 1*nck
            do bc = 1, 1*ncb
               c(1:40,1:2,bc,kc) = c(1:40,1:2,bc,kc) + kcd(kc,kq)*cb(1:40,1:2,bc)
            end do
         end do
      end do
      res = 0.0_dp
      if (.not. any) return
      do ck = 1, nck
         do cc = 1, ncb
            col = cc + ncb*(ck-1)
            bc = cc; kc = ck
            call hrr_002()
            res(1,col) = -h(7)
            res(2,col) = -h(13)
            res(3,col) = -h(19)
            res(4,col) = -h(23)
            res(5,col) = -h(27)
            res(6,col) = -h(31)
            res(7,col) = -h(38)
            res(8,col) = -h(44)
            res(9,col) = -h(50)
            res(10,col) = -h(54)
            res(11,col) = -h(58)
            res(12,col) = -h(62)
            res(13,col) = -h(69)
            res(14,col) = -h(75)
            res(15,col) = -h(81)
            res(16,col) = -h(85)
            res(17,col) = -h(89)
            res(18,col) = -h(93)
         end do
      end do

   contains
   subroutine vrr_001()
      t(1) = b(0)
      t(2) = b(1)
      t(3) = QC0*t(1) + WQ0*t(2)
      t(4) = QC1*t(1) + WQ1*t(2)
      t(5) = QC2*t(1) + WQ2*t(2)
      t(6) = b(2)
      t(7) = QC0*t(2) + WQ0*t(6)
      t(8) = QC0*t(3) + WQ0*t(7) + oo2q*t(1) - oo2q*rq*t(2)
      t(9) = QC1*t(2) + WQ1*t(6)
      t(10) = QC0*t(4) + WQ0*t(9)
      t(11) = QC2*t(2) + WQ2*t(6)
      t(12) = QC0*t(5) + WQ0*t(11)
      t(13) = QC1*t(4) + WQ1*t(9) + oo2q*t(1) - oo2q*rq*t(2)
      t(14) = QC1*t(5) + WQ1*t(11)
      t(15) = QC2*t(5) + WQ2*t(11) + oo2q*t(1) - oo2q*rq*t(2)
      t(16) = PA0*t(1) + WP0*t(2)
      t(17) = PA1*t(1) + WP1*t(2)
      t(18) = PA2*t(1) + WP2*t(2)
      t(19) = PA0*t(3) + WP0*t(7) + oo2pq*t(2)
      t(20) = PA0*t(4) + WP0*t(9)
      t(21) = PA0*t(5) + WP0*t(11)
      t(22) = PA1*t(3) + WP1*t(7)
      t(23) = PA1*t(4) + WP1*t(9) + oo2pq*t(2)
      t(24) = PA1*t(5) + WP1*t(11)
      t(25) = PA2*t(3) + WP2*t(7)
      t(26) = PA2*t(4) + WP2*t(9)
      t(27) = PA2*t(5) + WP2*t(11) + oo2pq*t(2)
      t(28) = b(3)
      t(29) = QC0*t(6) + WQ0*t(28)
      t(30) = QC0*t(7) + WQ0*t(29) + oo2q*t(2) - oo2q*rq*t(6)
      t(31) = PA0*t(8) + WP0*t(30) + 2.0_dp*oo2pq*t(7)
      t(32) = QC1*t(6) + WQ1*t(28)
      t(33) = QC0*t(9) + WQ0*t(32)
      t(34) = PA0*t(10) + WP0*t(33) + oo2pq*t(9)
      t(35) = QC2*t(6) + WQ2*t(28)
      t(36) = QC0*t(11) + WQ0*t(35)
      t(37) = PA0*t(12) + WP0*t(36) + oo2pq*t(11)
      t(38) = QC1*t(9) + WQ1*t(32) + oo2q*t(2) - oo2q*rq*t(6)
      t(39) = PA0*t(13) + WP0*t(38)
      t(40) = QC1*t(11) + WQ1*t(35)
      t(41) = PA0*t(14) + WP0*t(40)
      t(42) = QC2*t(11) + WQ2*t(35) + oo2q*t(2) - oo2q*rq*t(6)
      t(43) = PA0*t(15) + WP0*t(42)
      t(44) = PA1*t(8) + WP1*t(30)
      t(45) = PA1*t(10) + WP1*t(33) + oo2pq*t(7)
      t(46) = PA1*t(12) + WP1*t(36)
      t(47) = PA1*t(13) + WP1*t(38) + 2.0_dp*oo2pq*t(9)
      t(48) = PA1*t(14) + WP1*t(40) + oo2pq*t(11)
      t(49) = PA1*t(15) + WP1*t(42)
      t(50) = PA2*t(8) + WP2*t(30)
      t(51) = PA2*t(10) + WP2*t(33)
      t(52) = PA2*t(12) + WP2*t(36) + oo2pq*t(7)
      t(53) = PA2*t(13) + WP2*t(38)
      t(54) = PA2*t(14) + WP2*t(40) + oo2pq*t(9)
      t(55) = PA2*t(15) + WP2*t(42) + 2.0_dp*oo2pq*t(11)
   end subroutine vrr_001
   subroutine hrr_002()
      h(1) = c(23,2,bc,kc)
      h(2) = c(14,2,bc,kc)
      h(3) = h(1) + CD0*h(2)
      h(4) = c(11,2,bc,kc)
      h(5) = h(2) + CD0*h(4)
      h(6) = h(3) + CD0*h(5)
      h(7) = h(6)
      h(8) = c(24,2,bc,kc)
      h(9) = h(8) + CD1*h(2)
      h(10) = c(15,2,bc,kc)
      h(11) = h(10) + CD1*h(4)
      h(12) = h(9) + CD0*h(11)
      h(13) = h(12)
      h(14) = c(25,2,bc,kc)
      h(15) = h(14) + CD2*h(2)
      h(16) = c(16,2,bc,kc)
      h(17) = h(16) + CD2*h(4)
      h(18) = h(15) + CD0*h(17)
      h(19) = h(18)
      h(20) = c(26,2,bc,kc)
      h(21) = h(20) + CD1*h(10)
      h(22) = h(21) + CD1*h(11)
      h(23) = h(22)
      h(24) = c(27,2,bc,kc)
      h(25) = h(24) + CD2*h(10)
      h(26) = h(25) + CD1*h(17)
      h(27) = h(26)
      h(28) = c(28,2,bc,kc)
      h(29) = h(28) + CD2*h(16)
      h(30) = h(29) + CD2*h(17)
      h(31) = h(30)
      h(32) = c(29,2,bc,kc)
      h(33) = c(17,2,bc,kc)
      h(34) = h(32) + CD0*h(33)
      h(35) = c(12,2,bc,kc)
      h(36) = h(33) + CD0*h(35)
      h(37) = h(34) + CD0*h(36)
      h(38) = h(37)
      h(39) = c(30,2,bc,kc)
      h(40) = h(39) + CD1*h(33)
      h(41) = c(18,2,bc,kc)
      h(42) = h(41) + CD1*h(35)
      h(43) = h(40) + CD0*h(42)
      h(44) = h(43)
      h(45) = c(31,2,bc,kc)
      h(46) = h(45) + CD2*h(33)
      h(47) = c(19,2,bc,kc)
      h(48) = h(47) + CD2*h(35)
      h(49) = h(46) + CD0*h(48)
      h(50) = h(49)
      h(51) = c(32,2,bc,kc)
      h(52) = h(51) + CD1*h(41)
      h(53) = h(52) + CD1*h(42)
      h(54) = h(53)
      h(55) = c(33,2,bc,kc)
      h(56) = h(55) + CD2*h(41)
      h(57) = h(56) + CD1*h(48)
      h(58) = h(57)
      h(59) = c(34,2,bc,kc)
      h(60) = h(59) + CD2*h(47)
      h(61) = h(60) + CD2*h(48)
      h(62) = h(61)
      h(63) = c(35,2,bc,kc)
      h(64) = c(20,2,bc,kc)
      h(65) = h(63) + CD0*h(64)
      h(66) = c(13,2,bc,kc)
      h(67) = h(64) + CD0*h(66)
      h(68) = h(65) + CD0*h(67)
      h(69) = h(68)
      h(70) = c(36,2,bc,kc)
      h(71) = h(70) + CD1*h(64)
      h(72) = c(21,2,bc,kc)
      h(73) = h(72) + CD1*h(66)
      h(74) = h(71) + CD0*h(73)
      h(75) = h(74)
      h(76) = c(37,2,bc,kc)
      h(77) = h(76) + CD2*h(64)
      h(78) = c(22,2,bc,kc)
      h(79) = h(78) + CD2*h(66)
      h(80) = h(77) + CD0*h(79)
      h(81) = h(80)
      h(82) = c(38,2,bc,kc)
      h(83) = h(82) + CD1*h(72)
      h(84) = h(83) + CD1*h(73)
      h(85) = h(84)
      h(86) = c(39,2,bc,kc)
      h(87) = h(86) + CD2*h(72)
      h(88) = h(87) + CD1*h(79)
      h(89) = h(88)
      h(90) = c(40,2,bc,kc)
      h(91) = h(90) + CD2*h(78)
      h(92) = h(91) + CD2*h(79)
      h(93) = h(92)
   end subroutine hrr_002
   end subroutine hgp_grad_sssd
end module hgp_grad_sssd_m
