! GENERATED by scripts/hgp -- do not edit.
! dsss: vrr=35 carried=20x2 hrr=31 in 1 block(s) comps=18
module hgp_grad_dsss_m
   use cint_const, only: dp
   use cint_rotaxis_boys, only: boys
   implicit none
   private
   public :: hgp_grad_dsss
   real(dp), parameter :: PI = 3.14159265358979323846_dp
   real(dp), parameter :: TWO_PI_52 = 2.0_dp*PI**2*sqrt(PI)
contains
   ! d/dA (ds|ss)  dsss: vrr=35 carried=20x2 hrr=31 in 1 block(s) comps=18
   subroutine hgp_grad_dsss(nbra, ncb, bp, kab, nket, nck, kp, kcd, ab, cd, cutoff, res, any)
      integer,  intent(in)  :: nbra, ncb, nket, nck
      real(dp), intent(in)  :: bp(11, nbra), kab(1*ncb, nbra)
      real(dp), intent(in)  :: kp(11, nket), kcd(1*nck, nket)
      real(dp), intent(in)  :: ab(3), cd(3), cutoff
      real(dp), intent(out) :: res(18, ncb*nck)
      logical,  intent(out) :: any
      ! TWO contracted sets: plain, and weighted by 2a.  d/dA
      ! raises the bra with the bra exponent, which varies per
      ! primitive while the transfers run once per contracted
      ! quartet -- so the exponent is folded in here, the last
      ! stage that still has it.
      real(dp) :: c(20, 2, 1*ncb, 1*nck)
      real(dp) :: cb(20, 2, 1*ncb)
      real(dp) :: t(35), tv(20), f(0:3), b(0:3)
      real(dp) :: h(31)
      real(dp) :: p, q, pq, rho, oo2p, oo2q, oo2pq, rp, rq, tt, w, eab, ecd, ea
      real(dp) :: PA0, PA1, PA2, QC0, QC1, QC2, WP0, WP1, WP2, WQ0, WQ1, WQ2
      real(dp) :: PQ0, PQ1, PQ2, AB0, AB1, AB2, CD0, CD1, CD2, wq_, wp_
      logical  :: hit
      integer  :: kq, bq, bc, kc, cc, ck, n, col

      AB0 = ab(1); AB1 = ab(2); AB2 = ab(3)
      CD0 = cd(1); CD1 = cd(2); CD2 = cd(3)
      any = .false.
      c = 0.0_dp
      do kq = 1, nket
         q = kp(1,kq); oo2q = kp(2,kq)
         QC0 = kp(3,kq); QC1 = kp(4,kq); QC2 = kp(5,kq)
         ecd = kp(10,kq)
         cb = 0.0_dp
         hit = .false.
         do bq = 1, nbra
            eab = bp(10,bq)
            if (eab + ecd > cutoff) cycle
            hit = .true.
            p = bp(1,bq); oo2p = bp(2,bq); ea = bp(11,bq)
            PA0 = bp(3,bq); PA1 = bp(4,bq); PA2 = bp(5,bq)
            PQ0 = bp(6,bq) - kp(6,kq)
            PQ1 = bp(7,bq) - kp(7,kq)
            PQ2 = bp(8,bq) - kp(8,kq)
            pq = p + q
            rho = p*q/pq
            oo2pq = 0.5_dp/pq
            rp = rho/p; rq = rho/q
            wp_ = -q/pq; wq_ = p/pq
            WP0 = wp_*PQ0; WP1 = wp_*PQ1; WP2 = wp_*PQ2
            WQ0 = wq_*PQ0; WQ1 = wq_*PQ1; WQ2 = wq_*PQ2
            tt = rho*(PQ0*PQ0 + PQ1*PQ1 + PQ2*PQ2)
            call boys(f, tt, 3)
            w = TWO_PI_52*bp(9,bq)*kp(9,kq)/sqrt(pq)
            do n = 0, 3
               b(n) = w*f(n)
            end do
            call vrr_001()
            tv(1) = t(1)
            tv(2) = t(3)
            tv(3) = t(4)
            tv(4) = t(5)
            tv(5) = t(8)
            tv(6) = t(10)
            tv(7) = t(12)
            tv(8) = t(13)
            tv(9) = t(14)
            tv(10) = t(15)
            tv(11) = t(19)
            tv(12) = t(22)
            tv(13) = t(25)
            tv(14) = t(27)
            tv(15) = t(29)
            tv(16) = t(31)
            tv(17) = t(32)
            tv(18) = t(33)
            tv(19) = t(34)
            tv(20) = t(35)
            do bc = 1, 1*ncb
               cb(1:20,1,bc) = cb(1:20,1,bc) + kab(bc,bq)*tv(1:20)
               cb(1:20,2,bc) = cb(1:20,2,bc) + (2.0_dp*ea)*kab(bc,bq)*tv(1:20)
            end do
         end do
         if (.not. hit) cycle
         any = .true.
         do kc = 1, 1*nck
            do bc = 1, 1*ncb
               c(1:20,1:2,bc,kc) = c(1:20,1:2,bc,kc) + kcd(kc,kq)*cb(1:20,1:2,bc)
            end do
         end do
      end do
      res = 0.0_dp
      if (.not. any) return
      do ck = 1, nck
         do cc = 1, ncb
            col = cc + ncb*(ck-1)
            bc = cc; kc = ck
            call hrr_002()
            res(1,col) = -h(3)
            res(2,col) = -h(6)
            res(3,col) = -h(9)
            res(4,col) = -h(11)
            res(5,col) = -h(13)
            res(6,col) = -h(15)
            res(7,col) = -h(16)
            res(8,col) = -h(17)
            res(9,col) = -h(18)
            res(10,col) = -h(20)
            res(11,col) = -h(22)
            res(12,col) = -h(24)
            res(13,col) = -h(25)
            res(14,col) = -h(26)
            res(15,col) = -h(27)
            res(16,col) = -h(28)
            res(17,col) = -h(29)
            res(18,col) = -h(31)
         end do
      end do

   contains
   subroutine vrr_001()
      t(1) = b(0)
      t(2) = b(1)
      t(3) = PA0*t(1) + WP0*t(2)
      t(4) = PA1*t(1) + WP1*t(2)
      t(5) = PA2*t(1) + WP2*t(2)
      t(6) = b(2)
      t(7) = PA0*t(2) + WP0*t(6)
      t(8) = PA0*t(3) + WP0*t(7) + oo2p*t(1) - oo2p*rp*t(2)
      t(9) = PA1*t(2) + WP1*t(6)
      t(10) = PA0*t(4) + WP0*t(9)
      t(11) = PA2*t(2) + WP2*t(6)
      t(12) = PA0*t(5) + WP0*t(11)
      t(13) = PA1*t(4) + WP1*t(9) + oo2p*t(1) - oo2p*rp*t(2)
      t(14) = PA1*t(5) + WP1*t(11)
      t(15) = PA2*t(5) + WP2*t(11) + oo2p*t(1) - oo2p*rp*t(2)
      t(16) = b(3)
      t(17) = PA0*t(6) + WP0*t(16)
      t(18) = PA0*t(7) + WP0*t(17) + oo2p*t(2) - oo2p*rp*t(6)
      t(19) = PA0*t(8) + WP0*t(18) + 2.0_dp*oo2p*t(3) - 2.0_dp*oo2p*rp*t(7)
      t(20) = PA1*t(6) + WP1*t(16)
      t(21) = PA0*t(9) + WP0*t(20)
      t(22) = PA0*t(10) + WP0*t(21) + oo2p*t(4) - oo2p*rp*t(9)
      t(23) = PA2*t(6) + WP2*t(16)
      t(24) = PA0*t(11) + WP0*t(23)
      t(25) = PA0*t(12) + WP0*t(24) + oo2p*t(5) - oo2p*rp*t(11)
      t(26) = PA1*t(9) + WP1*t(20) + oo2p*t(2) - oo2p*rp*t(6)
      t(27) = PA0*t(13) + WP0*t(26)
      t(28) = PA1*t(11) + WP1*t(23)
      t(29) = PA0*t(14) + WP0*t(28)
      t(30) = PA2*t(11) + WP2*t(23) + oo2p*t(2) - oo2p*rp*t(6)
      t(31) = PA0*t(15) + WP0*t(30)
      t(32) = PA1*t(13) + WP1*t(26) + 2.0_dp*oo2p*t(4) - 2.0_dp*oo2p*rp*t(9)
      t(33) = PA1*t(14) + WP1*t(28) + oo2p*t(5) - oo2p*rp*t(11)
      t(34) = PA1*t(15) + WP1*t(30)
      t(35) = PA2*t(15) + WP2*t(30) + 2.0_dp*oo2p*t(5) - 2.0_dp*oo2p*rp*t(11)
   end subroutine vrr_001
   subroutine hrr_002()
      h(1) = c(11,2,bc,kc)
      h(2) = c(2,1,bc,kc)
      h(3) = h(1) - 2.0_dp*h(2)
      h(4) = c(12,2,bc,kc)
      h(5) = c(3,1,bc,kc)
      h(6) = h(4) - h(5)
      h(7) = c(13,2,bc,kc)
      h(8) = c(4,1,bc,kc)
      h(9) = h(7) - h(8)
      h(10) = c(14,2,bc,kc)
      h(11) = h(10)
      h(12) = c(15,2,bc,kc)
      h(13) = h(12)
      h(14) = c(16,2,bc,kc)
      h(15) = h(14)
      h(16) = h(4)
      h(17) = h(10) - h(2)
      h(18) = h(12)
      h(19) = c(17,2,bc,kc)
      h(20) = h(19) - 2.0_dp*h(5)
      h(21) = c(18,2,bc,kc)
      h(22) = h(21) - h(8)
      h(23) = c(19,2,bc,kc)
      h(24) = h(23)
      h(25) = h(7)
      h(26) = h(12)
      h(27) = h(14) - h(2)
      h(28) = h(21)
      h(29) = h(23) - h(5)
      h(30) = c(20,2,bc,kc)
      h(31) = h(30) - 2.0_dp*h(8)
   end subroutine hrr_002
   end subroutine hgp_grad_dsss
end module hgp_grad_dsss_m
