! GENERATED by scripts/hgp -- do not edit.
! sLps: vrr=52 carried=30x2 hrr=99 in 2 block(s) comps=36
module hgp_grad_sLps_m
   use cint_const, only: dp
   use cint_rotaxis_boys, only: boys
   implicit none
   private
   public :: hgp_grad_sLps
   real(dp), parameter :: PI = 3.14159265358979323846_dp
   real(dp), parameter :: TWO_PI_52 = 2.0_dp*PI**2*sqrt(PI)
contains
   ! d/dA (sL|ps)  sLps: vrr=52 carried=30x2 hrr=99 in 2 block(s) comps=36
   subroutine hgp_grad_sLps(nbra, ncb, bp, kab, nket, nck, kp, kcd, ab, cd, cutoff, res, any)
      integer,  intent(in)  :: nbra, ncb, nket, nck
      real(dp), intent(in)  :: bp(11, nbra), kab(2*ncb, nbra)
      real(dp), intent(in)  :: kp(11, nket), kcd(1*nck, nket)
      real(dp), intent(in)  :: ab(3), cd(3), cutoff
      real(dp), intent(out) :: res(36, ncb*nck)
      logical,  intent(out) :: any
      ! TWO contracted sets: plain, and weighted by 2a.  d/dA
      ! raises the bra with the bra exponent, which varies per
      ! primitive while the transfers run once per contracted
      ! quartet -- so the exponent is folded in here, the last
      ! stage that still has it.
      real(dp) :: c(30, 2, 2*ncb, 1*nck)
      real(dp) :: cb(30, 2, 2*ncb)
      real(dp) :: t(52), tv(30), f(0:3), b(0:3)
      real(dp) :: h(81)
      real(dp) :: p, q, pq, rho, oo2p, oo2q, oo2pq, rp, rq, tt, w, eab, ecd, ea
      real(dp) :: PA0, PA1, PA2, QC0, QC1, QC2, WP0, WP1, WP2, WQ0, WQ1, WQ2
      real(dp) :: PQ0, PQ1, PQ2, AB0, AB1, AB2, CD0, CD1, CD2, wq_, wp_
      logical  :: hit
      integer  :: kq, bq, bc, kc, cc, ck, n, col

      AB0 = ab(1); AB1 = ab(2); AB2 = ab(3)
      CD0 = cd(1); CD1 = cd(2); CD2 = cd(3)
      any = .false.
      c = 0.0_dp
      do kq = 1, nket
         q = kp(1,kq); oo2q = kp(2,kq)
         QC0 = kp(3,kq); QC1 = kp(4,kq); QC2 = kp(5,kq)
         ecd = kp(10,kq)
         cb = 0.0_dp
         hit = .false.
         do bq = 1, nbra
            eab = bp(10,bq)
            if (eab + ecd > cutoff) cycle
            hit = .true.
            p = bp(1,bq); oo2p = bp(2,bq); ea = bp(11,bq)
            PA0 = bp(3,bq); PA1 = bp(4,bq); PA2 = bp(5,bq)
            PQ0 = bp(6,bq) - kp(6,kq)
            PQ1 = bp(7,bq) - kp(7,kq)
            PQ2 = bp(8,bq) - kp(8,kq)
            pq = p + q
            rho = p*q/pq
            oo2pq = 0.5_dp/pq
            rp = rho/p; rq = rho/q
            wp_ = -q/pq; wq_ = p/pq
            WP0 = wp_*PQ0; WP1 = wp_*PQ1; WP2 = wp_*PQ2
            WQ0 = wq_*PQ0; WQ1 = wq_*PQ1; WQ2 = wq_*PQ2
            tt = rho*(PQ0*PQ0 + PQ1*PQ1 + PQ2*PQ2)
            call boys(f, tt, 3)
            w = TWO_PI_52*bp(9,bq)*kp(9,kq)/sqrt(pq)
            do n = 0, 3
               b(n) = w*f(n)
            end do
            call vrr_001()
            tv(1) = t(3)
            tv(2) = t(4)
            tv(3) = t(5)
            tv(4) = t(8)
            tv(5) = t(10)
            tv(6) = t(12)
            tv(7) = t(13)
            tv(8) = t(14)
            tv(9) = t(15)
            tv(10) = t(16)
            tv(11) = t(17)
            tv(12) = t(18)
            tv(13) = t(23)
            tv(14) = t(26)
            tv(15) = t(29)
            tv(16) = t(32)
            tv(17) = t(34)
            tv(18) = t(36)
            tv(19) = t(39)
            tv(20) = t(41)
            tv(21) = t(43)
            tv(22) = t(44)
            tv(23) = t(45)
            tv(24) = t(46)
            tv(25) = t(47)
            tv(26) = t(48)
            tv(27) = t(49)
            tv(28) = t(50)
            tv(29) = t(51)
            tv(30) = t(52)
            do bc = 1, 2*ncb
               cb(1:30,1,bc) = cb(1:30,1,bc) + kab(bc,bq)*tv(1:30)
               cb(1:30,2,bc) = cb(1:30,2,bc) + (2.0_dp*ea)*kab(bc,bq)*tv(1:30)
            end do
         end do
         if (.not. hit) cycle
         any = .true.
         do kc = 1, 1*nck
            do bc = 1, 2*ncb
               c(1:30,1:2,bc,kc) = c(1:30,1:2,bc,kc) + kcd(kc,kq)*cb(1:30,1:2,bc)
            end do
         end do
      end do
      res = 0.0_dp
      if (.not. any) return
      do ck = 1, nck
         do cc = 1, ncb
            col = cc + ncb*(ck-1)
            bc = 1 + 2*(cc-1); kc = ck
            call hrr_002()
            res(1,col) = -h(2)
            res(5,col) = -h(4)
            res(9,col) = -h(6)
            res(13,col) = -h(8)
            res(17,col) = -h(10)
            res(21,col) = -h(12)
            res(25,col) = -h(14)
            res(29,col) = -h(16)
            res(33,col) = -h(18)
            bc = 2 + 2*(cc-1); kc = ck
            call hrr_003()
            res(2,col) = -h(4)
            res(3,col) = -h(7)
            res(4,col) = -h(10)
            res(6,col) = -h(14)
            res(7,col) = -h(17)
            res(8,col) = -h(20)
            res(10,col) = -h(24)
            res(11,col) = -h(27)
            res(12,col) = -h(30)
            res(14,col) = -h(33)
            res(15,col) = -h(36)
            res(16,col) = -h(39)
            res(18,col) = -h(42)
            res(19,col) = -h(45)
            res(20,col) = -h(48)
            res(22,col) = -h(51)
            res(23,col) = -h(54)
            res(24,col) = -h(57)
            res(26,col) = -h(60)
            res(27,col) = -h(62)
            res(28,col) = -h(65)
            res(30,col) = -h(68)
            res(31,col) = -h(70)
            res(32,col) = -h(73)
            res(34,col) = -h(76)
            res(35,col) = -h(78)
            res(36,col) = -h(81)
         end do
      end do

   contains
   subroutine vrr_001()
      t(1) = b(0)
      t(2) = b(1)
      t(3) = QC0*t(1) + WQ0*t(2)
      t(4) = QC1*t(1) + WQ1*t(2)
      t(5) = QC2*t(1) + WQ2*t(2)
      t(6) = b(2)
      t(7) = QC0*t(2) + WQ0*t(6)
      t(8) = PA0*t(3) + WP0*t(7) + oo2pq*t(2)
      t(9) = QC1*t(2) + WQ1*t(6)
      t(10) = PA0*t(4) + WP0*t(9)
      t(11) = QC2*t(2) + WQ2*t(6)
      t(12) = PA0*t(5) + WP0*t(11)
      t(13) = PA1*t(3) + WP1*t(7)
      t(14) = PA1*t(4) + WP1*t(9) + oo2pq*t(2)
      t(15) = PA1*t(5) + WP1*t(11)
      t(16) = PA2*t(3) + WP2*t(7)
      t(17) = PA2*t(4) + WP2*t(9)
      t(18) = PA2*t(5) + WP2*t(11) + oo2pq*t(2)
      t(19) = b(3)
      t(20) = QC0*t(6) + WQ0*t(19)
      t(21) = PA0*t(7) + WP0*t(20) + oo2pq*t(6)
      t(22) = PA0*t(2) + WP0*t(6)
      t(23) = PA0*t(8) + WP0*t(21) + oo2p*t(3) - oo2p*rp*t(7) + oo2pq*t(22)
      t(24) = QC1*t(6) + WQ1*t(19)
      t(25) = PA0*t(9) + WP0*t(24)
      t(26) = PA0*t(10) + WP0*t(25) + oo2p*t(4) - oo2p*rp*t(9)
      t(27) = QC2*t(6) + WQ2*t(19)
      t(28) = PA0*t(11) + WP0*t(27)
      t(29) = PA0*t(12) + WP0*t(28) + oo2p*t(5) - oo2p*rp*t(11)
      t(30) = PA1*t(7) + WP1*t(20)
      t(31) = PA1*t(2) + WP1*t(6)
      t(32) = PA0*t(13) + WP0*t(30) + oo2pq*t(31)
      t(33) = PA1*t(9) + WP1*t(24) + oo2pq*t(6)
      t(34) = PA0*t(14) + WP0*t(33)
      t(35) = PA1*t(11) + WP1*t(27)
      t(36) = PA0*t(15) + WP0*t(35)
      t(37) = PA2*t(7) + WP2*t(20)
      t(38) = PA2*t(2) + WP2*t(6)
      t(39) = PA0*t(16) + WP0*t(37) + oo2pq*t(38)
      t(40) = PA2*t(9) + WP2*t(24)
      t(41) = PA0*t(17) + WP0*t(40)
      t(42) = PA2*t(11) + WP2*t(27) + oo2pq*t(6)
      t(43) = PA0*t(18) + WP0*t(42)
      t(44) = PA1*t(13) + WP1*t(30) + oo2p*t(3) - oo2p*rp*t(7)
      t(45) = PA1*t(14) + WP1*t(33) + oo2p*t(4) - oo2p*rp*t(9) + oo2pq*t(31)
      t(46) = PA1*t(15) + WP1*t(35) + oo2p*t(5) - oo2p*rp*t(11)
      t(47) = PA1*t(16) + WP1*t(37)
      t(48) = PA1*t(17) + WP1*t(40) + oo2pq*t(38)
      t(49) = PA1*t(18) + WP1*t(42)
      t(50) = PA2*t(16) + WP2*t(37) + oo2p*t(3) - oo2p*rp*t(7)
      t(51) = PA2*t(17) + WP2*t(40) + oo2p*t(4) - oo2p*rp*t(9)
      t(52) = PA2*t(18) + WP2*t(42) + oo2p*t(5) - oo2p*rp*t(11) + oo2pq*t(38)
   end subroutine vrr_001
   subroutine hrr_002()
      h(1) = c(4,2,bc,kc)
      h(2) = h(1)
      h(3) = c(5,2,bc,kc)
      h(4) = h(3)
      h(5) = c(6,2,bc,kc)
      h(6) = h(5)
      h(7) = c(7,2,bc,kc)
      h(8) = h(7)
      h(9) = c(8,2,bc,kc)
      h(10) = h(9)
      h(11) = c(9,2,bc,kc)
      h(12) = h(11)
      h(13) = c(10,2,bc,kc)
      h(14) = h(13)
      h(15) = c(11,2,bc,kc)
      h(16) = h(15)
      h(17) = c(12,2,bc,kc)
      h(18) = h(17)
   end subroutine hrr_002
   subroutine hrr_003()
      h(1) = c(13,2,bc,kc)
      h(2) = c(4,2,bc,kc)
      h(3) = h(1) + AB0*h(2)
      h(4) = h(3)
      h(5) = c(16,2,bc,kc)
      h(6) = h(5) + AB1*h(2)
      h(7) = h(6)
      h(8) = c(19,2,bc,kc)
      h(9) = h(8) + AB2*h(2)
      h(10) = h(9)
      h(11) = c(14,2,bc,kc)
      h(12) = c(5,2,bc,kc)
      h(13) = h(11) + AB0*h(12)
      h(14) = h(13)
      h(15) = c(17,2,bc,kc)
      h(16) = h(15) + AB1*h(12)
      h(17) = h(16)
      h(18) = c(20,2,bc,kc)
      h(19) = h(18) + AB2*h(12)
      h(20) = h(19)
      h(21) = c(15,2,bc,kc)
      h(22) = c(6,2,bc,kc)
      h(23) = h(21) + AB0*h(22)
      h(24) = h(23)
      h(25) = c(18,2,bc,kc)
      h(26) = h(25) + AB1*h(22)
      h(27) = h(26)
      h(28) = c(21,2,bc,kc)
      h(29) = h(28) + AB2*h(22)
      h(30) = h(29)
      h(31) = c(7,2,bc,kc)
      h(32) = h(5) + AB0*h(31)
      h(33) = h(32)
      h(34) = c(22,2,bc,kc)
      h(35) = h(34) + AB1*h(31)
      h(36) = h(35)
      h(37) = c(25,2,bc,kc)
      h(38) = h(37) + AB2*h(31)
      h(39) = h(38)
      h(40) = c(8,2,bc,kc)
      h(41) = h(15) + AB0*h(40)
      h(42) = h(41)
      h(43) = c(23,2,bc,kc)
      h(44) = h(43) + AB1*h(40)
      h(45) = h(44)
      h(46) = c(26,2,bc,kc)
      h(47) = h(46) + AB2*h(40)
      h(48) = h(47)
      h(49) = c(9,2,bc,kc)
      h(50) = h(25) + AB0*h(49)
      h(51) = h(50)
      h(52) = c(24,2,bc,kc)
      h(53) = h(52) + AB1*h(49)
      h(54) = h(53)
      h(55) = c(27,2,bc,kc)
      h(56) = h(55) + AB2*h(49)
      h(57) = h(56)
      h(58) = c(10,2,bc,kc)
      h(59) = h(8) + AB0*h(58)
      h(60) = h(59)
      h(61) = h(37) + AB1*h(58)
      h(62) = h(61)
      h(63) = c(28,2,bc,kc)
      h(64) = h(63) + AB2*h(58)
      h(65) = h(64)
      h(66) = c(11,2,bc,kc)
      h(67) = h(18) + AB0*h(66)
      h(68) = h(67)
      h(69) = h(46) + AB1*h(66)
      h(70) = h(69)
      h(71) = c(29,2,bc,kc)
      h(72) = h(71) + AB2*h(66)
      h(73) = h(72)
      h(74) = c(12,2,bc,kc)
      h(75) = h(28) + AB0*h(74)
      h(76) = h(75)
      h(77) = h(55) + AB1*h(74)
      h(78) = h(77)
      h(79) = c(30,2,bc,kc)
      h(80) = h(79) + AB2*h(74)
      h(81) = h(80)
   end subroutine hrr_003
   end subroutine hgp_grad_sLps
end module hgp_grad_sLps_m
