! GENERATED by scripts/rotaxis_mmd -- do not edit.
! ppsL: L=4 comps=108 S=59 g=11 r=107 (terms 516) km=13 cm=13 assembly terms=217
module rotaxis_grad_ppsL_m
   use cint_const, only: dp
   use cint_rotaxis_boys, only: boys
   implicit none
   private
   public :: rotaxis_grad_ppsL
contains
   ! (pp|sL)  L=4: 59 bra accumulators, 107 ket accumulators, 108 components
   subroutine rotaxis_grad_ppsL(nbra, ncb, bp, kab, nket, nck, kp, kcd, gc, cutoff, res, any)
      integer,  intent(in)  :: nbra, ncb, nket, nck
      real(dp), intent(in)  :: bp(6, nbra), kab(1*ncb, nbra)
      real(dp), intent(in)  :: kp(7, nket), kcd(2*nck, nket), gc(3), cutoff
      real(dp), intent(out) :: res(108, ncb*nck)
      logical,  intent(out) :: any
      real(dp) :: s(59, ncb), r(107, ncb, nck), t(107)
      real(dp) :: f(0:4), b(0:4)
      real(dp) :: p, ip, za, zb, eab, q, iq, yc, yd, ax, az, ecd
      real(dp) :: zq, alpha, tt, w, m2a, Rs, Rc, cy, ea
      real(dp) :: g(11), km(13), cm(13), zq2, zq3, zq4
      integer :: kq, bq, cc, ck, n

      Rs = gc(1); Rc = gc(2); cy = gc(3)
      any = .false.
      r = 0.0_dp
      do kq = 1, nket
         q = kp(1,kq); iq = kp(2,kq); yc = kp(3,kq); yd = kp(4,kq)
         ax = kp(5,kq); az = kp(6,kq); ecd = kp(7,kq)
         s = 0.0_dp
         do bq = 1, nbra
            eab = bp(5,bq)
            if (eab + ecd > cutoff) cycle
            any = .true.
            p = bp(1,bq); ip = bp(2,bq); za = bp(3,bq); zb = bp(4,bq)
            ea = bp(6,bq)
            zq = za - az
            alpha = p*q/(p + q)
            tt = alpha*(ax*ax + cy*cy + zq*zq)
            call boys(f, tt, 4)
            w = 1.0_dp/sqrt(p + q)
            m2a = -2.0_dp*alpha
            do n = 0, 4
               b(n) = w*f(n)
               w = w*m2a
            end do
            zq2 = zq*zq
            zq3 = zq2*zq
            zq4 = zq3*zq
            g(1) = ip*ip*ea
            g(2) = ip*ip*ip*ea
            g(3) = ip
            g(4) = ip*za*ea
            g(5) = ip*ip*za*ea
            g(6) = ip*zb*ea
            g(7) = ip*ip*zb*ea
            g(8) = zb
            g(9) = ip*za*zb*ea
            g(10) = ip*za*za*ea
            g(11) = za*za*zb*ea
            do cc = 1, ncb
               s(1,cc) = s(1,cc) + kab(cc,bq)*g(1)*b(1)
               s(2,cc) = s(2,cc) + kab(cc,bq)*g(2)*b(3)
               s(3,cc) = s(3,cc) + kab(cc,bq)*g(2)*b(2)
               s(4,cc) = s(4,cc) + kab(cc,bq)*g(3)*b(1)
               s(5,cc) = s(5,cc) + kab(cc,bq)*g(4)*b(0)
               s(6,cc) = s(6,cc) + kab(cc,bq)*g(1)*b(1)*zq
               s(7,cc) = s(7,cc) + kab(cc,bq)*g(5)*b(2)
               s(8,cc) = s(8,cc) + kab(cc,bq)*g(5)*b(1)
               s(9,cc) = s(9,cc) + kab(cc,bq)*g(2)*b(3)*zq
               s(10,cc) = s(10,cc) + kab(cc,bq)*g(2)*b(2)*zq
               s(11,cc) = s(11,cc) + kab(cc,bq)*g(6)*b(0)
               s(12,cc) = s(12,cc) + kab(cc,bq)*g(7)*b(2)
               s(13,cc) = s(13,cc) + kab(cc,bq)*g(7)*b(1)
               s(14,cc) = s(14,cc) + kab(cc,bq)*g(8)*b(0)
               s(15,cc) = s(15,cc) + kab(cc,bq)*g(3)*b(1)*zq
               s(16,cc) = s(16,cc) + kab(cc,bq)*g(9)*b(1)
               s(17,cc) = s(17,cc) + kab(cc,bq)*g(7)*b(2)*zq
               s(18,cc) = s(18,cc) + kab(cc,bq)*g(5)*b(2)*zq
               s(19,cc) = s(19,cc) + kab(cc,bq)*g(2)*b(3)*zq2
               s(20,cc) = s(20,cc) + kab(cc,bq)*g(1)*b(2)
               s(21,cc) = s(21,cc) + kab(cc,bq)*g(2)*b(4)
               s(22,cc) = s(22,cc) + kab(cc,bq)*g(3)*b(2)
               s(23,cc) = s(23,cc) + kab(cc,bq)*g(4)*b(1)
               s(24,cc) = s(24,cc) + kab(cc,bq)*g(1)*b(2)*zq
               s(25,cc) = s(25,cc) + kab(cc,bq)*g(5)*b(3)
               s(26,cc) = s(26,cc) + kab(cc,bq)*g(2)*b(4)*zq
               s(27,cc) = s(27,cc) + kab(cc,bq)*g(6)*b(1)
               s(28,cc) = s(28,cc) + kab(cc,bq)*g(7)*b(3)
               s(29,cc) = s(29,cc) + kab(cc,bq)*g(8)*b(1)
               s(30,cc) = s(30,cc) + kab(cc,bq)*g(3)*b(2)*zq
               s(31,cc) = s(31,cc) + kab(cc,bq)*g(9)*b(2)
               s(32,cc) = s(32,cc) + kab(cc,bq)*g(7)*b(3)*zq
               s(33,cc) = s(33,cc) + kab(cc,bq)*g(5)*b(3)*zq
               s(34,cc) = s(34,cc) + kab(cc,bq)*g(2)*b(4)*zq2
               s(35,cc) = s(35,cc) + kab(cc,bq)*g(4)*b(1)*zq
               s(36,cc) = s(36,cc) + kab(cc,bq)*g(1)*b(2)*zq2
               s(37,cc) = s(37,cc) + kab(cc,bq)*g(6)*b(1)*zq
               s(38,cc) = s(38,cc) + kab(cc,bq)*g(8)*b(1)*zq
               s(39,cc) = s(39,cc) + kab(cc,bq)*g(3)*b(2)*zq2
               s(40,cc) = s(40,cc) + kab(cc,bq)*g(9)*b(2)*zq
               s(41,cc) = s(41,cc) + kab(cc,bq)*g(7)*b(3)*zq2
               s(42,cc) = s(42,cc) + kab(cc,bq)*g(5)*b(3)*zq2
               s(43,cc) = s(43,cc) + kab(cc,bq)*g(2)*b(4)*zq3
               s(44,cc) = s(44,cc) + kab(cc,bq)*g(10)*b(1)
               s(45,cc) = s(45,cc) + kab(cc,bq)*g(11)*b(0)
               s(46,cc) = s(46,cc) + kab(cc,bq)*g(9)*b(1)*zq
               s(47,cc) = s(47,cc) + kab(cc,bq)*g(10)*b(1)*zq
               s(48,cc) = s(48,cc) + kab(cc,bq)*g(7)*b(2)*zq2
               s(49,cc) = s(49,cc) + kab(cc,bq)*g(5)*b(2)*zq2
               s(50,cc) = s(50,cc) + kab(cc,bq)*g(2)*b(3)*zq3
               s(51,cc) = s(51,cc) + kab(cc,bq)*g(10)*b(2)
               s(52,cc) = s(52,cc) + kab(cc,bq)*g(11)*b(1)
               s(53,cc) = s(53,cc) + kab(cc,bq)*g(10)*b(2)*zq
               s(54,cc) = s(54,cc) + kab(cc,bq)*g(11)*b(1)*zq
               s(55,cc) = s(55,cc) + kab(cc,bq)*g(9)*b(2)*zq2
               s(56,cc) = s(56,cc) + kab(cc,bq)*g(10)*b(2)*zq2
               s(57,cc) = s(57,cc) + kab(cc,bq)*g(7)*b(3)*zq3
               s(58,cc) = s(58,cc) + kab(cc,bq)*g(5)*b(3)*zq3
               s(59,cc) = s(59,cc) + kab(cc,bq)*g(2)*b(4)*zq4
            end do
         end do
         if (.not. any) cycle
         km(1) = ax
         km(2) = ax*ax*ax
         km(3) = 1.0_dp
         km(4) = ax*ax
         km(5) = yc*ax
         km(6) = iq*ax*ax
         km(7) = iq
         km(8) = yc*ax*ax*ax
         km(9) = iq*ax*ax*ax*ax
         km(10) = yc
         km(11) = iq*ax
         km(12) = yc*ax*ax
         km(13) = iq*ax*ax*ax
         do cc = 1, ncb
            t(1) = km(1)*(s(1,cc) + s(3,cc) + (-1.0_dp/6.0_dp)*s(4,cc)) + &
               (1.0_dp/3.0_dp)*km(2)*s(2,cc)
            t(2) = (s(1,cc) + s(3,cc)) + km(4)*s(2,cc)
            t(3) = (s(5,cc) + s(6,cc) + s(8,cc) + s(10,cc)) + km(4)*(s(7,cc) + s(9,cc))
            t(4) = (s(1,cc) + s(3,cc) + (-1.0_dp/2.0_dp)*s(4,cc)) + km(4)*s(2,cc)
            t(5) = km(1)*(s(1,cc) + s(3,cc))
            t(6) = km(1)*s(2,cc)
            t(7) = km(1)*(s(7,cc) + s(9,cc))
            t(8) = (s(6,cc) + s(10,cc) + s(11,cc) + s(13,cc) + (-1.0_dp/2.0_dp)*s(14,cc) + &
               (-1.0_dp/2.0_dp)*s(15,cc)) + km(4)*(s(9,cc) + s(12,cc))
            t(9) = km(1)*(s(9,cc) + s(12,cc))
            t(10) = km(1)*(s(1,cc) + s(3,cc) + s(16,cc) + s(17,cc) + s(18,cc) + s(19,cc))
            t(11) = km(6)*(s(2,cc) + (1.0_dp/2.0_dp)*s(20,cc) + (-1.0_dp/12.0_dp)*s(22,cc)) + &
               km(7)*((1.0_dp/2.0_dp)*s(1,cc) + (1.0_dp/2.0_dp)*s(3,cc) + &
               (-1.0_dp/12.0_dp)*s(4,cc)) + (1.0_dp/6.0_dp)*km(9)*s(21,cc)
            t(12) = km(5)*(s(1,cc) + s(3,cc) + (-1.0_dp/6.0_dp)*s(4,cc)) + &
               (1.0_dp/3.0_dp)*km(8)*s(2,cc)
            t(13) = km(11)*(s(2,cc) + (1.0_dp/3.0_dp)*s(20,cc)) + (1.0_dp/3.0_dp)*km(13)*s(21,cc)
            t(14) = km(10)*(s(1,cc) + s(3,cc)) + km(12)*s(2,cc)
            t(15) = km(11)*(s(7,cc) + s(9,cc) + (1.0_dp/3.0_dp)*s(23,cc) + &
               (1.0_dp/3.0_dp)*s(24,cc)) + km(13)*((1.0_dp/3.0_dp)*s(25,cc) + &
               (1.0_dp/3.0_dp)*s(26,cc))
            t(16) = km(10)*(s(5,cc) + s(6,cc) + s(8,cc) + s(10,cc)) + km(12)*(s(7,cc) + s(9,cc))
            t(17) = km(11)*(s(2,cc) + (1.0_dp/3.0_dp)*s(20,cc) + (-1.0_dp/6.0_dp)*s(22,cc)) + &
               (1.0_dp/3.0_dp)*km(13)*s(21,cc)
            t(18) = km(10)*(s(1,cc) + s(3,cc) + (-1.0_dp/2.0_dp)*s(4,cc)) + km(12)*s(2,cc)
            t(19) = km(6)*(s(2,cc) + s(20,cc)) + km(7)*(s(1,cc) + s(3,cc))
            t(20) = km(6)*s(21,cc) + km(7)*s(2,cc)
            t(21) = km(5)*(s(1,cc) + s(3,cc))
            t(22) = km(5)*s(2,cc)
            t(23) = km(6)*(s(25,cc) + s(26,cc)) + km(7)*(s(7,cc) + s(9,cc))
            t(24) = km(5)*(s(7,cc) + s(9,cc))
            t(25) = km(11)*(s(9,cc) + s(12,cc) + (1.0_dp/3.0_dp)*s(24,cc) + &
               (1.0_dp/3.0_dp)*s(27,cc) + (-1.0_dp/6.0_dp)*s(29,cc) + (-1.0_dp/6.0_dp)*s(30,cc)) + &
               km(13)*((1.0_dp/3.0_dp)*s(26,cc) + (1.0_dp/3.0_dp)*s(28,cc))
            t(26) = km(10)*(s(6,cc) + s(10,cc) + s(11,cc) + s(13,cc) + (-1.0_dp/2.0_dp)*s(14,cc) + &
               (-1.0_dp/2.0_dp)*s(15,cc)) + km(12)*(s(9,cc) + s(12,cc))
            t(27) = km(6)*(s(26,cc) + s(28,cc)) + km(7)*(s(9,cc) + s(12,cc))
            t(28) = km(5)*(s(9,cc) + s(12,cc))
            t(29) = km(6)*(s(2,cc) + s(20,cc) + s(31,cc) + s(32,cc) + s(33,cc) + s(34,cc)) + &
               km(7)*(s(1,cc) + s(3,cc) + s(16,cc) + s(17,cc) + s(18,cc) + s(19,cc))
            t(30) = km(5)*(s(1,cc) + s(3,cc) + s(16,cc) + s(17,cc) + s(18,cc) + s(19,cc))
            t(31) = km(11)*(s(2,cc) + s(20,cc) + (-1.0_dp/6.0_dp)*s(22,cc)) + &
               (1.0_dp/3.0_dp)*km(13)*s(21,cc)
            t(32) = km(6)*s(2,cc) + km(7)*(s(1,cc) + s(3,cc))
            t(33) = km(6)*s(21,cc) + km(7)*(s(2,cc) + s(20,cc))
            t(34) = km(6)*(s(25,cc) + s(26,cc)) + km(7)*(s(7,cc) + s(9,cc) + s(23,cc) + s(24,cc))
            t(35) = km(6)*s(2,cc) + km(7)*(s(1,cc) + s(3,cc) + (-1.0_dp/2.0_dp)*s(4,cc))
            t(36) = km(6)*s(21,cc) + km(7)*(s(2,cc) + s(20,cc) + (-1.0_dp/2.0_dp)*s(22,cc))
            t(37) = km(11)*(s(2,cc) + (1.0_dp/3.0_dp)*s(20,cc))
            t(38) = km(11)*s(21,cc)
            t(39) = km(11)*(s(7,cc) + s(9,cc))
            t(40) = km(11)*(s(25,cc) + s(26,cc))
            t(41) = km(6)*(s(26,cc) + s(28,cc)) + km(7)*(s(9,cc) + s(12,cc) + s(24,cc) + s(27,cc) + &
               (-1.0_dp/2.0_dp)*s(29,cc) + (-1.0_dp/2.0_dp)*s(30,cc))
            t(42) = km(11)*(s(9,cc) + s(12,cc))
            t(43) = km(11)*(s(26,cc) + s(28,cc))
            t(44) = km(11)*(s(2,cc) + s(20,cc) + s(31,cc) + s(32,cc) + s(33,cc) + s(34,cc))
            t(45) = km(11)*(s(9,cc) + s(24,cc) + (-1.0_dp/6.0_dp)*s(30,cc)) + &
               (1.0_dp/3.0_dp)*km(13)*s(26,cc)
            t(46) = km(6)*s(26,cc) + km(7)*(s(9,cc) + s(24,cc))
            t(47) = km(6)*(s(2,cc) + s(33,cc) + s(34,cc)) + km(7)*(s(1,cc) + s(3,cc) + s(18,cc) + &
               s(19,cc) + s(35,cc) + s(36,cc))
            t(48) = km(6)*s(26,cc) + km(7)*(s(9,cc) + s(24,cc) + (-1.0_dp/2.0_dp)*s(30,cc))
            t(49) = km(11)*(s(9,cc) + s(24,cc))
            t(50) = km(11)*s(26,cc)
            t(51) = km(11)*(s(2,cc) + s(33,cc) + s(34,cc))
            t(52) = km(6)*(s(2,cc) + s(32,cc) + s(34,cc)) + km(7)*(s(1,cc) + s(3,cc) + &
               (-1.0_dp/2.0_dp)*s(4,cc) + s(17,cc) + s(19,cc) + s(36,cc) + s(37,cc) + &
               (-1.0_dp/2.0_dp)*s(38,cc) + (-1.0_dp/2.0_dp)*s(39,cc))
            t(53) = km(11)*(s(2,cc) + s(32,cc) + s(34,cc))
            t(54) = km(11)*(s(7,cc) + 3.0_dp*s(9,cc) + s(12,cc) + s(24,cc) + s(40,cc) + s(41,cc) + &
               s(42,cc) + s(43,cc))
            t(55) = km(1)*(s(1,cc) + s(3,cc) + (-1.0_dp/2.0_dp)*s(4,cc))
            t(56) = (s(1,cc) + s(3,cc) + (-1.0_dp/6.0_dp)*s(4,cc))
            t(57) = s(2,cc)
            t(58) = (s(5,cc) + s(6,cc) + s(8,cc) + s(10,cc))
            t(59) = (s(7,cc) + s(9,cc))
            t(60) = (s(6,cc) + s(10,cc) + s(11,cc) + s(13,cc) + (-1.0_dp/2.0_dp)*s(14,cc) + &
               (-1.0_dp/2.0_dp)*s(15,cc))
            t(61) = (s(9,cc) + s(12,cc))
            t(62) = (s(1,cc) + s(3,cc) + s(16,cc) + s(17,cc) + s(18,cc) + s(19,cc))
            t(63) = km(6)*(s(2,cc) + s(20,cc) + (-1.0_dp/2.0_dp)*s(22,cc)) + km(7)*(s(1,cc) + &
               s(3,cc) + (-1.0_dp/2.0_dp)*s(4,cc))
            t(64) = km(5)*(s(1,cc) + s(3,cc) + (-1.0_dp/2.0_dp)*s(4,cc))
            t(65) = km(11)*(s(2,cc) + s(20,cc) + (-1.0_dp/6.0_dp)*s(22,cc))
            t(66) = km(10)*(s(1,cc) + s(3,cc) + (-1.0_dp/6.0_dp)*s(4,cc))
            t(67) = km(10)*s(2,cc)
            t(68) = km(11)*(s(7,cc) + s(9,cc) + s(23,cc) + s(24,cc))
            t(69) = km(10)*(s(5,cc) + s(6,cc) + s(8,cc) + s(10,cc))
            t(70) = km(10)*(s(7,cc) + s(9,cc))
            t(71) = km(11)*(s(9,cc) + s(12,cc) + s(24,cc) + s(27,cc) + (-1.0_dp/2.0_dp)*s(29,cc) + &
               (-1.0_dp/2.0_dp)*s(30,cc))
            t(72) = km(10)*(s(6,cc) + s(10,cc) + s(11,cc) + s(13,cc) + (-1.0_dp/2.0_dp)*s(14,cc) + &
               (-1.0_dp/2.0_dp)*s(15,cc))
            t(73) = km(10)*(s(9,cc) + s(12,cc))
            t(74) = km(10)*(s(1,cc) + s(3,cc) + s(16,cc) + s(17,cc) + s(18,cc) + s(19,cc))
            t(75) = km(11)*(s(2,cc) + (1.0_dp/3.0_dp)*s(20,cc) + (-1.0_dp/6.0_dp)*s(22,cc))
            t(76) = km(7)*(s(1,cc) + s(3,cc) + (-1.0_dp/6.0_dp)*s(4,cc))
            t(77) = km(7)*(s(2,cc) + (1.0_dp/2.0_dp)*s(20,cc) + (-1.0_dp/12.0_dp)*s(22,cc))
            t(78) = km(7)*s(21,cc)
            t(79) = km(7)*(s(7,cc) + s(9,cc) + (1.0_dp/3.0_dp)*s(23,cc) + (1.0_dp/3.0_dp)*s(24,cc))
            t(80) = km(7)*(s(25,cc) + s(26,cc))
            t(81) = km(7)*(s(9,cc) + s(12,cc) + (1.0_dp/3.0_dp)*s(24,cc) + (1.0_dp/3.0_dp)*s(27,cc) &
               + (-1.0_dp/6.0_dp)*s(29,cc) + (-1.0_dp/6.0_dp)*s(30,cc))
            t(82) = km(7)*(s(26,cc) + s(28,cc))
            t(83) = km(7)*(s(1,cc) + s(3,cc) + s(16,cc) + s(17,cc) + s(18,cc) + s(19,cc))
            t(84) = km(7)*(s(2,cc) + s(20,cc) + s(31,cc) + s(32,cc) + s(33,cc) + s(34,cc))
            t(85) = km(11)*(s(9,cc) + s(24,cc) + (-1.0_dp/2.0_dp)*s(30,cc))
            t(86) = km(7)*(s(9,cc) + s(24,cc) + (-1.0_dp/6.0_dp)*s(30,cc))
            t(87) = km(7)*s(26,cc)
            t(88) = km(7)*(s(1,cc) + s(3,cc) + s(18,cc) + s(19,cc) + s(35,cc) + s(36,cc))
            t(89) = km(7)*(s(2,cc) + s(33,cc) + s(34,cc))
            t(90) = km(7)*(s(1,cc) + s(3,cc) + (-1.0_dp/2.0_dp)*s(4,cc) + s(17,cc) + s(19,cc) + &
               s(36,cc) + s(37,cc) + (-1.0_dp/2.0_dp)*s(38,cc) + (-1.0_dp/2.0_dp)*s(39,cc))
            t(91) = km(7)*(s(2,cc) + s(32,cc) + s(34,cc))
            t(92) = km(7)*(s(7,cc) + 3.0_dp*s(9,cc) + s(12,cc) + s(24,cc) + s(40,cc) + s(41,cc) + &
               s(42,cc) + s(43,cc))
            t(93) = km(1)*(s(1,cc) + s(3,cc) + (-1.0_dp/2.0_dp)*s(4,cc) + 2.0_dp*s(18,cc) + &
               s(19,cc) + s(44,cc))
            t(94) = (s(1,cc) + s(3,cc) + (-1.0_dp/2.0_dp)*s(4,cc) + 2.0_dp*s(18,cc) + s(19,cc) + &
               s(44,cc))
            t(95) = (s(5,cc) + (3.0_dp/2.0_dp)*s(6,cc) + s(8,cc) + (3.0_dp/2.0_dp)*s(10,cc) + &
               (1.0_dp/2.0_dp)*s(11,cc) + (1.0_dp/2.0_dp)*s(13,cc) + (-1.0_dp/4.0_dp)*s(14,cc) + &
               (-1.0_dp/4.0_dp)*s(15,cc) + (1.0_dp/2.0_dp)*s(45,cc) + s(46,cc) + &
               (1.0_dp/2.0_dp)*s(47,cc) + (1.0_dp/2.0_dp)*s(48,cc) + s(49,cc) + &
               (1.0_dp/2.0_dp)*s(50,cc))
            t(96) = km(6)*(s(2,cc) + s(20,cc) + (-1.0_dp/2.0_dp)*s(22,cc) + 2.0_dp*s(33,cc) + &
               s(34,cc) + s(51,cc)) + km(7)*(s(1,cc) + s(3,cc) + (-1.0_dp/2.0_dp)*s(4,cc) + &
               2.0_dp*s(18,cc) + s(19,cc) + s(44,cc))
            t(97) = km(5)*(s(1,cc) + s(3,cc) + (-1.0_dp/2.0_dp)*s(4,cc) + 2.0_dp*s(18,cc) + &
               s(19,cc) + s(44,cc))
            t(98) = km(11)*(s(2,cc) + s(20,cc) + (-1.0_dp/2.0_dp)*s(22,cc) + 2.0_dp*s(33,cc) + &
               s(34,cc) + s(51,cc))
            t(99) = km(10)*(s(1,cc) + s(3,cc) + (-1.0_dp/2.0_dp)*s(4,cc) + 2.0_dp*s(18,cc) + &
               s(19,cc) + s(44,cc))
            t(100) = km(11)*(s(7,cc) + (3.0_dp/2.0_dp)*s(9,cc) + (1.0_dp/2.0_dp)*s(12,cc) + &
               s(23,cc) + (3.0_dp/2.0_dp)*s(24,cc) + (1.0_dp/2.0_dp)*s(27,cc) + &
               (-1.0_dp/4.0_dp)*s(29,cc) + (-1.0_dp/4.0_dp)*s(30,cc) + s(40,cc) + &
               (1.0_dp/2.0_dp)*s(41,cc) + s(42,cc) + (1.0_dp/2.0_dp)*s(43,cc) + &
               (1.0_dp/2.0_dp)*s(52,cc) + (1.0_dp/2.0_dp)*s(53,cc))
            t(101) = km(10)*(s(5,cc) + (3.0_dp/2.0_dp)*s(6,cc) + s(8,cc) + (3.0_dp/2.0_dp)*s(10,cc) &
               + (1.0_dp/2.0_dp)*s(11,cc) + (1.0_dp/2.0_dp)*s(13,cc) + (-1.0_dp/4.0_dp)*s(14,cc) + &
               (-1.0_dp/4.0_dp)*s(15,cc) + (1.0_dp/2.0_dp)*s(45,cc) + s(46,cc) + &
               (1.0_dp/2.0_dp)*s(47,cc) + (1.0_dp/2.0_dp)*s(48,cc) + s(49,cc) + &
               (1.0_dp/2.0_dp)*s(50,cc))
            t(102) = km(7)*(s(1,cc) + s(3,cc) + (-1.0_dp/2.0_dp)*s(4,cc) + 2.0_dp*s(18,cc) + &
               s(19,cc) + s(44,cc))
            t(103) = km(7)*(s(2,cc) + s(20,cc) + (-1.0_dp/2.0_dp)*s(22,cc) + 2.0_dp*s(33,cc) + &
               s(34,cc) + s(51,cc))
            t(104) = km(7)*(s(7,cc) + (3.0_dp/2.0_dp)*s(9,cc) + (1.0_dp/2.0_dp)*s(12,cc) + s(23,cc) &
               + (3.0_dp/2.0_dp)*s(24,cc) + (1.0_dp/2.0_dp)*s(27,cc) + (-1.0_dp/4.0_dp)*s(29,cc) + &
               (-1.0_dp/4.0_dp)*s(30,cc) + s(40,cc) + (1.0_dp/2.0_dp)*s(41,cc) + s(42,cc) + &
               (1.0_dp/2.0_dp)*s(43,cc) + (1.0_dp/2.0_dp)*s(52,cc) + (1.0_dp/2.0_dp)*s(53,cc))
            t(105) = km(11)*(s(7,cc) + (3.0_dp/2.0_dp)*s(9,cc) + (1.0_dp/2.0_dp)*s(24,cc) + &
               (-1.0_dp/4.0_dp)*s(30,cc) + s(42,cc) + (1.0_dp/2.0_dp)*s(43,cc) + &
               (1.0_dp/2.0_dp)*s(53,cc))
            t(106) = km(7)*(s(7,cc) + (3.0_dp/2.0_dp)*s(9,cc) + (1.0_dp/2.0_dp)*s(24,cc) + &
               (-1.0_dp/4.0_dp)*s(30,cc) + s(42,cc) + (1.0_dp/2.0_dp)*s(43,cc) + &
               (1.0_dp/2.0_dp)*s(53,cc))
            t(107) = km(7)*(s(1,cc) + s(3,cc) + (-1.0_dp/6.0_dp)*s(4,cc) + (2.0_dp/3.0_dp)*s(16,cc) &
               + s(17,cc) + 2.0_dp*s(18,cc) + 2.0_dp*s(19,cc) + (2.0_dp/3.0_dp)*s(35,cc) + s(36,cc) &
               + (1.0_dp/3.0_dp)*s(37,cc) + (-1.0_dp/6.0_dp)*s(38,cc) + (-1.0_dp/6.0_dp)*s(39,cc) + &
               (1.0_dp/3.0_dp)*s(44,cc) + (1.0_dp/3.0_dp)*s(54,cc) + (2.0_dp/3.0_dp)*s(55,cc) + &
               (1.0_dp/3.0_dp)*s(56,cc) + (1.0_dp/3.0_dp)*s(57,cc) + (2.0_dp/3.0_dp)*s(58,cc) + &
               (1.0_dp/3.0_dp)*s(59,cc))
            do ck = 1, nck
               r(1:10,cc,ck) = r(1:10,cc,ck) + kcd(1+2*(ck-1),kq)*t(1:10)
               r(55:62,cc,ck) = r(55:62,cc,ck) + kcd(1+2*(ck-1),kq)*t(55:62)
               r(93:95,cc,ck) = r(93:95,cc,ck) + kcd(1+2*(ck-1),kq)*t(93:95)
               r(11:54,cc,ck) = r(11:54,cc,ck) + kcd(2+2*(ck-1),kq)*t(11:54)
               r(63:92,cc,ck) = r(63:92,cc,ck) + kcd(2+2*(ck-1),kq)*t(63:92)
               r(96:107,cc,ck) = r(96:107,cc,ck) + kcd(2+2*(ck-1),kq)*t(96:107)
            end do
         end do
      end do
      res = 0.0_dp
      if (.not. any) return
      cm(1) = 1.0_dp
      cm(2) = cy
      cm(3) = cy*cy
      cm(4) = Rs
      cm(5) = Rs*cy
      cm(6) = Rs*cy*cy
      cm(7) = cy*cy*cy
      cm(8) = Rc
      cm(9) = Rc*cy
      cm(10) = Rc*cy*cy
      cm(11) = Rs*cy*cy*cy
      cm(12) = cy*cy*cy*cy
      cm(13) = Rc*cy*cy*cy
      do ck = 1, nck
         do cc = 1, ncb
            res(1,cc+ncb*(ck-1)) = 6.0_dp*r(1,cc,ck)
            res(2,cc+ncb*(ck-1)) = 2.0_dp*cm(2)*r(2,cc,ck)
            res(3,cc+ncb*(ck-1)) = (-2.0_dp)*r(3,cc,ck)
            res(4,cc+ncb*(ck-1)) = 2.0_dp*cm(2)*r(4,cc,ck)
            res(5,cc+ncb*(ck-1)) = 2.0_dp*r(5,cc,ck) + 2.0_dp*cm(3)*r(6,cc,ck)
            res(6,cc+ncb*(ck-1)) = (-2.0_dp)*cm(2)*r(7,cc,ck)
            res(7,cc+ncb*(ck-1)) = (-2.0_dp)*r(8,cc,ck)
            res(8,cc+ncb*(ck-1)) = (-2.0_dp)*cm(2)*r(9,cc,ck)
            res(9,cc+ncb*(ck-1)) = 2.0_dp*r(10,cc,ck)
            res(10,cc+ncb*(ck-1)) = 12.0_dp*r(11,cc,ck) + (-6.0_dp)*cm(4)*r(12,cc,ck)
            res(11,cc+ncb*(ck-1)) = 6.0_dp*cm(2)*r(13,cc,ck) + (-2.0_dp)*cm(5)*r(14,cc,ck)
            res(12,cc+ncb*(ck-1)) = (-6.0_dp)*r(15,cc,ck) + 2.0_dp*cm(4)*r(16,cc,ck)
            res(13,cc+ncb*(ck-1)) = 6.0_dp*cm(2)*r(17,cc,ck) + (-2.0_dp)*cm(5)*r(18,cc,ck)
            res(14,cc+ncb*(ck-1)) = 2.0_dp*r(19,cc,ck) + 2.0_dp*cm(3)*r(20,cc,ck) + &
               (-2.0_dp)*cm(4)*r(21,cc,ck) + (-2.0_dp)*cm(6)*r(22,cc,ck)
            res(15,cc+ncb*(ck-1)) = (-2.0_dp)*cm(2)*r(23,cc,ck) + 2.0_dp*cm(5)*r(24,cc,ck)
            res(16,cc+ncb*(ck-1)) = (-6.0_dp)*r(25,cc,ck) + 2.0_dp*cm(4)*r(26,cc,ck)
            res(17,cc+ncb*(ck-1)) = (-2.0_dp)*cm(2)*r(27,cc,ck) + 2.0_dp*cm(5)*r(28,cc,ck)
            res(18,cc+ncb*(ck-1)) = 2.0_dp*r(29,cc,ck) + (-2.0_dp)*cm(4)*r(30,cc,ck)
            res(19,cc+ncb*(ck-1)) = 6.0_dp*cm(2)*r(31,cc,ck)
            res(20,cc+ncb*(ck-1)) = 2.0_dp*r(32,cc,ck) + 2.0_dp*cm(3)*r(33,cc,ck)
            res(21,cc+ncb*(ck-1)) = (-2.0_dp)*cm(2)*r(34,cc,ck)
            res(22,cc+ncb*(ck-1)) = 2.0_dp*r(35,cc,ck) + 2.0_dp*cm(3)*r(36,cc,ck)
            res(23,cc+ncb*(ck-1)) = 6.0_dp*cm(2)*r(37,cc,ck) + 2.0_dp*cm(7)*r(38,cc,ck)
            res(24,cc+ncb*(ck-1)) = (-2.0_dp)*r(39,cc,ck) + (-2.0_dp)*cm(3)*r(40,cc,ck)
            res(25,cc+ncb*(ck-1)) = (-2.0_dp)*cm(2)*r(41,cc,ck)
            res(26,cc+ncb*(ck-1)) = (-2.0_dp)*r(42,cc,ck) + (-2.0_dp)*cm(3)*r(43,cc,ck)
            res(27,cc+ncb*(ck-1)) = 2.0_dp*cm(2)*r(44,cc,ck)
            res(28,cc+ncb*(ck-1)) = (-6.0_dp)*r(45,cc,ck) + (-6.0_dp)*cm(8)*r(12,cc,ck)
            res(29,cc+ncb*(ck-1)) = (-2.0_dp)*cm(2)*r(46,cc,ck) + (-2.0_dp)*cm(9)*r(14,cc,ck)
            res(30,cc+ncb*(ck-1)) = 2.0_dp*r(47,cc,ck) + 2.0_dp*cm(8)*r(16,cc,ck)
            res(31,cc+ncb*(ck-1)) = (-2.0_dp)*cm(2)*r(48,cc,ck) + (-2.0_dp)*cm(9)*r(18,cc,ck)
            res(32,cc+ncb*(ck-1)) = (-2.0_dp)*r(49,cc,ck) + (-2.0_dp)*cm(3)*r(50,cc,ck) + &
               (-2.0_dp)*cm(8)*r(21,cc,ck) + (-2.0_dp)*cm(10)*r(22,cc,ck)
            res(33,cc+ncb*(ck-1)) = 2.0_dp*cm(2)*r(51,cc,ck) + 2.0_dp*cm(9)*r(24,cc,ck)
            res(34,cc+ncb*(ck-1)) = 2.0_dp*r(52,cc,ck) + 2.0_dp*cm(8)*r(26,cc,ck)
            res(35,cc+ncb*(ck-1)) = 2.0_dp*cm(2)*r(53,cc,ck) + 2.0_dp*cm(9)*r(28,cc,ck)
            res(36,cc+ncb*(ck-1)) = (-2.0_dp)*r(54,cc,ck) + (-2.0_dp)*cm(8)*r(30,cc,ck)
            res(37,cc+ncb*(ck-1)) = 2.0_dp*cm(2)*r(2,cc,ck)
            res(38,cc+ncb*(ck-1)) = 2.0_dp*r(55,cc,ck) + 2.0_dp*cm(3)*r(6,cc,ck)
            res(39,cc+ncb*(ck-1)) = (-2.0_dp)*cm(2)*r(7,cc,ck)
            res(40,cc+ncb*(ck-1)) = 2.0_dp*r(5,cc,ck) + 2.0_dp*cm(3)*r(6,cc,ck)
            res(41,cc+ncb*(ck-1)) = 6.0_dp*cm(2)*r(56,cc,ck) + 2.0_dp*cm(7)*r(57,cc,ck)
            res(42,cc+ncb*(ck-1)) = (-2.0_dp)*r(58,cc,ck) + (-2.0_dp)*cm(3)*r(59,cc,ck)
            res(43,cc+ncb*(ck-1)) = (-2.0_dp)*cm(2)*r(9,cc,ck)
            res(44,cc+ncb*(ck-1)) = (-2.0_dp)*r(60,cc,ck) + (-2.0_dp)*cm(3)*r(61,cc,ck)
            res(45,cc+ncb*(ck-1)) = 2.0_dp*cm(2)*r(62,cc,ck)
            res(46,cc+ncb*(ck-1)) = 6.0_dp*cm(2)*r(13,cc,ck) + (-2.0_dp)*cm(5)*r(14,cc,ck)
            res(47,cc+ncb*(ck-1)) = 2.0_dp*r(63,cc,ck) + 2.0_dp*cm(3)*r(20,cc,ck) + &
               (-2.0_dp)*cm(4)*r(64,cc,ck) + (-2.0_dp)*cm(6)*r(22,cc,ck)
            res(48,cc+ncb*(ck-1)) = (-2.0_dp)*cm(2)*r(23,cc,ck) + 2.0_dp*cm(5)*r(24,cc,ck)
            res(49,cc+ncb*(ck-1)) = 2.0_dp*r(19,cc,ck) + 2.0_dp*cm(3)*r(20,cc,ck) + &
               (-2.0_dp)*cm(4)*r(21,cc,ck) + (-2.0_dp)*cm(6)*r(22,cc,ck)
            res(50,cc+ncb*(ck-1)) = 6.0_dp*cm(2)*r(65,cc,ck) + (-6.0_dp)*cm(5)*r(66,cc,ck) + &
               2.0_dp*cm(7)*r(38,cc,ck) + (-2.0_dp)*cm(11)*r(67,cc,ck)
            res(51,cc+ncb*(ck-1)) = (-2.0_dp)*r(68,cc,ck) + (-2.0_dp)*cm(3)*r(40,cc,ck) + &
               2.0_dp*cm(4)*r(69,cc,ck) + 2.0_dp*cm(6)*r(70,cc,ck)
            res(52,cc+ncb*(ck-1)) = (-2.0_dp)*cm(2)*r(27,cc,ck) + 2.0_dp*cm(5)*r(28,cc,ck)
            res(53,cc+ncb*(ck-1)) = (-2.0_dp)*r(71,cc,ck) + (-2.0_dp)*cm(3)*r(43,cc,ck) + &
               2.0_dp*cm(4)*r(72,cc,ck) + 2.0_dp*cm(6)*r(73,cc,ck)
            res(54,cc+ncb*(ck-1)) = 2.0_dp*cm(2)*r(44,cc,ck) + (-2.0_dp)*cm(5)*r(74,cc,ck)
            res(55,cc+ncb*(ck-1)) = 2.0_dp*r(32,cc,ck) + 2.0_dp*cm(3)*r(33,cc,ck)
            res(56,cc+ncb*(ck-1)) = 6.0_dp*cm(2)*r(75,cc,ck) + 2.0_dp*cm(7)*r(38,cc,ck)
            res(57,cc+ncb*(ck-1)) = (-2.0_dp)*r(39,cc,ck) + (-2.0_dp)*cm(3)*r(40,cc,ck)
            res(58,cc+ncb*(ck-1)) = 6.0_dp*cm(2)*r(37,cc,ck) + 2.0_dp*cm(7)*r(38,cc,ck)
            res(59,cc+ncb*(ck-1)) = 6.0_dp*r(76,cc,ck) + 12.0_dp*cm(3)*r(77,cc,ck) + &
               2.0_dp*cm(12)*r(78,cc,ck)
            res(60,cc+ncb*(ck-1)) = (-6.0_dp)*cm(2)*r(79,cc,ck) + (-2.0_dp)*cm(7)*r(80,cc,ck)
            res(61,cc+ncb*(ck-1)) = (-2.0_dp)*r(42,cc,ck) + (-2.0_dp)*cm(3)*r(43,cc,ck)
            res(62,cc+ncb*(ck-1)) = (-6.0_dp)*cm(2)*r(81,cc,ck) + (-2.0_dp)*cm(7)*r(82,cc,ck)
            res(63,cc+ncb*(ck-1)) = 2.0_dp*r(83,cc,ck) + 2.0_dp*cm(3)*r(84,cc,ck)
            res(64,cc+ncb*(ck-1)) = (-2.0_dp)*cm(2)*r(46,cc,ck) + (-2.0_dp)*cm(9)*r(14,cc,ck)
            res(65,cc+ncb*(ck-1)) = (-2.0_dp)*r(85,cc,ck) + (-2.0_dp)*cm(3)*r(50,cc,ck) + &
               (-2.0_dp)*cm(8)*r(64,cc,ck) + (-2.0_dp)*cm(10)*r(22,cc,ck)
            res(66,cc+ncb*(ck-1)) = 2.0_dp*cm(2)*r(51,cc,ck) + 2.0_dp*cm(9)*r(24,cc,ck)
            res(67,cc+ncb*(ck-1)) = (-2.0_dp)*r(49,cc,ck) + (-2.0_dp)*cm(3)*r(50,cc,ck) + &
               (-2.0_dp)*cm(8)*r(21,cc,ck) + (-2.0_dp)*cm(10)*r(22,cc,ck)
            res(68,cc+ncb*(ck-1)) = (-6.0_dp)*cm(2)*r(86,cc,ck) + (-2.0_dp)*cm(7)*r(87,cc,ck) + &
               (-6.0_dp)*cm(9)*r(66,cc,ck) + (-2.0_dp)*cm(13)*r(67,cc,ck)
            res(69,cc+ncb*(ck-1)) = 2.0_dp*r(88,cc,ck) + 2.0_dp*cm(3)*r(89,cc,ck) + &
               2.0_dp*cm(8)*r(69,cc,ck) + 2.0_dp*cm(10)*r(70,cc,ck)
            res(70,cc+ncb*(ck-1)) = 2.0_dp*cm(2)*r(53,cc,ck) + 2.0_dp*cm(9)*r(28,cc,ck)
            res(71,cc+ncb*(ck-1)) = 2.0_dp*r(90,cc,ck) + 2.0_dp*cm(3)*r(91,cc,ck) + &
               2.0_dp*cm(8)*r(72,cc,ck) + 2.0_dp*cm(10)*r(73,cc,ck)
            res(72,cc+ncb*(ck-1)) = (-2.0_dp)*cm(2)*r(92,cc,ck) + (-2.0_dp)*cm(9)*r(74,cc,ck)
            res(73,cc+ncb*(ck-1)) = (-2.0_dp)*r(3,cc,ck)
            res(74,cc+ncb*(ck-1)) = (-2.0_dp)*cm(2)*r(7,cc,ck)
            res(75,cc+ncb*(ck-1)) = 2.0_dp*r(93,cc,ck)
            res(76,cc+ncb*(ck-1)) = (-2.0_dp)*cm(2)*r(7,cc,ck)
            res(77,cc+ncb*(ck-1)) = (-2.0_dp)*r(58,cc,ck) + (-2.0_dp)*cm(3)*r(59,cc,ck)
            res(78,cc+ncb*(ck-1)) = 2.0_dp*cm(2)*r(94,cc,ck)
            res(79,cc+ncb*(ck-1)) = 2.0_dp*r(10,cc,ck)
            res(80,cc+ncb*(ck-1)) = 2.0_dp*cm(2)*r(62,cc,ck)
            res(81,cc+ncb*(ck-1)) = (-4.0_dp)*r(95,cc,ck)
            res(82,cc+ncb*(ck-1)) = (-6.0_dp)*r(15,cc,ck) + 2.0_dp*cm(4)*r(16,cc,ck)
            res(83,cc+ncb*(ck-1)) = (-2.0_dp)*cm(2)*r(23,cc,ck) + 2.0_dp*cm(5)*r(24,cc,ck)
            res(84,cc+ncb*(ck-1)) = 2.0_dp*r(96,cc,ck) + (-2.0_dp)*cm(4)*r(97,cc,ck)
            res(85,cc+ncb*(ck-1)) = (-2.0_dp)*cm(2)*r(23,cc,ck) + 2.0_dp*cm(5)*r(24,cc,ck)
            res(86,cc+ncb*(ck-1)) = (-2.0_dp)*r(68,cc,ck) + (-2.0_dp)*cm(3)*r(40,cc,ck) + &
               2.0_dp*cm(4)*r(69,cc,ck) + 2.0_dp*cm(6)*r(70,cc,ck)
            res(87,cc+ncb*(ck-1)) = 2.0_dp*cm(2)*r(98,cc,ck) + (-2.0_dp)*cm(5)*r(99,cc,ck)
            res(88,cc+ncb*(ck-1)) = 2.0_dp*r(29,cc,ck) + (-2.0_dp)*cm(4)*r(30,cc,ck)
            res(89,cc+ncb*(ck-1)) = 2.0_dp*cm(2)*r(44,cc,ck) + (-2.0_dp)*cm(5)*r(74,cc,ck)
            res(90,cc+ncb*(ck-1)) = (-4.0_dp)*r(100,cc,ck) + 4.0_dp*cm(4)*r(101,cc,ck)
            res(91,cc+ncb*(ck-1)) = (-2.0_dp)*cm(2)*r(34,cc,ck)
            res(92,cc+ncb*(ck-1)) = (-2.0_dp)*r(39,cc,ck) + (-2.0_dp)*cm(3)*r(40,cc,ck)
            res(93,cc+ncb*(ck-1)) = 2.0_dp*cm(2)*r(98,cc,ck)
            res(94,cc+ncb*(ck-1)) = (-2.0_dp)*r(39,cc,ck) + (-2.0_dp)*cm(3)*r(40,cc,ck)
            res(95,cc+ncb*(ck-1)) = (-6.0_dp)*cm(2)*r(79,cc,ck) + (-2.0_dp)*cm(7)*r(80,cc,ck)
            res(96,cc+ncb*(ck-1)) = 2.0_dp*r(102,cc,ck) + 2.0_dp*cm(3)*r(103,cc,ck)
            res(97,cc+ncb*(ck-1)) = 2.0_dp*cm(2)*r(44,cc,ck)
            res(98,cc+ncb*(ck-1)) = 2.0_dp*r(83,cc,ck) + 2.0_dp*cm(3)*r(84,cc,ck)
            res(99,cc+ncb*(ck-1)) = (-4.0_dp)*cm(2)*r(104,cc,ck)
            res(100,cc+ncb*(ck-1)) = 2.0_dp*r(47,cc,ck) + 2.0_dp*cm(8)*r(16,cc,ck)
            res(101,cc+ncb*(ck-1)) = 2.0_dp*cm(2)*r(51,cc,ck) + 2.0_dp*cm(9)*r(24,cc,ck)
            res(102,cc+ncb*(ck-1)) = (-4.0_dp)*r(105,cc,ck) + (-2.0_dp)*cm(8)*r(97,cc,ck)
            res(103,cc+ncb*(ck-1)) = 2.0_dp*cm(2)*r(51,cc,ck) + 2.0_dp*cm(9)*r(24,cc,ck)
            res(104,cc+ncb*(ck-1)) = 2.0_dp*r(88,cc,ck) + 2.0_dp*cm(3)*r(89,cc,ck) + &
               2.0_dp*cm(8)*r(69,cc,ck) + 2.0_dp*cm(10)*r(70,cc,ck)
            res(105,cc+ncb*(ck-1)) = (-4.0_dp)*cm(2)*r(106,cc,ck) + (-2.0_dp)*cm(9)*r(99,cc,ck)
            res(106,cc+ncb*(ck-1)) = (-2.0_dp)*r(54,cc,ck) + (-2.0_dp)*cm(8)*r(30,cc,ck)
            res(107,cc+ncb*(ck-1)) = (-2.0_dp)*cm(2)*r(92,cc,ck) + (-2.0_dp)*cm(9)*r(74,cc,ck)
            res(108,cc+ncb*(ck-1)) = 6.0_dp*r(107,cc,ck) + 4.0_dp*cm(8)*r(101,cc,ck)
         end do
      end do
   end subroutine rotaxis_grad_ppsL

end module rotaxis_grad_ppsL_m
