! GENERATED by scripts/rotaxis_mmd -- do not edit.
! Lsps: L=3 comps=36 S=30 g=6 r=40 (terms 100) km=7 cm=10 assembly terms=70
module rotaxis_grad_Lsps_m
   use cint_const, only: dp
   use cint_rotaxis_boys, only: boys
   implicit none
   private
   public :: rotaxis_grad_Lsps
contains
   ! (Ls|ps)  L=3: 30 bra accumulators, 40 ket accumulators, 36 components
   subroutine rotaxis_grad_Lsps(nbra, ncb, bp, kab, nket, nck, kp, kcd, gc, cutoff, res, any)
      integer,  intent(in)  :: nbra, ncb, nket, nck
      real(dp), intent(in)  :: bp(6, nbra), kab(2*ncb, nbra)
      real(dp), intent(in)  :: kp(7, nket), kcd(1*nck, nket), gc(3), cutoff
      real(dp), intent(out) :: res(36, ncb*nck)
      logical,  intent(out) :: any
      real(dp) :: s(30, ncb), r(40, ncb, nck), t(40)
      real(dp) :: f(0:3), b(0:3)
      real(dp) :: p, ip, za, zb, eab, q, iq, yc, yd, ax, az, ecd
      real(dp) :: zq, alpha, tt, w, m2a, Rs, Rc, cy, ea
      real(dp) :: g(6), km(7), cm(10), zq2, zq3
      integer :: kq, bq, cc, ck, n

      Rs = gc(1); Rc = gc(2); cy = gc(3)
      any = .false.
      r = 0.0_dp
      do kq = 1, nket
         q = kp(1,kq); iq = kp(2,kq); yc = kp(3,kq); yd = kp(4,kq)
         ax = kp(5,kq); az = kp(6,kq); ecd = kp(7,kq)
         s = 0.0_dp
         do bq = 1, nbra
            eab = bp(5,bq)
            if (eab + ecd > cutoff) cycle
            any = .true.
            p = bp(1,bq); ip = bp(2,bq); za = bp(3,bq); zb = bp(4,bq)
            ea = bp(6,bq)
            zq = za - az
            alpha = p*q/(p + q)
            tt = alpha*(ax*ax + cy*cy + zq*zq)
            call boys(f, tt, 3)
            w = 1.0_dp/sqrt(p + q)
            m2a = -2.0_dp*alpha
            do n = 0, 3
               b(n) = w*f(n)
               w = w*m2a
            end do
            zq2 = zq*zq
            zq3 = zq2*zq
            g(1) = ip*ea
            g(2) = ip*ip*ea
            g(3) = 1.0_dp
            g(4) = ip*za*ea
            g(5) = za*ea
            g(6) = za*za*ea
            do cc = 1, ncb
               s(1,cc) = s(1,cc) + kab(1+2*(cc-1),bq)*g(1)*b(1)
               s(2,cc) = s(2,cc) + kab(1+2*(cc-1),bq)*g(1)*b(2)
               s(3,cc) = s(3,cc) + kab(2+2*(cc-1),bq)*g(1)*b(0)
               s(4,cc) = s(4,cc) + kab(2+2*(cc-1),bq)*g(1)*b(1)
               s(5,cc) = s(5,cc) + kab(2+2*(cc-1),bq)*g(2)*b(2)
               s(6,cc) = s(6,cc) + kab(2+2*(cc-1),bq)*g(2)*b(1)
               s(7,cc) = s(7,cc) + kab(2+2*(cc-1),bq)*g(2)*b(3)
               s(8,cc) = s(8,cc) + kab(2+2*(cc-1),bq)*b(0)
               s(9,cc) = s(9,cc) + kab(2+2*(cc-1),bq)*b(1)
               s(10,cc) = s(10,cc) + kab(2+2*(cc-1),bq)*g(4)*b(1)
               s(11,cc) = s(11,cc) + kab(2+2*(cc-1),bq)*g(2)*b(2)*zq
               s(12,cc) = s(12,cc) + kab(2+2*(cc-1),bq)*g(4)*b(2)
               s(13,cc) = s(13,cc) + kab(2+2*(cc-1),bq)*g(2)*b(3)*zq
               s(14,cc) = s(14,cc) + kab(1+2*(cc-1),bq)*g(1)*b(2)*zq
               s(15,cc) = s(15,cc) + kab(2+2*(cc-1),bq)*g(1)*b(1)*zq
               s(16,cc) = s(16,cc) + kab(2+2*(cc-1),bq)*b(1)*zq
               s(17,cc) = s(17,cc) + kab(2+2*(cc-1),bq)*g(4)*b(2)*zq
               s(18,cc) = s(18,cc) + kab(2+2*(cc-1),bq)*g(2)*b(3)*zq2
               s(19,cc) = s(19,cc) + kab(1+2*(cc-1),bq)*g(5)*b(0)
               s(20,cc) = s(20,cc) + kab(1+2*(cc-1),bq)*g(1)*b(1)*zq
               s(21,cc) = s(21,cc) + kab(1+2*(cc-1),bq)*g(5)*b(1)
               s(22,cc) = s(22,cc) + kab(2+2*(cc-1),bq)*g(6)*b(0)
               s(23,cc) = s(23,cc) + kab(2+2*(cc-1),bq)*g(4)*b(1)*zq
               s(24,cc) = s(24,cc) + kab(2+2*(cc-1),bq)*g(2)*b(2)*zq2
               s(25,cc) = s(25,cc) + kab(2+2*(cc-1),bq)*g(6)*b(1)
               s(26,cc) = s(26,cc) + kab(1+2*(cc-1),bq)*g(5)*b(1)*zq
               s(27,cc) = s(27,cc) + kab(1+2*(cc-1),bq)*g(1)*b(2)*zq2
               s(28,cc) = s(28,cc) + kab(2+2*(cc-1),bq)*g(6)*b(1)*zq
               s(29,cc) = s(29,cc) + kab(2+2*(cc-1),bq)*g(4)*b(2)*zq2
               s(30,cc) = s(30,cc) + kab(2+2*(cc-1),bq)*g(2)*b(3)*zq3
            end do
         end do
         if (.not. any) cycle
         km(1) = yd*ax
         km(2) = iq*ax*ax
         km(3) = iq
         km(4) = yd
         km(5) = iq*ax
         km(6) = yd*ax*ax
         km(7) = iq*ax*ax*ax
         do cc = 1, ncb
            t(1) = km(1)*s(1,cc)
            t(2) = km(2)*s(2,cc) + km(3)*s(1,cc)
            t(3) = km(4)*(s(3,cc) + s(6,cc) + (-1.0_dp/2.0_dp)*s(8,cc)) + km(6)*s(5,cc)
            t(4) = km(5)*(s(4,cc) + 3.0_dp*s(5,cc) + (-1.0_dp/2.0_dp)*s(9,cc)) + km(7)*s(7,cc)
            t(5) = km(1)*s(5,cc)
            t(6) = km(2)*s(7,cc) + km(3)*s(5,cc)
            t(7) = km(1)*(s(10,cc) + s(11,cc))
            t(8) = km(2)*(s(12,cc) + s(13,cc)) + km(3)*(s(10,cc) + s(11,cc))
            t(9) = km(5)*s(2,cc)
            t(10) = km(2)*s(7,cc) + km(3)*(s(4,cc) + s(5,cc) + (-1.0_dp/2.0_dp)*s(9,cc))
            t(11) = km(5)*s(5,cc)
            t(12) = km(5)*s(7,cc)
            t(13) = km(5)*(s(12,cc) + s(13,cc))
            t(14) = km(5)*s(14,cc)
            t(15) = km(2)*s(13,cc) + km(3)*(s(11,cc) + s(15,cc) + (-1.0_dp/2.0_dp)*s(16,cc))
            t(16) = km(5)*s(13,cc)
            t(17) = km(5)*(s(5,cc) + s(17,cc) + s(18,cc))
            t(18) = km(4)*s(1,cc)
            t(19) = km(4)*(s(3,cc) + s(6,cc) + (-1.0_dp/2.0_dp)*s(8,cc))
            t(20) = km(5)*(s(4,cc) + s(5,cc) + (-1.0_dp/2.0_dp)*s(9,cc))
            t(21) = km(4)*s(5,cc)
            t(22) = km(4)*(s(10,cc) + s(11,cc))
            t(23) = km(3)*s(1,cc)
            t(24) = km(3)*s(2,cc)
            t(25) = km(3)*(s(4,cc) + 3.0_dp*s(5,cc) + (-1.0_dp/2.0_dp)*s(9,cc))
            t(26) = km(3)*s(7,cc)
            t(27) = km(3)*(s(10,cc) + s(11,cc))
            t(28) = km(3)*(s(12,cc) + s(13,cc))
            t(29) = km(3)*s(14,cc)
            t(30) = km(3)*(s(11,cc) + s(15,cc) + (-1.0_dp/2.0_dp)*s(16,cc))
            t(31) = km(3)*s(13,cc)
            t(32) = km(3)*(s(5,cc) + s(17,cc) + s(18,cc))
            t(33) = km(4)*(s(19,cc) + s(20,cc))
            t(34) = km(5)*(s(14,cc) + s(21,cc))
            t(35) = km(4)*(s(3,cc) + s(6,cc) + (-1.0_dp/2.0_dp)*s(8,cc) + s(22,cc) + &
               2.0_dp*s(23,cc) + s(24,cc))
            t(36) = km(5)*(s(4,cc) + s(5,cc) + (-1.0_dp/2.0_dp)*s(9,cc) + 2.0_dp*s(17,cc) + &
               s(18,cc) + s(25,cc))
            t(37) = km(3)*(s(14,cc) + s(21,cc))
            t(38) = km(3)*(s(4,cc) + s(5,cc) + (-1.0_dp/2.0_dp)*s(9,cc) + 2.0_dp*s(17,cc) + &
               s(18,cc) + s(25,cc))
            t(39) = km(3)*(s(1,cc) + s(26,cc) + s(27,cc))
            t(40) = km(3)*(s(10,cc) + (3.0_dp/2.0_dp)*s(11,cc) + (1.0_dp/2.0_dp)*s(15,cc) + &
               (-1.0_dp/4.0_dp)*s(16,cc) + (1.0_dp/2.0_dp)*s(28,cc) + s(29,cc) + &
               (1.0_dp/2.0_dp)*s(30,cc))
            do ck = 1, nck
               r(1:40,cc,ck) = r(1:40,cc,ck) + kcd(ck,kq)*t(1:40)
            end do
         end do
      end do
      res = 0.0_dp
      if (.not. any) return
      cm(1) = Rs
      cm(2) = 1.0_dp
      cm(3) = Rs*cy
      cm(4) = cy
      cm(5) = cy*cy
      cm(6) = Rc
      cm(7) = Rc*cy
      cm(8) = Rs*cy*cy
      cm(9) = cy*cy*cy
      cm(10) = Rc*cy*cy
      do ck = 1, nck
         do cc = 1, ncb
            res(1,cc+ncb*(ck-1)) = 2.0_dp*cm(1)*r(1,cc,ck) + 2.0_dp*r(2,cc,ck)
            res(2,cc+ncb*(ck-1)) = (-2.0_dp)*cm(1)*r(3,cc,ck) + (-2.0_dp)*r(4,cc,ck)
            res(3,cc+ncb*(ck-1)) = (-2.0_dp)*cm(3)*r(5,cc,ck) + (-2.0_dp)*cm(4)*r(6,cc,ck)
            res(4,cc+ncb*(ck-1)) = 2.0_dp*cm(1)*r(7,cc,ck) + 2.0_dp*r(8,cc,ck)
            res(5,cc+ncb*(ck-1)) = 2.0_dp*cm(4)*r(9,cc,ck)
            res(6,cc+ncb*(ck-1)) = (-2.0_dp)*cm(4)*r(10,cc,ck)
            res(7,cc+ncb*(ck-1)) = (-2.0_dp)*r(11,cc,ck) + (-2.0_dp)*cm(5)*r(12,cc,ck)
            res(8,cc+ncb*(ck-1)) = 2.0_dp*cm(4)*r(13,cc,ck)
            res(9,cc+ncb*(ck-1)) = (-2.0_dp)*r(14,cc,ck) + 2.0_dp*cm(6)*r(1,cc,ck)
            res(10,cc+ncb*(ck-1)) = 2.0_dp*r(15,cc,ck) + (-2.0_dp)*cm(6)*r(3,cc,ck)
            res(11,cc+ncb*(ck-1)) = 2.0_dp*cm(4)*r(16,cc,ck) + (-2.0_dp)*cm(7)*r(5,cc,ck)
            res(12,cc+ncb*(ck-1)) = (-2.0_dp)*r(17,cc,ck) + 2.0_dp*cm(6)*r(7,cc,ck)
            res(13,cc+ncb*(ck-1)) = 2.0_dp*cm(3)*r(18,cc,ck) + 2.0_dp*cm(4)*r(9,cc,ck)
            res(14,cc+ncb*(ck-1)) = (-2.0_dp)*cm(3)*r(5,cc,ck) + (-2.0_dp)*cm(4)*r(6,cc,ck)
            res(15,cc+ncb*(ck-1)) = (-2.0_dp)*cm(1)*r(19,cc,ck) + (-2.0_dp)*r(20,cc,ck) + &
               (-2.0_dp)*cm(5)*r(12,cc,ck) + (-2.0_dp)*cm(8)*r(21,cc,ck)
            res(16,cc+ncb*(ck-1)) = 2.0_dp*cm(3)*r(22,cc,ck) + 2.0_dp*cm(4)*r(13,cc,ck)
            res(17,cc+ncb*(ck-1)) = 2.0_dp*r(23,cc,ck) + 2.0_dp*cm(5)*r(24,cc,ck)
            res(18,cc+ncb*(ck-1)) = (-2.0_dp)*r(11,cc,ck) + (-2.0_dp)*cm(5)*r(12,cc,ck)
            res(19,cc+ncb*(ck-1)) = (-2.0_dp)*cm(4)*r(25,cc,ck) + (-2.0_dp)*cm(9)*r(26,cc,ck)
            res(20,cc+ncb*(ck-1)) = 2.0_dp*r(27,cc,ck) + 2.0_dp*cm(5)*r(28,cc,ck)
            res(21,cc+ncb*(ck-1)) = (-2.0_dp)*cm(4)*r(29,cc,ck) + 2.0_dp*cm(7)*r(18,cc,ck)
            res(22,cc+ncb*(ck-1)) = 2.0_dp*cm(4)*r(16,cc,ck) + (-2.0_dp)*cm(7)*r(5,cc,ck)
            res(23,cc+ncb*(ck-1)) = 2.0_dp*r(30,cc,ck) + 2.0_dp*cm(5)*r(31,cc,ck) + &
               (-2.0_dp)*cm(6)*r(19,cc,ck) + (-2.0_dp)*cm(10)*r(21,cc,ck)
            res(24,cc+ncb*(ck-1)) = (-2.0_dp)*cm(4)*r(32,cc,ck) + 2.0_dp*cm(7)*r(22,cc,ck)
            res(25,cc+ncb*(ck-1)) = (-2.0_dp)*cm(1)*r(33,cc,ck) + (-2.0_dp)*r(34,cc,ck)
            res(26,cc+ncb*(ck-1)) = 2.0_dp*cm(1)*r(7,cc,ck) + 2.0_dp*r(8,cc,ck)
            res(27,cc+ncb*(ck-1)) = 2.0_dp*cm(3)*r(22,cc,ck) + 2.0_dp*cm(4)*r(13,cc,ck)
            res(28,cc+ncb*(ck-1)) = (-2.0_dp)*cm(1)*r(35,cc,ck) + (-2.0_dp)*r(36,cc,ck)
            res(29,cc+ncb*(ck-1)) = (-2.0_dp)*cm(4)*r(37,cc,ck)
            res(30,cc+ncb*(ck-1)) = 2.0_dp*cm(4)*r(13,cc,ck)
            res(31,cc+ncb*(ck-1)) = 2.0_dp*r(27,cc,ck) + 2.0_dp*cm(5)*r(28,cc,ck)
            res(32,cc+ncb*(ck-1)) = (-2.0_dp)*cm(4)*r(38,cc,ck)
            res(33,cc+ncb*(ck-1)) = 2.0_dp*r(39,cc,ck) + (-2.0_dp)*cm(6)*r(33,cc,ck)
            res(34,cc+ncb*(ck-1)) = (-2.0_dp)*r(17,cc,ck) + 2.0_dp*cm(6)*r(7,cc,ck)
            res(35,cc+ncb*(ck-1)) = (-2.0_dp)*cm(4)*r(32,cc,ck) + 2.0_dp*cm(7)*r(22,cc,ck)
            res(36,cc+ncb*(ck-1)) = 4.0_dp*r(40,cc,ck) + (-2.0_dp)*cm(6)*r(35,cc,ck)
         end do
      end do
   end subroutine rotaxis_grad_Lsps

end module rotaxis_grad_Lsps_m
