! GENERATED by scripts/rotaxis_mmd -- do not edit.
! psds: L=4 comps=54 S=40 g=5 r=76 (terms 321) km=15 cm=22 assembly terms=175
module rotaxis_grad_psds_m
   use cint_const, only: dp
   use cint_rotaxis_boys, only: boys
   implicit none
   private
   public :: rotaxis_grad_psds
contains
   ! (ps|ds)  L=4: 40 bra accumulators, 76 ket accumulators, 54 components
   subroutine rotaxis_grad_psds(nbra, ncb, bp, kab, nket, nck, kp, kcd, gc, cutoff, res, any)
      integer,  intent(in)  :: nbra, ncb, nket, nck
      real(dp), intent(in)  :: bp(6, nbra), kab(1*ncb, nbra)
      real(dp), intent(in)  :: kp(7, nket), kcd(1*nck, nket), gc(3), cutoff
      real(dp), intent(out) :: res(54, ncb*nck)
      logical,  intent(out) :: any
      real(dp) :: s(40, ncb), r(76, ncb, nck), t(76)
      real(dp) :: f(0:4), b(0:4)
      real(dp) :: p, ip, za, zb, eab, q, iq, yc, yd, ax, az, ecd
      real(dp) :: zq, alpha, tt, w, m2a, Rs, Rc, cy, ea
      real(dp) :: g(5), km(15), cm(22), zq2, zq3, zq4
      integer :: kq, bq, cc, ck, n

      Rs = gc(1); Rc = gc(2); cy = gc(3)
      any = .false.
      r = 0.0_dp
      do kq = 1, nket
         q = kp(1,kq); iq = kp(2,kq); yc = kp(3,kq); yd = kp(4,kq)
         ax = kp(5,kq); az = kp(6,kq); ecd = kp(7,kq)
         s = 0.0_dp
         do bq = 1, nbra
            eab = bp(5,bq)
            if (eab + ecd > cutoff) cycle
            any = .true.
            p = bp(1,bq); ip = bp(2,bq); za = bp(3,bq); zb = bp(4,bq)
            ea = bp(6,bq)
            zq = za - az
            alpha = p*q/(p + q)
            tt = alpha*(ax*ax + cy*cy + zq*zq)
            call boys(f, tt, 4)
            w = 1.0_dp/sqrt(p + q)
            m2a = -2.0_dp*alpha
            do n = 0, 4
               b(n) = w*f(n)
               w = w*m2a
            end do
            zq2 = zq*zq
            zq3 = zq2*zq
            zq4 = zq3*zq
            g(1) = ip*ea
            g(2) = ip*ip*ea
            g(3) = 1.0_dp
            g(4) = ip*za*ea
            g(5) = za*za*ea
            do cc = 1, ncb
               s(1,cc) = s(1,cc) + kab(cc,bq)*g(1)*b(0)
               s(2,cc) = s(2,cc) + kab(cc,bq)*g(1)*b(1)
               s(3,cc) = s(3,cc) + kab(cc,bq)*g(1)*b(2)
               s(4,cc) = s(4,cc) + kab(cc,bq)*g(2)*b(2)
               s(5,cc) = s(5,cc) + kab(cc,bq)*g(2)*b(1)
               s(6,cc) = s(6,cc) + kab(cc,bq)*g(2)*b(3)
               s(7,cc) = s(7,cc) + kab(cc,bq)*g(2)*b(4)
               s(8,cc) = s(8,cc) + kab(cc,bq)*b(0)
               s(9,cc) = s(9,cc) + kab(cc,bq)*b(1)
               s(10,cc) = s(10,cc) + kab(cc,bq)*b(2)
               s(11,cc) = s(11,cc) + kab(cc,bq)*g(4)*b(1)
               s(12,cc) = s(12,cc) + kab(cc,bq)*g(2)*b(2)*zq
               s(13,cc) = s(13,cc) + kab(cc,bq)*g(4)*b(2)
               s(14,cc) = s(14,cc) + kab(cc,bq)*g(2)*b(3)*zq
               s(15,cc) = s(15,cc) + kab(cc,bq)*g(4)*b(3)
               s(16,cc) = s(16,cc) + kab(cc,bq)*g(2)*b(4)*zq
               s(17,cc) = s(17,cc) + kab(cc,bq)*g(1)*b(1)*zq
               s(18,cc) = s(18,cc) + kab(cc,bq)*g(1)*b(2)*zq
               s(19,cc) = s(19,cc) + kab(cc,bq)*b(1)*zq
               s(20,cc) = s(20,cc) + kab(cc,bq)*b(2)*zq
               s(21,cc) = s(21,cc) + kab(cc,bq)*g(4)*b(2)*zq
               s(22,cc) = s(22,cc) + kab(cc,bq)*g(2)*b(3)*zq2
               s(23,cc) = s(23,cc) + kab(cc,bq)*g(4)*b(3)*zq
               s(24,cc) = s(24,cc) + kab(cc,bq)*g(2)*b(4)*zq2
               s(25,cc) = s(25,cc) + kab(cc,bq)*g(1)*b(2)*zq2
               s(26,cc) = s(26,cc) + kab(cc,bq)*b(2)*zq2
               s(27,cc) = s(27,cc) + kab(cc,bq)*g(4)*b(3)*zq2
               s(28,cc) = s(28,cc) + kab(cc,bq)*g(2)*b(4)*zq3
               s(29,cc) = s(29,cc) + kab(cc,bq)*g(5)*b(0)
               s(30,cc) = s(30,cc) + kab(cc,bq)*g(4)*b(1)*zq
               s(31,cc) = s(31,cc) + kab(cc,bq)*g(2)*b(2)*zq2
               s(32,cc) = s(32,cc) + kab(cc,bq)*g(5)*b(1)
               s(33,cc) = s(33,cc) + kab(cc,bq)*g(5)*b(2)
               s(34,cc) = s(34,cc) + kab(cc,bq)*g(5)*b(1)*zq
               s(35,cc) = s(35,cc) + kab(cc,bq)*g(4)*b(2)*zq2
               s(36,cc) = s(36,cc) + kab(cc,bq)*g(2)*b(3)*zq3
               s(37,cc) = s(37,cc) + kab(cc,bq)*g(5)*b(2)*zq
               s(38,cc) = s(38,cc) + kab(cc,bq)*g(5)*b(2)*zq2
               s(39,cc) = s(39,cc) + kab(cc,bq)*g(4)*b(3)*zq3
               s(40,cc) = s(40,cc) + kab(cc,bq)*g(2)*b(4)*zq4
            end do
         end do
         if (.not. any) cycle
         km(1) = yd*yd
         km(2) = iq
         km(3) = iq*yd*ax
         km(4) = iq*iq*ax*ax
         km(5) = iq*iq
         km(6) = yd*yd*ax*ax
         km(7) = iq*ax*ax
         km(8) = iq*yd*ax*ax*ax
         km(9) = iq*iq*ax*ax*ax*ax
         km(10) = yd*yd*ax
         km(11) = iq*ax
         km(12) = iq*yd*ax*ax
         km(13) = iq*yd
         km(14) = iq*iq*ax*ax*ax
         km(15) = iq*iq*ax
         do cc = 1, ncb
            t(1) = km(1)*(s(1,cc) + s(5,cc) + (-1.0_dp/2.0_dp)*s(8,cc)) + km(6)*s(4,cc)
            t(2) = km(2)*(s(1,cc) + s(5,cc) + (-1.0_dp/2.0_dp)*s(8,cc)) + km(4)*(s(3,cc) + &
               6.0_dp*s(6,cc) + (-1.0_dp/2.0_dp)*s(10,cc)) + km(5)*(s(2,cc) + 3.0_dp*s(4,cc) + &
               (-1.0_dp/2.0_dp)*s(9,cc)) + km(7)*s(4,cc) + km(9)*s(7,cc)
            t(3) = km(3)*(s(2,cc) + 3.0_dp*s(4,cc) + (-1.0_dp/2.0_dp)*s(9,cc)) + km(8)*s(6,cc)
            t(4) = km(10)*s(4,cc)
            t(5) = km(11)*s(4,cc) + km(14)*s(7,cc) + 3.0_dp*km(15)*s(6,cc)
            t(6) = km(12)*s(6,cc) + km(13)*s(4,cc)
            t(7) = km(10)*(s(11,cc) + s(12,cc))
            t(8) = km(11)*(s(11,cc) + s(12,cc)) + km(14)*(s(15,cc) + s(16,cc)) + &
               km(15)*(3.0_dp*s(13,cc) + 3.0_dp*s(14,cc))
            t(9) = km(12)*(s(13,cc) + s(14,cc)) + km(13)*(s(11,cc) + s(12,cc))
            t(10) = km(14)*s(7,cc) + km(15)*(s(3,cc) + 3.0_dp*s(6,cc) + (-1.0_dp/2.0_dp)*s(10,cc))
            t(11) = km(12)*s(6,cc) + km(13)*(s(2,cc) + s(4,cc) + (-1.0_dp/2.0_dp)*s(9,cc))
            t(12) = km(4)*s(6,cc) + km(5)*s(4,cc)
            t(13) = km(3)*s(4,cc)
            t(14) = km(3)*s(6,cc)
            t(15) = km(4)*s(7,cc) + km(5)*s(6,cc)
            t(16) = km(4)*(s(15,cc) + s(16,cc)) + km(5)*(s(13,cc) + s(14,cc))
            t(17) = km(3)*(s(13,cc) + s(14,cc))
            t(18) = km(14)*s(16,cc) + km(15)*(3.0_dp*s(14,cc) + s(18,cc) + &
               (-1.0_dp/2.0_dp)*s(20,cc))
            t(19) = km(12)*s(14,cc) + km(13)*(s(12,cc) + s(17,cc) + (-1.0_dp/2.0_dp)*s(19,cc))
            t(20) = km(4)*s(16,cc) + km(5)*s(14,cc)
            t(21) = km(3)*s(14,cc)
            t(22) = km(4)*(s(6,cc) + s(23,cc) + s(24,cc)) + km(5)*(s(4,cc) + s(21,cc) + s(22,cc))
            t(23) = km(3)*(s(4,cc) + s(21,cc) + s(22,cc))
            t(24) = km(2)*(s(1,cc) + s(5,cc) + (-1.0_dp/2.0_dp)*s(8,cc)) + km(4)*s(6,cc) + &
               km(5)*(s(2,cc) + s(4,cc) + (-1.0_dp/2.0_dp)*s(9,cc)) + km(7)*s(4,cc)
            t(25) = km(4)*s(7,cc) + km(5)*(s(3,cc) + s(6,cc) + (-1.0_dp/2.0_dp)*s(10,cc))
            t(26) = km(11)*s(4,cc) + 3.0_dp*km(15)*s(6,cc)
            t(27) = km(15)*s(7,cc)
            t(28) = km(11)*(s(11,cc) + s(12,cc)) + km(15)*(s(13,cc) + s(14,cc))
            t(29) = km(15)*(s(15,cc) + s(16,cc))
            t(30) = km(4)*s(16,cc) + km(5)*(s(14,cc) + s(18,cc) + (-1.0_dp/2.0_dp)*s(20,cc))
            t(31) = km(15)*s(14,cc)
            t(32) = km(15)*s(16,cc)
            t(33) = km(15)*(s(6,cc) + s(23,cc) + s(24,cc))
            t(34) = km(2)*(s(1,cc) + s(5,cc) + (-1.0_dp/2.0_dp)*s(8,cc)) + km(4)*(s(6,cc) + &
               s(24,cc)) + km(5)*(s(2,cc) + s(4,cc) + (-1.0_dp/2.0_dp)*s(9,cc) + s(22,cc) + &
               s(25,cc) + (-1.0_dp/2.0_dp)*s(26,cc)) + km(7)*s(4,cc)
            t(35) = km(11)*s(4,cc) + km(15)*(s(6,cc) + s(24,cc))
            t(36) = km(11)*(s(11,cc) + s(12,cc)) + km(15)*(s(13,cc) + 3.0_dp*s(14,cc) + s(27,cc) + &
               s(28,cc))
            t(37) = km(1)*(s(1,cc) + s(5,cc) + (-1.0_dp/2.0_dp)*s(8,cc))
            t(38) = km(2)*(s(1,cc) + s(5,cc) + (-1.0_dp/2.0_dp)*s(8,cc)) + km(4)*(s(3,cc) + s(6,cc) &
               + (-1.0_dp/2.0_dp)*s(10,cc)) + km(5)*(s(2,cc) + s(4,cc) + (-1.0_dp/2.0_dp)*s(9,cc))
            t(39) = km(3)*(s(2,cc) + s(4,cc) + (-1.0_dp/2.0_dp)*s(9,cc))
            t(40) = km(2)*s(4,cc) + km(4)*s(7,cc) + km(5)*s(6,cc)
            t(41) = km(1)*s(4,cc)
            t(42) = km(1)*(s(11,cc) + s(12,cc))
            t(43) = km(2)*(s(11,cc) + s(12,cc)) + km(4)*(s(15,cc) + s(16,cc)) + km(5)*(s(13,cc) + &
               s(14,cc))
            t(44) = km(15)*(s(3,cc) + 3.0_dp*s(6,cc) + (-1.0_dp/2.0_dp)*s(10,cc))
            t(45) = km(13)*(s(2,cc) + 3.0_dp*s(4,cc) + (-1.0_dp/2.0_dp)*s(9,cc))
            t(46) = km(13)*s(6,cc)
            t(47) = km(15)*(s(13,cc) + s(14,cc))
            t(48) = km(13)*(s(11,cc) + s(12,cc))
            t(49) = km(13)*(s(13,cc) + s(14,cc))
            t(50) = km(15)*(s(14,cc) + s(18,cc) + (-1.0_dp/2.0_dp)*s(20,cc))
            t(51) = km(13)*(s(12,cc) + s(17,cc) + (-1.0_dp/2.0_dp)*s(19,cc))
            t(52) = km(13)*s(14,cc)
            t(53) = km(13)*(s(4,cc) + s(21,cc) + s(22,cc))
            t(54) = km(2)*(s(1,cc) + s(5,cc) + (-1.0_dp/2.0_dp)*s(8,cc)) + km(5)*(s(2,cc) + &
               3.0_dp*s(4,cc) + (-1.0_dp/2.0_dp)*s(9,cc))
            t(55) = km(2)*s(4,cc) + km(5)*(s(3,cc) + 6.0_dp*s(6,cc) + (-1.0_dp/2.0_dp)*s(10,cc))
            t(56) = km(5)*s(7,cc)
            t(57) = km(2)*(s(11,cc) + s(12,cc)) + km(5)*(3.0_dp*s(13,cc) + 3.0_dp*s(14,cc))
            t(58) = km(5)*(s(15,cc) + s(16,cc))
            t(59) = km(5)*(s(14,cc) + (1.0_dp/3.0_dp)*s(18,cc) + (-1.0_dp/6.0_dp)*s(20,cc))
            t(60) = km(5)*s(16,cc)
            t(61) = km(5)*(s(4,cc) + s(21,cc) + s(22,cc))
            t(62) = km(5)*(s(6,cc) + s(23,cc) + s(24,cc))
            t(63) = km(2)*(s(1,cc) + s(5,cc) + (-1.0_dp/2.0_dp)*s(8,cc)) + km(5)*(s(2,cc) + s(4,cc) &
               + (-1.0_dp/2.0_dp)*s(9,cc) + s(22,cc) + s(25,cc) + (-1.0_dp/2.0_dp)*s(26,cc))
            t(64) = km(2)*s(4,cc) + km(5)*(s(6,cc) + s(24,cc))
            t(65) = km(2)*(s(11,cc) + s(12,cc)) + km(5)*(s(13,cc) + 3.0_dp*s(14,cc) + s(27,cc) + &
               s(28,cc))
            t(66) = km(1)*(s(1,cc) + s(5,cc) + (-1.0_dp/2.0_dp)*s(8,cc) + s(29,cc) + &
               2.0_dp*s(30,cc) + s(31,cc))
            t(67) = km(2)*(s(1,cc) + s(5,cc) + (-1.0_dp/2.0_dp)*s(8,cc) + s(29,cc) + &
               2.0_dp*s(30,cc) + s(31,cc)) + km(4)*(s(3,cc) + s(6,cc) + (-1.0_dp/2.0_dp)*s(10,cc) + &
               2.0_dp*s(23,cc) + s(24,cc) + s(33,cc)) + km(5)*(s(2,cc) + s(4,cc) + &
               (-1.0_dp/2.0_dp)*s(9,cc) + 2.0_dp*s(21,cc) + s(22,cc) + s(32,cc))
            t(68) = km(3)*(s(2,cc) + s(4,cc) + (-1.0_dp/2.0_dp)*s(9,cc) + 2.0_dp*s(21,cc) + &
               s(22,cc) + s(32,cc))
            t(69) = km(15)*(s(3,cc) + s(6,cc) + (-1.0_dp/2.0_dp)*s(10,cc) + 2.0_dp*s(23,cc) + &
               s(24,cc) + s(33,cc))
            t(70) = km(13)*(s(2,cc) + s(4,cc) + (-1.0_dp/2.0_dp)*s(9,cc) + 2.0_dp*s(21,cc) + &
               s(22,cc) + s(32,cc))
            t(71) = km(15)*(s(13,cc) + (3.0_dp/2.0_dp)*s(14,cc) + (1.0_dp/2.0_dp)*s(18,cc) + &
               (-1.0_dp/4.0_dp)*s(20,cc) + s(27,cc) + (1.0_dp/2.0_dp)*s(28,cc) + &
               (1.0_dp/2.0_dp)*s(37,cc))
            t(72) = km(13)*(s(11,cc) + (3.0_dp/2.0_dp)*s(12,cc) + (1.0_dp/2.0_dp)*s(17,cc) + &
               (-1.0_dp/4.0_dp)*s(19,cc) + (1.0_dp/2.0_dp)*s(34,cc) + s(35,cc) + &
               (1.0_dp/2.0_dp)*s(36,cc))
            t(73) = km(2)*(s(1,cc) + s(5,cc) + (-1.0_dp/2.0_dp)*s(8,cc) + s(29,cc) + &
               2.0_dp*s(30,cc) + s(31,cc)) + km(5)*(s(2,cc) + s(4,cc) + (-1.0_dp/2.0_dp)*s(9,cc) + &
               2.0_dp*s(21,cc) + s(22,cc) + s(32,cc))
            t(74) = km(5)*(s(3,cc) + s(6,cc) + (-1.0_dp/2.0_dp)*s(10,cc) + 2.0_dp*s(23,cc) + &
               s(24,cc) + s(33,cc))
            t(75) = km(5)*(s(13,cc) + (3.0_dp/2.0_dp)*s(14,cc) + (1.0_dp/2.0_dp)*s(18,cc) + &
               (-1.0_dp/4.0_dp)*s(20,cc) + s(27,cc) + (1.0_dp/2.0_dp)*s(28,cc) + &
               (1.0_dp/2.0_dp)*s(37,cc))
            t(76) = km(2)*(s(1,cc) + s(5,cc) + (-1.0_dp/2.0_dp)*s(8,cc) + s(29,cc) + &
               2.0_dp*s(30,cc) + s(31,cc)) + km(5)*(s(2,cc) + 3.0_dp*s(4,cc) + &
               (-1.0_dp/2.0_dp)*s(9,cc) + 6.0_dp*s(21,cc) + 6.0_dp*s(22,cc) + s(25,cc) + &
               (-1.0_dp/2.0_dp)*s(26,cc) + s(32,cc) + s(38,cc) + 2.0_dp*s(39,cc) + s(40,cc))
            do ck = 1, nck
               r(1:76,cc,ck) = r(1:76,cc,ck) + kcd(ck,kq)*t(1:76)
            end do
         end do
      end do
      res = 0.0_dp
      if (.not. any) return
      cm(1) = Rs*Rs
      cm(2) = 1.0_dp
      cm(3) = Rs
      cm(4) = Rs*Rs*cy
      cm(5) = cy
      cm(6) = Rs*cy
      cm(7) = Rs*cy*cy
      cm(8) = cy*cy
      cm(9) = Rs*Rc
      cm(10) = Rc
      cm(11) = Rs*Rc*cy
      cm(12) = Rc*cy
      cm(13) = cy*cy*cy
      cm(14) = Rc*cy*cy
      cm(15) = Rc*Rc
      cm(16) = Rc*Rc*cy
      cm(17) = Rs*Rs*cy*cy
      cm(18) = Rs*cy*cy*cy
      cm(19) = Rs*Rc*cy*cy
      cm(20) = cy*cy*cy*cy
      cm(21) = Rc*cy*cy*cy
      cm(22) = Rc*Rc*cy*cy
      do ck = 1, nck
         do cc = 1, ncb
            res(1,cc+ncb*(ck-1)) = (-2.0_dp)*cm(1)*r(1,cc,ck) + (-2.0_dp)*r(2,cc,ck) + &
               (-4.0_dp)*cm(3)*r(3,cc,ck)
            res(2,cc+ncb*(ck-1)) = (-2.0_dp)*cm(4)*r(4,cc,ck) + (-2.0_dp)*cm(5)*r(5,cc,ck) + &
               (-4.0_dp)*cm(6)*r(6,cc,ck)
            res(3,cc+ncb*(ck-1)) = 2.0_dp*cm(1)*r(7,cc,ck) + 2.0_dp*r(8,cc,ck) + &
               4.0_dp*cm(3)*r(9,cc,ck)
            res(4,cc+ncb*(ck-1)) = (-2.0_dp)*cm(5)*r(10,cc,ck) + (-2.0_dp)*cm(6)*r(11,cc,ck)
            res(5,cc+ncb*(ck-1)) = (-2.0_dp)*r(12,cc,ck) + (-2.0_dp)*cm(3)*r(13,cc,ck) + &
               (-2.0_dp)*cm(7)*r(14,cc,ck) + (-2.0_dp)*cm(8)*r(15,cc,ck)
            res(6,cc+ncb*(ck-1)) = 2.0_dp*cm(5)*r(16,cc,ck) + 2.0_dp*cm(6)*r(17,cc,ck)
            res(7,cc+ncb*(ck-1)) = 2.0_dp*r(18,cc,ck) + 2.0_dp*cm(3)*r(19,cc,ck) + &
               (-2.0_dp)*cm(9)*r(1,cc,ck) + (-2.0_dp)*cm(10)*r(3,cc,ck)
            res(8,cc+ncb*(ck-1)) = 2.0_dp*cm(5)*r(20,cc,ck) + 2.0_dp*cm(6)*r(21,cc,ck) + &
               (-2.0_dp)*cm(11)*r(4,cc,ck) + (-2.0_dp)*cm(12)*r(6,cc,ck)
            res(9,cc+ncb*(ck-1)) = (-2.0_dp)*r(22,cc,ck) + (-2.0_dp)*cm(3)*r(23,cc,ck) + &
               2.0_dp*cm(9)*r(7,cc,ck) + 2.0_dp*cm(10)*r(9,cc,ck)
            res(10,cc+ncb*(ck-1)) = (-2.0_dp)*r(24,cc,ck) + (-2.0_dp)*cm(8)*r(25,cc,ck)
            res(11,cc+ncb*(ck-1)) = (-2.0_dp)*cm(5)*r(26,cc,ck) + (-2.0_dp)*cm(13)*r(27,cc,ck)
            res(12,cc+ncb*(ck-1)) = 2.0_dp*r(28,cc,ck) + 2.0_dp*cm(8)*r(29,cc,ck)
            res(13,cc+ncb*(ck-1)) = 2.0_dp*cm(5)*r(30,cc,ck) + (-2.0_dp)*cm(12)*r(11,cc,ck)
            res(14,cc+ncb*(ck-1)) = 2.0_dp*r(31,cc,ck) + 2.0_dp*cm(8)*r(32,cc,ck) + &
               (-2.0_dp)*cm(10)*r(13,cc,ck) + (-2.0_dp)*cm(14)*r(14,cc,ck)
            res(15,cc+ncb*(ck-1)) = (-2.0_dp)*cm(5)*r(33,cc,ck) + 2.0_dp*cm(12)*r(17,cc,ck)
            res(16,cc+ncb*(ck-1)) = (-2.0_dp)*r(34,cc,ck) + 4.0_dp*cm(10)*r(19,cc,ck) + &
               (-2.0_dp)*cm(15)*r(1,cc,ck)
            res(17,cc+ncb*(ck-1)) = (-2.0_dp)*cm(5)*r(35,cc,ck) + 4.0_dp*cm(12)*r(21,cc,ck) + &
               (-2.0_dp)*cm(16)*r(4,cc,ck)
            res(18,cc+ncb*(ck-1)) = 2.0_dp*r(36,cc,ck) + (-4.0_dp)*cm(10)*r(23,cc,ck) + &
               2.0_dp*cm(15)*r(7,cc,ck)
            res(19,cc+ncb*(ck-1)) = (-2.0_dp)*cm(4)*r(4,cc,ck) + (-2.0_dp)*cm(5)*r(5,cc,ck) + &
               (-4.0_dp)*cm(6)*r(6,cc,ck)
            res(20,cc+ncb*(ck-1)) = (-2.0_dp)*cm(1)*r(37,cc,ck) + (-2.0_dp)*r(38,cc,ck) + &
               (-4.0_dp)*cm(3)*r(39,cc,ck) + (-4.0_dp)*cm(7)*r(14,cc,ck) + &
               (-2.0_dp)*cm(8)*r(40,cc,ck) + (-2.0_dp)*cm(17)*r(41,cc,ck)
            res(21,cc+ncb*(ck-1)) = 2.0_dp*cm(4)*r(42,cc,ck) + 2.0_dp*cm(5)*r(43,cc,ck) + &
               4.0_dp*cm(6)*r(17,cc,ck)
            res(22,cc+ncb*(ck-1)) = (-2.0_dp)*r(12,cc,ck) + (-2.0_dp)*cm(3)*r(13,cc,ck) + &
               (-2.0_dp)*cm(7)*r(14,cc,ck) + (-2.0_dp)*cm(8)*r(15,cc,ck)
            res(23,cc+ncb*(ck-1)) = (-2.0_dp)*cm(5)*r(44,cc,ck) + (-2.0_dp)*cm(6)*r(45,cc,ck) + &
               (-2.0_dp)*cm(13)*r(27,cc,ck) + (-2.0_dp)*cm(18)*r(46,cc,ck)
            res(24,cc+ncb*(ck-1)) = 2.0_dp*r(47,cc,ck) + 2.0_dp*cm(3)*r(48,cc,ck) + &
               2.0_dp*cm(7)*r(49,cc,ck) + 2.0_dp*cm(8)*r(29,cc,ck)
            res(25,cc+ncb*(ck-1)) = 2.0_dp*cm(5)*r(20,cc,ck) + 2.0_dp*cm(6)*r(21,cc,ck) + &
               (-2.0_dp)*cm(11)*r(4,cc,ck) + (-2.0_dp)*cm(12)*r(6,cc,ck)
            res(26,cc+ncb*(ck-1)) = 2.0_dp*r(50,cc,ck) + 2.0_dp*cm(3)*r(51,cc,ck) + &
               2.0_dp*cm(7)*r(52,cc,ck) + 2.0_dp*cm(8)*r(32,cc,ck) + (-2.0_dp)*cm(9)*r(37,cc,ck) + &
               (-2.0_dp)*cm(10)*r(39,cc,ck) + (-2.0_dp)*cm(14)*r(14,cc,ck) + &
               (-2.0_dp)*cm(19)*r(41,cc,ck)
            res(27,cc+ncb*(ck-1)) = (-2.0_dp)*cm(5)*r(33,cc,ck) + (-2.0_dp)*cm(6)*r(53,cc,ck) + &
               2.0_dp*cm(11)*r(42,cc,ck) + 2.0_dp*cm(12)*r(17,cc,ck)
            res(28,cc+ncb*(ck-1)) = (-2.0_dp)*cm(5)*r(26,cc,ck) + (-2.0_dp)*cm(13)*r(27,cc,ck)
            res(29,cc+ncb*(ck-1)) = (-2.0_dp)*r(54,cc,ck) + (-2.0_dp)*cm(8)*r(55,cc,ck) + &
               (-2.0_dp)*cm(20)*r(56,cc,ck)
            res(30,cc+ncb*(ck-1)) = 2.0_dp*cm(5)*r(57,cc,ck) + 2.0_dp*cm(13)*r(58,cc,ck)
            res(31,cc+ncb*(ck-1)) = 2.0_dp*r(31,cc,ck) + 2.0_dp*cm(8)*r(32,cc,ck) + &
               (-2.0_dp)*cm(10)*r(13,cc,ck) + (-2.0_dp)*cm(14)*r(14,cc,ck)
            res(32,cc+ncb*(ck-1)) = 6.0_dp*cm(5)*r(59,cc,ck) + (-2.0_dp)*cm(12)*r(45,cc,ck) + &
               2.0_dp*cm(13)*r(60,cc,ck) + (-2.0_dp)*cm(21)*r(46,cc,ck)
            res(33,cc+ncb*(ck-1)) = (-2.0_dp)*r(61,cc,ck) + (-2.0_dp)*cm(8)*r(62,cc,ck) + &
               2.0_dp*cm(10)*r(48,cc,ck) + 2.0_dp*cm(14)*r(49,cc,ck)
            res(34,cc+ncb*(ck-1)) = (-2.0_dp)*cm(5)*r(35,cc,ck) + 4.0_dp*cm(12)*r(21,cc,ck) + &
               (-2.0_dp)*cm(16)*r(4,cc,ck)
            res(35,cc+ncb*(ck-1)) = (-2.0_dp)*r(63,cc,ck) + (-2.0_dp)*cm(8)*r(64,cc,ck) + &
               4.0_dp*cm(10)*r(51,cc,ck) + 4.0_dp*cm(14)*r(52,cc,ck) + (-2.0_dp)*cm(15)*r(37,cc,ck) &
               + (-2.0_dp)*cm(22)*r(41,cc,ck)
            res(36,cc+ncb*(ck-1)) = 2.0_dp*cm(5)*r(65,cc,ck) + (-4.0_dp)*cm(12)*r(53,cc,ck) + &
               2.0_dp*cm(16)*r(42,cc,ck)
            res(37,cc+ncb*(ck-1)) = 2.0_dp*cm(1)*r(7,cc,ck) + 2.0_dp*r(8,cc,ck) + &
               4.0_dp*cm(3)*r(9,cc,ck)
            res(38,cc+ncb*(ck-1)) = 2.0_dp*cm(4)*r(42,cc,ck) + 2.0_dp*cm(5)*r(43,cc,ck) + &
               4.0_dp*cm(6)*r(17,cc,ck)
            res(39,cc+ncb*(ck-1)) = (-2.0_dp)*cm(1)*r(66,cc,ck) + (-2.0_dp)*r(67,cc,ck) + &
               (-4.0_dp)*cm(3)*r(68,cc,ck)
            res(40,cc+ncb*(ck-1)) = 2.0_dp*cm(5)*r(16,cc,ck) + 2.0_dp*cm(6)*r(17,cc,ck)
            res(41,cc+ncb*(ck-1)) = 2.0_dp*r(47,cc,ck) + 2.0_dp*cm(3)*r(48,cc,ck) + &
               2.0_dp*cm(7)*r(49,cc,ck) + 2.0_dp*cm(8)*r(29,cc,ck)
            res(42,cc+ncb*(ck-1)) = (-2.0_dp)*cm(5)*r(69,cc,ck) + (-2.0_dp)*cm(6)*r(70,cc,ck)
            res(43,cc+ncb*(ck-1)) = (-2.0_dp)*r(22,cc,ck) + (-2.0_dp)*cm(3)*r(23,cc,ck) + &
               2.0_dp*cm(9)*r(7,cc,ck) + 2.0_dp*cm(10)*r(9,cc,ck)
            res(44,cc+ncb*(ck-1)) = (-2.0_dp)*cm(5)*r(33,cc,ck) + (-2.0_dp)*cm(6)*r(53,cc,ck) + &
               2.0_dp*cm(11)*r(42,cc,ck) + 2.0_dp*cm(12)*r(17,cc,ck)
            res(45,cc+ncb*(ck-1)) = 4.0_dp*r(71,cc,ck) + 4.0_dp*cm(3)*r(72,cc,ck) + &
               (-2.0_dp)*cm(9)*r(66,cc,ck) + (-2.0_dp)*cm(10)*r(68,cc,ck)
            res(46,cc+ncb*(ck-1)) = 2.0_dp*r(28,cc,ck) + 2.0_dp*cm(8)*r(29,cc,ck)
            res(47,cc+ncb*(ck-1)) = 2.0_dp*cm(5)*r(57,cc,ck) + 2.0_dp*cm(13)*r(58,cc,ck)
            res(48,cc+ncb*(ck-1)) = (-2.0_dp)*r(73,cc,ck) + (-2.0_dp)*cm(8)*r(74,cc,ck)
            res(49,cc+ncb*(ck-1)) = (-2.0_dp)*cm(5)*r(33,cc,ck) + 2.0_dp*cm(12)*r(17,cc,ck)
            res(50,cc+ncb*(ck-1)) = (-2.0_dp)*r(61,cc,ck) + (-2.0_dp)*cm(8)*r(62,cc,ck) + &
               2.0_dp*cm(10)*r(48,cc,ck) + 2.0_dp*cm(14)*r(49,cc,ck)
            res(51,cc+ncb*(ck-1)) = 4.0_dp*cm(5)*r(75,cc,ck) + (-2.0_dp)*cm(12)*r(70,cc,ck)
            res(52,cc+ncb*(ck-1)) = 2.0_dp*r(36,cc,ck) + (-4.0_dp)*cm(10)*r(23,cc,ck) + &
               2.0_dp*cm(15)*r(7,cc,ck)
            res(53,cc+ncb*(ck-1)) = 2.0_dp*cm(5)*r(65,cc,ck) + (-4.0_dp)*cm(12)*r(53,cc,ck) + &
               2.0_dp*cm(16)*r(42,cc,ck)
            res(54,cc+ncb*(ck-1)) = (-2.0_dp)*r(76,cc,ck) + 8.0_dp*cm(10)*r(72,cc,ck) + &
               (-2.0_dp)*cm(15)*r(66,cc,ck)
         end do
      end do
   end subroutine rotaxis_grad_psds

end module rotaxis_grad_psds_m
