# GENERATED by scripts/rotaxis_mmd -- do not edit.
# The rotated-axis kernel sources, one per class, plus the shared Boys
# wrapper; included from src/CMakeLists.txt.
set(cintRotaxisSrc
  rotaxis/cint_rotaxis_boys.f90
  rotaxis/rotaxis_ssss.f90
  rotaxis/rotaxis_sssp.f90
  rotaxis/rotaxis_sssL.f90
  rotaxis/rotaxis_sspp.f90
  rotaxis/rotaxis_sspL.f90
  rotaxis/rotaxis_ssLL.f90
  rotaxis/rotaxis_spsp.f90
  rotaxis/rotaxis_spsL.f90
  rotaxis/rotaxis_sppp.f90
  rotaxis/rotaxis_sppL.f90
  rotaxis/rotaxis_spLL.f90
  rotaxis/rotaxis_sLsL.f90
  rotaxis/rotaxis_sLpp.f90
  rotaxis/rotaxis_sLpL.f90
  rotaxis/rotaxis_sLLL.f90
  rotaxis/rotaxis_pppp.f90
  rotaxis/rotaxis_pppL.f90
  rotaxis/rotaxis_ppLL.f90
  rotaxis/rotaxis_pLpL.f90
  rotaxis/rotaxis_pLLL.f90
  rotaxis/rotaxis_LLLL.f90
)
