! GENERATED by scripts/rotaxis_mmd -- do not edit.
! sdpd: L=5 comps=108 S=53 g=4 r=295 (terms 1488) km=37 cm=40 assembly terms=559
module rotaxis_sdpd_m
   use cint_const, only: dp
   use cint_rotaxis_boys, only: boys
   implicit none
   private
   public :: rotaxis_sdpd
contains
   ! (sd|pd)  L=5: 53 bra accumulators, 295 ket accumulators, 108 components
   subroutine rotaxis_sdpd(nbra, ncb, bp, kab, nket, nck, kp, kcd, gc, cutoff, res, any)
      integer,  intent(in)  :: nbra, ncb, nket, nck
      real(dp), intent(in)  :: bp(5, nbra), kab(1*ncb, nbra)
      real(dp), intent(in)  :: kp(7, nket), kcd(1*nck, nket), gc(3), cutoff
      real(dp), intent(out) :: res(108, ncb*nck)
      logical,  intent(out) :: any
      real(dp) :: s(53, ncb), r(295, ncb, nck), t(295)
      real(dp) :: f(0:5), b(0:5)
      real(dp) :: p, ip, za, zb, eab, q, iq, yc, yd, ax, az, ecd
      real(dp) :: zq, alpha, tt, w, m2a, Rs, Rc, cy
      real(dp) :: g(4), km(37), cm(40), zq2, zq3, zq4, zq5
      integer :: kq, bq, cc, ck, n

      Rs = gc(1); Rc = gc(2); cy = gc(3)
      any = .false.
      r = 0.0_dp
      do kq = 1, nket
         q = kp(1,kq); iq = kp(2,kq); yc = kp(3,kq); yd = kp(4,kq)
         ax = kp(5,kq); az = kp(6,kq); ecd = kp(7,kq)
         s = 0.0_dp
         do bq = 1, nbra
            eab = bp(5,bq)
            if (eab + ecd > cutoff) cycle
            any = .true.
            p = bp(1,bq); ip = bp(2,bq); za = bp(3,bq); zb = bp(4,bq)
            zq = za - az
            alpha = p*q/(p + q)
            tt = alpha*(ax*ax + cy*cy + zq*zq)
            call boys(f, tt, 5)
            w = 1.0_dp/sqrt(p + q)
            m2a = -2.0_dp*alpha
            do n = 0, 5
               b(n) = w*f(n)
               w = w*m2a
            end do
            zq2 = zq*zq
            zq3 = zq2*zq
            zq4 = zq3*zq
            zq5 = zq4*zq
            g(1) = ip
            g(2) = ip*ip
            g(3) = ip*zb
            g(4) = zb*zb
            do cc = 1, ncb
               s(1,cc) = s(1,cc) + kab(cc,bq)*g(1)*b(0)
               s(2,cc) = s(2,cc) + kab(cc,bq)*g(1)*b(1)
               s(3,cc) = s(3,cc) + kab(cc,bq)*g(1)*b(2)
               s(4,cc) = s(4,cc) + kab(cc,bq)*g(2)*b(2)
               s(5,cc) = s(5,cc) + kab(cc,bq)*g(2)*b(1)
               s(6,cc) = s(6,cc) + kab(cc,bq)*g(1)*b(3)
               s(7,cc) = s(7,cc) + kab(cc,bq)*g(2)*b(3)
               s(8,cc) = s(8,cc) + kab(cc,bq)*g(2)*b(4)
               s(9,cc) = s(9,cc) + kab(cc,bq)*g(2)*b(5)
               s(10,cc) = s(10,cc) + kab(cc,bq)*g(3)*b(1)
               s(11,cc) = s(11,cc) + kab(cc,bq)*g(2)*b(2)*zq
               s(12,cc) = s(12,cc) + kab(cc,bq)*g(3)*b(2)
               s(13,cc) = s(13,cc) + kab(cc,bq)*g(2)*b(3)*zq
               s(14,cc) = s(14,cc) + kab(cc,bq)*g(3)*b(3)
               s(15,cc) = s(15,cc) + kab(cc,bq)*g(2)*b(4)*zq
               s(16,cc) = s(16,cc) + kab(cc,bq)*g(3)*b(4)
               s(17,cc) = s(17,cc) + kab(cc,bq)*g(2)*b(5)*zq
               s(18,cc) = s(18,cc) + kab(cc,bq)*g(4)*b(0)
               s(19,cc) = s(19,cc) + kab(cc,bq)*g(3)*b(1)*zq
               s(20,cc) = s(20,cc) + kab(cc,bq)*g(2)*b(2)*zq2
               s(21,cc) = s(21,cc) + kab(cc,bq)*g(4)*b(1)
               s(22,cc) = s(22,cc) + kab(cc,bq)*g(3)*b(2)*zq
               s(23,cc) = s(23,cc) + kab(cc,bq)*g(2)*b(3)*zq2
               s(24,cc) = s(24,cc) + kab(cc,bq)*g(4)*b(2)
               s(25,cc) = s(25,cc) + kab(cc,bq)*g(3)*b(3)*zq
               s(26,cc) = s(26,cc) + kab(cc,bq)*g(2)*b(4)*zq2
               s(27,cc) = s(27,cc) + kab(cc,bq)*g(4)*b(3)
               s(28,cc) = s(28,cc) + kab(cc,bq)*g(3)*b(4)*zq
               s(29,cc) = s(29,cc) + kab(cc,bq)*g(2)*b(5)*zq2
               s(30,cc) = s(30,cc) + kab(cc,bq)*g(1)*b(1)*zq
               s(31,cc) = s(31,cc) + kab(cc,bq)*g(1)*b(2)*zq
               s(32,cc) = s(32,cc) + kab(cc,bq)*g(1)*b(3)*zq
               s(33,cc) = s(33,cc) + kab(cc,bq)*g(4)*b(1)*zq
               s(34,cc) = s(34,cc) + kab(cc,bq)*g(3)*b(2)*zq2
               s(35,cc) = s(35,cc) + kab(cc,bq)*g(2)*b(3)*zq3
               s(36,cc) = s(36,cc) + kab(cc,bq)*g(4)*b(2)*zq
               s(37,cc) = s(37,cc) + kab(cc,bq)*g(3)*b(3)*zq2
               s(38,cc) = s(38,cc) + kab(cc,bq)*g(2)*b(4)*zq3
               s(39,cc) = s(39,cc) + kab(cc,bq)*g(4)*b(3)*zq
               s(40,cc) = s(40,cc) + kab(cc,bq)*g(3)*b(4)*zq2
               s(41,cc) = s(41,cc) + kab(cc,bq)*g(2)*b(5)*zq3
               s(42,cc) = s(42,cc) + kab(cc,bq)*g(1)*b(2)*zq2
               s(43,cc) = s(43,cc) + kab(cc,bq)*g(1)*b(3)*zq2
               s(44,cc) = s(44,cc) + kab(cc,bq)*g(4)*b(2)*zq2
               s(45,cc) = s(45,cc) + kab(cc,bq)*g(3)*b(3)*zq3
               s(46,cc) = s(46,cc) + kab(cc,bq)*g(2)*b(4)*zq4
               s(47,cc) = s(47,cc) + kab(cc,bq)*g(4)*b(3)*zq2
               s(48,cc) = s(48,cc) + kab(cc,bq)*g(3)*b(4)*zq3
               s(49,cc) = s(49,cc) + kab(cc,bq)*g(2)*b(5)*zq4
               s(50,cc) = s(50,cc) + kab(cc,bq)*g(1)*b(3)*zq3
               s(51,cc) = s(51,cc) + kab(cc,bq)*g(4)*b(3)*zq3
               s(52,cc) = s(52,cc) + kab(cc,bq)*g(3)*b(4)*zq4
               s(53,cc) = s(53,cc) + kab(cc,bq)*g(2)*b(5)*zq5
            end do
         end do
         if (.not. any) cycle
         km(1) = yc*yc*yd
         km(2) = iq*yd
         km(3) = iq*yc
         km(4) = iq*yc*yc*ax
         km(5) = iq*iq*ax
         km(6) = iq*yc*yd*ax
         km(7) = iq*iq*yc*ax*ax
         km(8) = iq*iq*yc
         km(9) = iq*iq*yd*ax*ax
         km(10) = iq*iq*yd
         km(11) = yc*yc*yd*ax*ax
         km(12) = iq*yd*ax*ax
         km(13) = iq*yc*ax*ax
         km(14) = iq*iq*iq*ax*ax*ax
         km(15) = iq*iq*iq*ax
         km(16) = iq*yc*yc*ax*ax*ax
         km(17) = iq*iq*ax*ax*ax
         km(18) = iq*yc*yd*ax*ax*ax
         km(19) = iq*iq*yc*ax*ax*ax*ax
         km(20) = iq*iq*yd*ax*ax*ax*ax
         km(21) = iq*iq*iq*ax*ax*ax*ax*ax
         km(22) = yc*yc*yd*ax
         km(23) = iq*yd*ax
         km(24) = iq*yc*ax
         km(25) = iq*yc*yc*ax*ax
         km(26) = iq*yc*yc
         km(27) = iq*iq*ax*ax
         km(28) = iq*iq
         km(29) = iq*yc*yd*ax*ax
         km(30) = iq*yc*yd
         km(31) = iq*iq*yc*ax*ax*ax
         km(32) = iq*iq*yc*ax
         km(33) = iq*iq*yd*ax*ax*ax
         km(34) = iq*iq*yd*ax
         km(35) = iq*iq*iq*ax*ax*ax*ax
         km(36) = iq*iq*iq*ax*ax
         km(37) = iq*iq*iq
         do cc = 1, ncb
            t(1) = km(1)*(s(1,cc) + s(5,cc)) + km(11)*s(4,cc)
            t(2) = km(2)*(s(1,cc) + s(5,cc)) + km(3)*((-2.0_dp)*s(1,cc) + (-2.0_dp)*s(5,cc)) + &
               km(7)*((-2.0_dp)*s(3,cc) + (-12.0_dp)*s(7,cc)) + km(8)*((-2.0_dp)*s(2,cc) + &
               (-6.0_dp)*s(4,cc)) + km(9)*(s(3,cc) + 6.0_dp*s(7,cc)) + km(10)*(s(2,cc) + &
               3.0_dp*s(4,cc)) + km(12)*s(4,cc) + (-2.0_dp)*km(13)*s(4,cc) + &
               (-2.0_dp)*km(19)*s(8,cc) + km(20)*s(8,cc)
            t(3) = km(4)*(s(2,cc) + 3.0_dp*s(4,cc)) + km(6)*((-2.0_dp)*s(2,cc) + (-6.0_dp)*s(4,cc)) &
               + km(16)*s(7,cc) + (-2.0_dp)*km(18)*s(7,cc)
            t(4) = km(5)*(s(2,cc) + 3.0_dp*s(4,cc)) + km(14)*((1.0_dp/3.0_dp)*s(6,cc) + &
               (10.0_dp/3.0_dp)*s(8,cc)) + km(15)*(s(3,cc) + 5.0_dp*s(7,cc)) + km(17)*s(7,cc) + &
               (1.0_dp/3.0_dp)*km(21)*s(9,cc)
            t(5) = km(22)*s(4,cc)
            t(6) = km(23)*s(4,cc) + (-2.0_dp)*km(24)*s(4,cc) + (-2.0_dp)*km(31)*s(8,cc) + &
               (-6.0_dp)*km(32)*s(7,cc) + km(33)*s(8,cc) + 3.0_dp*km(34)*s(7,cc)
            t(7) = km(25)*s(7,cc) + km(26)*s(4,cc) + (-2.0_dp)*km(29)*s(7,cc) + &
               (-2.0_dp)*km(30)*s(4,cc)
            t(8) = km(27)*s(7,cc) + km(28)*s(4,cc) + (1.0_dp/3.0_dp)*km(35)*s(9,cc) + &
               2.0_dp*km(36)*s(8,cc) + km(37)*s(7,cc)
            t(9) = km(22)*(s(10,cc) + s(11,cc))
            t(10) = km(23)*(s(10,cc) + s(11,cc)) + km(24)*((-2.0_dp)*s(10,cc) + (-2.0_dp)*s(11,cc)) &
               + km(31)*((-2.0_dp)*s(14,cc) + (-2.0_dp)*s(15,cc)) + km(32)*((-6.0_dp)*s(12,cc) + &
               (-6.0_dp)*s(13,cc)) + km(33)*(s(14,cc) + s(15,cc)) + km(34)*(3.0_dp*s(12,cc) + &
               3.0_dp*s(13,cc))
            t(11) = km(25)*(s(12,cc) + s(13,cc)) + km(26)*(s(10,cc) + s(11,cc)) + &
               km(29)*((-2.0_dp)*s(12,cc) + (-2.0_dp)*s(13,cc)) + km(30)*((-2.0_dp)*s(10,cc) + &
               (-2.0_dp)*s(11,cc))
            t(12) = km(27)*(s(12,cc) + s(13,cc)) + km(28)*(s(10,cc) + s(11,cc)) + &
               km(35)*((1.0_dp/3.0_dp)*s(16,cc) + (1.0_dp/3.0_dp)*s(17,cc)) + &
               km(36)*(2.0_dp*s(14,cc) + 2.0_dp*s(15,cc)) + km(37)*(s(12,cc) + s(13,cc))
            t(13) = km(1)*(s(1,cc) + s(5,cc))
            t(14) = km(2)*(s(1,cc) + s(5,cc)) + km(3)*((-2.0_dp)*s(1,cc) + (-2.0_dp)*s(5,cc)) + &
               km(7)*((-2.0_dp)*s(3,cc) + (-2.0_dp)*s(7,cc)) + km(8)*((-2.0_dp)*s(2,cc) + &
               (-2.0_dp)*s(4,cc)) + km(9)*(s(3,cc) + s(7,cc)) + km(10)*(s(2,cc) + s(4,cc))
            t(15) = km(4)*(s(2,cc) + s(4,cc)) + km(6)*((-2.0_dp)*s(2,cc) + (-2.0_dp)*s(4,cc))
            t(16) = km(5)*(s(2,cc) + s(4,cc)) + km(14)*((1.0_dp/3.0_dp)*s(6,cc) + &
               (1.0_dp/3.0_dp)*s(8,cc)) + km(15)*(s(3,cc) + s(7,cc))
            t(17) = km(1)*s(4,cc)
            t(18) = km(2)*s(4,cc) + (-2.0_dp)*km(3)*s(4,cc) + (-2.0_dp)*km(7)*s(8,cc) + &
               (-2.0_dp)*km(8)*s(7,cc) + km(9)*s(8,cc) + km(10)*s(7,cc)
            t(19) = km(4)*s(7,cc) + (-2.0_dp)*km(6)*s(7,cc)
            t(20) = km(5)*s(7,cc) + (1.0_dp/3.0_dp)*km(14)*s(9,cc) + km(15)*s(8,cc)
            t(21) = km(1)*(s(10,cc) + s(11,cc))
            t(22) = km(2)*(s(10,cc) + s(11,cc)) + km(3)*((-2.0_dp)*s(10,cc) + (-2.0_dp)*s(11,cc)) + &
               km(7)*((-2.0_dp)*s(14,cc) + (-2.0_dp)*s(15,cc)) + km(8)*((-2.0_dp)*s(12,cc) + &
               (-2.0_dp)*s(13,cc)) + km(9)*(s(14,cc) + s(15,cc)) + km(10)*(s(12,cc) + s(13,cc))
            t(23) = km(4)*(s(12,cc) + s(13,cc)) + km(6)*((-2.0_dp)*s(12,cc) + (-2.0_dp)*s(13,cc))
            t(24) = km(5)*(s(12,cc) + s(13,cc)) + km(14)*((1.0_dp/3.0_dp)*s(16,cc) + &
               (1.0_dp/3.0_dp)*s(17,cc)) + km(15)*(s(14,cc) + s(15,cc))
            t(25) = km(1)*(s(1,cc) + s(5,cc) + s(18,cc) + 2.0_dp*s(19,cc) + s(20,cc))
            t(26) = km(2)*(s(1,cc) + s(5,cc) + s(18,cc) + 2.0_dp*s(19,cc) + s(20,cc)) + &
               km(3)*((-2.0_dp)*s(1,cc) + (-2.0_dp)*s(5,cc) + (-2.0_dp)*s(18,cc) + &
               (-4.0_dp)*s(19,cc) + (-2.0_dp)*s(20,cc)) + km(7)*((-2.0_dp)*s(3,cc) + &
               (-2.0_dp)*s(7,cc) + (-2.0_dp)*s(24,cc) + (-4.0_dp)*s(25,cc) + (-2.0_dp)*s(26,cc)) + &
               km(8)*((-2.0_dp)*s(2,cc) + (-2.0_dp)*s(4,cc) + (-2.0_dp)*s(21,cc) + &
               (-4.0_dp)*s(22,cc) + (-2.0_dp)*s(23,cc)) + km(9)*(s(3,cc) + s(7,cc) + s(24,cc) + &
               2.0_dp*s(25,cc) + s(26,cc)) + km(10)*(s(2,cc) + s(4,cc) + s(21,cc) + 2.0_dp*s(22,cc) &
               + s(23,cc))
            t(27) = km(4)*(s(2,cc) + s(4,cc) + s(21,cc) + 2.0_dp*s(22,cc) + s(23,cc)) + &
               km(6)*((-2.0_dp)*s(2,cc) + (-2.0_dp)*s(4,cc) + (-2.0_dp)*s(21,cc) + &
               (-4.0_dp)*s(22,cc) + (-2.0_dp)*s(23,cc))
            t(28) = km(5)*(s(2,cc) + s(4,cc) + s(21,cc) + 2.0_dp*s(22,cc) + s(23,cc)) + &
               km(14)*((1.0_dp/3.0_dp)*s(6,cc) + (1.0_dp/3.0_dp)*s(8,cc) + (1.0_dp/3.0_dp)*s(27,cc) &
               + (2.0_dp/3.0_dp)*s(28,cc) + (1.0_dp/3.0_dp)*s(29,cc)) + km(15)*(s(3,cc) + s(7,cc) + &
               s(24,cc) + 2.0_dp*s(25,cc) + s(26,cc))
            t(29) = km(31)*s(8,cc) + km(32)*(s(3,cc) + 3.0_dp*s(7,cc))
            t(30) = km(25)*s(7,cc) + km(26)*(s(2,cc) + s(4,cc))
            t(31) = km(27)*s(7,cc) + km(28)*(s(2,cc) + s(4,cc)) + km(35)*s(9,cc) + km(36)*(s(6,cc) &
               + 6.0_dp*s(8,cc)) + km(37)*(s(3,cc) + 3.0_dp*s(7,cc))
            t(32) = km(7)*s(7,cc) + km(8)*s(4,cc)
            t(33) = km(4)*s(4,cc)
            t(34) = km(5)*s(4,cc) + km(14)*s(8,cc) + 3.0_dp*km(15)*s(7,cc)
            t(35) = km(7)*s(8,cc) + km(8)*s(7,cc)
            t(36) = km(4)*s(7,cc)
            t(37) = km(5)*s(7,cc) + km(14)*s(9,cc) + 3.0_dp*km(15)*s(8,cc)
            t(38) = km(7)*(s(14,cc) + s(15,cc)) + km(8)*(s(12,cc) + s(13,cc))
            t(39) = km(4)*(s(12,cc) + s(13,cc))
            t(40) = km(5)*(s(12,cc) + s(13,cc)) + km(14)*(s(16,cc) + s(17,cc)) + &
               km(15)*(3.0_dp*s(14,cc) + 3.0_dp*s(15,cc))
            t(41) = km(32)*(s(3,cc) + 3.0_dp*s(7,cc))
            t(42) = km(26)*(s(2,cc) + 3.0_dp*s(4,cc))
            t(43) = km(28)*(s(2,cc) + 3.0_dp*s(4,cc)) + km(36)*(s(6,cc) + 3.0_dp*s(8,cc)) + &
               km(37)*(s(3,cc) + 3.0_dp*s(7,cc))
            t(44) = km(26)*s(7,cc)
            t(45) = km(28)*s(7,cc) + km(36)*s(9,cc) + km(37)*s(8,cc)
            t(46) = km(32)*s(8,cc)
            t(47) = km(32)*(s(12,cc) + s(13,cc))
            t(48) = km(26)*(s(10,cc) + s(11,cc))
            t(49) = km(28)*(s(10,cc) + s(11,cc)) + km(36)*(s(14,cc) + s(15,cc)) + km(37)*(s(12,cc) &
               + s(13,cc))
            t(50) = km(32)*(s(14,cc) + s(15,cc))
            t(51) = km(26)*(s(12,cc) + s(13,cc))
            t(52) = km(28)*(s(12,cc) + s(13,cc)) + km(36)*(s(16,cc) + s(17,cc)) + km(37)*(s(14,cc) &
               + s(15,cc))
            t(53) = km(32)*(s(3,cc) + s(7,cc) + s(24,cc) + 2.0_dp*s(25,cc) + s(26,cc))
            t(54) = km(26)*(s(2,cc) + s(4,cc) + s(21,cc) + 2.0_dp*s(22,cc) + s(23,cc))
            t(55) = km(28)*(s(2,cc) + s(4,cc) + s(21,cc) + 2.0_dp*s(22,cc) + s(23,cc)) + &
               km(36)*(s(6,cc) + s(8,cc) + s(27,cc) + 2.0_dp*s(28,cc) + s(29,cc)) + km(37)*(s(3,cc) &
               + s(7,cc) + s(24,cc) + 2.0_dp*s(25,cc) + s(26,cc))
            t(56) = km(31)*s(15,cc) + km(32)*(3.0_dp*s(13,cc) + s(31,cc))
            t(57) = km(25)*s(13,cc) + km(26)*(s(11,cc) + s(30,cc))
            t(58) = km(27)*s(13,cc) + km(28)*(s(11,cc) + s(30,cc)) + km(35)*s(17,cc) + &
               km(36)*(6.0_dp*s(15,cc) + s(32,cc)) + km(37)*(3.0_dp*s(13,cc) + s(31,cc))
            t(59) = km(2)*(s(1,cc) + s(5,cc)) + km(9)*(s(3,cc) + 6.0_dp*s(7,cc)) + km(10)*(s(2,cc) &
               + 3.0_dp*s(4,cc)) + km(12)*s(4,cc) + km(20)*s(8,cc)
            t(60) = km(6)*(s(2,cc) + 3.0_dp*s(4,cc)) + km(18)*s(7,cc)
            t(61) = km(7)*s(15,cc) + km(8)*s(13,cc)
            t(62) = km(4)*s(13,cc)
            t(63) = km(5)*s(13,cc) + km(14)*s(17,cc) + 3.0_dp*km(15)*s(15,cc)
            t(64) = km(23)*s(4,cc) + km(33)*s(8,cc) + 3.0_dp*km(34)*s(7,cc)
            t(65) = km(29)*s(7,cc) + km(30)*s(4,cc)
            t(66) = km(7)*(s(7,cc) + s(25,cc) + s(26,cc)) + km(8)*(s(4,cc) + s(22,cc) + s(23,cc))
            t(67) = km(4)*(s(4,cc) + s(22,cc) + s(23,cc))
            t(68) = km(5)*(s(4,cc) + s(22,cc) + s(23,cc)) + km(14)*(s(8,cc) + s(28,cc) + s(29,cc)) &
               + km(15)*(3.0_dp*s(7,cc) + 3.0_dp*s(25,cc) + 3.0_dp*s(26,cc))
            t(69) = km(23)*(s(10,cc) + s(11,cc)) + km(33)*(s(14,cc) + s(15,cc)) + &
               km(34)*(3.0_dp*s(12,cc) + 3.0_dp*s(13,cc))
            t(70) = km(29)*(s(12,cc) + s(13,cc)) + km(30)*(s(10,cc) + s(11,cc))
            t(71) = km(32)*(s(13,cc) + s(31,cc))
            t(72) = km(26)*(s(11,cc) + s(30,cc))
            t(73) = km(28)*(s(11,cc) + s(30,cc)) + km(36)*(s(15,cc) + s(32,cc)) + km(37)*(s(13,cc) &
               + s(31,cc))
            t(74) = km(32)*s(15,cc)
            t(75) = km(26)*s(13,cc)
            t(76) = km(28)*s(13,cc) + km(36)*s(17,cc) + km(37)*s(15,cc)
            t(77) = km(2)*(s(1,cc) + s(5,cc)) + km(9)*(s(3,cc) + s(7,cc)) + km(10)*(s(2,cc) + &
               s(4,cc))
            t(78) = km(6)*(s(2,cc) + s(4,cc))
            t(79) = km(2)*s(4,cc) + km(9)*s(8,cc) + km(10)*s(7,cc)
            t(80) = km(6)*s(7,cc)
            t(81) = km(32)*(s(7,cc) + s(25,cc) + s(26,cc))
            t(82) = km(26)*(s(4,cc) + s(22,cc) + s(23,cc))
            t(83) = km(28)*(s(4,cc) + s(22,cc) + s(23,cc)) + km(36)*(s(8,cc) + s(28,cc) + s(29,cc)) &
               + km(37)*(s(7,cc) + s(25,cc) + s(26,cc))
            t(84) = km(2)*(s(10,cc) + s(11,cc)) + km(9)*(s(14,cc) + s(15,cc)) + km(10)*(s(12,cc) + &
               s(13,cc))
            t(85) = km(6)*(s(12,cc) + s(13,cc))
            t(86) = km(32)*(s(12,cc) + (3.0_dp/2.0_dp)*s(13,cc) + (1.0_dp/2.0_dp)*s(31,cc) + &
               (1.0_dp/2.0_dp)*s(36,cc) + s(37,cc) + (1.0_dp/2.0_dp)*s(38,cc))
            t(87) = km(26)*(s(10,cc) + (3.0_dp/2.0_dp)*s(11,cc) + (1.0_dp/2.0_dp)*s(30,cc) + &
               (1.0_dp/2.0_dp)*s(33,cc) + s(34,cc) + (1.0_dp/2.0_dp)*s(35,cc))
            t(88) = km(28)*(s(10,cc) + (3.0_dp/2.0_dp)*s(11,cc) + (1.0_dp/2.0_dp)*s(30,cc) + &
               (1.0_dp/2.0_dp)*s(33,cc) + s(34,cc) + (1.0_dp/2.0_dp)*s(35,cc)) + km(36)*(s(14,cc) + &
               (3.0_dp/2.0_dp)*s(15,cc) + (1.0_dp/2.0_dp)*s(32,cc) + (1.0_dp/2.0_dp)*s(39,cc) + &
               s(40,cc) + (1.0_dp/2.0_dp)*s(41,cc)) + km(37)*(s(12,cc) + (3.0_dp/2.0_dp)*s(13,cc) + &
               (1.0_dp/2.0_dp)*s(31,cc) + (1.0_dp/2.0_dp)*s(36,cc) + s(37,cc) + &
               (1.0_dp/2.0_dp)*s(38,cc))
            t(89) = km(2)*(s(1,cc) + s(5,cc) + s(18,cc) + 2.0_dp*s(19,cc) + s(20,cc)) + &
               km(9)*(s(3,cc) + s(7,cc) + s(24,cc) + 2.0_dp*s(25,cc) + s(26,cc)) + km(10)*(s(2,cc) &
               + s(4,cc) + s(21,cc) + 2.0_dp*s(22,cc) + s(23,cc))
            t(90) = km(6)*(s(2,cc) + s(4,cc) + s(21,cc) + 2.0_dp*s(22,cc) + s(23,cc))
            t(91) = km(31)*s(8,cc) + km(32)*(s(3,cc) + 3.0_dp*s(7,cc)) - km(33)*s(8,cc) + &
               km(34)*(-s(3,cc) + (-3.0_dp)*s(7,cc))
            t(92) = km(29)*s(7,cc) + km(30)*(s(2,cc) + s(4,cc))
            t(93) = km(7)*s(7,cc) + km(8)*s(4,cc) - km(9)*s(7,cc) - km(10)*s(4,cc)
            t(94) = km(6)*s(4,cc)
            t(95) = km(7)*s(8,cc) + km(8)*s(7,cc) - km(9)*s(8,cc) - km(10)*s(7,cc)
            t(96) = km(7)*(s(14,cc) + s(15,cc)) + km(8)*(s(12,cc) + s(13,cc)) + km(9)*(-s(14,cc) - &
               s(15,cc)) + km(10)*(-s(12,cc) - s(13,cc))
            t(97) = km(32)*(s(3,cc) + 3.0_dp*s(7,cc)) + km(34)*(-s(3,cc) + (-3.0_dp)*s(7,cc))
            t(98) = km(30)*(s(2,cc) + 3.0_dp*s(4,cc))
            t(99) = km(30)*s(7,cc)
            t(100) = km(32)*s(8,cc) - km(34)*s(8,cc)
            t(101) = km(32)*(s(12,cc) + s(13,cc)) + km(34)*(-s(12,cc) - s(13,cc))
            t(102) = km(30)*(s(10,cc) + s(11,cc))
            t(103) = km(32)*(s(14,cc) + s(15,cc)) + km(34)*(-s(14,cc) - s(15,cc))
            t(104) = km(30)*(s(12,cc) + s(13,cc))
            t(105) = km(32)*(s(3,cc) + s(7,cc) + s(24,cc) + 2.0_dp*s(25,cc) + s(26,cc)) + &
               km(34)*(-s(3,cc) - s(7,cc) - s(24,cc) + (-2.0_dp)*s(25,cc) - s(26,cc))
            t(106) = km(30)*(s(2,cc) + s(4,cc) + s(21,cc) + 2.0_dp*s(22,cc) + s(23,cc))
            t(107) = km(3)*(s(1,cc) + s(5,cc)) + km(7)*s(7,cc) + km(8)*(s(2,cc) + s(4,cc)) + &
               km(13)*s(4,cc)
            t(108) = km(5)*(s(2,cc) + 3.0_dp*s(4,cc)) + km(14)*s(8,cc) + km(15)*(s(3,cc) + &
               3.0_dp*s(7,cc)) + km(17)*s(7,cc)
            t(109) = km(7)*s(8,cc) + km(8)*(s(3,cc) + s(7,cc))
            t(110) = km(14)*s(9,cc) + km(15)*(s(6,cc) + 3.0_dp*s(8,cc))
            t(111) = km(24)*s(4,cc) + 3.0_dp*km(32)*s(7,cc)
            t(112) = km(27)*s(7,cc) + km(28)*s(4,cc) + 3.0_dp*km(36)*s(8,cc) + &
               3.0_dp*km(37)*s(7,cc)
            t(113) = km(36)*s(9,cc) + km(37)*s(8,cc)
            t(114) = km(24)*(s(10,cc) + s(11,cc)) + km(32)*(s(12,cc) + s(13,cc))
            t(115) = km(27)*(s(12,cc) + s(13,cc)) + km(28)*(s(10,cc) + s(11,cc)) + km(36)*(s(14,cc) &
               + s(15,cc)) + km(37)*(s(12,cc) + s(13,cc))
            t(116) = km(36)*(s(16,cc) + s(17,cc)) + km(37)*(s(14,cc) + s(15,cc))
            t(117) = km(3)*(s(1,cc) + s(5,cc)) + km(8)*(s(2,cc) + 3.0_dp*s(4,cc))
            t(118) = km(5)*(s(2,cc) + s(4,cc)) + km(15)*(s(3,cc) + 3.0_dp*s(7,cc))
            t(119) = km(3)*s(4,cc) + km(8)*(s(3,cc) + 6.0_dp*s(7,cc))
            t(120) = km(5)*s(7,cc) + km(15)*(s(6,cc) + 6.0_dp*s(8,cc))
            t(121) = km(8)*s(8,cc)
            t(122) = km(15)*s(9,cc)
            t(123) = km(3)*(s(10,cc) + s(11,cc)) + km(8)*(3.0_dp*s(12,cc) + 3.0_dp*s(13,cc))
            t(124) = km(5)*(s(12,cc) + s(13,cc)) + km(15)*(3.0_dp*s(14,cc) + 3.0_dp*s(15,cc))
            t(125) = km(15)*(s(16,cc) + s(17,cc))
            t(126) = km(8)*(s(14,cc) + s(15,cc))
            t(127) = km(3)*(s(1,cc) + s(5,cc) + s(18,cc) + 2.0_dp*s(19,cc) + s(20,cc)) + &
               km(8)*(s(2,cc) + s(4,cc) + s(21,cc) + 2.0_dp*s(22,cc) + s(23,cc))
            t(128) = km(5)*(s(2,cc) + s(4,cc) + s(21,cc) + 2.0_dp*s(22,cc) + s(23,cc)) + &
               km(15)*(s(3,cc) + s(7,cc) + s(24,cc) + 2.0_dp*s(25,cc) + s(26,cc))
            t(129) = km(8)*(s(3,cc) + s(7,cc) + s(24,cc) + 2.0_dp*s(25,cc) + s(26,cc))
            t(130) = km(15)*(s(6,cc) + s(8,cc) + s(27,cc) + 2.0_dp*s(28,cc) + s(29,cc))
            t(131) = km(7)*s(15,cc) + km(8)*(s(13,cc) + s(31,cc))
            t(132) = km(14)*s(17,cc) + km(15)*(3.0_dp*s(15,cc) + s(32,cc))
            t(133) = km(33)*s(8,cc) + km(34)*(s(3,cc) + 3.0_dp*s(7,cc))
            t(134) = km(32)*s(13,cc)
            t(135) = km(36)*s(15,cc) + km(37)*s(13,cc)
            t(136) = km(36)*s(17,cc) + km(37)*s(15,cc)
            t(137) = km(9)*s(7,cc) + km(10)*s(4,cc)
            t(138) = km(9)*s(8,cc) + km(10)*s(7,cc)
            t(139) = km(36)*(s(8,cc) + s(28,cc) + s(29,cc)) + km(37)*(s(7,cc) + s(25,cc) + &
               s(26,cc))
            t(140) = km(9)*(s(14,cc) + s(15,cc)) + km(10)*(s(12,cc) + s(13,cc))
            t(141) = km(8)*(s(13,cc) + (1.0_dp/3.0_dp)*s(31,cc))
            t(142) = km(15)*(s(15,cc) + (1.0_dp/3.0_dp)*s(32,cc))
            t(143) = km(15)*s(17,cc)
            t(144) = km(8)*s(15,cc)
            t(145) = km(34)*(s(3,cc) + 3.0_dp*s(7,cc))
            t(146) = km(34)*s(8,cc)
            t(147) = km(8)*(s(4,cc) + s(22,cc) + s(23,cc))
            t(148) = km(15)*(s(7,cc) + s(25,cc) + s(26,cc))
            t(149) = km(8)*(s(7,cc) + s(25,cc) + s(26,cc))
            t(150) = km(15)*(s(8,cc) + s(28,cc) + s(29,cc))
            t(151) = km(34)*(s(12,cc) + s(13,cc))
            t(152) = km(34)*(s(14,cc) + s(15,cc))
            t(153) = km(8)*(s(12,cc) + (3.0_dp/2.0_dp)*s(13,cc) + (1.0_dp/2.0_dp)*s(31,cc) + &
               (1.0_dp/2.0_dp)*s(36,cc) + s(37,cc) + (1.0_dp/2.0_dp)*s(38,cc))
            t(154) = km(15)*(s(14,cc) + (3.0_dp/2.0_dp)*s(15,cc) + (1.0_dp/2.0_dp)*s(32,cc) + &
               (1.0_dp/2.0_dp)*s(39,cc) + s(40,cc) + (1.0_dp/2.0_dp)*s(41,cc))
            t(155) = km(34)*(s(3,cc) + s(7,cc) + s(24,cc) + 2.0_dp*s(25,cc) + s(26,cc))
            t(156) = km(31)*s(15,cc) + km(32)*(3.0_dp*s(13,cc) + s(31,cc)) - km(33)*s(15,cc) + &
               km(34)*((-3.0_dp)*s(13,cc) - s(31,cc))
            t(157) = km(29)*s(13,cc) + km(30)*(s(11,cc) + s(30,cc))
            t(158) = km(3)*(s(1,cc) + s(5,cc)) + km(7)*(s(3,cc) + 6.0_dp*s(7,cc)) + km(8)*(s(2,cc) &
               + 3.0_dp*s(4,cc)) + km(13)*s(4,cc) + km(19)*s(8,cc)
            t(159) = km(4)*(s(2,cc) + 3.0_dp*s(4,cc)) + km(6)*(-s(2,cc) + (-3.0_dp)*s(4,cc)) + &
               km(16)*s(7,cc) - km(18)*s(7,cc)
            t(160) = km(7)*s(15,cc) + km(8)*s(13,cc) - km(9)*s(15,cc) - km(10)*s(13,cc)
            t(161) = km(6)*s(13,cc)
            t(162) = km(24)*s(4,cc) + km(31)*s(8,cc) + 3.0_dp*km(32)*s(7,cc)
            t(163) = km(25)*s(7,cc) + km(26)*s(4,cc) - km(29)*s(7,cc) - km(30)*s(4,cc)
            t(164) = km(7)*(s(7,cc) + s(25,cc) + s(26,cc)) + km(8)*(s(4,cc) + s(22,cc) + s(23,cc)) &
               + km(9)*(-s(7,cc) - s(25,cc) - s(26,cc)) + km(10)*(-s(4,cc) - s(22,cc) - s(23,cc))
            t(165) = km(6)*(s(4,cc) + s(22,cc) + s(23,cc))
            t(166) = km(24)*(s(10,cc) + s(11,cc)) + km(31)*(s(14,cc) + s(15,cc)) + &
               km(32)*(3.0_dp*s(12,cc) + 3.0_dp*s(13,cc))
            t(167) = km(25)*(s(12,cc) + s(13,cc)) + km(26)*(s(10,cc) + s(11,cc)) + &
               km(29)*(-s(12,cc) - s(13,cc)) + km(30)*(-s(10,cc) - s(11,cc))
            t(168) = km(32)*(s(13,cc) + s(31,cc)) + km(34)*(-s(13,cc) - s(31,cc))
            t(169) = km(30)*(s(11,cc) + s(30,cc))
            t(170) = km(32)*s(15,cc) - km(34)*s(15,cc)
            t(171) = km(30)*s(13,cc)
            t(172) = km(3)*(s(1,cc) + s(5,cc)) + km(7)*(s(3,cc) + s(7,cc)) + km(8)*(s(2,cc) + &
               s(4,cc))
            t(173) = km(4)*(s(2,cc) + s(4,cc)) + km(6)*(-s(2,cc) - s(4,cc))
            t(174) = km(3)*s(4,cc) + km(7)*s(8,cc) + km(8)*s(7,cc)
            t(175) = km(4)*s(7,cc) - km(6)*s(7,cc)
            t(176) = km(32)*(s(7,cc) + s(25,cc) + s(26,cc)) + km(34)*(-s(7,cc) - s(25,cc) - &
               s(26,cc))
            t(177) = km(30)*(s(4,cc) + s(22,cc) + s(23,cc))
            t(178) = km(3)*(s(10,cc) + s(11,cc)) + km(7)*(s(14,cc) + s(15,cc)) + km(8)*(s(12,cc) + &
               s(13,cc))
            t(179) = km(4)*(s(12,cc) + s(13,cc)) + km(6)*(-s(12,cc) - s(13,cc))
            t(180) = km(32)*(s(12,cc) + (3.0_dp/2.0_dp)*s(13,cc) + (1.0_dp/2.0_dp)*s(31,cc) + &
               (1.0_dp/2.0_dp)*s(36,cc) + s(37,cc) + (1.0_dp/2.0_dp)*s(38,cc)) + km(34)*(-s(12,cc) &
               + (-3.0_dp/2.0_dp)*s(13,cc) + (-1.0_dp/2.0_dp)*s(31,cc) + (-1.0_dp/2.0_dp)*s(36,cc) &
               - s(37,cc) + (-1.0_dp/2.0_dp)*s(38,cc))
            t(181) = km(30)*(s(10,cc) + (3.0_dp/2.0_dp)*s(11,cc) + (1.0_dp/2.0_dp)*s(30,cc) + &
               (1.0_dp/2.0_dp)*s(33,cc) + s(34,cc) + (1.0_dp/2.0_dp)*s(35,cc))
            t(182) = km(3)*(s(1,cc) + s(5,cc) + s(18,cc) + 2.0_dp*s(19,cc) + s(20,cc)) + &
               km(7)*(s(3,cc) + s(7,cc) + s(24,cc) + 2.0_dp*s(25,cc) + s(26,cc)) + km(8)*(s(2,cc) + &
               s(4,cc) + s(21,cc) + 2.0_dp*s(22,cc) + s(23,cc))
            t(183) = km(4)*(s(2,cc) + s(4,cc) + s(21,cc) + 2.0_dp*s(22,cc) + s(23,cc)) + &
               km(6)*(-s(2,cc) - s(4,cc) - s(21,cc) + (-2.0_dp)*s(22,cc) - s(23,cc))
            t(184) = km(3)*(s(1,cc) + s(5,cc)) + km(7)*(s(7,cc) + s(26,cc)) + km(8)*(s(2,cc) + &
               s(4,cc) + s(23,cc) + s(42,cc)) + km(13)*s(4,cc)
            t(185) = km(5)*(s(2,cc) + 3.0_dp*s(4,cc)) + km(14)*(s(8,cc) + s(29,cc)) + &
               km(15)*(s(3,cc) + 3.0_dp*s(7,cc) + 3.0_dp*s(26,cc) + s(43,cc)) + km(17)*s(7,cc)
            t(186) = km(25)*s(13,cc) + km(26)*(s(11,cc) + s(30,cc)) - km(29)*s(13,cc) + &
               km(30)*(-s(11,cc) - s(30,cc))
            t(187) = km(24)*s(4,cc) + km(32)*(s(7,cc) + s(26,cc))
            t(188) = km(27)*s(7,cc) + km(28)*s(4,cc) + km(36)*(s(8,cc) + s(29,cc)) + &
               km(37)*(s(7,cc) + s(26,cc))
            t(189) = km(4)*s(13,cc) - km(6)*s(13,cc)
            t(190) = km(24)*(s(10,cc) + s(11,cc)) + km(32)*(s(12,cc) + 3.0_dp*s(13,cc) + s(37,cc) + &
               s(38,cc))
            t(191) = km(27)*(s(12,cc) + s(13,cc)) + km(28)*(s(10,cc) + s(11,cc)) + km(36)*(s(14,cc) &
               + 3.0_dp*s(15,cc) + s(40,cc) + s(41,cc)) + km(37)*(s(12,cc) + 3.0_dp*s(13,cc) + &
               s(37,cc) + s(38,cc))
            t(192) = km(4)*(s(4,cc) + s(22,cc) + s(23,cc)) + km(6)*(-s(4,cc) - s(22,cc) - s(23,cc))
            t(193) = km(3)*(s(1,cc) + s(5,cc)) + km(8)*(s(2,cc) + s(4,cc) + s(23,cc) + s(42,cc))
            t(194) = km(5)*(s(2,cc) + s(4,cc)) + km(15)*(s(3,cc) + s(7,cc) + s(26,cc) + s(43,cc))
            t(195) = km(3)*s(4,cc) + km(8)*(s(7,cc) + s(26,cc))
            t(196) = km(5)*s(7,cc) + km(15)*(s(8,cc) + s(29,cc))
            t(197) = km(26)*(s(11,cc) + s(30,cc)) + km(30)*(-s(11,cc) - s(30,cc))
            t(198) = km(26)*s(13,cc) - km(30)*s(13,cc)
            t(199) = km(3)*(s(10,cc) + s(11,cc)) + km(8)*(s(12,cc) + 3.0_dp*s(13,cc) + s(37,cc) + &
               s(38,cc))
            t(200) = km(5)*(s(12,cc) + s(13,cc)) + km(15)*(s(14,cc) + 3.0_dp*s(15,cc) + s(40,cc) + &
               s(41,cc))
            t(201) = km(26)*(s(4,cc) + s(22,cc) + s(23,cc)) + km(30)*(-s(4,cc) - s(22,cc) - &
               s(23,cc))
            t(202) = km(3)*(s(1,cc) + s(5,cc) + s(18,cc) + 2.0_dp*s(19,cc) + s(20,cc)) + &
               km(8)*(s(2,cc) + 3.0_dp*s(4,cc) + s(21,cc) + 6.0_dp*s(22,cc) + 6.0_dp*s(23,cc) + &
               s(42,cc) + s(44,cc) + 2.0_dp*s(45,cc) + s(46,cc))
            t(203) = km(5)*(s(2,cc) + s(4,cc) + s(21,cc) + 2.0_dp*s(22,cc) + s(23,cc)) + &
               km(15)*(s(3,cc) + 3.0_dp*s(7,cc) + s(24,cc) + 6.0_dp*s(25,cc) + 6.0_dp*s(26,cc) + &
               s(43,cc) + s(47,cc) + 2.0_dp*s(48,cc) + s(49,cc))
            t(204) = km(26)*(s(10,cc) + (3.0_dp/2.0_dp)*s(11,cc) + (1.0_dp/2.0_dp)*s(30,cc) + &
               (1.0_dp/2.0_dp)*s(33,cc) + s(34,cc) + (1.0_dp/2.0_dp)*s(35,cc)) + km(30)*(-s(10,cc) &
               + (-3.0_dp/2.0_dp)*s(11,cc) + (-1.0_dp/2.0_dp)*s(30,cc) + (-1.0_dp/2.0_dp)*s(33,cc) &
               - s(34,cc) + (-1.0_dp/2.0_dp)*s(35,cc))
            t(205) = km(2)*(s(1,cc) + s(5,cc)) + km(9)*s(7,cc) + km(10)*(s(2,cc) + s(4,cc)) + &
               km(12)*s(4,cc)
            t(206) = km(9)*s(8,cc) + km(10)*(s(3,cc) + s(7,cc))
            t(207) = km(23)*s(4,cc) + 3.0_dp*km(34)*s(7,cc)
            t(208) = km(23)*(s(10,cc) + s(11,cc)) + km(34)*(s(12,cc) + s(13,cc))
            t(209) = km(2)*(s(1,cc) + s(5,cc)) + km(10)*(s(2,cc) + 3.0_dp*s(4,cc))
            t(210) = km(2)*s(4,cc) + km(10)*(s(3,cc) + 6.0_dp*s(7,cc))
            t(211) = km(10)*s(8,cc)
            t(212) = km(2)*(s(10,cc) + s(11,cc)) + km(10)*(3.0_dp*s(12,cc) + 3.0_dp*s(13,cc))
            t(213) = km(10)*(s(14,cc) + s(15,cc))
            t(214) = km(2)*(s(1,cc) + s(5,cc) + s(18,cc) + 2.0_dp*s(19,cc) + s(20,cc)) + &
               km(10)*(s(2,cc) + s(4,cc) + s(21,cc) + 2.0_dp*s(22,cc) + s(23,cc))
            t(215) = km(10)*(s(3,cc) + s(7,cc) + s(24,cc) + 2.0_dp*s(25,cc) + s(26,cc))
            t(216) = km(27)*s(7,cc) + km(28)*(s(2,cc) + s(4,cc)) + km(36)*s(8,cc) + km(37)*(s(3,cc) &
               + s(7,cc))
            t(217) = km(36)*s(9,cc) + km(37)*(s(6,cc) + s(8,cc))
            t(218) = km(5)*s(4,cc) + km(15)*s(7,cc)
            t(219) = km(5)*s(7,cc) + 2.0_dp*km(15)*s(8,cc)
            t(220) = km(5)*(s(12,cc) + s(13,cc)) + km(15)*(s(14,cc) + s(15,cc))
            t(221) = km(28)*(s(2,cc) + 3.0_dp*s(4,cc)) + km(37)*(s(3,cc) + 5.0_dp*s(7,cc))
            t(222) = km(28)*s(7,cc) + km(37)*((1.0_dp/3.0_dp)*s(6,cc) + (10.0_dp/3.0_dp)*s(8,cc))
            t(223) = km(37)*s(9,cc)
            t(224) = km(28)*(s(10,cc) + s(11,cc)) + km(37)*(s(12,cc) + s(13,cc))
            t(225) = km(28)*(s(12,cc) + s(13,cc)) + km(37)*(2.0_dp*s(14,cc) + 2.0_dp*s(15,cc))
            t(226) = km(37)*(s(16,cc) + s(17,cc))
            t(227) = km(28)*(s(2,cc) + s(4,cc) + s(21,cc) + 2.0_dp*s(22,cc) + s(23,cc)) + &
               km(37)*(s(3,cc) + s(7,cc) + s(24,cc) + 2.0_dp*s(25,cc) + s(26,cc))
            t(228) = km(37)*(s(6,cc) + s(8,cc) + s(27,cc) + 2.0_dp*s(28,cc) + s(29,cc))
            t(229) = km(27)*s(13,cc) + km(28)*(s(11,cc) + s(30,cc)) + km(36)*s(15,cc) + &
               km(37)*(s(13,cc) + s(31,cc))
            t(230) = km(36)*s(17,cc) + km(37)*(s(15,cc) + s(32,cc))
            t(231) = km(5)*s(13,cc) + 3.0_dp*km(15)*s(15,cc)
            t(232) = km(5)*(s(4,cc) + s(22,cc) + s(23,cc)) + km(15)*(s(7,cc) + s(25,cc) + s(26,cc))
            t(233) = km(28)*(s(11,cc) + s(30,cc)) + km(37)*(3.0_dp*s(13,cc) + s(31,cc))
            t(234) = km(28)*s(13,cc) + km(37)*(6.0_dp*s(15,cc) + s(32,cc))
            t(235) = km(37)*s(17,cc)
            t(236) = km(28)*(s(4,cc) + s(22,cc) + s(23,cc)) + km(37)*(3.0_dp*s(7,cc) + &
               3.0_dp*s(25,cc) + 3.0_dp*s(26,cc))
            t(237) = km(37)*(s(8,cc) + s(28,cc) + s(29,cc))
            t(238) = km(28)*(s(10,cc) + (3.0_dp/2.0_dp)*s(11,cc) + (1.0_dp/2.0_dp)*s(30,cc) + &
               (1.0_dp/2.0_dp)*s(33,cc) + s(34,cc) + (1.0_dp/2.0_dp)*s(35,cc)) + km(37)*(s(12,cc) + &
               (3.0_dp/2.0_dp)*s(13,cc) + (1.0_dp/2.0_dp)*s(31,cc) + (1.0_dp/2.0_dp)*s(36,cc) + &
               s(37,cc) + (1.0_dp/2.0_dp)*s(38,cc))
            t(239) = km(37)*(s(14,cc) + (3.0_dp/2.0_dp)*s(15,cc) + (1.0_dp/2.0_dp)*s(32,cc) + &
               (1.0_dp/2.0_dp)*s(39,cc) + s(40,cc) + (1.0_dp/2.0_dp)*s(41,cc))
            t(240) = km(9)*s(15,cc) + km(10)*(s(13,cc) + s(31,cc))
            t(241) = km(34)*s(13,cc)
            t(242) = km(34)*s(15,cc)
            t(243) = km(34)*(s(7,cc) + s(25,cc) + s(26,cc))
            t(244) = km(10)*(s(13,cc) + (1.0_dp/3.0_dp)*s(31,cc))
            t(245) = km(10)*s(15,cc)
            t(246) = km(10)*(s(4,cc) + s(22,cc) + s(23,cc))
            t(247) = km(10)*(s(7,cc) + s(25,cc) + s(26,cc))
            t(248) = km(10)*(s(12,cc) + (3.0_dp/2.0_dp)*s(13,cc) + (1.0_dp/2.0_dp)*s(31,cc) + &
               (1.0_dp/2.0_dp)*s(36,cc) + s(37,cc) + (1.0_dp/2.0_dp)*s(38,cc))
            t(249) = km(27)*s(7,cc) + km(28)*(s(2,cc) + s(4,cc)) + km(36)*(s(8,cc) + s(29,cc)) + &
               km(37)*(s(3,cc) + s(7,cc) + s(26,cc) + s(43,cc))
            t(250) = km(7)*s(15,cc) + km(8)*(s(13,cc) + s(31,cc)) - km(9)*s(15,cc) + &
               km(10)*(-s(13,cc) - s(31,cc))
            t(251) = km(5)*s(4,cc) + km(15)*(s(7,cc) + s(26,cc))
            t(252) = km(32)*s(13,cc) - km(34)*s(13,cc)
            t(253) = km(28)*(s(2,cc) + 3.0_dp*s(4,cc)) + km(37)*(s(3,cc) + 3.0_dp*s(7,cc) + &
               3.0_dp*s(26,cc) + s(43,cc))
            t(254) = km(28)*s(7,cc) + km(37)*(s(8,cc) + s(29,cc))
            t(255) = km(8)*(s(13,cc) + (1.0_dp/3.0_dp)*s(31,cc)) + km(10)*(-s(13,cc) + &
               (-1.0_dp/3.0_dp)*s(31,cc))
            t(256) = km(8)*s(15,cc) - km(10)*s(15,cc)
            t(257) = km(28)*(s(10,cc) + s(11,cc)) + km(37)*(s(12,cc) + 3.0_dp*s(13,cc) + s(37,cc) + &
               s(38,cc))
            t(258) = km(28)*(s(12,cc) + s(13,cc)) + km(37)*(s(14,cc) + 3.0_dp*s(15,cc) + s(40,cc) + &
               s(41,cc))
            t(259) = km(8)*(s(4,cc) + s(22,cc) + s(23,cc)) + km(10)*(-s(4,cc) - s(22,cc) - &
               s(23,cc))
            t(260) = km(8)*(s(7,cc) + s(25,cc) + s(26,cc)) + km(10)*(-s(7,cc) - s(25,cc) - &
               s(26,cc))
            t(261) = km(28)*(s(2,cc) + s(4,cc) + s(21,cc) + 2.0_dp*s(22,cc) + s(23,cc)) + &
               km(37)*(s(3,cc) + 3.0_dp*s(7,cc) + s(24,cc) + 6.0_dp*s(25,cc) + 6.0_dp*s(26,cc) + &
               s(43,cc) + s(47,cc) + 2.0_dp*s(48,cc) + s(49,cc))
            t(262) = km(8)*(s(12,cc) + (3.0_dp/2.0_dp)*s(13,cc) + (1.0_dp/2.0_dp)*s(31,cc) + &
               (1.0_dp/2.0_dp)*s(36,cc) + s(37,cc) + (1.0_dp/2.0_dp)*s(38,cc)) + km(10)*(-s(12,cc) &
               + (-3.0_dp/2.0_dp)*s(13,cc) + (-1.0_dp/2.0_dp)*s(31,cc) + (-1.0_dp/2.0_dp)*s(36,cc) &
               - s(37,cc) + (-1.0_dp/2.0_dp)*s(38,cc))
            t(263) = km(2)*(s(1,cc) + s(5,cc)) + km(9)*(s(7,cc) + s(26,cc)) + km(10)*(s(2,cc) + &
               s(4,cc) + s(23,cc) + s(42,cc)) + km(12)*s(4,cc)
            t(264) = km(4)*(s(2,cc) + 3.0_dp*s(4,cc)) + km(16)*s(7,cc)
            t(265) = km(23)*s(4,cc) + km(34)*(s(7,cc) + s(26,cc))
            t(266) = km(25)*s(7,cc) + km(26)*s(4,cc)
            t(267) = km(23)*(s(10,cc) + s(11,cc)) + km(34)*(s(12,cc) + 3.0_dp*s(13,cc) + s(37,cc) + &
               s(38,cc))
            t(268) = km(25)*(s(12,cc) + s(13,cc)) + km(26)*(s(10,cc) + s(11,cc))
            t(269) = km(2)*(s(1,cc) + s(5,cc)) + km(10)*(s(2,cc) + s(4,cc) + s(23,cc) + s(42,cc))
            t(270) = km(2)*s(4,cc) + km(10)*(s(7,cc) + s(26,cc))
            t(271) = km(4)*(s(2,cc) + s(4,cc))
            t(272) = km(2)*(s(10,cc) + s(11,cc)) + km(10)*(s(12,cc) + 3.0_dp*s(13,cc) + s(37,cc) + &
               s(38,cc))
            t(273) = km(2)*(s(1,cc) + s(5,cc) + s(18,cc) + 2.0_dp*s(19,cc) + s(20,cc)) + &
               km(10)*(s(2,cc) + 3.0_dp*s(4,cc) + s(21,cc) + 6.0_dp*s(22,cc) + 6.0_dp*s(23,cc) + &
               s(42,cc) + s(44,cc) + 2.0_dp*s(45,cc) + s(46,cc))
            t(274) = km(4)*(s(2,cc) + s(4,cc) + s(21,cc) + 2.0_dp*s(22,cc) + s(23,cc))
            t(275) = km(27)*s(13,cc) + km(28)*(s(11,cc) + s(30,cc)) + km(36)*(s(15,cc) + &
               (1.0_dp/3.0_dp)*s(41,cc)) + km(37)*(s(13,cc) + s(31,cc) + (1.0_dp/3.0_dp)*s(38,cc) + &
               (1.0_dp/3.0_dp)*s(50,cc))
            t(276) = km(2)*(s(1,cc) + s(5,cc)) + km(3)*((-2.0_dp)*s(1,cc) + (-2.0_dp)*s(5,cc)) + &
               km(7)*((-2.0_dp)*s(7,cc) + (-2.0_dp)*s(26,cc)) + km(8)*((-2.0_dp)*s(2,cc) + &
               (-2.0_dp)*s(4,cc) + (-2.0_dp)*s(23,cc) + (-2.0_dp)*s(42,cc)) + km(9)*(s(7,cc) + &
               s(26,cc)) + km(10)*(s(2,cc) + s(4,cc) + s(23,cc) + s(42,cc)) + km(12)*s(4,cc) + &
               (-2.0_dp)*km(13)*s(4,cc)
            t(277) = km(25)*s(13,cc) + km(26)*(s(11,cc) + s(30,cc)) + (-2.0_dp)*km(29)*s(13,cc) + &
               km(30)*((-2.0_dp)*s(11,cc) + (-2.0_dp)*s(30,cc))
            t(278) = km(5)*s(13,cc) + km(15)*(s(15,cc) + (1.0_dp/3.0_dp)*s(41,cc))
            t(279) = km(23)*s(4,cc) + (-2.0_dp)*km(24)*s(4,cc) + km(32)*((-2.0_dp)*s(7,cc) + &
               (-2.0_dp)*s(26,cc)) + km(34)*(s(7,cc) + s(26,cc))
            t(280) = km(4)*s(13,cc) + (-2.0_dp)*km(6)*s(13,cc)
            t(281) = km(5)*(s(4,cc) + s(22,cc) + s(23,cc)) + km(15)*(s(7,cc) + s(25,cc) + &
               2.0_dp*s(26,cc) + (1.0_dp/3.0_dp)*s(48,cc) + (1.0_dp/3.0_dp)*s(49,cc))
            t(282) = km(23)*(s(10,cc) + s(11,cc)) + km(24)*((-2.0_dp)*s(10,cc) + &
               (-2.0_dp)*s(11,cc)) + km(32)*((-2.0_dp)*s(12,cc) + (-6.0_dp)*s(13,cc) + &
               (-2.0_dp)*s(37,cc) + (-2.0_dp)*s(38,cc)) + km(34)*(s(12,cc) + 3.0_dp*s(13,cc) + &
               s(37,cc) + s(38,cc))
            t(283) = km(4)*(s(4,cc) + s(22,cc) + s(23,cc)) + km(6)*((-2.0_dp)*s(4,cc) + &
               (-2.0_dp)*s(22,cc) + (-2.0_dp)*s(23,cc))
            t(284) = km(28)*(s(11,cc) + s(30,cc)) + km(37)*(s(13,cc) + s(31,cc) + &
               (1.0_dp/3.0_dp)*s(38,cc) + (1.0_dp/3.0_dp)*s(50,cc))
            t(285) = km(28)*s(13,cc) + km(37)*(s(15,cc) + (1.0_dp/3.0_dp)*s(41,cc))
            t(286) = km(2)*(s(1,cc) + s(5,cc)) + km(3)*((-2.0_dp)*s(1,cc) + (-2.0_dp)*s(5,cc)) + &
               km(8)*((-2.0_dp)*s(2,cc) + (-2.0_dp)*s(4,cc) + (-2.0_dp)*s(23,cc) + &
               (-2.0_dp)*s(42,cc)) + km(10)*(s(2,cc) + s(4,cc) + s(23,cc) + s(42,cc))
            t(287) = km(2)*s(4,cc) + (-2.0_dp)*km(3)*s(4,cc) + km(8)*((-2.0_dp)*s(7,cc) + &
               (-2.0_dp)*s(26,cc)) + km(10)*(s(7,cc) + s(26,cc))
            t(288) = km(26)*(s(11,cc) + s(30,cc)) + km(30)*((-2.0_dp)*s(11,cc) + &
               (-2.0_dp)*s(30,cc))
            t(289) = km(26)*s(13,cc) + (-2.0_dp)*km(30)*s(13,cc)
            t(290) = km(28)*(s(4,cc) + s(22,cc) + s(23,cc)) + km(37)*(s(7,cc) + s(25,cc) + &
               2.0_dp*s(26,cc) + (1.0_dp/3.0_dp)*s(48,cc) + (1.0_dp/3.0_dp)*s(49,cc))
            t(291) = km(2)*(s(10,cc) + s(11,cc)) + km(3)*((-2.0_dp)*s(10,cc) + (-2.0_dp)*s(11,cc)) &
               + km(8)*((-2.0_dp)*s(12,cc) + (-6.0_dp)*s(13,cc) + (-2.0_dp)*s(37,cc) + &
               (-2.0_dp)*s(38,cc)) + km(10)*(s(12,cc) + 3.0_dp*s(13,cc) + s(37,cc) + s(38,cc))
            t(292) = km(26)*(s(4,cc) + s(22,cc) + s(23,cc)) + km(30)*((-2.0_dp)*s(4,cc) + &
               (-2.0_dp)*s(22,cc) + (-2.0_dp)*s(23,cc))
            t(293) = km(28)*(s(10,cc) + (3.0_dp/2.0_dp)*s(11,cc) + (1.0_dp/2.0_dp)*s(30,cc) + &
               (1.0_dp/2.0_dp)*s(33,cc) + s(34,cc) + (1.0_dp/2.0_dp)*s(35,cc)) + km(37)*(s(12,cc) + &
               (5.0_dp/2.0_dp)*s(13,cc) + (1.0_dp/2.0_dp)*s(31,cc) + (1.0_dp/2.0_dp)*s(36,cc) + &
               2.0_dp*s(37,cc) + (5.0_dp/3.0_dp)*s(38,cc) + (1.0_dp/6.0_dp)*s(50,cc) + &
               (1.0_dp/6.0_dp)*s(51,cc) + (1.0_dp/3.0_dp)*s(52,cc) + (1.0_dp/6.0_dp)*s(53,cc))
            t(294) = km(2)*(s(1,cc) + s(5,cc) + s(18,cc) + 2.0_dp*s(19,cc) + s(20,cc)) + &
               km(3)*((-2.0_dp)*s(1,cc) + (-2.0_dp)*s(5,cc) + (-2.0_dp)*s(18,cc) + &
               (-4.0_dp)*s(19,cc) + (-2.0_dp)*s(20,cc)) + km(8)*((-2.0_dp)*s(2,cc) + &
               (-6.0_dp)*s(4,cc) + (-2.0_dp)*s(21,cc) + (-12.0_dp)*s(22,cc) + (-12.0_dp)*s(23,cc) + &
               (-2.0_dp)*s(42,cc) + (-2.0_dp)*s(44,cc) + (-4.0_dp)*s(45,cc) + (-2.0_dp)*s(46,cc)) + &
               km(10)*(s(2,cc) + 3.0_dp*s(4,cc) + s(21,cc) + 6.0_dp*s(22,cc) + 6.0_dp*s(23,cc) + &
               s(42,cc) + s(44,cc) + 2.0_dp*s(45,cc) + s(46,cc))
            t(295) = km(26)*(s(10,cc) + (3.0_dp/2.0_dp)*s(11,cc) + (1.0_dp/2.0_dp)*s(30,cc) + &
               (1.0_dp/2.0_dp)*s(33,cc) + s(34,cc) + (1.0_dp/2.0_dp)*s(35,cc)) + &
               km(30)*((-2.0_dp)*s(10,cc) + (-3.0_dp)*s(11,cc) - s(30,cc) - s(33,cc) + &
               (-2.0_dp)*s(34,cc) - s(35,cc))
            do ck = 1, nck
               r(1:295,cc,ck) = r(1:295,cc,ck) + kcd(ck,kq)*t(1:295)
            end do
         end do
      end do
      res = 0.0_dp
      if (.not. any) return
      cm(1) = Rs*Rs*Rs
      cm(2) = Rs
      cm(3) = Rs*Rs
      cm(4) = 1.0_dp
      cm(5) = Rs*Rs*Rs*cy
      cm(6) = Rs*cy
      cm(7) = Rs*Rs*cy
      cm(8) = cy
      cm(9) = Rs*Rs*Rs*cy*cy
      cm(10) = Rs*cy*cy
      cm(11) = Rs*Rs*cy*cy
      cm(12) = cy*cy
      cm(13) = Rs*Rs*cy*cy*cy
      cm(14) = cy*cy*cy
      cm(15) = Rs*cy*cy*cy
      cm(16) = Rs*Rs*Rc
      cm(17) = Rc
      cm(18) = Rs*Rc
      cm(19) = Rs*Rs*Rc*cy
      cm(20) = Rc*cy
      cm(21) = Rs*Rc*cy
      cm(22) = Rs*Rs*Rc*cy*cy
      cm(23) = Rc*cy*cy
      cm(24) = Rs*Rc*cy*cy
      cm(25) = Rs*cy*cy*cy*cy
      cm(26) = cy*cy*cy*cy
      cm(27) = Rs*Rc*cy*cy*cy
      cm(28) = Rc*cy*cy*cy
      cm(29) = Rs*Rc*Rc
      cm(30) = Rc*Rc
      cm(31) = Rs*Rc*Rc*cy
      cm(32) = Rc*Rc*cy
      cm(33) = Rs*Rc*Rc*cy*cy
      cm(34) = Rc*Rc*cy*cy
      cm(35) = cy*cy*cy*cy*cy
      cm(36) = Rc*cy*cy*cy*cy
      cm(37) = Rc*Rc*cy*cy*cy
      cm(38) = Rc*Rc*Rc
      cm(39) = Rc*Rc*Rc*cy
      cm(40) = Rc*Rc*Rc*cy*cy
      do ck = 1, nck
         do cc = 1, ncb
            res(1,cc+ncb*(ck-1)) = cm(1)*r(1,cc,ck) + cm(2)*r(2,cc,ck) + cm(3)*r(3,cc,ck) + &
               3.0_dp*r(4,cc,ck)
            res(2,cc+ncb*(ck-1)) = cm(5)*r(5,cc,ck) + cm(6)*r(6,cc,ck) + cm(7)*r(7,cc,ck) + &
               3.0_dp*cm(8)*r(8,cc,ck)
            res(3,cc+ncb*(ck-1)) = -cm(1)*r(9,cc,ck) - cm(2)*r(10,cc,ck) - cm(3)*r(11,cc,ck) + &
               (-3.0_dp)*r(12,cc,ck)
            res(4,cc+ncb*(ck-1)) = cm(1)*r(13,cc,ck) + cm(2)*r(14,cc,ck) + cm(3)*r(15,cc,ck) + &
               3.0_dp*r(16,cc,ck) + cm(9)*r(17,cc,ck) + cm(10)*r(18,cc,ck) + cm(11)*r(19,cc,ck) + &
               3.0_dp*cm(12)*r(20,cc,ck)
            res(5,cc+ncb*(ck-1)) = -cm(5)*r(21,cc,ck) - cm(6)*r(22,cc,ck) - cm(7)*r(23,cc,ck) + &
               (-3.0_dp)*cm(8)*r(24,cc,ck)
            res(6,cc+ncb*(ck-1)) = cm(1)*r(25,cc,ck) + cm(2)*r(26,cc,ck) + cm(3)*r(27,cc,ck) + &
               3.0_dp*r(28,cc,ck)
            res(7,cc+ncb*(ck-1)) = (-2.0_dp)*cm(6)*r(29,cc,ck) + cm(7)*r(30,cc,ck) + &
               cm(8)*r(31,cc,ck)
            res(8,cc+ncb*(ck-1)) = (-2.0_dp)*cm(2)*r(32,cc,ck) + cm(3)*r(33,cc,ck) + r(34,cc,ck) + &
               (-2.0_dp)*cm(10)*r(35,cc,ck) + cm(11)*r(36,cc,ck) + cm(12)*r(37,cc,ck)
            res(9,cc+ncb*(ck-1)) = 2.0_dp*cm(6)*r(38,cc,ck) - cm(7)*r(39,cc,ck) - cm(8)*r(40,cc,ck)
            res(10,cc+ncb*(ck-1)) = (-2.0_dp)*cm(6)*r(41,cc,ck) + cm(7)*r(42,cc,ck) + &
               cm(8)*r(43,cc,ck) + cm(13)*r(44,cc,ck) + cm(14)*r(45,cc,ck) + &
               (-2.0_dp)*cm(15)*r(46,cc,ck)
            res(11,cc+ncb*(ck-1)) = 2.0_dp*cm(2)*r(47,cc,ck) - cm(3)*r(48,cc,ck) - r(49,cc,ck) + &
               2.0_dp*cm(10)*r(50,cc,ck) - cm(11)*r(51,cc,ck) - cm(12)*r(52,cc,ck)
            res(12,cc+ncb*(ck-1)) = (-2.0_dp)*cm(6)*r(53,cc,ck) + cm(7)*r(54,cc,ck) + &
               cm(8)*r(55,cc,ck)
            res(13,cc+ncb*(ck-1)) = 2.0_dp*cm(2)*r(56,cc,ck) - cm(3)*r(57,cc,ck) - r(58,cc,ck) + &
               cm(16)*r(1,cc,ck) + cm(17)*r(59,cc,ck) + (-2.0_dp)*cm(18)*r(60,cc,ck)
            res(14,cc+ncb*(ck-1)) = 2.0_dp*cm(6)*r(61,cc,ck) - cm(7)*r(62,cc,ck) - &
               cm(8)*r(63,cc,ck) + cm(19)*r(5,cc,ck) + cm(20)*r(64,cc,ck) + &
               (-2.0_dp)*cm(21)*r(65,cc,ck)
            res(15,cc+ncb*(ck-1)) = (-2.0_dp)*cm(2)*r(66,cc,ck) + cm(3)*r(67,cc,ck) + r(68,cc,ck) - &
               cm(16)*r(9,cc,ck) - cm(17)*r(69,cc,ck) + 2.0_dp*cm(18)*r(70,cc,ck)
            res(16,cc+ncb*(ck-1)) = 2.0_dp*cm(2)*r(71,cc,ck) - cm(3)*r(72,cc,ck) - r(73,cc,ck) + &
               2.0_dp*cm(10)*r(74,cc,ck) - cm(11)*r(75,cc,ck) - cm(12)*r(76,cc,ck) + &
               cm(16)*r(13,cc,ck) + cm(17)*r(77,cc,ck) + (-2.0_dp)*cm(18)*r(78,cc,ck) + &
               cm(22)*r(17,cc,ck) + cm(23)*r(79,cc,ck) + (-2.0_dp)*cm(24)*r(80,cc,ck)
            res(17,cc+ncb*(ck-1)) = (-2.0_dp)*cm(6)*r(81,cc,ck) + cm(7)*r(82,cc,ck) + &
               cm(8)*r(83,cc,ck) - cm(19)*r(21,cc,ck) - cm(20)*r(84,cc,ck) + &
               2.0_dp*cm(21)*r(85,cc,ck)
            res(18,cc+ncb*(ck-1)) = 4.0_dp*cm(2)*r(86,cc,ck) + (-2.0_dp)*cm(3)*r(87,cc,ck) + &
               (-2.0_dp)*r(88,cc,ck) + cm(16)*r(25,cc,ck) + cm(17)*r(89,cc,ck) + &
               (-2.0_dp)*cm(18)*r(90,cc,ck)
            res(19,cc+ncb*(ck-1)) = -cm(6)*r(91,cc,ck) - cm(7)*r(92,cc,ck) + cm(8)*r(31,cc,ck)
            res(20,cc+ncb*(ck-1)) = -cm(2)*r(93,cc,ck) - cm(3)*r(94,cc,ck) + r(34,cc,ck) - &
               cm(10)*r(95,cc,ck) - cm(11)*r(80,cc,ck) + cm(12)*r(37,cc,ck)
            res(21,cc+ncb*(ck-1)) = cm(6)*r(96,cc,ck) + cm(7)*r(85,cc,ck) - cm(8)*r(40,cc,ck)
            res(22,cc+ncb*(ck-1)) = -cm(6)*r(97,cc,ck) - cm(7)*r(98,cc,ck) + cm(8)*r(43,cc,ck) - &
               cm(13)*r(99,cc,ck) + cm(14)*r(45,cc,ck) - cm(15)*r(100,cc,ck)
            res(23,cc+ncb*(ck-1)) = cm(2)*r(101,cc,ck) + cm(3)*r(102,cc,ck) - r(49,cc,ck) + &
               cm(10)*r(103,cc,ck) + cm(11)*r(104,cc,ck) - cm(12)*r(52,cc,ck)
            res(24,cc+ncb*(ck-1)) = -cm(6)*r(105,cc,ck) - cm(7)*r(106,cc,ck) + cm(8)*r(55,cc,ck)
            res(25,cc+ncb*(ck-1)) = -cm(2)*r(107,cc,ck) + r(108,cc,ck) - cm(10)*r(109,cc,ck) + &
               cm(12)*r(110,cc,ck)
            res(26,cc+ncb*(ck-1)) = -cm(6)*r(111,cc,ck) + cm(8)*r(112,cc,ck) + cm(14)*r(113,cc,ck) &
               - cm(15)*r(46,cc,ck)
            res(27,cc+ncb*(ck-1)) = cm(2)*r(114,cc,ck) - r(115,cc,ck) + cm(10)*r(50,cc,ck) - &
               cm(12)*r(116,cc,ck)
            res(28,cc+ncb*(ck-1)) = -cm(2)*r(117,cc,ck) + r(118,cc,ck) - cm(10)*r(119,cc,ck) + &
               cm(12)*r(120,cc,ck) - cm(25)*r(121,cc,ck) + cm(26)*r(122,cc,ck)
            res(29,cc+ncb*(ck-1)) = cm(6)*r(123,cc,ck) - cm(8)*r(124,cc,ck) - cm(14)*r(125,cc,ck) + &
               cm(15)*r(126,cc,ck)
            res(30,cc+ncb*(ck-1)) = -cm(2)*r(127,cc,ck) + r(128,cc,ck) - cm(10)*r(129,cc,ck) + &
               cm(12)*r(130,cc,ck)
            res(31,cc+ncb*(ck-1)) = cm(6)*r(131,cc,ck) - cm(8)*r(132,cc,ck) + cm(20)*r(133,cc,ck) - &
               cm(21)*r(92,cc,ck)
            res(32,cc+ncb*(ck-1)) = cm(2)*r(134,cc,ck) - r(135,cc,ck) + cm(10)*r(74,cc,ck) - &
               cm(12)*r(136,cc,ck) + cm(17)*r(137,cc,ck) - cm(18)*r(94,cc,ck) + cm(23)*r(138,cc,ck) &
               - cm(24)*r(80,cc,ck)
            res(33,cc+ncb*(ck-1)) = -cm(6)*r(81,cc,ck) + cm(8)*r(139,cc,ck) - cm(20)*r(140,cc,ck) + &
               cm(21)*r(85,cc,ck)
            res(34,cc+ncb*(ck-1)) = 3.0_dp*cm(6)*r(141,cc,ck) + (-3.0_dp)*cm(8)*r(142,cc,ck) - &
               cm(14)*r(143,cc,ck) + cm(15)*r(144,cc,ck) + cm(20)*r(145,cc,ck) - cm(21)*r(98,cc,ck) &
               - cm(27)*r(99,cc,ck) + cm(28)*r(146,cc,ck)
            res(35,cc+ncb*(ck-1)) = -cm(2)*r(147,cc,ck) + r(148,cc,ck) - cm(10)*r(149,cc,ck) + &
               cm(12)*r(150,cc,ck) - cm(17)*r(151,cc,ck) + cm(18)*r(102,cc,ck) - &
               cm(23)*r(152,cc,ck) + cm(24)*r(104,cc,ck)
            res(36,cc+ncb*(ck-1)) = 2.0_dp*cm(6)*r(153,cc,ck) + (-2.0_dp)*cm(8)*r(154,cc,ck) + &
               cm(20)*r(155,cc,ck) - cm(21)*r(106,cc,ck)
            res(37,cc+ncb*(ck-1)) = cm(2)*r(156,cc,ck) + cm(3)*r(157,cc,ck) - r(58,cc,ck) + &
               cm(16)*r(1,cc,ck) - cm(17)*r(158,cc,ck) + cm(18)*r(159,cc,ck)
            res(38,cc+ncb*(ck-1)) = cm(6)*r(160,cc,ck) + cm(7)*r(161,cc,ck) - cm(8)*r(63,cc,ck) + &
               cm(19)*r(5,cc,ck) - cm(20)*r(162,cc,ck) + cm(21)*r(163,cc,ck)
            res(39,cc+ncb*(ck-1)) = -cm(2)*r(164,cc,ck) - cm(3)*r(165,cc,ck) + r(68,cc,ck) - &
               cm(16)*r(9,cc,ck) + cm(17)*r(166,cc,ck) - cm(18)*r(167,cc,ck)
            res(40,cc+ncb*(ck-1)) = cm(2)*r(168,cc,ck) + cm(3)*r(169,cc,ck) - r(73,cc,ck) + &
               cm(10)*r(170,cc,ck) + cm(11)*r(171,cc,ck) - cm(12)*r(76,cc,ck) + cm(16)*r(13,cc,ck) &
               - cm(17)*r(172,cc,ck) + cm(18)*r(173,cc,ck) + cm(22)*r(17,cc,ck) - &
               cm(23)*r(174,cc,ck) + cm(24)*r(175,cc,ck)
            res(41,cc+ncb*(ck-1)) = -cm(6)*r(176,cc,ck) - cm(7)*r(177,cc,ck) + cm(8)*r(83,cc,ck) - &
               cm(19)*r(21,cc,ck) + cm(20)*r(178,cc,ck) - cm(21)*r(179,cc,ck)
            res(42,cc+ncb*(ck-1)) = 2.0_dp*cm(2)*r(180,cc,ck) + 2.0_dp*cm(3)*r(181,cc,ck) + &
               (-2.0_dp)*r(88,cc,ck) + cm(16)*r(25,cc,ck) - cm(17)*r(182,cc,ck) + &
               cm(18)*r(183,cc,ck)
            res(43,cc+ncb*(ck-1)) = cm(6)*r(131,cc,ck) - cm(8)*r(132,cc,ck) - cm(20)*r(29,cc,ck) + &
               cm(21)*r(30,cc,ck)
            res(44,cc+ncb*(ck-1)) = cm(2)*r(134,cc,ck) - r(135,cc,ck) + cm(10)*r(74,cc,ck) - &
               cm(12)*r(136,cc,ck) - cm(17)*r(32,cc,ck) + cm(18)*r(33,cc,ck) - cm(23)*r(35,cc,ck) + &
               cm(24)*r(36,cc,ck)
            res(45,cc+ncb*(ck-1)) = -cm(6)*r(81,cc,ck) + cm(8)*r(139,cc,ck) + cm(20)*r(38,cc,ck) - &
               cm(21)*r(39,cc,ck)
            res(46,cc+ncb*(ck-1)) = 3.0_dp*cm(6)*r(141,cc,ck) + (-3.0_dp)*cm(8)*r(142,cc,ck) - &
               cm(14)*r(143,cc,ck) + cm(15)*r(144,cc,ck) - cm(20)*r(41,cc,ck) + cm(21)*r(42,cc,ck) &
               + cm(27)*r(44,cc,ck) - cm(28)*r(46,cc,ck)
            res(47,cc+ncb*(ck-1)) = -cm(2)*r(147,cc,ck) + r(148,cc,ck) - cm(10)*r(149,cc,ck) + &
               cm(12)*r(150,cc,ck) + cm(17)*r(47,cc,ck) - cm(18)*r(48,cc,ck) + cm(23)*r(50,cc,ck) - &
               cm(24)*r(51,cc,ck)
            res(48,cc+ncb*(ck-1)) = 2.0_dp*cm(6)*r(153,cc,ck) + (-2.0_dp)*cm(8)*r(154,cc,ck) - &
               cm(20)*r(53,cc,ck) + cm(21)*r(54,cc,ck)
            res(49,cc+ncb*(ck-1)) = -cm(2)*r(184,cc,ck) + r(185,cc,ck) + cm(17)*r(156,cc,ck) - &
               cm(18)*r(186,cc,ck) + cm(29)*r(1,cc,ck) - cm(30)*r(60,cc,ck)
            res(50,cc+ncb*(ck-1)) = -cm(6)*r(187,cc,ck) + cm(8)*r(188,cc,ck) + cm(20)*r(160,cc,ck) &
               - cm(21)*r(189,cc,ck) + cm(31)*r(5,cc,ck) - cm(32)*r(65,cc,ck)
            res(51,cc+ncb*(ck-1)) = cm(2)*r(190,cc,ck) - r(191,cc,ck) - cm(17)*r(164,cc,ck) + &
               cm(18)*r(192,cc,ck) - cm(29)*r(9,cc,ck) + cm(30)*r(70,cc,ck)
            res(52,cc+ncb*(ck-1)) = -cm(2)*r(193,cc,ck) + r(194,cc,ck) - cm(10)*r(195,cc,ck) + &
               cm(12)*r(196,cc,ck) + cm(17)*r(168,cc,ck) - cm(18)*r(197,cc,ck) + &
               cm(23)*r(170,cc,ck) - cm(24)*r(198,cc,ck) + cm(29)*r(13,cc,ck) - cm(30)*r(78,cc,ck) &
               + cm(33)*r(17,cc,ck) - cm(34)*r(80,cc,ck)
            res(53,cc+ncb*(ck-1)) = cm(6)*r(199,cc,ck) - cm(8)*r(200,cc,ck) - cm(20)*r(176,cc,ck) + &
               cm(21)*r(201,cc,ck) - cm(31)*r(21,cc,ck) + cm(32)*r(85,cc,ck)
            res(54,cc+ncb*(ck-1)) = -cm(2)*r(202,cc,ck) + r(203,cc,ck) + 2.0_dp*cm(17)*r(180,cc,ck) &
               + (-2.0_dp)*cm(18)*r(204,cc,ck) + cm(29)*r(25,cc,ck) - cm(30)*r(90,cc,ck)
            res(55,cc+ncb*(ck-1)) = cm(2)*r(205,cc,ck) + r(108,cc,ck) + cm(10)*r(206,cc,ck) + &
               cm(12)*r(110,cc,ck)
            res(56,cc+ncb*(ck-1)) = cm(6)*r(207,cc,ck) + cm(8)*r(112,cc,ck) + cm(14)*r(113,cc,ck) + &
               cm(15)*r(146,cc,ck)
            res(57,cc+ncb*(ck-1)) = -cm(2)*r(208,cc,ck) - r(115,cc,ck) - cm(10)*r(152,cc,ck) - &
               cm(12)*r(116,cc,ck)
            res(58,cc+ncb*(ck-1)) = cm(2)*r(209,cc,ck) + r(118,cc,ck) + cm(10)*r(210,cc,ck) + &
               cm(12)*r(120,cc,ck) + cm(25)*r(211,cc,ck) + cm(26)*r(122,cc,ck)
            res(59,cc+ncb*(ck-1)) = -cm(6)*r(212,cc,ck) - cm(8)*r(124,cc,ck) - cm(14)*r(125,cc,ck) &
               - cm(15)*r(213,cc,ck)
            res(60,cc+ncb*(ck-1)) = cm(2)*r(214,cc,ck) + r(128,cc,ck) + cm(10)*r(215,cc,ck) + &
               cm(12)*r(130,cc,ck)
            res(61,cc+ncb*(ck-1)) = 3.0_dp*cm(8)*r(216,cc,ck) + cm(14)*r(217,cc,ck)
            res(62,cc+ncb*(ck-1)) = 3.0_dp*r(218,cc,ck) + 3.0_dp*cm(12)*r(219,cc,ck) + &
               cm(26)*r(122,cc,ck)
            res(63,cc+ncb*(ck-1)) = (-3.0_dp)*cm(8)*r(220,cc,ck) - cm(14)*r(125,cc,ck)
            res(64,cc+ncb*(ck-1)) = 3.0_dp*cm(8)*r(221,cc,ck) + 3.0_dp*cm(14)*r(222,cc,ck) + &
               cm(35)*r(223,cc,ck)
            res(65,cc+ncb*(ck-1)) = (-3.0_dp)*r(224,cc,ck) + (-3.0_dp)*cm(12)*r(225,cc,ck) - &
               cm(26)*r(226,cc,ck)
            res(66,cc+ncb*(ck-1)) = 3.0_dp*cm(8)*r(227,cc,ck) + cm(14)*r(228,cc,ck)
            res(67,cc+ncb*(ck-1)) = -r(229,cc,ck) - cm(12)*r(230,cc,ck) + cm(17)*r(205,cc,ck) + &
               cm(23)*r(206,cc,ck)
            res(68,cc+ncb*(ck-1)) = -cm(8)*r(231,cc,ck) - cm(14)*r(143,cc,ck) + cm(20)*r(207,cc,ck) &
               + cm(28)*r(146,cc,ck)
            res(69,cc+ncb*(ck-1)) = r(232,cc,ck) + cm(12)*r(150,cc,ck) - cm(17)*r(208,cc,ck) - &
               cm(23)*r(152,cc,ck)
            res(70,cc+ncb*(ck-1)) = -r(233,cc,ck) - cm(12)*r(234,cc,ck) + cm(17)*r(209,cc,ck) + &
               cm(23)*r(210,cc,ck) - cm(26)*r(235,cc,ck) + cm(36)*r(211,cc,ck)
            res(71,cc+ncb*(ck-1)) = cm(8)*r(236,cc,ck) + cm(14)*r(237,cc,ck) - cm(20)*r(212,cc,ck) &
               - cm(28)*r(213,cc,ck)
            res(72,cc+ncb*(ck-1)) = (-2.0_dp)*r(238,cc,ck) + (-2.0_dp)*cm(12)*r(239,cc,ck) + &
               cm(17)*r(214,cc,ck) + cm(23)*r(215,cc,ck)
            res(73,cc+ncb*(ck-1)) = -cm(6)*r(240,cc,ck) - cm(8)*r(132,cc,ck) - cm(20)*r(29,cc,ck) - &
               cm(21)*r(92,cc,ck)
            res(74,cc+ncb*(ck-1)) = -cm(2)*r(241,cc,ck) - r(135,cc,ck) - cm(10)*r(242,cc,ck) - &
               cm(12)*r(136,cc,ck) - cm(17)*r(32,cc,ck) - cm(18)*r(94,cc,ck) - cm(23)*r(35,cc,ck) - &
               cm(24)*r(80,cc,ck)
            res(75,cc+ncb*(ck-1)) = cm(6)*r(243,cc,ck) + cm(8)*r(139,cc,ck) + cm(20)*r(38,cc,ck) + &
               cm(21)*r(85,cc,ck)
            res(76,cc+ncb*(ck-1)) = (-3.0_dp)*cm(6)*r(244,cc,ck) + (-3.0_dp)*cm(8)*r(142,cc,ck) - &
               cm(14)*r(143,cc,ck) - cm(15)*r(245,cc,ck) - cm(20)*r(41,cc,ck) - cm(21)*r(98,cc,ck) &
               - cm(27)*r(99,cc,ck) - cm(28)*r(46,cc,ck)
            res(77,cc+ncb*(ck-1)) = cm(2)*r(246,cc,ck) + r(148,cc,ck) + cm(10)*r(247,cc,ck) + &
               cm(12)*r(150,cc,ck) + cm(17)*r(47,cc,ck) + cm(18)*r(102,cc,ck) + cm(23)*r(50,cc,ck) &
               + cm(24)*r(104,cc,ck)
            res(78,cc+ncb*(ck-1)) = (-2.0_dp)*cm(6)*r(248,cc,ck) + (-2.0_dp)*cm(8)*r(154,cc,ck) - &
               cm(20)*r(53,cc,ck) - cm(21)*r(106,cc,ck)
            res(79,cc+ncb*(ck-1)) = -r(229,cc,ck) - cm(12)*r(230,cc,ck) - cm(17)*r(107,cc,ck) - &
               cm(23)*r(109,cc,ck)
            res(80,cc+ncb*(ck-1)) = -cm(8)*r(231,cc,ck) - cm(14)*r(143,cc,ck) - cm(20)*r(111,cc,ck) &
               - cm(28)*r(46,cc,ck)
            res(81,cc+ncb*(ck-1)) = r(232,cc,ck) + cm(12)*r(150,cc,ck) + cm(17)*r(114,cc,ck) + &
               cm(23)*r(50,cc,ck)
            res(82,cc+ncb*(ck-1)) = -r(233,cc,ck) - cm(12)*r(234,cc,ck) - cm(17)*r(117,cc,ck) - &
               cm(23)*r(119,cc,ck) - cm(26)*r(235,cc,ck) - cm(36)*r(121,cc,ck)
            res(83,cc+ncb*(ck-1)) = cm(8)*r(236,cc,ck) + cm(14)*r(237,cc,ck) + cm(20)*r(123,cc,ck) &
               + cm(28)*r(126,cc,ck)
            res(84,cc+ncb*(ck-1)) = (-2.0_dp)*r(238,cc,ck) + (-2.0_dp)*cm(12)*r(239,cc,ck) - &
               cm(17)*r(127,cc,ck) - cm(23)*r(129,cc,ck)
            res(85,cc+ncb*(ck-1)) = cm(8)*r(249,cc,ck) + cm(20)*r(250,cc,ck) - cm(32)*r(92,cc,ck)
            res(86,cc+ncb*(ck-1)) = r(251,cc,ck) + cm(12)*r(196,cc,ck) + cm(17)*r(252,cc,ck) + &
               cm(23)*r(170,cc,ck) - cm(30)*r(94,cc,ck) - cm(34)*r(80,cc,ck)
            res(87,cc+ncb*(ck-1)) = -cm(8)*r(200,cc,ck) - cm(20)*r(176,cc,ck) + cm(32)*r(85,cc,ck)
            res(88,cc+ncb*(ck-1)) = cm(8)*r(253,cc,ck) + cm(14)*r(254,cc,ck) + &
               3.0_dp*cm(20)*r(255,cc,ck) + cm(28)*r(256,cc,ck) - cm(32)*r(98,cc,ck) - &
               cm(37)*r(99,cc,ck)
            res(89,cc+ncb*(ck-1)) = -r(257,cc,ck) - cm(12)*r(258,cc,ck) - cm(17)*r(259,cc,ck) - &
               cm(23)*r(260,cc,ck) + cm(30)*r(102,cc,ck) + cm(34)*r(104,cc,ck)
            res(90,cc+ncb*(ck-1)) = cm(8)*r(261,cc,ck) + 2.0_dp*cm(20)*r(262,cc,ck) - &
               cm(32)*r(106,cc,ck)
            res(91,cc+ncb*(ck-1)) = cm(2)*r(263,cc,ck) + r(185,cc,ck) + 2.0_dp*cm(17)*r(56,cc,ck) + &
               2.0_dp*cm(18)*r(157,cc,ck) + cm(29)*r(1,cc,ck) + cm(30)*r(264,cc,ck)
            res(92,cc+ncb*(ck-1)) = cm(6)*r(265,cc,ck) + cm(8)*r(188,cc,ck) + &
               2.0_dp*cm(20)*r(61,cc,ck) + 2.0_dp*cm(21)*r(161,cc,ck) + cm(31)*r(5,cc,ck) + &
               cm(32)*r(266,cc,ck)
            res(93,cc+ncb*(ck-1)) = -cm(2)*r(267,cc,ck) - r(191,cc,ck) + &
               (-2.0_dp)*cm(17)*r(66,cc,ck) + (-2.0_dp)*cm(18)*r(165,cc,ck) - cm(29)*r(9,cc,ck) - &
               cm(30)*r(268,cc,ck)
            res(94,cc+ncb*(ck-1)) = cm(2)*r(269,cc,ck) + r(194,cc,ck) + cm(10)*r(270,cc,ck) + &
               cm(12)*r(196,cc,ck) + 2.0_dp*cm(17)*r(71,cc,ck) + 2.0_dp*cm(18)*r(169,cc,ck) + &
               2.0_dp*cm(23)*r(74,cc,ck) + 2.0_dp*cm(24)*r(171,cc,ck) + cm(29)*r(13,cc,ck) + &
               cm(30)*r(271,cc,ck) + cm(33)*r(17,cc,ck) + cm(34)*r(36,cc,ck)
            res(95,cc+ncb*(ck-1)) = -cm(6)*r(272,cc,ck) - cm(8)*r(200,cc,ck) + &
               (-2.0_dp)*cm(20)*r(81,cc,ck) + (-2.0_dp)*cm(21)*r(177,cc,ck) - cm(31)*r(21,cc,ck) - &
               cm(32)*r(39,cc,ck)
            res(96,cc+ncb*(ck-1)) = cm(2)*r(273,cc,ck) + r(203,cc,ck) + 4.0_dp*cm(17)*r(86,cc,ck) + &
               4.0_dp*cm(18)*r(181,cc,ck) + cm(29)*r(25,cc,ck) + cm(30)*r(274,cc,ck)
            res(97,cc+ncb*(ck-1)) = cm(8)*r(249,cc,ck) + 2.0_dp*cm(20)*r(131,cc,ck) + &
               cm(32)*r(30,cc,ck)
            res(98,cc+ncb*(ck-1)) = r(251,cc,ck) + cm(12)*r(196,cc,ck) + 2.0_dp*cm(17)*r(134,cc,ck) &
               + 2.0_dp*cm(23)*r(74,cc,ck) + cm(30)*r(33,cc,ck) + cm(34)*r(36,cc,ck)
            res(99,cc+ncb*(ck-1)) = -cm(8)*r(200,cc,ck) + (-2.0_dp)*cm(20)*r(81,cc,ck) - &
               cm(32)*r(39,cc,ck)
            res(100,cc+ncb*(ck-1)) = cm(8)*r(253,cc,ck) + cm(14)*r(254,cc,ck) + &
               6.0_dp*cm(20)*r(141,cc,ck) + 2.0_dp*cm(28)*r(144,cc,ck) + cm(32)*r(42,cc,ck) + &
               cm(37)*r(44,cc,ck)
            res(101,cc+ncb*(ck-1)) = -r(257,cc,ck) - cm(12)*r(258,cc,ck) + &
               (-2.0_dp)*cm(17)*r(147,cc,ck) + (-2.0_dp)*cm(23)*r(149,cc,ck) - cm(30)*r(48,cc,ck) - &
               cm(34)*r(51,cc,ck)
            res(102,cc+ncb*(ck-1)) = cm(8)*r(261,cc,ck) + 4.0_dp*cm(20)*r(153,cc,ck) + &
               cm(32)*r(54,cc,ck)
            res(103,cc+ncb*(ck-1)) = (-3.0_dp)*r(275,cc,ck) + cm(17)*r(276,cc,ck) - &
               cm(30)*r(277,cc,ck) + cm(38)*r(1,cc,ck)
            res(104,cc+ncb*(ck-1)) = (-3.0_dp)*cm(8)*r(278,cc,ck) + cm(20)*r(279,cc,ck) - &
               cm(32)*r(280,cc,ck) + cm(39)*r(5,cc,ck)
            res(105,cc+ncb*(ck-1)) = 3.0_dp*r(281,cc,ck) - cm(17)*r(282,cc,ck) + &
               cm(30)*r(283,cc,ck) - cm(38)*r(9,cc,ck)
            res(106,cc+ncb*(ck-1)) = (-3.0_dp)*r(284,cc,ck) + (-3.0_dp)*cm(12)*r(285,cc,ck) + &
               cm(17)*r(286,cc,ck) + cm(23)*r(287,cc,ck) - cm(30)*r(288,cc,ck) - &
               cm(34)*r(289,cc,ck) + cm(38)*r(13,cc,ck) + cm(40)*r(17,cc,ck)
            res(107,cc+ncb*(ck-1)) = 3.0_dp*cm(8)*r(290,cc,ck) - cm(20)*r(291,cc,ck) + &
               cm(32)*r(292,cc,ck) - cm(39)*r(21,cc,ck)
            res(108,cc+ncb*(ck-1)) = (-6.0_dp)*r(293,cc,ck) + cm(17)*r(294,cc,ck) + &
               (-2.0_dp)*cm(30)*r(295,cc,ck) + cm(38)*r(25,cc,ck)
         end do
      end do
   end subroutine rotaxis_sdpd

end module rotaxis_sdpd_m
