! GENERATED by scripts/rotaxis_mmd -- do not edit.
! LLLL: L=4 comps=256 S=79 g=8 r=399 (terms 1080) km=29 cm=22 assembly terms=654
module rotaxis_LLLL_m
   use cint_const, only: dp
   use cint_rotaxis_boys, only: boys
   implicit none
   private
   public :: rotaxis_LLLL
contains
   ! (LL|LL)  L=4: 79 bra accumulators, 399 ket accumulators, 256 components
   subroutine rotaxis_LLLL(nbra, ncb, bp, kab, nket, nck, kp, kcd, gc, cutoff, res, any)
      integer,  intent(in)  :: nbra, ncb, nket, nck
      real(dp), intent(in)  :: bp(5, nbra), kab(4*ncb, nbra)
      real(dp), intent(in)  :: kp(7, nket), kcd(4*nck, nket), gc(3), cutoff
      real(dp), intent(out) :: res(256, ncb*nck)
      logical,  intent(out) :: any
      real(dp) :: s(79, ncb), r(399, ncb, nck), t(399)
      real(dp) :: f(0:4), b(0:4)
      real(dp) :: p, ip, za, zb, eab, q, iq, yc, yd, ax, az, ecd
      real(dp) :: zq, alpha, tt, w, m2a, Rs, Rc, cy
      real(dp) :: g(8), km(29), cm(22), zq2, zq3, zq4
      integer :: kq, bq, cc, ck, n

      Rs = gc(1); Rc = gc(2); cy = gc(3)
      any = .false.
      r = 0.0_dp
      do kq = 1, nket
         q = kp(1,kq); iq = kp(2,kq); yc = kp(3,kq); yd = kp(4,kq)
         ax = kp(5,kq); az = kp(6,kq); ecd = kp(7,kq)
         s = 0.0_dp
         do bq = 1, nbra
            eab = bp(5,bq)
            if (eab + ecd > cutoff) cycle
            any = .true.
            p = bp(1,bq); ip = bp(2,bq); za = bp(3,bq); zb = bp(4,bq)
            zq = za - az
            alpha = p*q/(p + q)
            tt = alpha*(ax*ax + cy*cy + zq*zq)
            call boys(f, tt, 4)
            w = 1.0_dp/sqrt(p + q)
            m2a = -2.0_dp*alpha
            do n = 0, 4
               b(n) = w*f(n)
               w = w*m2a
            end do
            zq2 = zq*zq
            zq3 = zq2*zq
            zq4 = zq3*zq
            g(1) = 1.0_dp
            g(2) = ip
            g(3) = za
            g(4) = ip*ip
            g(5) = ip*za
            g(6) = zb
            g(7) = ip*zb
            g(8) = za*zb
            do cc = 1, ncb
               s(1,cc) = s(1,cc) + kab(1+4*(cc-1),bq)*b(0)
               s(2,cc) = s(2,cc) + kab(2+4*(cc-1),bq)*g(2)*b(1)
               s(3,cc) = s(3,cc) + kab(2+4*(cc-1),bq)*g(3)*b(0)
               s(4,cc) = s(4,cc) + kab(2+4*(cc-1),bq)*g(2)*b(1)*zq
               s(5,cc) = s(5,cc) + kab(3+4*(cc-1),bq)*g(2)*b(1)
               s(6,cc) = s(6,cc) + kab(4+4*(cc-1),bq)*g(2)*b(0)
               s(7,cc) = s(7,cc) + kab(4+4*(cc-1),bq)*g(4)*b(2)
               s(8,cc) = s(8,cc) + kab(4+4*(cc-1),bq)*g(4)*b(1)
               s(9,cc) = s(9,cc) + kab(4+4*(cc-1),bq)*g(5)*b(1)
               s(10,cc) = s(10,cc) + kab(4+4*(cc-1),bq)*g(4)*b(2)*zq
               s(11,cc) = s(11,cc) + kab(3+4*(cc-1),bq)*g(6)*b(0)
               s(12,cc) = s(12,cc) + kab(3+4*(cc-1),bq)*g(2)*b(1)*zq
               s(13,cc) = s(13,cc) + kab(4+4*(cc-1),bq)*g(7)*b(1)
               s(14,cc) = s(14,cc) + kab(4+4*(cc-1),bq)*g(8)*b(0)
               s(15,cc) = s(15,cc) + kab(4+4*(cc-1),bq)*g(7)*b(1)*zq
               s(16,cc) = s(16,cc) + kab(4+4*(cc-1),bq)*g(5)*b(1)*zq
               s(17,cc) = s(17,cc) + kab(4+4*(cc-1),bq)*g(4)*b(2)*zq2
               s(18,cc) = s(18,cc) + kab(1+4*(cc-1),bq)*b(1)
               s(19,cc) = s(19,cc) + kab(2+4*(cc-1),bq)*g(2)*b(2)
               s(20,cc) = s(20,cc) + kab(2+4*(cc-1),bq)*g(3)*b(1)
               s(21,cc) = s(21,cc) + kab(2+4*(cc-1),bq)*g(2)*b(2)*zq
               s(22,cc) = s(22,cc) + kab(3+4*(cc-1),bq)*g(2)*b(2)
               s(23,cc) = s(23,cc) + kab(4+4*(cc-1),bq)*g(2)*b(1)
               s(24,cc) = s(24,cc) + kab(4+4*(cc-1),bq)*g(4)*b(3)
               s(25,cc) = s(25,cc) + kab(4+4*(cc-1),bq)*g(5)*b(2)
               s(26,cc) = s(26,cc) + kab(4+4*(cc-1),bq)*g(4)*b(3)*zq
               s(27,cc) = s(27,cc) + kab(3+4*(cc-1),bq)*g(6)*b(1)
               s(28,cc) = s(28,cc) + kab(3+4*(cc-1),bq)*g(2)*b(2)*zq
               s(29,cc) = s(29,cc) + kab(4+4*(cc-1),bq)*g(7)*b(2)
               s(30,cc) = s(30,cc) + kab(4+4*(cc-1),bq)*g(8)*b(1)
               s(31,cc) = s(31,cc) + kab(4+4*(cc-1),bq)*g(7)*b(2)*zq
               s(32,cc) = s(32,cc) + kab(4+4*(cc-1),bq)*g(5)*b(2)*zq
               s(33,cc) = s(33,cc) + kab(4+4*(cc-1),bq)*g(4)*b(3)*zq2
               s(34,cc) = s(34,cc) + kab(1+4*(cc-1),bq)*b(1)*zq
               s(35,cc) = s(35,cc) + kab(2+4*(cc-1),bq)*g(3)*b(1)*zq
               s(36,cc) = s(36,cc) + kab(2+4*(cc-1),bq)*g(2)*b(2)*zq2
               s(37,cc) = s(37,cc) + kab(4+4*(cc-1),bq)*g(2)*b(1)*zq
               s(38,cc) = s(38,cc) + kab(3+4*(cc-1),bq)*g(6)*b(1)*zq
               s(39,cc) = s(39,cc) + kab(3+4*(cc-1),bq)*g(2)*b(2)*zq2
               s(40,cc) = s(40,cc) + kab(4+4*(cc-1),bq)*g(8)*b(1)*zq
               s(41,cc) = s(41,cc) + kab(4+4*(cc-1),bq)*g(7)*b(2)*zq2
               s(42,cc) = s(42,cc) + kab(4+4*(cc-1),bq)*g(5)*b(2)*zq2
               s(43,cc) = s(43,cc) + kab(4+4*(cc-1),bq)*g(4)*b(3)*zq3
               s(44,cc) = s(44,cc) + kab(1+4*(cc-1),bq)*b(2)
               s(45,cc) = s(45,cc) + kab(2+4*(cc-1),bq)*g(2)*b(3)
               s(46,cc) = s(46,cc) + kab(2+4*(cc-1),bq)*g(3)*b(2)
               s(47,cc) = s(47,cc) + kab(2+4*(cc-1),bq)*g(2)*b(3)*zq
               s(48,cc) = s(48,cc) + kab(3+4*(cc-1),bq)*g(2)*b(3)
               s(49,cc) = s(49,cc) + kab(4+4*(cc-1),bq)*g(2)*b(2)
               s(50,cc) = s(50,cc) + kab(4+4*(cc-1),bq)*g(4)*b(4)
               s(51,cc) = s(51,cc) + kab(4+4*(cc-1),bq)*g(5)*b(3)
               s(52,cc) = s(52,cc) + kab(4+4*(cc-1),bq)*g(4)*b(4)*zq
               s(53,cc) = s(53,cc) + kab(3+4*(cc-1),bq)*g(6)*b(2)
               s(54,cc) = s(54,cc) + kab(3+4*(cc-1),bq)*g(2)*b(3)*zq
               s(55,cc) = s(55,cc) + kab(4+4*(cc-1),bq)*g(7)*b(3)
               s(56,cc) = s(56,cc) + kab(4+4*(cc-1),bq)*g(8)*b(2)
               s(57,cc) = s(57,cc) + kab(4+4*(cc-1),bq)*g(7)*b(3)*zq
               s(58,cc) = s(58,cc) + kab(4+4*(cc-1),bq)*g(5)*b(3)*zq
               s(59,cc) = s(59,cc) + kab(4+4*(cc-1),bq)*g(4)*b(4)*zq2
               s(60,cc) = s(60,cc) + kab(1+4*(cc-1),bq)*b(2)*zq
               s(61,cc) = s(61,cc) + kab(2+4*(cc-1),bq)*g(3)*b(2)*zq
               s(62,cc) = s(62,cc) + kab(2+4*(cc-1),bq)*g(2)*b(3)*zq2
               s(63,cc) = s(63,cc) + kab(4+4*(cc-1),bq)*g(2)*b(2)*zq
               s(64,cc) = s(64,cc) + kab(3+4*(cc-1),bq)*g(6)*b(2)*zq
               s(65,cc) = s(65,cc) + kab(3+4*(cc-1),bq)*g(2)*b(3)*zq2
               s(66,cc) = s(66,cc) + kab(4+4*(cc-1),bq)*g(8)*b(2)*zq
               s(67,cc) = s(67,cc) + kab(4+4*(cc-1),bq)*g(7)*b(3)*zq2
               s(68,cc) = s(68,cc) + kab(4+4*(cc-1),bq)*g(5)*b(3)*zq2
               s(69,cc) = s(69,cc) + kab(4+4*(cc-1),bq)*g(4)*b(4)*zq3
               s(70,cc) = s(70,cc) + kab(1+4*(cc-1),bq)*b(2)*zq2
               s(71,cc) = s(71,cc) + kab(2+4*(cc-1),bq)*g(3)*b(2)*zq2
               s(72,cc) = s(72,cc) + kab(2+4*(cc-1),bq)*g(2)*b(3)*zq3
               s(73,cc) = s(73,cc) + kab(4+4*(cc-1),bq)*g(2)*b(2)*zq2
               s(74,cc) = s(74,cc) + kab(3+4*(cc-1),bq)*g(6)*b(2)*zq2
               s(75,cc) = s(75,cc) + kab(3+4*(cc-1),bq)*g(2)*b(3)*zq3
               s(76,cc) = s(76,cc) + kab(4+4*(cc-1),bq)*g(8)*b(2)*zq2
               s(77,cc) = s(77,cc) + kab(4+4*(cc-1),bq)*g(7)*b(3)*zq3
               s(78,cc) = s(78,cc) + kab(4+4*(cc-1),bq)*g(5)*b(3)*zq3
               s(79,cc) = s(79,cc) + kab(4+4*(cc-1),bq)*g(4)*b(4)*zq4
            end do
         end do
         if (.not. any) cycle
         km(1) = 1.0_dp
         km(2) = ax
         km(3) = ax*ax
         km(4) = yd
         km(5) = iq*ax
         km(6) = yd*ax
         km(7) = iq*ax*ax
         km(8) = iq
         km(9) = yd*ax*ax
         km(10) = iq*ax*ax*ax
         km(11) = yc
         km(12) = yc*ax
         km(13) = yc*ax*ax
         km(14) = yc*yd
         km(15) = iq*yc*ax
         km(16) = iq*yd*ax
         km(17) = iq*iq*ax*ax
         km(18) = iq*iq
         km(19) = yc*yd*ax
         km(20) = iq*yc*ax*ax
         km(21) = iq*yc
         km(22) = iq*yd*ax*ax
         km(23) = iq*yd
         km(24) = iq*iq*ax*ax*ax
         km(25) = iq*iq*ax
         km(26) = yc*yd*ax*ax
         km(27) = iq*yc*ax*ax*ax
         km(28) = iq*yd*ax*ax*ax
         km(29) = iq*iq*ax*ax*ax*ax
         do cc = 1, ncb
            t(1) = s(1,cc)
            t(2) = km(2)*s(2,cc)
            t(3) = s(2,cc)
            t(4) = (s(3,cc) + s(4,cc))
            t(5) = km(2)*s(5,cc)
            t(6) = (s(6,cc) + s(8,cc)) + km(3)*s(7,cc)
            t(7) = km(2)*s(7,cc)
            t(8) = km(2)*(s(9,cc) + s(10,cc))
            t(9) = s(5,cc)
            t(10) = (s(6,cc) + s(8,cc))
            t(11) = s(7,cc)
            t(12) = (s(9,cc) + s(10,cc))
            t(13) = (s(11,cc) + s(12,cc))
            t(14) = km(2)*(s(10,cc) + s(13,cc))
            t(15) = (s(10,cc) + s(13,cc))
            t(16) = (s(6,cc) + s(8,cc) + s(14,cc) + s(15,cc) + s(16,cc) + s(17,cc))
            t(17) = km(5)*s(18,cc)
            t(18) = km(4)*s(1,cc)
            t(19) = km(7)*s(19,cc) + km(8)*s(2,cc)
            t(20) = km(6)*s(2,cc)
            t(21) = km(5)*s(19,cc)
            t(22) = km(4)*s(2,cc)
            t(23) = km(5)*(s(20,cc) + s(21,cc))
            t(24) = km(4)*(s(3,cc) + s(4,cc))
            t(25) = km(7)*s(22,cc) + km(8)*s(5,cc)
            t(26) = km(6)*s(5,cc)
            t(27) = km(5)*(s(7,cc) + (1.0_dp/3.0_dp)*s(23,cc)) + (1.0_dp/3.0_dp)*km(10)*s(24,cc)
            t(28) = km(4)*(s(6,cc) + s(8,cc)) + km(9)*s(7,cc)
            t(29) = km(7)*s(24,cc) + km(8)*s(7,cc)
            t(30) = km(6)*s(7,cc)
            t(31) = km(7)*(s(25,cc) + s(26,cc)) + km(8)*(s(9,cc) + s(10,cc))
            t(32) = km(6)*(s(9,cc) + s(10,cc))
            t(33) = km(5)*s(22,cc)
            t(34) = km(4)*s(5,cc)
            t(35) = km(5)*(s(7,cc) + s(23,cc))
            t(36) = km(5)*s(24,cc)
            t(37) = km(4)*(s(6,cc) + s(8,cc))
            t(38) = km(4)*s(7,cc)
            t(39) = km(5)*(s(25,cc) + s(26,cc))
            t(40) = km(4)*(s(9,cc) + s(10,cc))
            t(41) = km(5)*(s(27,cc) + s(28,cc))
            t(42) = km(4)*(s(11,cc) + s(12,cc))
            t(43) = km(7)*(s(26,cc) + s(29,cc)) + km(8)*(s(10,cc) + s(13,cc))
            t(44) = km(6)*(s(10,cc) + s(13,cc))
            t(45) = km(5)*(s(26,cc) + s(29,cc))
            t(46) = km(4)*(s(10,cc) + s(13,cc))
            t(47) = km(5)*(s(7,cc) + s(23,cc) + s(30,cc) + s(31,cc) + s(32,cc) + s(33,cc))
            t(48) = km(4)*(s(6,cc) + s(8,cc) + s(14,cc) + s(15,cc) + s(16,cc) + s(17,cc))
            t(49) = km(8)*s(18,cc)
            t(50) = km(8)*s(2,cc)
            t(51) = km(8)*s(19,cc)
            t(52) = km(8)*(s(20,cc) + s(21,cc))
            t(53) = km(7)*s(24,cc) + km(8)*(s(7,cc) + s(23,cc))
            t(54) = km(5)*s(7,cc)
            t(55) = km(8)*s(5,cc)
            t(56) = km(8)*s(22,cc)
            t(57) = km(8)*(s(7,cc) + (1.0_dp/3.0_dp)*s(23,cc))
            t(58) = km(8)*s(24,cc)
            t(59) = km(8)*(s(9,cc) + s(10,cc))
            t(60) = km(8)*(s(25,cc) + s(26,cc))
            t(61) = km(8)*(s(27,cc) + s(28,cc))
            t(62) = km(8)*(s(10,cc) + s(13,cc))
            t(63) = km(8)*(s(26,cc) + s(29,cc))
            t(64) = km(8)*(s(7,cc) + s(23,cc) + s(30,cc) + s(31,cc) + s(32,cc) + s(33,cc))
            t(65) = km(8)*s(34,cc)
            t(66) = km(5)*s(21,cc)
            t(67) = km(8)*s(21,cc)
            t(68) = km(8)*(s(2,cc) + s(35,cc) + s(36,cc))
            t(69) = km(5)*s(28,cc)
            t(70) = km(7)*s(26,cc) + km(8)*(s(10,cc) + s(37,cc))
            t(71) = km(5)*s(26,cc)
            t(72) = km(5)*(s(7,cc) + s(32,cc) + s(33,cc))
            t(73) = km(8)*s(28,cc)
            t(74) = km(8)*(s(10,cc) + s(37,cc))
            t(75) = km(8)*s(26,cc)
            t(76) = km(8)*(s(7,cc) + s(32,cc) + s(33,cc))
            t(77) = km(8)*(s(5,cc) + s(38,cc) + s(39,cc))
            t(78) = km(5)*(s(7,cc) + s(31,cc) + s(33,cc))
            t(79) = km(8)*(s(7,cc) + s(31,cc) + s(33,cc))
            t(80) = km(8)*(s(9,cc) + 3.0_dp*s(10,cc) + s(13,cc) + s(37,cc) + s(40,cc) + s(41,cc) + &
               s(42,cc) + s(43,cc))
            t(81) = km(5)*s(18,cc)
            t(82) = km(11)*s(1,cc)
            t(83) = km(7)*s(19,cc) + km(8)*s(2,cc)
            t(84) = km(12)*s(2,cc)
            t(85) = km(5)*s(19,cc)
            t(86) = km(11)*s(2,cc)
            t(87) = km(5)*(s(20,cc) + s(21,cc))
            t(88) = km(11)*(s(3,cc) + s(4,cc))
            t(89) = km(7)*s(22,cc) + km(8)*s(5,cc)
            t(90) = km(12)*s(5,cc)
            t(91) = km(5)*(s(7,cc) + (1.0_dp/3.0_dp)*s(23,cc)) + (1.0_dp/3.0_dp)*km(10)*s(24,cc)
            t(92) = km(11)*(s(6,cc) + s(8,cc)) + km(13)*s(7,cc)
            t(93) = km(7)*s(24,cc) + km(8)*s(7,cc)
            t(94) = km(12)*s(7,cc)
            t(95) = km(7)*(s(25,cc) + s(26,cc)) + km(8)*(s(9,cc) + s(10,cc))
            t(96) = km(12)*(s(9,cc) + s(10,cc))
            t(97) = km(5)*s(22,cc)
            t(98) = km(11)*s(5,cc)
            t(99) = km(5)*(s(7,cc) + s(23,cc))
            t(100) = km(5)*s(24,cc)
            t(101) = km(11)*(s(6,cc) + s(8,cc))
            t(102) = km(11)*s(7,cc)
            t(103) = km(5)*(s(25,cc) + s(26,cc))
            t(104) = km(11)*(s(9,cc) + s(10,cc))
            t(105) = km(5)*(s(27,cc) + s(28,cc))
            t(106) = km(11)*(s(11,cc) + s(12,cc))
            t(107) = km(7)*(s(26,cc) + s(29,cc)) + km(8)*(s(10,cc) + s(13,cc))
            t(108) = km(12)*(s(10,cc) + s(13,cc))
            t(109) = km(5)*(s(26,cc) + s(29,cc))
            t(110) = km(11)*(s(10,cc) + s(13,cc))
            t(111) = km(5)*(s(7,cc) + s(23,cc) + s(30,cc) + s(31,cc) + s(32,cc) + s(33,cc))
            t(112) = km(11)*(s(6,cc) + s(8,cc) + s(14,cc) + s(15,cc) + s(16,cc) + s(17,cc))
            t(113) = km(8)*s(1,cc) + km(17)*s(44,cc) + km(18)*s(18,cc)
            t(114) = km(15)*s(18,cc) - km(16)*s(18,cc)
            t(115) = km(14)*s(1,cc)
            t(116) = km(5)*s(2,cc) + km(24)*s(45,cc) + 3.0_dp*km(25)*s(19,cc)
            t(117) = km(20)*s(19,cc) + km(21)*s(2,cc) - km(22)*s(19,cc) - km(23)*s(2,cc)
            t(118) = km(19)*s(2,cc)
            t(119) = km(8)*s(2,cc) + km(17)*s(45,cc) + km(18)*s(19,cc)
            t(120) = km(15)*s(19,cc) - km(16)*s(19,cc)
            t(121) = km(14)*s(2,cc)
            t(122) = km(8)*(s(3,cc) + s(4,cc)) + km(17)*(s(46,cc) + s(47,cc)) + km(18)*(s(20,cc) + &
               s(21,cc))
            t(123) = km(15)*(s(20,cc) + s(21,cc)) + km(16)*(-s(20,cc) - s(21,cc))
            t(124) = km(14)*(s(3,cc) + s(4,cc))
            t(125) = km(5)*s(5,cc) + km(24)*s(48,cc) + 3.0_dp*km(25)*s(22,cc)
            t(126) = km(20)*s(22,cc) + km(21)*s(5,cc) - km(22)*s(22,cc) - km(23)*s(5,cc)
            t(127) = km(19)*s(5,cc)
            t(128) = km(7)*s(7,cc) + km(8)*(s(6,cc) + s(8,cc)) + km(17)*(6.0_dp*s(24,cc) + &
               s(49,cc)) + km(18)*(3.0_dp*s(7,cc) + s(23,cc)) + km(29)*s(50,cc)
            t(129) = km(15)*(s(7,cc) + (1.0_dp/3.0_dp)*s(23,cc)) + km(16)*(-s(7,cc) + &
               (-1.0_dp/3.0_dp)*s(23,cc)) + (1.0_dp/3.0_dp)*km(27)*s(24,cc) + &
               (-1.0_dp/3.0_dp)*km(28)*s(24,cc)
            t(130) = km(14)*(s(6,cc) + s(8,cc)) + km(26)*s(7,cc)
            t(131) = km(5)*s(7,cc) + km(24)*s(50,cc) + 3.0_dp*km(25)*s(24,cc)
            t(132) = km(20)*s(24,cc) + km(21)*s(7,cc) - km(22)*s(24,cc) - km(23)*s(7,cc)
            t(133) = km(19)*s(7,cc)
            t(134) = km(5)*(s(9,cc) + s(10,cc)) + km(24)*(s(51,cc) + s(52,cc)) + &
               km(25)*(3.0_dp*s(25,cc) + 3.0_dp*s(26,cc))
            t(135) = km(20)*(s(25,cc) + s(26,cc)) + km(21)*(s(9,cc) + s(10,cc)) + km(22)*(-s(25,cc) &
               - s(26,cc)) + km(23)*(-s(9,cc) - s(10,cc))
            t(136) = km(19)*(s(9,cc) + s(10,cc))
            t(137) = km(8)*s(5,cc) + km(17)*s(48,cc) + km(18)*s(22,cc)
            t(138) = km(15)*s(22,cc) - km(16)*s(22,cc)
            t(139) = km(14)*s(5,cc)
            t(140) = km(8)*(s(6,cc) + s(8,cc)) + km(17)*(s(24,cc) + s(49,cc)) + km(18)*(s(7,cc) + &
               s(23,cc))
            t(141) = km(8)*s(7,cc) + km(17)*s(50,cc) + km(18)*s(24,cc)
            t(142) = km(15)*(s(7,cc) + s(23,cc)) + km(16)*(-s(7,cc) - s(23,cc))
            t(143) = km(15)*s(24,cc) - km(16)*s(24,cc)
            t(144) = km(14)*(s(6,cc) + s(8,cc))
            t(145) = km(14)*s(7,cc)
            t(146) = km(8)*(s(9,cc) + s(10,cc)) + km(17)*(s(51,cc) + s(52,cc)) + km(18)*(s(25,cc) + &
               s(26,cc))
            t(147) = km(15)*(s(25,cc) + s(26,cc)) + km(16)*(-s(25,cc) - s(26,cc))
            t(148) = km(14)*(s(9,cc) + s(10,cc))
            t(149) = km(8)*(s(11,cc) + s(12,cc)) + km(17)*(s(53,cc) + s(54,cc)) + km(18)*(s(27,cc) &
               + s(28,cc))
            t(150) = km(15)*(s(27,cc) + s(28,cc)) + km(16)*(-s(27,cc) - s(28,cc))
            t(151) = km(14)*(s(11,cc) + s(12,cc))
            t(152) = km(5)*(s(10,cc) + s(13,cc)) + km(24)*(s(52,cc) + s(55,cc)) + &
               km(25)*(3.0_dp*s(26,cc) + 3.0_dp*s(29,cc))
            t(153) = km(20)*(s(26,cc) + s(29,cc)) + km(21)*(s(10,cc) + s(13,cc)) + &
               km(22)*(-s(26,cc) - s(29,cc)) + km(23)*(-s(10,cc) - s(13,cc))
            t(154) = km(19)*(s(10,cc) + s(13,cc))
            t(155) = km(8)*(s(10,cc) + s(13,cc)) + km(17)*(s(52,cc) + s(55,cc)) + km(18)*(s(26,cc) &
               + s(29,cc))
            t(156) = km(15)*(s(26,cc) + s(29,cc)) + km(16)*(-s(26,cc) - s(29,cc))
            t(157) = km(14)*(s(10,cc) + s(13,cc))
            t(158) = km(8)*(s(6,cc) + s(8,cc) + s(14,cc) + s(15,cc) + s(16,cc) + s(17,cc)) + &
               km(17)*(s(24,cc) + s(49,cc) + s(56,cc) + s(57,cc) + s(58,cc) + s(59,cc)) + &
               km(18)*(s(7,cc) + s(23,cc) + s(30,cc) + s(31,cc) + s(32,cc) + s(33,cc))
            t(159) = km(15)*(s(7,cc) + s(23,cc) + s(30,cc) + s(31,cc) + s(32,cc) + s(33,cc)) + &
               km(16)*(-s(7,cc) - s(23,cc) - s(30,cc) - s(31,cc) - s(32,cc) - s(33,cc))
            t(160) = km(14)*(s(6,cc) + s(8,cc) + s(14,cc) + s(15,cc) + s(16,cc) + s(17,cc))
            t(161) = km(25)*s(44,cc)
            t(162) = km(21)*s(18,cc)
            t(163) = km(17)*s(45,cc) + km(18)*s(19,cc)
            t(164) = km(15)*s(19,cc)
            t(165) = km(25)*s(19,cc)
            t(166) = km(25)*s(45,cc)
            t(167) = km(21)*s(2,cc)
            t(168) = km(21)*s(19,cc)
            t(169) = km(25)*(s(46,cc) + s(47,cc))
            t(170) = km(21)*(s(20,cc) + s(21,cc))
            t(171) = km(17)*s(48,cc) + km(18)*s(22,cc)
            t(172) = km(15)*s(22,cc)
            t(173) = km(24)*s(50,cc) + km(25)*(3.0_dp*s(24,cc) + s(49,cc))
            t(174) = km(20)*s(24,cc) + km(21)*(s(7,cc) + s(23,cc))
            t(175) = km(17)*s(24,cc) + km(18)*s(7,cc)
            t(176) = km(17)*s(50,cc) + km(18)*s(24,cc)
            t(177) = km(15)*s(7,cc)
            t(178) = km(15)*s(24,cc)
            t(179) = km(17)*(s(51,cc) + s(52,cc)) + km(18)*(s(25,cc) + s(26,cc))
            t(180) = km(15)*(s(25,cc) + s(26,cc))
            t(181) = km(25)*s(22,cc)
            t(182) = km(25)*s(48,cc)
            t(183) = km(21)*s(5,cc)
            t(184) = km(21)*s(22,cc)
            t(185) = km(25)*(s(24,cc) + (1.0_dp/3.0_dp)*s(49,cc))
            t(186) = km(21)*(s(7,cc) + (1.0_dp/3.0_dp)*s(23,cc))
            t(187) = km(25)*s(50,cc)
            t(188) = km(21)*s(24,cc)
            t(189) = km(25)*(s(25,cc) + s(26,cc))
            t(190) = km(25)*(s(51,cc) + s(52,cc))
            t(191) = km(21)*(s(9,cc) + s(10,cc))
            t(192) = km(21)*(s(25,cc) + s(26,cc))
            t(193) = km(25)*(s(53,cc) + s(54,cc))
            t(194) = km(21)*(s(27,cc) + s(28,cc))
            t(195) = km(17)*(s(52,cc) + s(55,cc)) + km(18)*(s(26,cc) + s(29,cc))
            t(196) = km(15)*(s(26,cc) + s(29,cc))
            t(197) = km(25)*(s(26,cc) + s(29,cc))
            t(198) = km(25)*(s(52,cc) + s(55,cc))
            t(199) = km(21)*(s(10,cc) + s(13,cc))
            t(200) = km(21)*(s(26,cc) + s(29,cc))
            t(201) = km(25)*(s(24,cc) + s(49,cc) + s(56,cc) + s(57,cc) + s(58,cc) + s(59,cc))
            t(202) = km(21)*(s(7,cc) + s(23,cc) + s(30,cc) + s(31,cc) + s(32,cc) + s(33,cc))
            t(203) = km(25)*s(60,cc)
            t(204) = km(21)*s(34,cc)
            t(205) = km(16)*s(18,cc)
            t(206) = km(17)*s(47,cc) + km(18)*s(21,cc)
            t(207) = km(15)*s(21,cc)
            t(208) = km(22)*s(19,cc) + km(23)*s(2,cc)
            t(209) = km(25)*s(47,cc)
            t(210) = km(21)*s(21,cc)
            t(211) = km(16)*s(19,cc)
            t(212) = km(25)*(s(19,cc) + s(61,cc) + s(62,cc))
            t(213) = km(21)*(s(2,cc) + s(35,cc) + s(36,cc))
            t(214) = km(16)*(s(20,cc) + s(21,cc))
            t(215) = km(17)*s(54,cc) + km(18)*s(28,cc)
            t(216) = km(15)*s(28,cc)
            t(217) = km(22)*s(22,cc) + km(23)*s(5,cc)
            t(218) = km(24)*s(52,cc) + km(25)*(3.0_dp*s(26,cc) + s(63,cc))
            t(219) = km(20)*s(26,cc) + km(21)*(s(10,cc) + s(37,cc))
            t(220) = km(16)*(s(7,cc) + (1.0_dp/3.0_dp)*s(23,cc)) + (1.0_dp/3.0_dp)*km(28)*s(24,cc)
            t(221) = km(17)*s(52,cc) + km(18)*s(26,cc)
            t(222) = km(15)*s(26,cc)
            t(223) = km(22)*s(24,cc) + km(23)*s(7,cc)
            t(224) = km(17)*(s(24,cc) + s(58,cc) + s(59,cc)) + km(18)*(s(7,cc) + s(32,cc) + &
               s(33,cc))
            t(225) = km(15)*(s(7,cc) + s(32,cc) + s(33,cc))
            t(226) = km(22)*(s(25,cc) + s(26,cc)) + km(23)*(s(9,cc) + s(10,cc))
            t(227) = km(25)*s(54,cc)
            t(228) = km(21)*s(28,cc)
            t(229) = km(16)*s(22,cc)
            t(230) = km(25)*(s(26,cc) + s(63,cc))
            t(231) = km(25)*s(52,cc)
            t(232) = km(21)*(s(10,cc) + s(37,cc))
            t(233) = km(21)*s(26,cc)
            t(234) = km(16)*(s(7,cc) + s(23,cc))
            t(235) = km(16)*s(24,cc)
            t(236) = km(25)*(s(24,cc) + s(58,cc) + s(59,cc))
            t(237) = km(21)*(s(7,cc) + s(32,cc) + s(33,cc))
            t(238) = km(16)*(s(25,cc) + s(26,cc))
            t(239) = km(25)*(s(22,cc) + s(64,cc) + s(65,cc))
            t(240) = km(21)*(s(5,cc) + s(38,cc) + s(39,cc))
            t(241) = km(16)*(s(27,cc) + s(28,cc))
            t(242) = km(17)*(s(24,cc) + s(57,cc) + s(59,cc)) + km(18)*(s(7,cc) + s(31,cc) + &
               s(33,cc))
            t(243) = km(15)*(s(7,cc) + s(31,cc) + s(33,cc))
            t(244) = km(22)*(s(26,cc) + s(29,cc)) + km(23)*(s(10,cc) + s(13,cc))
            t(245) = km(25)*(s(24,cc) + s(57,cc) + s(59,cc))
            t(246) = km(21)*(s(7,cc) + s(31,cc) + s(33,cc))
            t(247) = km(16)*(s(26,cc) + s(29,cc))
            t(248) = km(25)*(s(25,cc) + 3.0_dp*s(26,cc) + s(29,cc) + s(63,cc) + s(66,cc) + s(67,cc) &
               + s(68,cc) + s(69,cc))
            t(249) = km(21)*(s(9,cc) + 3.0_dp*s(10,cc) + s(13,cc) + s(37,cc) + s(40,cc) + s(41,cc) &
               + s(42,cc) + s(43,cc))
            t(250) = km(16)*(s(7,cc) + s(23,cc) + s(30,cc) + s(31,cc) + s(32,cc) + s(33,cc))
            t(251) = km(8)*s(18,cc)
            t(252) = km(8)*s(2,cc)
            t(253) = km(8)*s(19,cc)
            t(254) = km(8)*(s(20,cc) + s(21,cc))
            t(255) = km(7)*s(24,cc) + km(8)*(s(7,cc) + s(23,cc))
            t(256) = km(5)*s(7,cc)
            t(257) = km(8)*s(5,cc)
            t(258) = km(8)*s(22,cc)
            t(259) = km(8)*(s(7,cc) + (1.0_dp/3.0_dp)*s(23,cc))
            t(260) = km(8)*s(24,cc)
            t(261) = km(8)*(s(9,cc) + s(10,cc))
            t(262) = km(8)*(s(25,cc) + s(26,cc))
            t(263) = km(8)*(s(27,cc) + s(28,cc))
            t(264) = km(8)*(s(10,cc) + s(13,cc))
            t(265) = km(8)*(s(26,cc) + s(29,cc))
            t(266) = km(8)*(s(7,cc) + s(23,cc) + s(30,cc) + s(31,cc) + s(32,cc) + s(33,cc))
            t(267) = km(23)*s(18,cc)
            t(268) = km(23)*s(2,cc)
            t(269) = km(23)*s(19,cc)
            t(270) = km(23)*(s(20,cc) + s(21,cc))
            t(271) = km(22)*s(24,cc) + km(23)*(s(7,cc) + s(23,cc))
            t(272) = km(16)*s(7,cc)
            t(273) = km(23)*s(5,cc)
            t(274) = km(23)*s(22,cc)
            t(275) = km(23)*(s(7,cc) + (1.0_dp/3.0_dp)*s(23,cc))
            t(276) = km(23)*s(24,cc)
            t(277) = km(23)*(s(9,cc) + s(10,cc))
            t(278) = km(23)*(s(25,cc) + s(26,cc))
            t(279) = km(23)*(s(27,cc) + s(28,cc))
            t(280) = km(23)*(s(10,cc) + s(13,cc))
            t(281) = km(23)*(s(26,cc) + s(29,cc))
            t(282) = km(23)*(s(7,cc) + s(23,cc) + s(30,cc) + s(31,cc) + s(32,cc) + s(33,cc))
            t(283) = km(8)*s(1,cc) + km(18)*s(18,cc)
            t(284) = km(18)*s(44,cc)
            t(285) = km(5)*s(2,cc) + km(25)*s(19,cc)
            t(286) = km(8)*s(2,cc) + 3.0_dp*km(18)*s(19,cc)
            t(287) = km(18)*s(45,cc)
            t(288) = km(8)*(s(3,cc) + s(4,cc)) + km(18)*(s(20,cc) + s(21,cc))
            t(289) = km(18)*(s(46,cc) + s(47,cc))
            t(290) = km(5)*s(5,cc) + km(25)*s(22,cc)
            t(291) = km(7)*s(7,cc) + km(8)*(s(6,cc) + s(8,cc)) + km(17)*s(24,cc) + km(18)*(s(7,cc) &
               + s(23,cc))
            t(292) = km(17)*s(50,cc) + km(18)*(s(24,cc) + s(49,cc))
            t(293) = km(5)*s(7,cc) + 3.0_dp*km(25)*s(24,cc)
            t(294) = km(5)*(s(9,cc) + s(10,cc)) + km(25)*(s(25,cc) + s(26,cc))
            t(295) = km(8)*s(5,cc) + 3.0_dp*km(18)*s(22,cc)
            t(296) = km(18)*s(48,cc)
            t(297) = km(8)*(s(6,cc) + s(8,cc)) + km(18)*(3.0_dp*s(7,cc) + s(23,cc))
            t(298) = km(8)*s(7,cc) + km(18)*(6.0_dp*s(24,cc) + s(49,cc))
            t(299) = km(18)*s(50,cc)
            t(300) = km(8)*(s(9,cc) + s(10,cc)) + km(18)*(3.0_dp*s(25,cc) + 3.0_dp*s(26,cc))
            t(301) = km(18)*(s(51,cc) + s(52,cc))
            t(302) = km(8)*(s(11,cc) + s(12,cc)) + km(18)*(s(27,cc) + s(28,cc))
            t(303) = km(18)*(s(53,cc) + s(54,cc))
            t(304) = km(5)*(s(10,cc) + s(13,cc)) + km(25)*(s(26,cc) + s(29,cc))
            t(305) = km(8)*(s(10,cc) + s(13,cc)) + km(18)*(3.0_dp*s(26,cc) + 3.0_dp*s(29,cc))
            t(306) = km(18)*(s(52,cc) + s(55,cc))
            t(307) = km(8)*(s(6,cc) + s(8,cc) + s(14,cc) + s(15,cc) + s(16,cc) + s(17,cc)) + &
               km(18)*(s(7,cc) + s(23,cc) + s(30,cc) + s(31,cc) + s(32,cc) + s(33,cc))
            t(308) = km(18)*(s(24,cc) + s(49,cc) + s(56,cc) + s(57,cc) + s(58,cc) + s(59,cc))
            t(309) = km(18)*s(60,cc)
            t(310) = km(18)*s(21,cc)
            t(311) = km(18)*s(47,cc)
            t(312) = km(18)*(s(19,cc) + s(61,cc) + s(62,cc))
            t(313) = km(17)*s(52,cc) + km(18)*(s(26,cc) + s(63,cc))
            t(314) = km(25)*s(26,cc)
            t(315) = km(18)*s(28,cc)
            t(316) = km(18)*s(54,cc)
            t(317) = km(18)*(s(26,cc) + (1.0_dp/3.0_dp)*s(63,cc))
            t(318) = km(18)*s(52,cc)
            t(319) = km(18)*(s(7,cc) + s(32,cc) + s(33,cc))
            t(320) = km(18)*(s(24,cc) + s(58,cc) + s(59,cc))
            t(321) = km(18)*(s(22,cc) + s(64,cc) + s(65,cc))
            t(322) = km(18)*(s(7,cc) + s(31,cc) + s(33,cc))
            t(323) = km(18)*(s(24,cc) + s(57,cc) + s(59,cc))
            t(324) = km(18)*(s(25,cc) + 3.0_dp*s(26,cc) + s(29,cc) + s(63,cc) + s(66,cc) + s(67,cc) &
               + s(68,cc) + s(69,cc))
            t(325) = km(8)*s(34,cc)
            t(326) = km(5)*s(21,cc)
            t(327) = km(8)*s(21,cc)
            t(328) = km(8)*(s(2,cc) + s(35,cc) + s(36,cc))
            t(329) = km(5)*s(28,cc)
            t(330) = km(7)*s(26,cc) + km(8)*(s(10,cc) + s(37,cc))
            t(331) = km(5)*s(26,cc)
            t(332) = km(5)*(s(7,cc) + s(32,cc) + s(33,cc))
            t(333) = km(8)*s(28,cc)
            t(334) = km(8)*(s(10,cc) + s(37,cc))
            t(335) = km(8)*s(26,cc)
            t(336) = km(8)*(s(7,cc) + s(32,cc) + s(33,cc))
            t(337) = km(8)*(s(5,cc) + s(38,cc) + s(39,cc))
            t(338) = km(5)*(s(7,cc) + s(31,cc) + s(33,cc))
            t(339) = km(8)*(s(7,cc) + s(31,cc) + s(33,cc))
            t(340) = km(8)*(s(9,cc) + 3.0_dp*s(10,cc) + s(13,cc) + s(37,cc) + s(40,cc) + s(41,cc) + &
               s(42,cc) + s(43,cc))
            t(341) = km(23)*s(34,cc)
            t(342) = km(15)*s(18,cc)
            t(343) = km(16)*s(21,cc)
            t(344) = km(20)*s(19,cc) + km(21)*s(2,cc)
            t(345) = km(23)*s(21,cc)
            t(346) = km(23)*(s(2,cc) + s(35,cc) + s(36,cc))
            t(347) = km(15)*(s(20,cc) + s(21,cc))
            t(348) = km(16)*s(28,cc)
            t(349) = km(20)*s(22,cc) + km(21)*s(5,cc)
            t(350) = km(22)*s(26,cc) + km(23)*(s(10,cc) + s(37,cc))
            t(351) = km(15)*(s(7,cc) + (1.0_dp/3.0_dp)*s(23,cc)) + (1.0_dp/3.0_dp)*km(27)*s(24,cc)
            t(352) = km(16)*s(26,cc)
            t(353) = km(20)*s(24,cc) + km(21)*s(7,cc)
            t(354) = km(16)*(s(7,cc) + s(32,cc) + s(33,cc))
            t(355) = km(20)*(s(25,cc) + s(26,cc)) + km(21)*(s(9,cc) + s(10,cc))
            t(356) = km(23)*s(28,cc)
            t(357) = km(23)*(s(10,cc) + s(37,cc))
            t(358) = km(23)*s(26,cc)
            t(359) = km(15)*(s(7,cc) + s(23,cc))
            t(360) = km(23)*(s(7,cc) + s(32,cc) + s(33,cc))
            t(361) = km(23)*(s(5,cc) + s(38,cc) + s(39,cc))
            t(362) = km(15)*(s(27,cc) + s(28,cc))
            t(363) = km(16)*(s(7,cc) + s(31,cc) + s(33,cc))
            t(364) = km(20)*(s(26,cc) + s(29,cc)) + km(21)*(s(10,cc) + s(13,cc))
            t(365) = km(23)*(s(7,cc) + s(31,cc) + s(33,cc))
            t(366) = km(23)*(s(9,cc) + 3.0_dp*s(10,cc) + s(13,cc) + s(37,cc) + s(40,cc) + s(41,cc) &
               + s(42,cc) + s(43,cc))
            t(367) = km(15)*(s(7,cc) + s(23,cc) + s(30,cc) + s(31,cc) + s(32,cc) + s(33,cc))
            t(368) = km(8)*s(1,cc) + km(18)*(s(18,cc) + s(70,cc))
            t(369) = km(21)*s(34,cc) - km(23)*s(34,cc)
            t(370) = km(5)*s(2,cc) + km(25)*(s(19,cc) + s(62,cc))
            t(371) = km(15)*s(21,cc) - km(16)*s(21,cc)
            t(372) = km(8)*s(2,cc) + km(18)*(s(19,cc) + s(62,cc))
            t(373) = km(21)*s(21,cc) - km(23)*s(21,cc)
            t(374) = km(8)*(s(3,cc) + s(4,cc)) + km(18)*(s(20,cc) + 3.0_dp*s(21,cc) + s(71,cc) + &
               s(72,cc))
            t(375) = km(21)*(s(2,cc) + s(35,cc) + s(36,cc)) + km(23)*(-s(2,cc) - s(35,cc) - &
               s(36,cc))
            t(376) = km(5)*s(5,cc) + km(25)*(s(22,cc) + s(65,cc))
            t(377) = km(15)*s(28,cc) - km(16)*s(28,cc)
            t(378) = km(7)*s(7,cc) + km(8)*(s(6,cc) + s(8,cc)) + km(17)*(s(24,cc) + s(59,cc)) + &
               km(18)*(s(7,cc) + s(23,cc) + s(33,cc) + s(73,cc))
            t(379) = km(20)*s(26,cc) + km(21)*(s(10,cc) + s(37,cc)) - km(22)*s(26,cc) + &
               km(23)*(-s(10,cc) - s(37,cc))
            t(380) = km(5)*s(7,cc) + km(25)*(s(24,cc) + s(59,cc))
            t(381) = km(15)*s(26,cc) - km(16)*s(26,cc)
            t(382) = km(5)*(s(9,cc) + s(10,cc)) + km(25)*(s(25,cc) + 3.0_dp*s(26,cc) + s(68,cc) + &
               s(69,cc))
            t(383) = km(15)*(s(7,cc) + s(32,cc) + s(33,cc)) + km(16)*(-s(7,cc) - s(32,cc) - &
               s(33,cc))
            t(384) = km(8)*s(5,cc) + km(18)*(s(22,cc) + s(65,cc))
            t(385) = km(21)*s(28,cc) - km(23)*s(28,cc)
            t(386) = km(8)*(s(6,cc) + s(8,cc)) + km(18)*(s(7,cc) + s(23,cc) + s(33,cc) + s(73,cc))
            t(387) = km(8)*s(7,cc) + km(18)*(s(24,cc) + s(59,cc))
            t(388) = km(21)*(s(10,cc) + s(37,cc)) + km(23)*(-s(10,cc) - s(37,cc))
            t(389) = km(21)*s(26,cc) - km(23)*s(26,cc)
            t(390) = km(8)*(s(9,cc) + s(10,cc)) + km(18)*(s(25,cc) + 3.0_dp*s(26,cc) + s(68,cc) + &
               s(69,cc))
            t(391) = km(21)*(s(7,cc) + s(32,cc) + s(33,cc)) + km(23)*(-s(7,cc) - s(32,cc) - &
               s(33,cc))
            t(392) = km(8)*(s(11,cc) + s(12,cc)) + km(18)*(s(27,cc) + 3.0_dp*s(28,cc) + s(74,cc) + &
               s(75,cc))
            t(393) = km(21)*(s(5,cc) + s(38,cc) + s(39,cc)) + km(23)*(-s(5,cc) - s(38,cc) - &
               s(39,cc))
            t(394) = km(5)*(s(10,cc) + s(13,cc)) + km(25)*(3.0_dp*s(26,cc) + s(29,cc) + s(67,cc) + &
               s(69,cc))
            t(395) = km(15)*(s(7,cc) + s(31,cc) + s(33,cc)) + km(16)*(-s(7,cc) - s(31,cc) - &
               s(33,cc))
            t(396) = km(8)*(s(10,cc) + s(13,cc)) + km(18)*(3.0_dp*s(26,cc) + s(29,cc) + s(67,cc) + &
               s(69,cc))
            t(397) = km(21)*(s(7,cc) + s(31,cc) + s(33,cc)) + km(23)*(-s(7,cc) - s(31,cc) - &
               s(33,cc))
            t(398) = km(8)*(s(6,cc) + s(8,cc) + s(14,cc) + s(15,cc) + s(16,cc) + s(17,cc)) + &
               km(18)*(3.0_dp*s(7,cc) + s(23,cc) + s(30,cc) + 3.0_dp*s(31,cc) + 3.0_dp*s(32,cc) + &
               6.0_dp*s(33,cc) + s(73,cc) + s(76,cc) + s(77,cc) + s(78,cc) + s(79,cc))
            t(399) = km(21)*(s(9,cc) + 3.0_dp*s(10,cc) + s(13,cc) + s(37,cc) + s(40,cc) + s(41,cc) &
               + s(42,cc) + s(43,cc)) + km(23)*(-s(9,cc) + (-3.0_dp)*s(10,cc) - s(13,cc) - s(37,cc) &
               - s(40,cc) - s(41,cc) - s(42,cc) - s(43,cc))
            do ck = 1, nck
               r(1:16,cc,ck) = r(1:16,cc,ck) + kcd(1+4*(ck-1),kq)*t(1:16)
               r(17:80,cc,ck) = r(17:80,cc,ck) + kcd(2+4*(ck-1),kq)*t(17:80)
               r(81:112,cc,ck) = r(81:112,cc,ck) + kcd(3+4*(ck-1),kq)*t(81:112)
               r(251:266,cc,ck) = r(251:266,cc,ck) + kcd(3+4*(ck-1),kq)*t(251:266)
               r(325:340,cc,ck) = r(325:340,cc,ck) + kcd(3+4*(ck-1),kq)*t(325:340)
               r(113:250,cc,ck) = r(113:250,cc,ck) + kcd(4+4*(ck-1),kq)*t(113:250)
               r(267:324,cc,ck) = r(267:324,cc,ck) + kcd(4+4*(ck-1),kq)*t(267:324)
               r(341:399,cc,ck) = r(341:399,cc,ck) + kcd(4+4*(ck-1),kq)*t(341:399)
            end do
         end do
      end do
      res = 0.0_dp
      if (.not. any) return
      cm(1) = 1.0_dp
      cm(2) = cy
      cm(3) = cy*cy
      cm(4) = Rs
      cm(5) = Rs*cy
      cm(6) = Rs*cy*cy
      cm(7) = cy*cy*cy
      cm(8) = Rc
      cm(9) = Rc*cy
      cm(10) = Rc*cy*cy
      cm(11) = Rs*Rs
      cm(12) = Rs*Rs*cy
      cm(13) = Rs*Rs*cy*cy
      cm(14) = Rs*cy*cy*cy
      cm(15) = Rs*Rc
      cm(16) = Rs*Rc*cy
      cm(17) = Rs*Rc*cy*cy
      cm(18) = cy*cy*cy*cy
      cm(19) = Rc*cy*cy*cy
      cm(20) = Rc*Rc
      cm(21) = Rc*Rc*cy
      cm(22) = Rc*Rc*cy*cy
      do ck = 1, nck
         do cc = 1, ncb
            res(1,cc+ncb*(ck-1)) = r(1,cc,ck)
            res(2,cc+ncb*(ck-1)) = -r(2,cc,ck)
            res(3,cc+ncb*(ck-1)) = -cm(2)*r(3,cc,ck)
            res(4,cc+ncb*(ck-1)) = r(4,cc,ck)
            res(5,cc+ncb*(ck-1)) = -r(5,cc,ck)
            res(6,cc+ncb*(ck-1)) = r(6,cc,ck)
            res(7,cc+ncb*(ck-1)) = cm(2)*r(7,cc,ck)
            res(8,cc+ncb*(ck-1)) = -r(8,cc,ck)
            res(9,cc+ncb*(ck-1)) = -cm(2)*r(9,cc,ck)
            res(10,cc+ncb*(ck-1)) = cm(2)*r(7,cc,ck)
            res(11,cc+ncb*(ck-1)) = r(10,cc,ck) + cm(3)*r(11,cc,ck)
            res(12,cc+ncb*(ck-1)) = -cm(2)*r(12,cc,ck)
            res(13,cc+ncb*(ck-1)) = r(13,cc,ck)
            res(14,cc+ncb*(ck-1)) = -r(14,cc,ck)
            res(15,cc+ncb*(ck-1)) = -cm(2)*r(15,cc,ck)
            res(16,cc+ncb*(ck-1)) = r(16,cc,ck)
            res(17,cc+ncb*(ck-1)) = r(17,cc,ck) + cm(4)*r(18,cc,ck)
            res(18,cc+ncb*(ck-1)) = -r(19,cc,ck) - cm(4)*r(20,cc,ck)
            res(19,cc+ncb*(ck-1)) = -cm(2)*r(21,cc,ck) - cm(5)*r(22,cc,ck)
            res(20,cc+ncb*(ck-1)) = r(23,cc,ck) + cm(4)*r(24,cc,ck)
            res(21,cc+ncb*(ck-1)) = -r(25,cc,ck) - cm(4)*r(26,cc,ck)
            res(22,cc+ncb*(ck-1)) = 3.0_dp*r(27,cc,ck) + cm(4)*r(28,cc,ck)
            res(23,cc+ncb*(ck-1)) = cm(2)*r(29,cc,ck) + cm(5)*r(30,cc,ck)
            res(24,cc+ncb*(ck-1)) = -r(31,cc,ck) - cm(4)*r(32,cc,ck)
            res(25,cc+ncb*(ck-1)) = -cm(2)*r(33,cc,ck) - cm(5)*r(34,cc,ck)
            res(26,cc+ncb*(ck-1)) = cm(2)*r(29,cc,ck) + cm(5)*r(30,cc,ck)
            res(27,cc+ncb*(ck-1)) = r(35,cc,ck) + cm(3)*r(36,cc,ck) + cm(4)*r(37,cc,ck) + &
               cm(6)*r(38,cc,ck)
            res(28,cc+ncb*(ck-1)) = -cm(2)*r(39,cc,ck) - cm(5)*r(40,cc,ck)
            res(29,cc+ncb*(ck-1)) = r(41,cc,ck) + cm(4)*r(42,cc,ck)
            res(30,cc+ncb*(ck-1)) = -r(43,cc,ck) - cm(4)*r(44,cc,ck)
            res(31,cc+ncb*(ck-1)) = -cm(2)*r(45,cc,ck) - cm(5)*r(46,cc,ck)
            res(32,cc+ncb*(ck-1)) = r(47,cc,ck) + cm(4)*r(48,cc,ck)
            res(33,cc+ncb*(ck-1)) = cm(2)*r(49,cc,ck)
            res(34,cc+ncb*(ck-1)) = -cm(2)*r(21,cc,ck)
            res(35,cc+ncb*(ck-1)) = -r(50,cc,ck) - cm(3)*r(51,cc,ck)
            res(36,cc+ncb*(ck-1)) = cm(2)*r(52,cc,ck)
            res(37,cc+ncb*(ck-1)) = -cm(2)*r(33,cc,ck)
            res(38,cc+ncb*(ck-1)) = cm(2)*r(53,cc,ck)
            res(39,cc+ncb*(ck-1)) = r(54,cc,ck) + cm(3)*r(36,cc,ck)
            res(40,cc+ncb*(ck-1)) = -cm(2)*r(39,cc,ck)
            res(41,cc+ncb*(ck-1)) = -r(55,cc,ck) - cm(3)*r(56,cc,ck)
            res(42,cc+ncb*(ck-1)) = r(54,cc,ck) + cm(3)*r(36,cc,ck)
            res(43,cc+ncb*(ck-1)) = 3.0_dp*cm(2)*r(57,cc,ck) + cm(7)*r(58,cc,ck)
            res(44,cc+ncb*(ck-1)) = -r(59,cc,ck) - cm(3)*r(60,cc,ck)
            res(45,cc+ncb*(ck-1)) = cm(2)*r(61,cc,ck)
            res(46,cc+ncb*(ck-1)) = -cm(2)*r(45,cc,ck)
            res(47,cc+ncb*(ck-1)) = -r(62,cc,ck) - cm(3)*r(63,cc,ck)
            res(48,cc+ncb*(ck-1)) = cm(2)*r(64,cc,ck)
            res(49,cc+ncb*(ck-1)) = -r(65,cc,ck) + cm(8)*r(18,cc,ck)
            res(50,cc+ncb*(ck-1)) = r(66,cc,ck) - cm(8)*r(20,cc,ck)
            res(51,cc+ncb*(ck-1)) = cm(2)*r(67,cc,ck) - cm(9)*r(22,cc,ck)
            res(52,cc+ncb*(ck-1)) = -r(68,cc,ck) + cm(8)*r(24,cc,ck)
            res(53,cc+ncb*(ck-1)) = r(69,cc,ck) - cm(8)*r(26,cc,ck)
            res(54,cc+ncb*(ck-1)) = -r(70,cc,ck) + cm(8)*r(28,cc,ck)
            res(55,cc+ncb*(ck-1)) = -cm(2)*r(71,cc,ck) + cm(9)*r(30,cc,ck)
            res(56,cc+ncb*(ck-1)) = r(72,cc,ck) - cm(8)*r(32,cc,ck)
            res(57,cc+ncb*(ck-1)) = cm(2)*r(73,cc,ck) - cm(9)*r(34,cc,ck)
            res(58,cc+ncb*(ck-1)) = -cm(2)*r(71,cc,ck) + cm(9)*r(30,cc,ck)
            res(59,cc+ncb*(ck-1)) = -r(74,cc,ck) - cm(3)*r(75,cc,ck) + cm(8)*r(37,cc,ck) + &
               cm(10)*r(38,cc,ck)
            res(60,cc+ncb*(ck-1)) = cm(2)*r(76,cc,ck) - cm(9)*r(40,cc,ck)
            res(61,cc+ncb*(ck-1)) = -r(77,cc,ck) + cm(8)*r(42,cc,ck)
            res(62,cc+ncb*(ck-1)) = r(78,cc,ck) - cm(8)*r(44,cc,ck)
            res(63,cc+ncb*(ck-1)) = cm(2)*r(79,cc,ck) - cm(9)*r(46,cc,ck)
            res(64,cc+ncb*(ck-1)) = -r(80,cc,ck) + cm(8)*r(48,cc,ck)
            res(65,cc+ncb*(ck-1)) = r(81,cc,ck) - cm(4)*r(82,cc,ck)
            res(66,cc+ncb*(ck-1)) = -r(83,cc,ck) + cm(4)*r(84,cc,ck)
            res(67,cc+ncb*(ck-1)) = -cm(2)*r(85,cc,ck) + cm(5)*r(86,cc,ck)
            res(68,cc+ncb*(ck-1)) = r(87,cc,ck) - cm(4)*r(88,cc,ck)
            res(69,cc+ncb*(ck-1)) = -r(89,cc,ck) + cm(4)*r(90,cc,ck)
            res(70,cc+ncb*(ck-1)) = 3.0_dp*r(91,cc,ck) - cm(4)*r(92,cc,ck)
            res(71,cc+ncb*(ck-1)) = cm(2)*r(93,cc,ck) - cm(5)*r(94,cc,ck)
            res(72,cc+ncb*(ck-1)) = -r(95,cc,ck) + cm(4)*r(96,cc,ck)
            res(73,cc+ncb*(ck-1)) = -cm(2)*r(97,cc,ck) + cm(5)*r(98,cc,ck)
            res(74,cc+ncb*(ck-1)) = cm(2)*r(93,cc,ck) - cm(5)*r(94,cc,ck)
            res(75,cc+ncb*(ck-1)) = r(99,cc,ck) + cm(3)*r(100,cc,ck) - cm(4)*r(101,cc,ck) - &
               cm(6)*r(102,cc,ck)
            res(76,cc+ncb*(ck-1)) = -cm(2)*r(103,cc,ck) + cm(5)*r(104,cc,ck)
            res(77,cc+ncb*(ck-1)) = r(105,cc,ck) - cm(4)*r(106,cc,ck)
            res(78,cc+ncb*(ck-1)) = -r(107,cc,ck) + cm(4)*r(108,cc,ck)
            res(79,cc+ncb*(ck-1)) = -cm(2)*r(109,cc,ck) + cm(5)*r(110,cc,ck)
            res(80,cc+ncb*(ck-1)) = r(111,cc,ck) - cm(4)*r(112,cc,ck)
            res(81,cc+ncb*(ck-1)) = r(113,cc,ck) - cm(4)*r(114,cc,ck) - cm(11)*r(115,cc,ck)
            res(82,cc+ncb*(ck-1)) = -r(116,cc,ck) + cm(4)*r(117,cc,ck) + cm(11)*r(118,cc,ck)
            res(83,cc+ncb*(ck-1)) = -cm(2)*r(119,cc,ck) + cm(5)*r(120,cc,ck) + cm(12)*r(121,cc,ck)
            res(84,cc+ncb*(ck-1)) = r(122,cc,ck) - cm(4)*r(123,cc,ck) - cm(11)*r(124,cc,ck)
            res(85,cc+ncb*(ck-1)) = -r(125,cc,ck) + cm(4)*r(126,cc,ck) + cm(11)*r(127,cc,ck)
            res(86,cc+ncb*(ck-1)) = r(128,cc,ck) + (-3.0_dp)*cm(4)*r(129,cc,ck) - &
               cm(11)*r(130,cc,ck)
            res(87,cc+ncb*(ck-1)) = cm(2)*r(131,cc,ck) - cm(5)*r(132,cc,ck) - cm(12)*r(133,cc,ck)
            res(88,cc+ncb*(ck-1)) = -r(134,cc,ck) + cm(4)*r(135,cc,ck) + cm(11)*r(136,cc,ck)
            res(89,cc+ncb*(ck-1)) = -cm(2)*r(137,cc,ck) + cm(5)*r(138,cc,ck) + cm(12)*r(139,cc,ck)
            res(90,cc+ncb*(ck-1)) = cm(2)*r(131,cc,ck) - cm(5)*r(132,cc,ck) - cm(12)*r(133,cc,ck)
            res(91,cc+ncb*(ck-1)) = r(140,cc,ck) + cm(3)*r(141,cc,ck) - cm(4)*r(142,cc,ck) - &
               cm(6)*r(143,cc,ck) - cm(11)*r(144,cc,ck) - cm(13)*r(145,cc,ck)
            res(92,cc+ncb*(ck-1)) = -cm(2)*r(146,cc,ck) + cm(5)*r(147,cc,ck) + cm(12)*r(148,cc,ck)
            res(93,cc+ncb*(ck-1)) = r(149,cc,ck) - cm(4)*r(150,cc,ck) - cm(11)*r(151,cc,ck)
            res(94,cc+ncb*(ck-1)) = -r(152,cc,ck) + cm(4)*r(153,cc,ck) + cm(11)*r(154,cc,ck)
            res(95,cc+ncb*(ck-1)) = -cm(2)*r(155,cc,ck) + cm(5)*r(156,cc,ck) + cm(12)*r(157,cc,ck)
            res(96,cc+ncb*(ck-1)) = r(158,cc,ck) - cm(4)*r(159,cc,ck) - cm(11)*r(160,cc,ck)
            res(97,cc+ncb*(ck-1)) = cm(2)*r(161,cc,ck) - cm(5)*r(162,cc,ck)
            res(98,cc+ncb*(ck-1)) = -cm(2)*r(163,cc,ck) + cm(5)*r(164,cc,ck)
            res(99,cc+ncb*(ck-1)) = -r(165,cc,ck) - cm(3)*r(166,cc,ck) + cm(4)*r(167,cc,ck) + &
               cm(6)*r(168,cc,ck)
            res(100,cc+ncb*(ck-1)) = cm(2)*r(169,cc,ck) - cm(5)*r(170,cc,ck)
            res(101,cc+ncb*(ck-1)) = -cm(2)*r(171,cc,ck) + cm(5)*r(172,cc,ck)
            res(102,cc+ncb*(ck-1)) = cm(2)*r(173,cc,ck) - cm(5)*r(174,cc,ck)
            res(103,cc+ncb*(ck-1)) = r(175,cc,ck) + cm(3)*r(176,cc,ck) - cm(4)*r(177,cc,ck) - &
               cm(6)*r(178,cc,ck)
            res(104,cc+ncb*(ck-1)) = -cm(2)*r(179,cc,ck) + cm(5)*r(180,cc,ck)
            res(105,cc+ncb*(ck-1)) = -r(181,cc,ck) - cm(3)*r(182,cc,ck) + cm(4)*r(183,cc,ck) + &
               cm(6)*r(184,cc,ck)
            res(106,cc+ncb*(ck-1)) = r(175,cc,ck) + cm(3)*r(176,cc,ck) - cm(4)*r(177,cc,ck) - &
               cm(6)*r(178,cc,ck)
            res(107,cc+ncb*(ck-1)) = 3.0_dp*cm(2)*r(185,cc,ck) + (-3.0_dp)*cm(5)*r(186,cc,ck) + &
               cm(7)*r(187,cc,ck) - cm(14)*r(188,cc,ck)
            res(108,cc+ncb*(ck-1)) = -r(189,cc,ck) - cm(3)*r(190,cc,ck) + cm(4)*r(191,cc,ck) + &
               cm(6)*r(192,cc,ck)
            res(109,cc+ncb*(ck-1)) = cm(2)*r(193,cc,ck) - cm(5)*r(194,cc,ck)
            res(110,cc+ncb*(ck-1)) = -cm(2)*r(195,cc,ck) + cm(5)*r(196,cc,ck)
            res(111,cc+ncb*(ck-1)) = -r(197,cc,ck) - cm(3)*r(198,cc,ck) + cm(4)*r(199,cc,ck) + &
               cm(6)*r(200,cc,ck)
            res(112,cc+ncb*(ck-1)) = cm(2)*r(201,cc,ck) - cm(5)*r(202,cc,ck)
            res(113,cc+ncb*(ck-1)) = -r(203,cc,ck) + cm(4)*r(204,cc,ck) + cm(8)*r(205,cc,ck) - &
               cm(15)*r(115,cc,ck)
            res(114,cc+ncb*(ck-1)) = r(206,cc,ck) - cm(4)*r(207,cc,ck) - cm(8)*r(208,cc,ck) + &
               cm(15)*r(118,cc,ck)
            res(115,cc+ncb*(ck-1)) = cm(2)*r(209,cc,ck) - cm(5)*r(210,cc,ck) - cm(9)*r(211,cc,ck) + &
               cm(16)*r(121,cc,ck)
            res(116,cc+ncb*(ck-1)) = -r(212,cc,ck) + cm(4)*r(213,cc,ck) + cm(8)*r(214,cc,ck) - &
               cm(15)*r(124,cc,ck)
            res(117,cc+ncb*(ck-1)) = r(215,cc,ck) - cm(4)*r(216,cc,ck) - cm(8)*r(217,cc,ck) + &
               cm(15)*r(127,cc,ck)
            res(118,cc+ncb*(ck-1)) = -r(218,cc,ck) + cm(4)*r(219,cc,ck) + 3.0_dp*cm(8)*r(220,cc,ck) &
               - cm(15)*r(130,cc,ck)
            res(119,cc+ncb*(ck-1)) = -cm(2)*r(221,cc,ck) + cm(5)*r(222,cc,ck) + cm(9)*r(223,cc,ck) &
               - cm(16)*r(133,cc,ck)
            res(120,cc+ncb*(ck-1)) = r(224,cc,ck) - cm(4)*r(225,cc,ck) - cm(8)*r(226,cc,ck) + &
               cm(15)*r(136,cc,ck)
            res(121,cc+ncb*(ck-1)) = cm(2)*r(227,cc,ck) - cm(5)*r(228,cc,ck) - cm(9)*r(229,cc,ck) + &
               cm(16)*r(139,cc,ck)
            res(122,cc+ncb*(ck-1)) = -cm(2)*r(221,cc,ck) + cm(5)*r(222,cc,ck) + cm(9)*r(223,cc,ck) &
               - cm(16)*r(133,cc,ck)
            res(123,cc+ncb*(ck-1)) = -r(230,cc,ck) - cm(3)*r(231,cc,ck) + cm(4)*r(232,cc,ck) + &
               cm(6)*r(233,cc,ck) + cm(8)*r(234,cc,ck) + cm(10)*r(235,cc,ck) - cm(15)*r(144,cc,ck) &
               - cm(17)*r(145,cc,ck)
            res(124,cc+ncb*(ck-1)) = cm(2)*r(236,cc,ck) - cm(5)*r(237,cc,ck) - cm(9)*r(238,cc,ck) + &
               cm(16)*r(148,cc,ck)
            res(125,cc+ncb*(ck-1)) = -r(239,cc,ck) + cm(4)*r(240,cc,ck) + cm(8)*r(241,cc,ck) - &
               cm(15)*r(151,cc,ck)
            res(126,cc+ncb*(ck-1)) = r(242,cc,ck) - cm(4)*r(243,cc,ck) - cm(8)*r(244,cc,ck) + &
               cm(15)*r(154,cc,ck)
            res(127,cc+ncb*(ck-1)) = cm(2)*r(245,cc,ck) - cm(5)*r(246,cc,ck) - cm(9)*r(247,cc,ck) + &
               cm(16)*r(157,cc,ck)
            res(128,cc+ncb*(ck-1)) = -r(248,cc,ck) + cm(4)*r(249,cc,ck) + cm(8)*r(250,cc,ck) - &
               cm(15)*r(160,cc,ck)
            res(129,cc+ncb*(ck-1)) = cm(2)*r(251,cc,ck)
            res(130,cc+ncb*(ck-1)) = -cm(2)*r(85,cc,ck)
            res(131,cc+ncb*(ck-1)) = -r(252,cc,ck) - cm(3)*r(253,cc,ck)
            res(132,cc+ncb*(ck-1)) = cm(2)*r(254,cc,ck)
            res(133,cc+ncb*(ck-1)) = -cm(2)*r(97,cc,ck)
            res(134,cc+ncb*(ck-1)) = cm(2)*r(255,cc,ck)
            res(135,cc+ncb*(ck-1)) = r(256,cc,ck) + cm(3)*r(100,cc,ck)
            res(136,cc+ncb*(ck-1)) = -cm(2)*r(103,cc,ck)
            res(137,cc+ncb*(ck-1)) = -r(257,cc,ck) - cm(3)*r(258,cc,ck)
            res(138,cc+ncb*(ck-1)) = r(256,cc,ck) + cm(3)*r(100,cc,ck)
            res(139,cc+ncb*(ck-1)) = 3.0_dp*cm(2)*r(259,cc,ck) + cm(7)*r(260,cc,ck)
            res(140,cc+ncb*(ck-1)) = -r(261,cc,ck) - cm(3)*r(262,cc,ck)
            res(141,cc+ncb*(ck-1)) = cm(2)*r(263,cc,ck)
            res(142,cc+ncb*(ck-1)) = -cm(2)*r(109,cc,ck)
            res(143,cc+ncb*(ck-1)) = -r(264,cc,ck) - cm(3)*r(265,cc,ck)
            res(144,cc+ncb*(ck-1)) = cm(2)*r(266,cc,ck)
            res(145,cc+ncb*(ck-1)) = cm(2)*r(161,cc,ck) + cm(5)*r(267,cc,ck)
            res(146,cc+ncb*(ck-1)) = -cm(2)*r(163,cc,ck) - cm(5)*r(211,cc,ck)
            res(147,cc+ncb*(ck-1)) = -r(165,cc,ck) - cm(3)*r(166,cc,ck) - cm(4)*r(268,cc,ck) - &
               cm(6)*r(269,cc,ck)
            res(148,cc+ncb*(ck-1)) = cm(2)*r(169,cc,ck) + cm(5)*r(270,cc,ck)
            res(149,cc+ncb*(ck-1)) = -cm(2)*r(171,cc,ck) - cm(5)*r(229,cc,ck)
            res(150,cc+ncb*(ck-1)) = cm(2)*r(173,cc,ck) + cm(5)*r(271,cc,ck)
            res(151,cc+ncb*(ck-1)) = r(175,cc,ck) + cm(3)*r(176,cc,ck) + cm(4)*r(272,cc,ck) + &
               cm(6)*r(235,cc,ck)
            res(152,cc+ncb*(ck-1)) = -cm(2)*r(179,cc,ck) - cm(5)*r(238,cc,ck)
            res(153,cc+ncb*(ck-1)) = -r(181,cc,ck) - cm(3)*r(182,cc,ck) - cm(4)*r(273,cc,ck) - &
               cm(6)*r(274,cc,ck)
            res(154,cc+ncb*(ck-1)) = r(175,cc,ck) + cm(3)*r(176,cc,ck) + cm(4)*r(272,cc,ck) + &
               cm(6)*r(235,cc,ck)
            res(155,cc+ncb*(ck-1)) = 3.0_dp*cm(2)*r(185,cc,ck) + 3.0_dp*cm(5)*r(275,cc,ck) + &
               cm(7)*r(187,cc,ck) + cm(14)*r(276,cc,ck)
            res(156,cc+ncb*(ck-1)) = -r(189,cc,ck) - cm(3)*r(190,cc,ck) - cm(4)*r(277,cc,ck) - &
               cm(6)*r(278,cc,ck)
            res(157,cc+ncb*(ck-1)) = cm(2)*r(193,cc,ck) + cm(5)*r(279,cc,ck)
            res(158,cc+ncb*(ck-1)) = -cm(2)*r(195,cc,ck) - cm(5)*r(247,cc,ck)
            res(159,cc+ncb*(ck-1)) = -r(197,cc,ck) - cm(3)*r(198,cc,ck) - cm(4)*r(280,cc,ck) - &
               cm(6)*r(281,cc,ck)
            res(160,cc+ncb*(ck-1)) = cm(2)*r(201,cc,ck) + cm(5)*r(282,cc,ck)
            res(161,cc+ncb*(ck-1)) = r(283,cc,ck) + cm(3)*r(284,cc,ck)
            res(162,cc+ncb*(ck-1)) = -r(285,cc,ck) - cm(3)*r(166,cc,ck)
            res(163,cc+ncb*(ck-1)) = -cm(2)*r(286,cc,ck) - cm(7)*r(287,cc,ck)
            res(164,cc+ncb*(ck-1)) = r(288,cc,ck) + cm(3)*r(289,cc,ck)
            res(165,cc+ncb*(ck-1)) = -r(290,cc,ck) - cm(3)*r(182,cc,ck)
            res(166,cc+ncb*(ck-1)) = r(291,cc,ck) + cm(3)*r(292,cc,ck)
            res(167,cc+ncb*(ck-1)) = cm(2)*r(293,cc,ck) + cm(7)*r(187,cc,ck)
            res(168,cc+ncb*(ck-1)) = -r(294,cc,ck) - cm(3)*r(190,cc,ck)
            res(169,cc+ncb*(ck-1)) = -cm(2)*r(295,cc,ck) - cm(7)*r(296,cc,ck)
            res(170,cc+ncb*(ck-1)) = cm(2)*r(293,cc,ck) + cm(7)*r(187,cc,ck)
            res(171,cc+ncb*(ck-1)) = r(297,cc,ck) + cm(3)*r(298,cc,ck) + cm(18)*r(299,cc,ck)
            res(172,cc+ncb*(ck-1)) = -cm(2)*r(300,cc,ck) - cm(7)*r(301,cc,ck)
            res(173,cc+ncb*(ck-1)) = r(302,cc,ck) + cm(3)*r(303,cc,ck)
            res(174,cc+ncb*(ck-1)) = -r(304,cc,ck) - cm(3)*r(198,cc,ck)
            res(175,cc+ncb*(ck-1)) = -cm(2)*r(305,cc,ck) - cm(7)*r(306,cc,ck)
            res(176,cc+ncb*(ck-1)) = r(307,cc,ck) + cm(3)*r(308,cc,ck)
            res(177,cc+ncb*(ck-1)) = -cm(2)*r(309,cc,ck) + cm(9)*r(267,cc,ck)
            res(178,cc+ncb*(ck-1)) = cm(2)*r(209,cc,ck) - cm(9)*r(211,cc,ck)
            res(179,cc+ncb*(ck-1)) = r(310,cc,ck) + cm(3)*r(311,cc,ck) - cm(8)*r(268,cc,ck) - &
               cm(10)*r(269,cc,ck)
            res(180,cc+ncb*(ck-1)) = -cm(2)*r(312,cc,ck) + cm(9)*r(270,cc,ck)
            res(181,cc+ncb*(ck-1)) = cm(2)*r(227,cc,ck) - cm(9)*r(229,cc,ck)
            res(182,cc+ncb*(ck-1)) = -cm(2)*r(313,cc,ck) + cm(9)*r(271,cc,ck)
            res(183,cc+ncb*(ck-1)) = -r(314,cc,ck) - cm(3)*r(231,cc,ck) + cm(8)*r(272,cc,ck) + &
               cm(10)*r(235,cc,ck)
            res(184,cc+ncb*(ck-1)) = cm(2)*r(236,cc,ck) - cm(9)*r(238,cc,ck)
            res(185,cc+ncb*(ck-1)) = r(315,cc,ck) + cm(3)*r(316,cc,ck) - cm(8)*r(273,cc,ck) - &
               cm(10)*r(274,cc,ck)
            res(186,cc+ncb*(ck-1)) = -r(314,cc,ck) - cm(3)*r(231,cc,ck) + cm(8)*r(272,cc,ck) + &
               cm(10)*r(235,cc,ck)
            res(187,cc+ncb*(ck-1)) = (-3.0_dp)*cm(2)*r(317,cc,ck) - cm(7)*r(318,cc,ck) + &
               3.0_dp*cm(9)*r(275,cc,ck) + cm(19)*r(276,cc,ck)
            res(188,cc+ncb*(ck-1)) = r(319,cc,ck) + cm(3)*r(320,cc,ck) - cm(8)*r(277,cc,ck) - &
               cm(10)*r(278,cc,ck)
            res(189,cc+ncb*(ck-1)) = -cm(2)*r(321,cc,ck) + cm(9)*r(279,cc,ck)
            res(190,cc+ncb*(ck-1)) = cm(2)*r(245,cc,ck) - cm(9)*r(247,cc,ck)
            res(191,cc+ncb*(ck-1)) = r(322,cc,ck) + cm(3)*r(323,cc,ck) - cm(8)*r(280,cc,ck) - &
               cm(10)*r(281,cc,ck)
            res(192,cc+ncb*(ck-1)) = -cm(2)*r(324,cc,ck) + cm(9)*r(282,cc,ck)
            res(193,cc+ncb*(ck-1)) = -r(325,cc,ck) - cm(8)*r(82,cc,ck)
            res(194,cc+ncb*(ck-1)) = r(326,cc,ck) + cm(8)*r(84,cc,ck)
            res(195,cc+ncb*(ck-1)) = cm(2)*r(327,cc,ck) + cm(9)*r(86,cc,ck)
            res(196,cc+ncb*(ck-1)) = -r(328,cc,ck) - cm(8)*r(88,cc,ck)
            res(197,cc+ncb*(ck-1)) = r(329,cc,ck) + cm(8)*r(90,cc,ck)
            res(198,cc+ncb*(ck-1)) = -r(330,cc,ck) - cm(8)*r(92,cc,ck)
            res(199,cc+ncb*(ck-1)) = -cm(2)*r(331,cc,ck) - cm(9)*r(94,cc,ck)
            res(200,cc+ncb*(ck-1)) = r(332,cc,ck) + cm(8)*r(96,cc,ck)
            res(201,cc+ncb*(ck-1)) = cm(2)*r(333,cc,ck) + cm(9)*r(98,cc,ck)
            res(202,cc+ncb*(ck-1)) = -cm(2)*r(331,cc,ck) - cm(9)*r(94,cc,ck)
            res(203,cc+ncb*(ck-1)) = -r(334,cc,ck) - cm(3)*r(335,cc,ck) - cm(8)*r(101,cc,ck) - &
               cm(10)*r(102,cc,ck)
            res(204,cc+ncb*(ck-1)) = cm(2)*r(336,cc,ck) + cm(9)*r(104,cc,ck)
            res(205,cc+ncb*(ck-1)) = -r(337,cc,ck) - cm(8)*r(106,cc,ck)
            res(206,cc+ncb*(ck-1)) = r(338,cc,ck) + cm(8)*r(108,cc,ck)
            res(207,cc+ncb*(ck-1)) = cm(2)*r(339,cc,ck) + cm(9)*r(110,cc,ck)
            res(208,cc+ncb*(ck-1)) = -r(340,cc,ck) - cm(8)*r(112,cc,ck)
            res(209,cc+ncb*(ck-1)) = -r(203,cc,ck) - cm(4)*r(341,cc,ck) - cm(8)*r(342,cc,ck) - &
               cm(15)*r(115,cc,ck)
            res(210,cc+ncb*(ck-1)) = r(206,cc,ck) + cm(4)*r(343,cc,ck) + cm(8)*r(344,cc,ck) + &
               cm(15)*r(118,cc,ck)
            res(211,cc+ncb*(ck-1)) = cm(2)*r(209,cc,ck) + cm(5)*r(345,cc,ck) + cm(9)*r(164,cc,ck) + &
               cm(16)*r(121,cc,ck)
            res(212,cc+ncb*(ck-1)) = -r(212,cc,ck) - cm(4)*r(346,cc,ck) - cm(8)*r(347,cc,ck) - &
               cm(15)*r(124,cc,ck)
            res(213,cc+ncb*(ck-1)) = r(215,cc,ck) + cm(4)*r(348,cc,ck) + cm(8)*r(349,cc,ck) + &
               cm(15)*r(127,cc,ck)
            res(214,cc+ncb*(ck-1)) = -r(218,cc,ck) - cm(4)*r(350,cc,ck) + &
               (-3.0_dp)*cm(8)*r(351,cc,ck) - cm(15)*r(130,cc,ck)
            res(215,cc+ncb*(ck-1)) = -cm(2)*r(221,cc,ck) - cm(5)*r(352,cc,ck) - cm(9)*r(353,cc,ck) &
               - cm(16)*r(133,cc,ck)
            res(216,cc+ncb*(ck-1)) = r(224,cc,ck) + cm(4)*r(354,cc,ck) + cm(8)*r(355,cc,ck) + &
               cm(15)*r(136,cc,ck)
            res(217,cc+ncb*(ck-1)) = cm(2)*r(227,cc,ck) + cm(5)*r(356,cc,ck) + cm(9)*r(172,cc,ck) + &
               cm(16)*r(139,cc,ck)
            res(218,cc+ncb*(ck-1)) = -cm(2)*r(221,cc,ck) - cm(5)*r(352,cc,ck) - cm(9)*r(353,cc,ck) &
               - cm(16)*r(133,cc,ck)
            res(219,cc+ncb*(ck-1)) = -r(230,cc,ck) - cm(3)*r(231,cc,ck) - cm(4)*r(357,cc,ck) - &
               cm(6)*r(358,cc,ck) - cm(8)*r(359,cc,ck) - cm(10)*r(178,cc,ck) - cm(15)*r(144,cc,ck) &
               - cm(17)*r(145,cc,ck)
            res(220,cc+ncb*(ck-1)) = cm(2)*r(236,cc,ck) + cm(5)*r(360,cc,ck) + cm(9)*r(180,cc,ck) + &
               cm(16)*r(148,cc,ck)
            res(221,cc+ncb*(ck-1)) = -r(239,cc,ck) - cm(4)*r(361,cc,ck) - cm(8)*r(362,cc,ck) - &
               cm(15)*r(151,cc,ck)
            res(222,cc+ncb*(ck-1)) = r(242,cc,ck) + cm(4)*r(363,cc,ck) + cm(8)*r(364,cc,ck) + &
               cm(15)*r(154,cc,ck)
            res(223,cc+ncb*(ck-1)) = cm(2)*r(245,cc,ck) + cm(5)*r(365,cc,ck) + cm(9)*r(196,cc,ck) + &
               cm(16)*r(157,cc,ck)
            res(224,cc+ncb*(ck-1)) = -r(248,cc,ck) - cm(4)*r(366,cc,ck) - cm(8)*r(367,cc,ck) - &
               cm(15)*r(160,cc,ck)
            res(225,cc+ncb*(ck-1)) = -cm(2)*r(309,cc,ck) - cm(9)*r(162,cc,ck)
            res(226,cc+ncb*(ck-1)) = cm(2)*r(209,cc,ck) + cm(9)*r(164,cc,ck)
            res(227,cc+ncb*(ck-1)) = r(310,cc,ck) + cm(3)*r(311,cc,ck) + cm(8)*r(167,cc,ck) + &
               cm(10)*r(168,cc,ck)
            res(228,cc+ncb*(ck-1)) = -cm(2)*r(312,cc,ck) - cm(9)*r(170,cc,ck)
            res(229,cc+ncb*(ck-1)) = cm(2)*r(227,cc,ck) + cm(9)*r(172,cc,ck)
            res(230,cc+ncb*(ck-1)) = -cm(2)*r(313,cc,ck) - cm(9)*r(174,cc,ck)
            res(231,cc+ncb*(ck-1)) = -r(314,cc,ck) - cm(3)*r(231,cc,ck) - cm(8)*r(177,cc,ck) - &
               cm(10)*r(178,cc,ck)
            res(232,cc+ncb*(ck-1)) = cm(2)*r(236,cc,ck) + cm(9)*r(180,cc,ck)
            res(233,cc+ncb*(ck-1)) = r(315,cc,ck) + cm(3)*r(316,cc,ck) + cm(8)*r(183,cc,ck) + &
               cm(10)*r(184,cc,ck)
            res(234,cc+ncb*(ck-1)) = -r(314,cc,ck) - cm(3)*r(231,cc,ck) - cm(8)*r(177,cc,ck) - &
               cm(10)*r(178,cc,ck)
            res(235,cc+ncb*(ck-1)) = (-3.0_dp)*cm(2)*r(317,cc,ck) - cm(7)*r(318,cc,ck) + &
               (-3.0_dp)*cm(9)*r(186,cc,ck) - cm(19)*r(188,cc,ck)
            res(236,cc+ncb*(ck-1)) = r(319,cc,ck) + cm(3)*r(320,cc,ck) + cm(8)*r(191,cc,ck) + &
               cm(10)*r(192,cc,ck)
            res(237,cc+ncb*(ck-1)) = -cm(2)*r(321,cc,ck) - cm(9)*r(194,cc,ck)
            res(238,cc+ncb*(ck-1)) = cm(2)*r(245,cc,ck) + cm(9)*r(196,cc,ck)
            res(239,cc+ncb*(ck-1)) = r(322,cc,ck) + cm(3)*r(323,cc,ck) + cm(8)*r(199,cc,ck) + &
               cm(10)*r(200,cc,ck)
            res(240,cc+ncb*(ck-1)) = -cm(2)*r(324,cc,ck) - cm(9)*r(202,cc,ck)
            res(241,cc+ncb*(ck-1)) = r(368,cc,ck) + cm(8)*r(369,cc,ck) - cm(20)*r(115,cc,ck)
            res(242,cc+ncb*(ck-1)) = -r(370,cc,ck) - cm(8)*r(371,cc,ck) + cm(20)*r(118,cc,ck)
            res(243,cc+ncb*(ck-1)) = -cm(2)*r(372,cc,ck) - cm(9)*r(373,cc,ck) + cm(21)*r(121,cc,ck)
            res(244,cc+ncb*(ck-1)) = r(374,cc,ck) + cm(8)*r(375,cc,ck) - cm(20)*r(124,cc,ck)
            res(245,cc+ncb*(ck-1)) = -r(376,cc,ck) - cm(8)*r(377,cc,ck) + cm(20)*r(127,cc,ck)
            res(246,cc+ncb*(ck-1)) = r(378,cc,ck) + cm(8)*r(379,cc,ck) - cm(20)*r(130,cc,ck)
            res(247,cc+ncb*(ck-1)) = cm(2)*r(380,cc,ck) + cm(9)*r(381,cc,ck) - cm(21)*r(133,cc,ck)
            res(248,cc+ncb*(ck-1)) = -r(382,cc,ck) - cm(8)*r(383,cc,ck) + cm(20)*r(136,cc,ck)
            res(249,cc+ncb*(ck-1)) = -cm(2)*r(384,cc,ck) - cm(9)*r(385,cc,ck) + cm(21)*r(139,cc,ck)
            res(250,cc+ncb*(ck-1)) = cm(2)*r(380,cc,ck) + cm(9)*r(381,cc,ck) - cm(21)*r(133,cc,ck)
            res(251,cc+ncb*(ck-1)) = r(386,cc,ck) + cm(3)*r(387,cc,ck) + cm(8)*r(388,cc,ck) + &
               cm(10)*r(389,cc,ck) - cm(20)*r(144,cc,ck) - cm(22)*r(145,cc,ck)
            res(252,cc+ncb*(ck-1)) = -cm(2)*r(390,cc,ck) - cm(9)*r(391,cc,ck) + cm(21)*r(148,cc,ck)
            res(253,cc+ncb*(ck-1)) = r(392,cc,ck) + cm(8)*r(393,cc,ck) - cm(20)*r(151,cc,ck)
            res(254,cc+ncb*(ck-1)) = -r(394,cc,ck) - cm(8)*r(395,cc,ck) + cm(20)*r(154,cc,ck)
            res(255,cc+ncb*(ck-1)) = -cm(2)*r(396,cc,ck) - cm(9)*r(397,cc,ck) + cm(21)*r(157,cc,ck)
            res(256,cc+ncb*(ck-1)) = r(398,cc,ck) + cm(8)*r(399,cc,ck) - cm(20)*r(160,cc,ck)
         end do
      end do
   end subroutine rotaxis_LLLL

end module rotaxis_LLLL_m
