! GENERATED by scripts/rotaxis_mmd -- do not edit.
! sppp: L=3 comps=27 S=15 g=2 r=48 (terms 104) km=14 cm=16 assembly terms=80
module rotaxis_sppp_m
   use cint_const, only: dp
   use cint_rotaxis_boys, only: boys
   implicit none
   private
   public :: rotaxis_sppp
contains
   ! (sp|pp)  L=3: 15 bra accumulators, 48 ket accumulators, 27 components
   subroutine rotaxis_sppp(nbra, ncb, bp, kab, nket, nck, kp, kcd, gc, cutoff, res, any)
      integer,  intent(in)  :: nbra, ncb, nket, nck
      real(dp), intent(in)  :: bp(5, nbra), kab(1*ncb, nbra)
      real(dp), intent(in)  :: kp(7, nket), kcd(1*nck, nket), gc(3), cutoff
      real(dp), intent(out) :: res(27, ncb*nck)
      logical,  intent(out) :: any
      real(dp) :: s(15, ncb), r(48, ncb, nck), t(48)
      real(dp) :: f(0:3), b(0:3)
      real(dp) :: p, ip, za, zb, eab, q, iq, yc, yd, ax, az, ecd
      real(dp) :: zq, alpha, tt, w, m2a, Rs, Rc, cy
      real(dp) :: g(2), km(14), cm(16), zq2, zq3
      integer :: kq, bq, cc, ck, n

      Rs = gc(1); Rc = gc(2); cy = gc(3)
      any = .false.
      r = 0.0_dp
      do kq = 1, nket
         q = kp(1,kq); iq = kp(2,kq); yc = kp(3,kq); yd = kp(4,kq)
         ax = kp(5,kq); az = kp(6,kq); ecd = kp(7,kq)
         s = 0.0_dp
         do bq = 1, nbra
            eab = bp(5,bq)
            if (eab + ecd > cutoff) cycle
            any = .true.
            p = bp(1,bq); ip = bp(2,bq); za = bp(3,bq); zb = bp(4,bq)
            zq = za - az
            alpha = p*q/(p + q)
            tt = alpha*(ax*ax + cy*cy + zq*zq)
            call boys(f, tt, 3)
            w = 1.0_dp/sqrt(p + q)
            m2a = -2.0_dp*alpha
            do n = 0, 3
               b(n) = w*f(n)
               w = w*m2a
            end do
            zq2 = zq*zq
            zq3 = zq2*zq
            g(1) = ip
            g(2) = zb
            do cc = 1, ncb
               s(1,cc) = s(1,cc) + kab(cc,bq)*g(1)*b(1)
               s(2,cc) = s(2,cc) + kab(cc,bq)*g(1)*b(2)
               s(3,cc) = s(3,cc) + kab(cc,bq)*g(1)*b(3)
               s(4,cc) = s(4,cc) + kab(cc,bq)*g(2)*b(0)
               s(5,cc) = s(5,cc) + kab(cc,bq)*g(1)*b(1)*zq
               s(6,cc) = s(6,cc) + kab(cc,bq)*g(2)*b(1)
               s(7,cc) = s(7,cc) + kab(cc,bq)*g(1)*b(2)*zq
               s(8,cc) = s(8,cc) + kab(cc,bq)*g(2)*b(2)
               s(9,cc) = s(9,cc) + kab(cc,bq)*g(1)*b(3)*zq
               s(10,cc) = s(10,cc) + kab(cc,bq)*g(2)*b(1)*zq
               s(11,cc) = s(11,cc) + kab(cc,bq)*g(1)*b(2)*zq2
               s(12,cc) = s(12,cc) + kab(cc,bq)*g(2)*b(2)*zq
               s(13,cc) = s(13,cc) + kab(cc,bq)*g(1)*b(3)*zq2
               s(14,cc) = s(14,cc) + kab(cc,bq)*g(2)*b(2)*zq2
               s(15,cc) = s(15,cc) + kab(cc,bq)*g(1)*b(3)*zq3
            end do
         end do
         if (.not. any) cycle
         km(1) = yc*yd*ax
         km(2) = iq*ax
         km(3) = iq*yc*ax*ax
         km(4) = iq*yc
         km(5) = iq*yd*ax*ax
         km(6) = iq*yd
         km(7) = iq*iq*ax*ax*ax
         km(8) = iq*iq*ax
         km(9) = yc*yd
         km(10) = iq
         km(11) = iq*yc*ax
         km(12) = iq*yd*ax
         km(13) = iq*iq*ax*ax
         km(14) = iq*iq
         do cc = 1, ncb
            t(1) = km(1)*s(1,cc)
            t(2) = km(2)*s(1,cc) + km(7)*s(3,cc) + 3.0_dp*km(8)*s(2,cc)
            t(3) = km(3)*s(2,cc) + km(4)*s(1,cc) - km(5)*s(2,cc) - km(6)*s(1,cc)
            t(4) = km(9)*s(1,cc)
            t(5) = km(10)*s(1,cc) + km(13)*s(3,cc) + km(14)*s(2,cc)
            t(6) = km(11)*s(2,cc) - km(12)*s(2,cc)
            t(7) = km(9)*(s(4,cc) + s(5,cc))
            t(8) = km(10)*(s(4,cc) + s(5,cc)) + km(13)*(s(8,cc) + s(9,cc)) + km(14)*(s(6,cc) + &
               s(7,cc))
            t(9) = km(11)*(s(6,cc) + s(7,cc)) + km(12)*(-s(6,cc) - s(7,cc))
            t(10) = km(13)*s(3,cc) + km(14)*s(2,cc)
            t(11) = km(11)*s(2,cc)
            t(12) = km(8)*s(2,cc)
            t(13) = km(4)*s(1,cc)
            t(14) = km(4)*s(2,cc)
            t(15) = km(8)*s(3,cc)
            t(16) = km(8)*(s(8,cc) + s(9,cc))
            t(17) = km(4)*(s(6,cc) + s(7,cc))
            t(18) = km(13)*s(9,cc) + km(14)*s(7,cc)
            t(19) = km(11)*s(7,cc)
            t(20) = km(5)*s(2,cc) + km(6)*s(1,cc)
            t(21) = km(8)*s(9,cc)
            t(22) = km(4)*s(7,cc)
            t(23) = km(12)*s(2,cc)
            t(24) = km(8)*(s(2,cc) + s(12,cc) + s(13,cc))
            t(25) = km(4)*(s(1,cc) + s(10,cc) + s(11,cc))
            t(26) = km(12)*(s(6,cc) + s(7,cc))
            t(27) = km(6)*s(1,cc)
            t(28) = km(6)*s(2,cc)
            t(29) = km(6)*(s(6,cc) + s(7,cc))
            t(30) = km(2)*s(1,cc) + km(8)*s(2,cc)
            t(31) = km(10)*s(1,cc) + 3.0_dp*km(14)*s(2,cc)
            t(32) = km(14)*s(3,cc)
            t(33) = km(10)*(s(4,cc) + s(5,cc)) + km(14)*(s(6,cc) + s(7,cc))
            t(34) = km(14)*(s(8,cc) + s(9,cc))
            t(35) = km(14)*s(7,cc)
            t(36) = km(14)*s(9,cc)
            t(37) = km(14)*(s(2,cc) + s(12,cc) + s(13,cc))
            t(38) = km(12)*s(7,cc)
            t(39) = km(3)*s(2,cc) + km(4)*s(1,cc)
            t(40) = km(6)*s(7,cc)
            t(41) = km(6)*(s(1,cc) + s(10,cc) + s(11,cc))
            t(42) = km(11)*(s(6,cc) + s(7,cc))
            t(43) = km(2)*s(1,cc) + km(8)*(s(2,cc) + s(13,cc))
            t(44) = km(11)*s(7,cc) - km(12)*s(7,cc)
            t(45) = km(10)*s(1,cc) + km(14)*(s(2,cc) + s(13,cc))
            t(46) = km(4)*s(7,cc) - km(6)*s(7,cc)
            t(47) = km(10)*(s(4,cc) + s(5,cc)) + km(14)*(s(6,cc) + 3.0_dp*s(7,cc) + s(14,cc) + &
               s(15,cc))
            t(48) = km(4)*(s(1,cc) + s(10,cc) + s(11,cc)) + km(6)*(-s(1,cc) - s(10,cc) - s(11,cc))
            do ck = 1, nck
               r(1:48,cc,ck) = r(1:48,cc,ck) + kcd(ck,kq)*t(1:48)
            end do
         end do
      end do
      res = 0.0_dp
      if (.not. any) return
      cm(1) = Rs*Rs
      cm(2) = 1.0_dp
      cm(3) = Rs
      cm(4) = Rs*Rs*cy
      cm(5) = cy
      cm(6) = Rs*cy
      cm(7) = Rs*cy*cy
      cm(8) = cy*cy
      cm(9) = Rs*Rc
      cm(10) = Rc
      cm(11) = Rs*Rc*cy
      cm(12) = Rc*cy
      cm(13) = cy*cy*cy
      cm(14) = Rc*cy*cy
      cm(15) = Rc*Rc
      cm(16) = Rc*Rc*cy
      do ck = 1, nck
         do cc = 1, ncb
            res(1,cc+ncb*(ck-1)) = cm(1)*r(1,cc,ck) - r(2,cc,ck) + cm(3)*r(3,cc,ck)
            res(2,cc+ncb*(ck-1)) = cm(4)*r(4,cc,ck) - cm(5)*r(5,cc,ck) + cm(6)*r(6,cc,ck)
            res(3,cc+ncb*(ck-1)) = -cm(1)*r(7,cc,ck) + r(8,cc,ck) - cm(3)*r(9,cc,ck)
            res(4,cc+ncb*(ck-1)) = -cm(5)*r(10,cc,ck) + cm(6)*r(11,cc,ck)
            res(5,cc+ncb*(ck-1)) = -r(12,cc,ck) + cm(3)*r(13,cc,ck) + cm(7)*r(14,cc,ck) - &
               cm(8)*r(15,cc,ck)
            res(6,cc+ncb*(ck-1)) = cm(5)*r(16,cc,ck) - cm(6)*r(17,cc,ck)
            res(7,cc+ncb*(ck-1)) = r(18,cc,ck) - cm(3)*r(19,cc,ck) + cm(9)*r(1,cc,ck) - &
               cm(10)*r(20,cc,ck)
            res(8,cc+ncb*(ck-1)) = cm(5)*r(21,cc,ck) - cm(6)*r(22,cc,ck) + cm(11)*r(4,cc,ck) - &
               cm(12)*r(23,cc,ck)
            res(9,cc+ncb*(ck-1)) = -r(24,cc,ck) + cm(3)*r(25,cc,ck) - cm(9)*r(7,cc,ck) + &
               cm(10)*r(26,cc,ck)
            res(10,cc+ncb*(ck-1)) = -cm(5)*r(10,cc,ck) - cm(6)*r(23,cc,ck)
            res(11,cc+ncb*(ck-1)) = -r(12,cc,ck) - cm(3)*r(27,cc,ck) - cm(7)*r(28,cc,ck) - &
               cm(8)*r(15,cc,ck)
            res(12,cc+ncb*(ck-1)) = cm(5)*r(16,cc,ck) + cm(6)*r(29,cc,ck)
            res(13,cc+ncb*(ck-1)) = -r(30,cc,ck) - cm(8)*r(15,cc,ck)
            res(14,cc+ncb*(ck-1)) = -cm(5)*r(31,cc,ck) - cm(13)*r(32,cc,ck)
            res(15,cc+ncb*(ck-1)) = r(33,cc,ck) + cm(8)*r(34,cc,ck)
            res(16,cc+ncb*(ck-1)) = cm(5)*r(21,cc,ck) - cm(12)*r(23,cc,ck)
            res(17,cc+ncb*(ck-1)) = r(35,cc,ck) + cm(8)*r(36,cc,ck) - cm(10)*r(27,cc,ck) - &
               cm(14)*r(28,cc,ck)
            res(18,cc+ncb*(ck-1)) = -cm(5)*r(37,cc,ck) + cm(12)*r(29,cc,ck)
            res(19,cc+ncb*(ck-1)) = r(18,cc,ck) + cm(3)*r(38,cc,ck) + cm(9)*r(1,cc,ck) + &
               cm(10)*r(39,cc,ck)
            res(20,cc+ncb*(ck-1)) = cm(5)*r(21,cc,ck) + cm(6)*r(40,cc,ck) + cm(11)*r(4,cc,ck) + &
               cm(12)*r(11,cc,ck)
            res(21,cc+ncb*(ck-1)) = -r(24,cc,ck) - cm(3)*r(41,cc,ck) - cm(9)*r(7,cc,ck) - &
               cm(10)*r(42,cc,ck)
            res(22,cc+ncb*(ck-1)) = cm(5)*r(21,cc,ck) + cm(12)*r(11,cc,ck)
            res(23,cc+ncb*(ck-1)) = r(35,cc,ck) + cm(8)*r(36,cc,ck) + cm(10)*r(13,cc,ck) + &
               cm(14)*r(14,cc,ck)
            res(24,cc+ncb*(ck-1)) = -cm(5)*r(37,cc,ck) - cm(12)*r(17,cc,ck)
            res(25,cc+ncb*(ck-1)) = -r(43,cc,ck) - cm(10)*r(44,cc,ck) + cm(15)*r(1,cc,ck)
            res(26,cc+ncb*(ck-1)) = -cm(5)*r(45,cc,ck) - cm(12)*r(46,cc,ck) + cm(16)*r(4,cc,ck)
            res(27,cc+ncb*(ck-1)) = r(47,cc,ck) + cm(10)*r(48,cc,ck) - cm(15)*r(7,cc,ck)
         end do
      end do
   end subroutine rotaxis_sppp

end module rotaxis_sppp_m
