! GENERATED by scripts/rotaxis_mmd -- do not edit.
! sdLL: L=4 comps=96 S=34 g=4 r=174 (terms 559) km=29 cm=22 assembly terms=264
module rotaxis_sdLL_m
   use cint_const, only: dp
   use cint_rotaxis_boys, only: boys
   implicit none
   private
   public :: rotaxis_sdLL
contains
   ! (sd|LL)  L=4: 34 bra accumulators, 174 ket accumulators, 96 components
   subroutine rotaxis_sdLL(nbra, ncb, bp, kab, nket, nck, kp, kcd, gc, cutoff, res, any)
      integer,  intent(in)  :: nbra, ncb, nket, nck
      real(dp), intent(in)  :: bp(5, nbra), kab(1*ncb, nbra)
      real(dp), intent(in)  :: kp(7, nket), kcd(4*nck, nket), gc(3), cutoff
      real(dp), intent(out) :: res(96, ncb*nck)
      logical,  intent(out) :: any
      real(dp) :: s(34, ncb), r(174, ncb, nck), t(174)
      real(dp) :: f(0:4), b(0:4)
      real(dp) :: p, ip, za, zb, eab, q, iq, yc, yd, ax, az, ecd
      real(dp) :: zq, alpha, tt, w, m2a, Rs, Rc, cy
      real(dp) :: g(4), km(29), cm(22), zq2, zq3, zq4
      integer :: kq, bq, cc, ck, n

      Rs = gc(1); Rc = gc(2); cy = gc(3)
      any = .false.
      r = 0.0_dp
      do kq = 1, nket
         q = kp(1,kq); iq = kp(2,kq); yc = kp(3,kq); yd = kp(4,kq)
         ax = kp(5,kq); az = kp(6,kq); ecd = kp(7,kq)
         s = 0.0_dp
         do bq = 1, nbra
            eab = bp(5,bq)
            if (eab + ecd > cutoff) cycle
            any = .true.
            p = bp(1,bq); ip = bp(2,bq); za = bp(3,bq); zb = bp(4,bq)
            zq = za - az
            alpha = p*q/(p + q)
            tt = alpha*(ax*ax + cy*cy + zq*zq)
            call boys(f, tt, 4)
            w = 1.0_dp/sqrt(p + q)
            m2a = -2.0_dp*alpha
            do n = 0, 4
               b(n) = w*f(n)
               w = w*m2a
            end do
            zq2 = zq*zq
            zq3 = zq2*zq
            zq4 = zq3*zq
            g(1) = ip
            g(2) = ip*ip
            g(3) = ip*zb
            g(4) = zb*zb
            do cc = 1, ncb
               s(1,cc) = s(1,cc) + kab(cc,bq)*g(1)*b(0)
               s(2,cc) = s(2,cc) + kab(cc,bq)*g(2)*b(2)
               s(3,cc) = s(3,cc) + kab(cc,bq)*g(2)*b(1)
               s(4,cc) = s(4,cc) + kab(cc,bq)*g(3)*b(1)
               s(5,cc) = s(5,cc) + kab(cc,bq)*g(2)*b(2)*zq
               s(6,cc) = s(6,cc) + kab(cc,bq)*g(4)*b(0)
               s(7,cc) = s(7,cc) + kab(cc,bq)*g(3)*b(1)*zq
               s(8,cc) = s(8,cc) + kab(cc,bq)*g(2)*b(2)*zq2
               s(9,cc) = s(9,cc) + kab(cc,bq)*g(1)*b(1)
               s(10,cc) = s(10,cc) + kab(cc,bq)*g(2)*b(3)
               s(11,cc) = s(11,cc) + kab(cc,bq)*g(3)*b(2)
               s(12,cc) = s(12,cc) + kab(cc,bq)*g(2)*b(3)*zq
               s(13,cc) = s(13,cc) + kab(cc,bq)*g(4)*b(1)
               s(14,cc) = s(14,cc) + kab(cc,bq)*g(3)*b(2)*zq
               s(15,cc) = s(15,cc) + kab(cc,bq)*g(2)*b(3)*zq2
               s(16,cc) = s(16,cc) + kab(cc,bq)*g(1)*b(1)*zq
               s(17,cc) = s(17,cc) + kab(cc,bq)*g(4)*b(1)*zq
               s(18,cc) = s(18,cc) + kab(cc,bq)*g(3)*b(2)*zq2
               s(19,cc) = s(19,cc) + kab(cc,bq)*g(2)*b(3)*zq3
               s(20,cc) = s(20,cc) + kab(cc,bq)*g(1)*b(2)
               s(21,cc) = s(21,cc) + kab(cc,bq)*g(2)*b(4)
               s(22,cc) = s(22,cc) + kab(cc,bq)*g(3)*b(3)
               s(23,cc) = s(23,cc) + kab(cc,bq)*g(2)*b(4)*zq
               s(24,cc) = s(24,cc) + kab(cc,bq)*g(4)*b(2)
               s(25,cc) = s(25,cc) + kab(cc,bq)*g(3)*b(3)*zq
               s(26,cc) = s(26,cc) + kab(cc,bq)*g(2)*b(4)*zq2
               s(27,cc) = s(27,cc) + kab(cc,bq)*g(1)*b(2)*zq
               s(28,cc) = s(28,cc) + kab(cc,bq)*g(4)*b(2)*zq
               s(29,cc) = s(29,cc) + kab(cc,bq)*g(3)*b(3)*zq2
               s(30,cc) = s(30,cc) + kab(cc,bq)*g(2)*b(4)*zq3
               s(31,cc) = s(31,cc) + kab(cc,bq)*g(1)*b(2)*zq2
               s(32,cc) = s(32,cc) + kab(cc,bq)*g(4)*b(2)*zq2
               s(33,cc) = s(33,cc) + kab(cc,bq)*g(3)*b(3)*zq3
               s(34,cc) = s(34,cc) + kab(cc,bq)*g(2)*b(4)*zq4
            end do
         end do
         if (.not. any) cycle
         km(1) = 1.0_dp
         km(2) = ax*ax
         km(3) = ax
         km(4) = yd
         km(5) = iq*ax
         km(6) = yd*ax*ax
         km(7) = iq*ax*ax*ax
         km(8) = yd*ax
         km(9) = iq*ax*ax
         km(10) = iq
         km(11) = yc
         km(12) = yc*ax*ax
         km(13) = yc*ax
         km(14) = yc*yd
         km(15) = iq*yc*ax
         km(16) = iq*yd*ax
         km(17) = iq*iq*ax*ax
         km(18) = iq*iq
         km(19) = yc*yd*ax*ax
         km(20) = iq*yc*ax*ax*ax
         km(21) = iq*yd*ax*ax*ax
         km(22) = iq*iq*ax*ax*ax*ax
         km(23) = yc*yd*ax
         km(24) = iq*yc*ax*ax
         km(25) = iq*yc
         km(26) = iq*yd*ax*ax
         km(27) = iq*yd
         km(28) = iq*iq*ax*ax*ax
         km(29) = iq*iq*ax
         do cc = 1, ncb
            t(1) = (s(1,cc) + s(3,cc)) + km(2)*s(2,cc)
            t(2) = km(3)*s(2,cc)
            t(3) = km(3)*(s(4,cc) + s(5,cc))
            t(4) = (s(1,cc) + s(3,cc))
            t(5) = s(2,cc)
            t(6) = (s(4,cc) + s(5,cc))
            t(7) = (s(1,cc) + s(3,cc) + s(6,cc) + 2.0_dp*s(7,cc) + s(8,cc))
            t(8) = km(5)*(s(2,cc) + (1.0_dp/3.0_dp)*s(9,cc)) + (1.0_dp/3.0_dp)*km(7)*s(10,cc)
            t(9) = km(4)*(s(1,cc) + s(3,cc)) + km(6)*s(2,cc)
            t(10) = km(9)*s(10,cc) + km(10)*s(2,cc)
            t(11) = km(8)*s(2,cc)
            t(12) = km(9)*(s(11,cc) + s(12,cc)) + km(10)*(s(4,cc) + s(5,cc))
            t(13) = km(8)*(s(4,cc) + s(5,cc))
            t(14) = km(5)*(s(2,cc) + s(9,cc))
            t(15) = km(5)*s(10,cc)
            t(16) = km(4)*(s(1,cc) + s(3,cc))
            t(17) = km(4)*s(2,cc)
            t(18) = km(5)*(s(11,cc) + s(12,cc))
            t(19) = km(4)*(s(4,cc) + s(5,cc))
            t(20) = km(5)*(s(2,cc) + s(9,cc) + s(13,cc) + 2.0_dp*s(14,cc) + s(15,cc))
            t(21) = km(4)*(s(1,cc) + s(3,cc) + s(6,cc) + 2.0_dp*s(7,cc) + s(8,cc))
            t(22) = km(9)*s(10,cc) + km(10)*(s(2,cc) + s(9,cc))
            t(23) = km(5)*s(2,cc)
            t(24) = km(10)*(s(2,cc) + (1.0_dp/3.0_dp)*s(9,cc))
            t(25) = km(10)*s(10,cc)
            t(26) = km(10)*(s(4,cc) + s(5,cc))
            t(27) = km(10)*(s(11,cc) + s(12,cc))
            t(28) = km(10)*(s(2,cc) + s(9,cc) + s(13,cc) + 2.0_dp*s(14,cc) + s(15,cc))
            t(29) = km(9)*s(12,cc) + km(10)*(s(5,cc) + s(16,cc))
            t(30) = km(5)*s(12,cc)
            t(31) = km(5)*(s(2,cc) + s(14,cc) + s(15,cc))
            t(32) = km(10)*(s(5,cc) + s(16,cc))
            t(33) = km(10)*s(12,cc)
            t(34) = km(10)*(s(2,cc) + s(14,cc) + s(15,cc))
            t(35) = km(10)*(s(4,cc) + (3.0_dp/2.0_dp)*s(5,cc) + (1.0_dp/2.0_dp)*s(16,cc) + &
               (1.0_dp/2.0_dp)*s(17,cc) + s(18,cc) + (1.0_dp/2.0_dp)*s(19,cc))
            t(36) = km(5)*(s(2,cc) + (1.0_dp/3.0_dp)*s(9,cc)) + (1.0_dp/3.0_dp)*km(7)*s(10,cc)
            t(37) = km(11)*(s(1,cc) + s(3,cc)) + km(12)*s(2,cc)
            t(38) = km(9)*s(10,cc) + km(10)*s(2,cc)
            t(39) = km(13)*s(2,cc)
            t(40) = km(9)*(s(11,cc) + s(12,cc)) + km(10)*(s(4,cc) + s(5,cc))
            t(41) = km(13)*(s(4,cc) + s(5,cc))
            t(42) = km(5)*(s(2,cc) + s(9,cc))
            t(43) = km(5)*s(10,cc)
            t(44) = km(11)*(s(1,cc) + s(3,cc))
            t(45) = km(11)*s(2,cc)
            t(46) = km(5)*(s(11,cc) + s(12,cc))
            t(47) = km(11)*(s(4,cc) + s(5,cc))
            t(48) = km(5)*(s(2,cc) + s(9,cc) + s(13,cc) + 2.0_dp*s(14,cc) + s(15,cc))
            t(49) = km(11)*(s(1,cc) + s(3,cc) + s(6,cc) + 2.0_dp*s(7,cc) + s(8,cc))
            t(50) = km(9)*s(2,cc) + km(10)*(s(1,cc) + s(3,cc)) + km(17)*(6.0_dp*s(10,cc) + &
               s(20,cc)) + km(18)*(3.0_dp*s(2,cc) + s(9,cc)) + km(22)*s(21,cc)
            t(51) = km(15)*(s(2,cc) + (1.0_dp/3.0_dp)*s(9,cc)) + km(16)*(-s(2,cc) + &
               (-1.0_dp/3.0_dp)*s(9,cc)) + (1.0_dp/3.0_dp)*km(20)*s(10,cc) + &
               (-1.0_dp/3.0_dp)*km(21)*s(10,cc)
            t(52) = km(14)*(s(1,cc) + s(3,cc)) + km(19)*s(2,cc)
            t(53) = km(5)*s(2,cc) + km(28)*s(21,cc) + 3.0_dp*km(29)*s(10,cc)
            t(54) = km(24)*s(10,cc) + km(25)*s(2,cc) - km(26)*s(10,cc) - km(27)*s(2,cc)
            t(55) = km(23)*s(2,cc)
            t(56) = km(5)*(s(4,cc) + s(5,cc)) + km(28)*(s(22,cc) + s(23,cc)) + &
               km(29)*(3.0_dp*s(11,cc) + 3.0_dp*s(12,cc))
            t(57) = km(24)*(s(11,cc) + s(12,cc)) + km(25)*(s(4,cc) + s(5,cc)) + km(26)*(-s(11,cc) - &
               s(12,cc)) + km(27)*(-s(4,cc) - s(5,cc))
            t(58) = km(23)*(s(4,cc) + s(5,cc))
            t(59) = km(10)*(s(1,cc) + s(3,cc)) + km(17)*(s(10,cc) + s(20,cc)) + km(18)*(s(2,cc) + &
               s(9,cc))
            t(60) = km(10)*s(2,cc) + km(17)*s(21,cc) + km(18)*s(10,cc)
            t(61) = km(15)*(s(2,cc) + s(9,cc)) + km(16)*(-s(2,cc) - s(9,cc))
            t(62) = km(15)*s(10,cc) - km(16)*s(10,cc)
            t(63) = km(14)*(s(1,cc) + s(3,cc))
            t(64) = km(14)*s(2,cc)
            t(65) = km(10)*(s(4,cc) + s(5,cc)) + km(17)*(s(22,cc) + s(23,cc)) + km(18)*(s(11,cc) + &
               s(12,cc))
            t(66) = km(15)*(s(11,cc) + s(12,cc)) + km(16)*(-s(11,cc) - s(12,cc))
            t(67) = km(14)*(s(4,cc) + s(5,cc))
            t(68) = km(10)*(s(1,cc) + s(3,cc) + s(6,cc) + 2.0_dp*s(7,cc) + s(8,cc)) + &
               km(17)*(s(10,cc) + s(20,cc) + s(24,cc) + 2.0_dp*s(25,cc) + s(26,cc)) + &
               km(18)*(s(2,cc) + s(9,cc) + s(13,cc) + 2.0_dp*s(14,cc) + s(15,cc))
            t(69) = km(15)*(s(2,cc) + s(9,cc) + s(13,cc) + 2.0_dp*s(14,cc) + s(15,cc)) + &
               km(16)*(-s(2,cc) - s(9,cc) - s(13,cc) + (-2.0_dp)*s(14,cc) - s(15,cc))
            t(70) = km(14)*(s(1,cc) + s(3,cc) + s(6,cc) + 2.0_dp*s(7,cc) + s(8,cc))
            t(71) = km(28)*s(21,cc) + km(29)*(3.0_dp*s(10,cc) + s(20,cc))
            t(72) = km(24)*s(10,cc) + km(25)*(s(2,cc) + s(9,cc))
            t(73) = km(17)*s(10,cc) + km(18)*s(2,cc)
            t(74) = km(17)*s(21,cc) + km(18)*s(10,cc)
            t(75) = km(15)*s(2,cc)
            t(76) = km(15)*s(10,cc)
            t(77) = km(17)*(s(22,cc) + s(23,cc)) + km(18)*(s(11,cc) + s(12,cc))
            t(78) = km(15)*(s(11,cc) + s(12,cc))
            t(79) = km(29)*(s(10,cc) + (1.0_dp/3.0_dp)*s(20,cc))
            t(80) = km(25)*(s(2,cc) + (1.0_dp/3.0_dp)*s(9,cc))
            t(81) = km(29)*s(21,cc)
            t(82) = km(25)*s(10,cc)
            t(83) = km(29)*(s(11,cc) + s(12,cc))
            t(84) = km(29)*(s(22,cc) + s(23,cc))
            t(85) = km(25)*(s(4,cc) + s(5,cc))
            t(86) = km(25)*(s(11,cc) + s(12,cc))
            t(87) = km(29)*(s(10,cc) + s(20,cc) + s(24,cc) + 2.0_dp*s(25,cc) + s(26,cc))
            t(88) = km(25)*(s(2,cc) + s(9,cc) + s(13,cc) + 2.0_dp*s(14,cc) + s(15,cc))
            t(89) = km(28)*s(23,cc) + km(29)*(3.0_dp*s(12,cc) + s(27,cc))
            t(90) = km(24)*s(12,cc) + km(25)*(s(5,cc) + s(16,cc))
            t(91) = km(16)*(s(2,cc) + (1.0_dp/3.0_dp)*s(9,cc)) + (1.0_dp/3.0_dp)*km(21)*s(10,cc)
            t(92) = km(17)*s(23,cc) + km(18)*s(12,cc)
            t(93) = km(15)*s(12,cc)
            t(94) = km(26)*s(10,cc) + km(27)*s(2,cc)
            t(95) = km(17)*(s(10,cc) + s(25,cc) + s(26,cc)) + km(18)*(s(2,cc) + s(14,cc) + &
               s(15,cc))
            t(96) = km(15)*(s(2,cc) + s(14,cc) + s(15,cc))
            t(97) = km(26)*(s(11,cc) + s(12,cc)) + km(27)*(s(4,cc) + s(5,cc))
            t(98) = km(29)*(s(12,cc) + s(27,cc))
            t(99) = km(29)*s(23,cc)
            t(100) = km(25)*(s(5,cc) + s(16,cc))
            t(101) = km(25)*s(12,cc)
            t(102) = km(16)*(s(2,cc) + s(9,cc))
            t(103) = km(16)*s(10,cc)
            t(104) = km(29)*(s(10,cc) + s(25,cc) + s(26,cc))
            t(105) = km(25)*(s(2,cc) + s(14,cc) + s(15,cc))
            t(106) = km(16)*(s(11,cc) + s(12,cc))
            t(107) = km(29)*(s(11,cc) + (3.0_dp/2.0_dp)*s(12,cc) + (1.0_dp/2.0_dp)*s(27,cc) + &
               (1.0_dp/2.0_dp)*s(28,cc) + s(29,cc) + (1.0_dp/2.0_dp)*s(30,cc))
            t(108) = km(25)*(s(4,cc) + (3.0_dp/2.0_dp)*s(5,cc) + (1.0_dp/2.0_dp)*s(16,cc) + &
               (1.0_dp/2.0_dp)*s(17,cc) + s(18,cc) + (1.0_dp/2.0_dp)*s(19,cc))
            t(109) = km(16)*(s(2,cc) + s(9,cc) + s(13,cc) + 2.0_dp*s(14,cc) + s(15,cc))
            t(110) = km(9)*s(10,cc) + km(10)*(s(2,cc) + s(9,cc))
            t(111) = km(5)*s(2,cc)
            t(112) = km(10)*(s(2,cc) + (1.0_dp/3.0_dp)*s(9,cc))
            t(113) = km(10)*s(10,cc)
            t(114) = km(10)*(s(4,cc) + s(5,cc))
            t(115) = km(10)*(s(11,cc) + s(12,cc))
            t(116) = km(10)*(s(2,cc) + s(9,cc) + s(13,cc) + 2.0_dp*s(14,cc) + s(15,cc))
            t(117) = km(26)*s(10,cc) + km(27)*(s(2,cc) + s(9,cc))
            t(118) = km(16)*s(2,cc)
            t(119) = km(27)*(s(2,cc) + (1.0_dp/3.0_dp)*s(9,cc))
            t(120) = km(27)*s(10,cc)
            t(121) = km(27)*(s(4,cc) + s(5,cc))
            t(122) = km(27)*(s(11,cc) + s(12,cc))
            t(123) = km(27)*(s(2,cc) + s(9,cc) + s(13,cc) + 2.0_dp*s(14,cc) + s(15,cc))
            t(124) = km(9)*s(2,cc) + km(10)*(s(1,cc) + s(3,cc)) + km(17)*s(10,cc) + km(18)*(s(2,cc) &
               + s(9,cc))
            t(125) = km(17)*s(21,cc) + km(18)*(s(10,cc) + s(20,cc))
            t(126) = km(5)*s(2,cc) + 3.0_dp*km(29)*s(10,cc)
            t(127) = km(5)*(s(4,cc) + s(5,cc)) + km(29)*(s(11,cc) + s(12,cc))
            t(128) = km(10)*(s(1,cc) + s(3,cc)) + km(18)*(3.0_dp*s(2,cc) + s(9,cc))
            t(129) = km(10)*s(2,cc) + km(18)*(6.0_dp*s(10,cc) + s(20,cc))
            t(130) = km(18)*s(21,cc)
            t(131) = km(10)*(s(4,cc) + s(5,cc)) + km(18)*(3.0_dp*s(11,cc) + 3.0_dp*s(12,cc))
            t(132) = km(18)*(s(22,cc) + s(23,cc))
            t(133) = km(10)*(s(1,cc) + s(3,cc) + s(6,cc) + 2.0_dp*s(7,cc) + s(8,cc)) + &
               km(18)*(s(2,cc) + s(9,cc) + s(13,cc) + 2.0_dp*s(14,cc) + s(15,cc))
            t(134) = km(18)*(s(10,cc) + s(20,cc) + s(24,cc) + 2.0_dp*s(25,cc) + s(26,cc))
            t(135) = km(17)*s(23,cc) + km(18)*(s(12,cc) + s(27,cc))
            t(136) = km(29)*s(12,cc)
            t(137) = km(18)*(s(12,cc) + (1.0_dp/3.0_dp)*s(27,cc))
            t(138) = km(18)*s(23,cc)
            t(139) = km(18)*(s(2,cc) + s(14,cc) + s(15,cc))
            t(140) = km(18)*(s(10,cc) + s(25,cc) + s(26,cc))
            t(141) = km(18)*(s(11,cc) + (3.0_dp/2.0_dp)*s(12,cc) + (1.0_dp/2.0_dp)*s(27,cc) + &
               (1.0_dp/2.0_dp)*s(28,cc) + s(29,cc) + (1.0_dp/2.0_dp)*s(30,cc))
            t(142) = km(9)*s(12,cc) + km(10)*(s(5,cc) + s(16,cc))
            t(143) = km(5)*s(12,cc)
            t(144) = km(5)*(s(2,cc) + s(14,cc) + s(15,cc))
            t(145) = km(10)*(s(5,cc) + s(16,cc))
            t(146) = km(10)*s(12,cc)
            t(147) = km(10)*(s(2,cc) + s(14,cc) + s(15,cc))
            t(148) = km(10)*(s(4,cc) + (3.0_dp/2.0_dp)*s(5,cc) + (1.0_dp/2.0_dp)*s(16,cc) + &
               (1.0_dp/2.0_dp)*s(17,cc) + s(18,cc) + (1.0_dp/2.0_dp)*s(19,cc))
            t(149) = km(26)*s(12,cc) + km(27)*(s(5,cc) + s(16,cc))
            t(150) = km(15)*(s(2,cc) + (1.0_dp/3.0_dp)*s(9,cc)) + (1.0_dp/3.0_dp)*km(20)*s(10,cc)
            t(151) = km(16)*s(12,cc)
            t(152) = km(24)*s(10,cc) + km(25)*s(2,cc)
            t(153) = km(16)*(s(2,cc) + s(14,cc) + s(15,cc))
            t(154) = km(24)*(s(11,cc) + s(12,cc)) + km(25)*(s(4,cc) + s(5,cc))
            t(155) = km(27)*(s(5,cc) + s(16,cc))
            t(156) = km(27)*s(12,cc)
            t(157) = km(15)*(s(2,cc) + s(9,cc))
            t(158) = km(27)*(s(2,cc) + s(14,cc) + s(15,cc))
            t(159) = km(27)*(s(4,cc) + (3.0_dp/2.0_dp)*s(5,cc) + (1.0_dp/2.0_dp)*s(16,cc) + &
               (1.0_dp/2.0_dp)*s(17,cc) + s(18,cc) + (1.0_dp/2.0_dp)*s(19,cc))
            t(160) = km(15)*(s(2,cc) + s(9,cc) + s(13,cc) + 2.0_dp*s(14,cc) + s(15,cc))
            t(161) = km(9)*s(2,cc) + km(10)*(s(1,cc) + s(3,cc)) + km(17)*(s(10,cc) + s(26,cc)) + &
               km(18)*(s(2,cc) + s(9,cc) + s(15,cc) + s(31,cc))
            t(162) = km(24)*s(12,cc) + km(25)*(s(5,cc) + s(16,cc)) - km(26)*s(12,cc) + &
               km(27)*(-s(5,cc) - s(16,cc))
            t(163) = km(5)*s(2,cc) + km(29)*(s(10,cc) + s(26,cc))
            t(164) = km(15)*s(12,cc) - km(16)*s(12,cc)
            t(165) = km(5)*(s(4,cc) + s(5,cc)) + km(29)*(s(11,cc) + 3.0_dp*s(12,cc) + s(29,cc) + &
               s(30,cc))
            t(166) = km(15)*(s(2,cc) + s(14,cc) + s(15,cc)) + km(16)*(-s(2,cc) - s(14,cc) - &
               s(15,cc))
            t(167) = km(10)*(s(1,cc) + s(3,cc)) + km(18)*(s(2,cc) + s(9,cc) + s(15,cc) + s(31,cc))
            t(168) = km(10)*s(2,cc) + km(18)*(s(10,cc) + s(26,cc))
            t(169) = km(25)*(s(5,cc) + s(16,cc)) + km(27)*(-s(5,cc) - s(16,cc))
            t(170) = km(25)*s(12,cc) - km(27)*s(12,cc)
            t(171) = km(10)*(s(4,cc) + s(5,cc)) + km(18)*(s(11,cc) + 3.0_dp*s(12,cc) + s(29,cc) + &
               s(30,cc))
            t(172) = km(25)*(s(2,cc) + s(14,cc) + s(15,cc)) + km(27)*(-s(2,cc) - s(14,cc) - &
               s(15,cc))
            t(173) = km(10)*(s(1,cc) + s(3,cc) + s(6,cc) + 2.0_dp*s(7,cc) + s(8,cc)) + &
               km(18)*(3.0_dp*s(2,cc) + s(9,cc) + s(13,cc) + 6.0_dp*s(14,cc) + 6.0_dp*s(15,cc) + &
               s(31,cc) + s(32,cc) + 2.0_dp*s(33,cc) + s(34,cc))
            t(174) = km(25)*(s(4,cc) + (3.0_dp/2.0_dp)*s(5,cc) + (1.0_dp/2.0_dp)*s(16,cc) + &
               (1.0_dp/2.0_dp)*s(17,cc) + s(18,cc) + (1.0_dp/2.0_dp)*s(19,cc)) + km(27)*(-s(4,cc) + &
               (-3.0_dp/2.0_dp)*s(5,cc) + (-1.0_dp/2.0_dp)*s(16,cc) + (-1.0_dp/2.0_dp)*s(17,cc) - &
               s(18,cc) + (-1.0_dp/2.0_dp)*s(19,cc))
            do ck = 1, nck
               r(1:7,cc,ck) = r(1:7,cc,ck) + kcd(1+4*(ck-1),kq)*t(1:7)
               r(8:35,cc,ck) = r(8:35,cc,ck) + kcd(2+4*(ck-1),kq)*t(8:35)
               r(36:49,cc,ck) = r(36:49,cc,ck) + kcd(3+4*(ck-1),kq)*t(36:49)
               r(110:116,cc,ck) = r(110:116,cc,ck) + kcd(3+4*(ck-1),kq)*t(110:116)
               r(142:148,cc,ck) = r(142:148,cc,ck) + kcd(3+4*(ck-1),kq)*t(142:148)
               r(50:109,cc,ck) = r(50:109,cc,ck) + kcd(4+4*(ck-1),kq)*t(50:109)
               r(117:141,cc,ck) = r(117:141,cc,ck) + kcd(4+4*(ck-1),kq)*t(117:141)
               r(149:174,cc,ck) = r(149:174,cc,ck) + kcd(4+4*(ck-1),kq)*t(149:174)
            end do
         end do
      end do
      res = 0.0_dp
      if (.not. any) return
      cm(1) = 1.0_dp
      cm(2) = cy
      cm(3) = cy*cy
      cm(4) = Rs
      cm(5) = Rs*cy
      cm(6) = Rs*cy*cy
      cm(7) = cy*cy*cy
      cm(8) = Rc
      cm(9) = Rc*cy
      cm(10) = Rc*cy*cy
      cm(11) = Rs*Rs
      cm(12) = Rs*Rs*cy
      cm(13) = Rs*Rs*cy*cy
      cm(14) = Rs*cy*cy*cy
      cm(15) = Rs*Rc
      cm(16) = Rs*Rc*cy
      cm(17) = Rs*Rc*cy*cy
      cm(18) = cy*cy*cy*cy
      cm(19) = Rc*cy*cy*cy
      cm(20) = Rc*Rc
      cm(21) = Rc*Rc*cy
      cm(22) = Rc*Rc*cy*cy
      do ck = 1, nck
         do cc = 1, ncb
            res(1,cc+ncb*(ck-1)) = r(1,cc,ck)
            res(2,cc+ncb*(ck-1)) = cm(2)*r(2,cc,ck)
            res(3,cc+ncb*(ck-1)) = -r(3,cc,ck)
            res(4,cc+ncb*(ck-1)) = r(4,cc,ck) + cm(3)*r(5,cc,ck)
            res(5,cc+ncb*(ck-1)) = -cm(2)*r(6,cc,ck)
            res(6,cc+ncb*(ck-1)) = r(7,cc,ck)
            res(7,cc+ncb*(ck-1)) = 3.0_dp*r(8,cc,ck) + cm(4)*r(9,cc,ck)
            res(8,cc+ncb*(ck-1)) = cm(2)*r(10,cc,ck) + cm(5)*r(11,cc,ck)
            res(9,cc+ncb*(ck-1)) = -r(12,cc,ck) - cm(4)*r(13,cc,ck)
            res(10,cc+ncb*(ck-1)) = r(14,cc,ck) + cm(3)*r(15,cc,ck) + cm(4)*r(16,cc,ck) + &
               cm(6)*r(17,cc,ck)
            res(11,cc+ncb*(ck-1)) = -cm(2)*r(18,cc,ck) - cm(5)*r(19,cc,ck)
            res(12,cc+ncb*(ck-1)) = r(20,cc,ck) + cm(4)*r(21,cc,ck)
            res(13,cc+ncb*(ck-1)) = cm(2)*r(22,cc,ck)
            res(14,cc+ncb*(ck-1)) = r(23,cc,ck) + cm(3)*r(15,cc,ck)
            res(15,cc+ncb*(ck-1)) = -cm(2)*r(18,cc,ck)
            res(16,cc+ncb*(ck-1)) = 3.0_dp*cm(2)*r(24,cc,ck) + cm(7)*r(25,cc,ck)
            res(17,cc+ncb*(ck-1)) = -r(26,cc,ck) - cm(3)*r(27,cc,ck)
            res(18,cc+ncb*(ck-1)) = cm(2)*r(28,cc,ck)
            res(19,cc+ncb*(ck-1)) = -r(29,cc,ck) + cm(8)*r(9,cc,ck)
            res(20,cc+ncb*(ck-1)) = -cm(2)*r(30,cc,ck) + cm(9)*r(11,cc,ck)
            res(21,cc+ncb*(ck-1)) = r(31,cc,ck) - cm(8)*r(13,cc,ck)
            res(22,cc+ncb*(ck-1)) = -r(32,cc,ck) - cm(3)*r(33,cc,ck) + cm(8)*r(16,cc,ck) + &
               cm(10)*r(17,cc,ck)
            res(23,cc+ncb*(ck-1)) = cm(2)*r(34,cc,ck) - cm(9)*r(19,cc,ck)
            res(24,cc+ncb*(ck-1)) = (-2.0_dp)*r(35,cc,ck) + cm(8)*r(21,cc,ck)
            res(25,cc+ncb*(ck-1)) = 3.0_dp*r(36,cc,ck) - cm(4)*r(37,cc,ck)
            res(26,cc+ncb*(ck-1)) = cm(2)*r(38,cc,ck) - cm(5)*r(39,cc,ck)
            res(27,cc+ncb*(ck-1)) = -r(40,cc,ck) + cm(4)*r(41,cc,ck)
            res(28,cc+ncb*(ck-1)) = r(42,cc,ck) + cm(3)*r(43,cc,ck) - cm(4)*r(44,cc,ck) - &
               cm(6)*r(45,cc,ck)
            res(29,cc+ncb*(ck-1)) = -cm(2)*r(46,cc,ck) + cm(5)*r(47,cc,ck)
            res(30,cc+ncb*(ck-1)) = r(48,cc,ck) - cm(4)*r(49,cc,ck)
            res(31,cc+ncb*(ck-1)) = r(50,cc,ck) + (-3.0_dp)*cm(4)*r(51,cc,ck) - cm(11)*r(52,cc,ck)
            res(32,cc+ncb*(ck-1)) = cm(2)*r(53,cc,ck) - cm(5)*r(54,cc,ck) - cm(12)*r(55,cc,ck)
            res(33,cc+ncb*(ck-1)) = -r(56,cc,ck) + cm(4)*r(57,cc,ck) + cm(11)*r(58,cc,ck)
            res(34,cc+ncb*(ck-1)) = r(59,cc,ck) + cm(3)*r(60,cc,ck) - cm(4)*r(61,cc,ck) - &
               cm(6)*r(62,cc,ck) - cm(11)*r(63,cc,ck) - cm(13)*r(64,cc,ck)
            res(35,cc+ncb*(ck-1)) = -cm(2)*r(65,cc,ck) + cm(5)*r(66,cc,ck) + cm(12)*r(67,cc,ck)
            res(36,cc+ncb*(ck-1)) = r(68,cc,ck) - cm(4)*r(69,cc,ck) - cm(11)*r(70,cc,ck)
            res(37,cc+ncb*(ck-1)) = cm(2)*r(71,cc,ck) - cm(5)*r(72,cc,ck)
            res(38,cc+ncb*(ck-1)) = r(73,cc,ck) + cm(3)*r(74,cc,ck) - cm(4)*r(75,cc,ck) - &
               cm(6)*r(76,cc,ck)
            res(39,cc+ncb*(ck-1)) = -cm(2)*r(77,cc,ck) + cm(5)*r(78,cc,ck)
            res(40,cc+ncb*(ck-1)) = 3.0_dp*cm(2)*r(79,cc,ck) + (-3.0_dp)*cm(5)*r(80,cc,ck) + &
               cm(7)*r(81,cc,ck) - cm(14)*r(82,cc,ck)
            res(41,cc+ncb*(ck-1)) = -r(83,cc,ck) - cm(3)*r(84,cc,ck) + cm(4)*r(85,cc,ck) + &
               cm(6)*r(86,cc,ck)
            res(42,cc+ncb*(ck-1)) = cm(2)*r(87,cc,ck) - cm(5)*r(88,cc,ck)
            res(43,cc+ncb*(ck-1)) = -r(89,cc,ck) + cm(4)*r(90,cc,ck) + 3.0_dp*cm(8)*r(91,cc,ck) - &
               cm(15)*r(52,cc,ck)
            res(44,cc+ncb*(ck-1)) = -cm(2)*r(92,cc,ck) + cm(5)*r(93,cc,ck) + cm(9)*r(94,cc,ck) - &
               cm(16)*r(55,cc,ck)
            res(45,cc+ncb*(ck-1)) = r(95,cc,ck) - cm(4)*r(96,cc,ck) - cm(8)*r(97,cc,ck) + &
               cm(15)*r(58,cc,ck)
            res(46,cc+ncb*(ck-1)) = -r(98,cc,ck) - cm(3)*r(99,cc,ck) + cm(4)*r(100,cc,ck) + &
               cm(6)*r(101,cc,ck) + cm(8)*r(102,cc,ck) + cm(10)*r(103,cc,ck) - cm(15)*r(63,cc,ck) - &
               cm(17)*r(64,cc,ck)
            res(47,cc+ncb*(ck-1)) = cm(2)*r(104,cc,ck) - cm(5)*r(105,cc,ck) - cm(9)*r(106,cc,ck) + &
               cm(16)*r(67,cc,ck)
            res(48,cc+ncb*(ck-1)) = (-2.0_dp)*r(107,cc,ck) + 2.0_dp*cm(4)*r(108,cc,ck) + &
               cm(8)*r(109,cc,ck) - cm(15)*r(70,cc,ck)
            res(49,cc+ncb*(ck-1)) = cm(2)*r(110,cc,ck)
            res(50,cc+ncb*(ck-1)) = r(111,cc,ck) + cm(3)*r(43,cc,ck)
            res(51,cc+ncb*(ck-1)) = -cm(2)*r(46,cc,ck)
            res(52,cc+ncb*(ck-1)) = 3.0_dp*cm(2)*r(112,cc,ck) + cm(7)*r(113,cc,ck)
            res(53,cc+ncb*(ck-1)) = -r(114,cc,ck) - cm(3)*r(115,cc,ck)
            res(54,cc+ncb*(ck-1)) = cm(2)*r(116,cc,ck)
            res(55,cc+ncb*(ck-1)) = cm(2)*r(71,cc,ck) + cm(5)*r(117,cc,ck)
            res(56,cc+ncb*(ck-1)) = r(73,cc,ck) + cm(3)*r(74,cc,ck) + cm(4)*r(118,cc,ck) + &
               cm(6)*r(103,cc,ck)
            res(57,cc+ncb*(ck-1)) = -cm(2)*r(77,cc,ck) - cm(5)*r(106,cc,ck)
            res(58,cc+ncb*(ck-1)) = 3.0_dp*cm(2)*r(79,cc,ck) + 3.0_dp*cm(5)*r(119,cc,ck) + &
               cm(7)*r(81,cc,ck) + cm(14)*r(120,cc,ck)
            res(59,cc+ncb*(ck-1)) = -r(83,cc,ck) - cm(3)*r(84,cc,ck) - cm(4)*r(121,cc,ck) - &
               cm(6)*r(122,cc,ck)
            res(60,cc+ncb*(ck-1)) = cm(2)*r(87,cc,ck) + cm(5)*r(123,cc,ck)
            res(61,cc+ncb*(ck-1)) = r(124,cc,ck) + cm(3)*r(125,cc,ck)
            res(62,cc+ncb*(ck-1)) = cm(2)*r(126,cc,ck) + cm(7)*r(81,cc,ck)
            res(63,cc+ncb*(ck-1)) = -r(127,cc,ck) - cm(3)*r(84,cc,ck)
            res(64,cc+ncb*(ck-1)) = r(128,cc,ck) + cm(3)*r(129,cc,ck) + cm(18)*r(130,cc,ck)
            res(65,cc+ncb*(ck-1)) = -cm(2)*r(131,cc,ck) - cm(7)*r(132,cc,ck)
            res(66,cc+ncb*(ck-1)) = r(133,cc,ck) + cm(3)*r(134,cc,ck)
            res(67,cc+ncb*(ck-1)) = -cm(2)*r(135,cc,ck) + cm(9)*r(117,cc,ck)
            res(68,cc+ncb*(ck-1)) = -r(136,cc,ck) - cm(3)*r(99,cc,ck) + cm(8)*r(118,cc,ck) + &
               cm(10)*r(103,cc,ck)
            res(69,cc+ncb*(ck-1)) = cm(2)*r(104,cc,ck) - cm(9)*r(106,cc,ck)
            res(70,cc+ncb*(ck-1)) = (-3.0_dp)*cm(2)*r(137,cc,ck) - cm(7)*r(138,cc,ck) + &
               3.0_dp*cm(9)*r(119,cc,ck) + cm(19)*r(120,cc,ck)
            res(71,cc+ncb*(ck-1)) = r(139,cc,ck) + cm(3)*r(140,cc,ck) - cm(8)*r(121,cc,ck) - &
               cm(10)*r(122,cc,ck)
            res(72,cc+ncb*(ck-1)) = (-2.0_dp)*cm(2)*r(141,cc,ck) + cm(9)*r(123,cc,ck)
            res(73,cc+ncb*(ck-1)) = -r(142,cc,ck) - cm(8)*r(37,cc,ck)
            res(74,cc+ncb*(ck-1)) = -cm(2)*r(143,cc,ck) - cm(9)*r(39,cc,ck)
            res(75,cc+ncb*(ck-1)) = r(144,cc,ck) + cm(8)*r(41,cc,ck)
            res(76,cc+ncb*(ck-1)) = -r(145,cc,ck) - cm(3)*r(146,cc,ck) - cm(8)*r(44,cc,ck) - &
               cm(10)*r(45,cc,ck)
            res(77,cc+ncb*(ck-1)) = cm(2)*r(147,cc,ck) + cm(9)*r(47,cc,ck)
            res(78,cc+ncb*(ck-1)) = (-2.0_dp)*r(148,cc,ck) - cm(8)*r(49,cc,ck)
            res(79,cc+ncb*(ck-1)) = -r(89,cc,ck) - cm(4)*r(149,cc,ck) + &
               (-3.0_dp)*cm(8)*r(150,cc,ck) - cm(15)*r(52,cc,ck)
            res(80,cc+ncb*(ck-1)) = -cm(2)*r(92,cc,ck) - cm(5)*r(151,cc,ck) - cm(9)*r(152,cc,ck) - &
               cm(16)*r(55,cc,ck)
            res(81,cc+ncb*(ck-1)) = r(95,cc,ck) + cm(4)*r(153,cc,ck) + cm(8)*r(154,cc,ck) + &
               cm(15)*r(58,cc,ck)
            res(82,cc+ncb*(ck-1)) = -r(98,cc,ck) - cm(3)*r(99,cc,ck) - cm(4)*r(155,cc,ck) - &
               cm(6)*r(156,cc,ck) - cm(8)*r(157,cc,ck) - cm(10)*r(76,cc,ck) - cm(15)*r(63,cc,ck) - &
               cm(17)*r(64,cc,ck)
            res(83,cc+ncb*(ck-1)) = cm(2)*r(104,cc,ck) + cm(5)*r(158,cc,ck) + cm(9)*r(78,cc,ck) + &
               cm(16)*r(67,cc,ck)
            res(84,cc+ncb*(ck-1)) = (-2.0_dp)*r(107,cc,ck) + (-2.0_dp)*cm(4)*r(159,cc,ck) - &
               cm(8)*r(160,cc,ck) - cm(15)*r(70,cc,ck)
            res(85,cc+ncb*(ck-1)) = -cm(2)*r(135,cc,ck) - cm(9)*r(72,cc,ck)
            res(86,cc+ncb*(ck-1)) = -r(136,cc,ck) - cm(3)*r(99,cc,ck) - cm(8)*r(75,cc,ck) - &
               cm(10)*r(76,cc,ck)
            res(87,cc+ncb*(ck-1)) = cm(2)*r(104,cc,ck) + cm(9)*r(78,cc,ck)
            res(88,cc+ncb*(ck-1)) = (-3.0_dp)*cm(2)*r(137,cc,ck) - cm(7)*r(138,cc,ck) + &
               (-3.0_dp)*cm(9)*r(80,cc,ck) - cm(19)*r(82,cc,ck)
            res(89,cc+ncb*(ck-1)) = r(139,cc,ck) + cm(3)*r(140,cc,ck) + cm(8)*r(85,cc,ck) + &
               cm(10)*r(86,cc,ck)
            res(90,cc+ncb*(ck-1)) = (-2.0_dp)*cm(2)*r(141,cc,ck) - cm(9)*r(88,cc,ck)
            res(91,cc+ncb*(ck-1)) = r(161,cc,ck) + cm(8)*r(162,cc,ck) - cm(20)*r(52,cc,ck)
            res(92,cc+ncb*(ck-1)) = cm(2)*r(163,cc,ck) + cm(9)*r(164,cc,ck) - cm(21)*r(55,cc,ck)
            res(93,cc+ncb*(ck-1)) = -r(165,cc,ck) - cm(8)*r(166,cc,ck) + cm(20)*r(58,cc,ck)
            res(94,cc+ncb*(ck-1)) = r(167,cc,ck) + cm(3)*r(168,cc,ck) + cm(8)*r(169,cc,ck) + &
               cm(10)*r(170,cc,ck) - cm(20)*r(63,cc,ck) - cm(22)*r(64,cc,ck)
            res(95,cc+ncb*(ck-1)) = -cm(2)*r(171,cc,ck) - cm(9)*r(172,cc,ck) + cm(21)*r(67,cc,ck)
            res(96,cc+ncb*(ck-1)) = r(173,cc,ck) + 2.0_dp*cm(8)*r(174,cc,ck) - cm(20)*r(70,cc,ck)
         end do
      end do
   end subroutine rotaxis_sdLL

end module rotaxis_sdLL_m
