! GENERATED by scripts/rotaxis_mmd -- do not edit.
! spLL: L=3 comps=48 S=15 g=2 r=75 (terms 144) km=21 cm=16 assembly terms=115
module rotaxis_spLL_m
   use cint_const, only: dp
   use cint_rotaxis_boys, only: boys
   implicit none
   private
   public :: rotaxis_spLL
contains
   ! (sp|LL)  L=3: 15 bra accumulators, 75 ket accumulators, 48 components
   subroutine rotaxis_spLL(nbra, ncb, bp, kab, nket, nck, kp, kcd, gc, cutoff, res, any)
      integer,  intent(in)  :: nbra, ncb, nket, nck
      real(dp), intent(in)  :: bp(5, nbra), kab(1*ncb, nbra)
      real(dp), intent(in)  :: kp(7, nket), kcd(4*nck, nket), gc(3), cutoff
      real(dp), intent(out) :: res(48, ncb*nck)
      logical,  intent(out) :: any
      real(dp) :: s(15, ncb), r(75, ncb, nck), t(75)
      real(dp) :: f(0:3), b(0:3)
      real(dp) :: p, ip, za, zb, eab, q, iq, yc, yd, ax, az, ecd
      real(dp) :: zq, alpha, tt, w, m2a, Rs, Rc, cy
      real(dp) :: g(2), km(21), cm(16), zq2, zq3
      integer :: kq, bq, cc, ck, n

      Rs = gc(1); Rc = gc(2); cy = gc(3)
      any = .false.
      r = 0.0_dp
      do kq = 1, nket
         q = kp(1,kq); iq = kp(2,kq); yc = kp(3,kq); yd = kp(4,kq)
         ax = kp(5,kq); az = kp(6,kq); ecd = kp(7,kq)
         s = 0.0_dp
         do bq = 1, nbra
            eab = bp(5,bq)
            if (eab + ecd > cutoff) cycle
            any = .true.
            p = bp(1,bq); ip = bp(2,bq); za = bp(3,bq); zb = bp(4,bq)
            zq = za - az
            alpha = p*q/(p + q)
            tt = alpha*(ax*ax + cy*cy + zq*zq)
            call boys(f, tt, 3)
            w = 1.0_dp/sqrt(p + q)
            m2a = -2.0_dp*alpha
            do n = 0, 3
               b(n) = w*f(n)
               w = w*m2a
            end do
            zq2 = zq*zq
            zq3 = zq2*zq
            g(1) = ip
            g(2) = zb
            do cc = 1, ncb
               s(1,cc) = s(1,cc) + kab(cc,bq)*g(1)*b(1)
               s(2,cc) = s(2,cc) + kab(cc,bq)*g(2)*b(0)
               s(3,cc) = s(3,cc) + kab(cc,bq)*g(1)*b(1)*zq
               s(4,cc) = s(4,cc) + kab(cc,bq)*g(1)*b(2)
               s(5,cc) = s(5,cc) + kab(cc,bq)*g(2)*b(1)
               s(6,cc) = s(6,cc) + kab(cc,bq)*g(1)*b(2)*zq
               s(7,cc) = s(7,cc) + kab(cc,bq)*g(2)*b(1)*zq
               s(8,cc) = s(8,cc) + kab(cc,bq)*g(1)*b(2)*zq2
               s(9,cc) = s(9,cc) + kab(cc,bq)*g(1)*b(3)
               s(10,cc) = s(10,cc) + kab(cc,bq)*g(2)*b(2)
               s(11,cc) = s(11,cc) + kab(cc,bq)*g(1)*b(3)*zq
               s(12,cc) = s(12,cc) + kab(cc,bq)*g(2)*b(2)*zq
               s(13,cc) = s(13,cc) + kab(cc,bq)*g(1)*b(3)*zq2
               s(14,cc) = s(14,cc) + kab(cc,bq)*g(2)*b(2)*zq2
               s(15,cc) = s(15,cc) + kab(cc,bq)*g(1)*b(3)*zq3
            end do
         end do
         if (.not. any) cycle
         km(1) = ax
         km(2) = 1.0_dp
         km(3) = yd*ax
         km(4) = iq*ax*ax
         km(5) = iq
         km(6) = yd
         km(7) = iq*ax
         km(8) = yc*ax
         km(9) = yc
         km(10) = yc*yd*ax
         km(11) = iq*yc*ax*ax
         km(12) = iq*yc
         km(13) = iq*yd*ax*ax
         km(14) = iq*yd
         km(15) = iq*iq*ax*ax*ax
         km(16) = iq*iq*ax
         km(17) = yc*yd
         km(18) = iq*yc*ax
         km(19) = iq*yd*ax
         km(20) = iq*iq*ax*ax
         km(21) = iq*iq
         do cc = 1, ncb
            t(1) = km(1)*s(1,cc)
            t(2) = s(1,cc)
            t(3) = (s(2,cc) + s(3,cc))
            t(4) = km(4)*s(4,cc) + km(5)*s(1,cc)
            t(5) = km(3)*s(1,cc)
            t(6) = km(7)*s(4,cc)
            t(7) = km(6)*s(1,cc)
            t(8) = km(7)*(s(5,cc) + s(6,cc))
            t(9) = km(6)*(s(2,cc) + s(3,cc))
            t(10) = km(5)*s(1,cc)
            t(11) = km(5)*s(4,cc)
            t(12) = km(5)*(s(5,cc) + s(6,cc))
            t(13) = km(7)*s(6,cc)
            t(14) = km(5)*s(6,cc)
            t(15) = km(5)*(s(1,cc) + s(7,cc) + s(8,cc))
            t(16) = km(4)*s(4,cc) + km(5)*s(1,cc)
            t(17) = km(8)*s(1,cc)
            t(18) = km(7)*s(4,cc)
            t(19) = km(9)*s(1,cc)
            t(20) = km(7)*(s(5,cc) + s(6,cc))
            t(21) = km(9)*(s(2,cc) + s(3,cc))
            t(22) = km(7)*s(1,cc) + km(15)*s(9,cc) + 3.0_dp*km(16)*s(4,cc)
            t(23) = km(11)*s(4,cc) + km(12)*s(1,cc) - km(13)*s(4,cc) - km(14)*s(1,cc)
            t(24) = km(10)*s(1,cc)
            t(25) = km(5)*s(1,cc) + km(20)*s(9,cc) + km(21)*s(4,cc)
            t(26) = km(18)*s(4,cc) - km(19)*s(4,cc)
            t(27) = km(17)*s(1,cc)
            t(28) = km(5)*(s(2,cc) + s(3,cc)) + km(20)*(s(10,cc) + s(11,cc)) + km(21)*(s(5,cc) + &
               s(6,cc))
            t(29) = km(18)*(s(5,cc) + s(6,cc)) + km(19)*(-s(5,cc) - s(6,cc))
            t(30) = km(17)*(s(2,cc) + s(3,cc))
            t(31) = km(20)*s(9,cc) + km(21)*s(4,cc)
            t(32) = km(18)*s(4,cc)
            t(33) = km(16)*s(4,cc)
            t(34) = km(12)*s(1,cc)
            t(35) = km(16)*s(9,cc)
            t(36) = km(12)*s(4,cc)
            t(37) = km(16)*(s(10,cc) + s(11,cc))
            t(38) = km(12)*(s(5,cc) + s(6,cc))
            t(39) = km(20)*s(11,cc) + km(21)*s(6,cc)
            t(40) = km(18)*s(6,cc)
            t(41) = km(13)*s(4,cc) + km(14)*s(1,cc)
            t(42) = km(16)*s(11,cc)
            t(43) = km(12)*s(6,cc)
            t(44) = km(19)*s(4,cc)
            t(45) = km(16)*(s(4,cc) + s(12,cc) + s(13,cc))
            t(46) = km(12)*(s(1,cc) + s(7,cc) + s(8,cc))
            t(47) = km(19)*(s(5,cc) + s(6,cc))
            t(48) = km(5)*s(1,cc)
            t(49) = km(5)*s(4,cc)
            t(50) = km(5)*(s(5,cc) + s(6,cc))
            t(51) = km(14)*s(1,cc)
            t(52) = km(14)*s(4,cc)
            t(53) = km(14)*(s(5,cc) + s(6,cc))
            t(54) = km(7)*s(1,cc) + km(16)*s(4,cc)
            t(55) = km(5)*s(1,cc) + 3.0_dp*km(21)*s(4,cc)
            t(56) = km(21)*s(9,cc)
            t(57) = km(5)*(s(2,cc) + s(3,cc)) + km(21)*(s(5,cc) + s(6,cc))
            t(58) = km(21)*(s(10,cc) + s(11,cc))
            t(59) = km(21)*s(6,cc)
            t(60) = km(21)*s(11,cc)
            t(61) = km(21)*(s(4,cc) + s(12,cc) + s(13,cc))
            t(62) = km(7)*s(6,cc)
            t(63) = km(5)*s(6,cc)
            t(64) = km(5)*(s(1,cc) + s(7,cc) + s(8,cc))
            t(65) = km(19)*s(6,cc)
            t(66) = km(11)*s(4,cc) + km(12)*s(1,cc)
            t(67) = km(14)*s(6,cc)
            t(68) = km(14)*(s(1,cc) + s(7,cc) + s(8,cc))
            t(69) = km(18)*(s(5,cc) + s(6,cc))
            t(70) = km(7)*s(1,cc) + km(16)*(s(4,cc) + s(13,cc))
            t(71) = km(18)*s(6,cc) - km(19)*s(6,cc)
            t(72) = km(5)*s(1,cc) + km(21)*(s(4,cc) + s(13,cc))
            t(73) = km(12)*s(6,cc) - km(14)*s(6,cc)
            t(74) = km(5)*(s(2,cc) + s(3,cc)) + km(21)*(s(5,cc) + 3.0_dp*s(6,cc) + s(14,cc) + &
               s(15,cc))
            t(75) = km(12)*(s(1,cc) + s(7,cc) + s(8,cc)) + km(14)*(-s(1,cc) - s(7,cc) - s(8,cc))
            do ck = 1, nck
               r(1:3,cc,ck) = r(1:3,cc,ck) + kcd(1+4*(ck-1),kq)*t(1:3)
               r(4:15,cc,ck) = r(4:15,cc,ck) + kcd(2+4*(ck-1),kq)*t(4:15)
               r(16:21,cc,ck) = r(16:21,cc,ck) + kcd(3+4*(ck-1),kq)*t(16:21)
               r(48:50,cc,ck) = r(48:50,cc,ck) + kcd(3+4*(ck-1),kq)*t(48:50)
               r(62:64,cc,ck) = r(62:64,cc,ck) + kcd(3+4*(ck-1),kq)*t(62:64)
               r(22:47,cc,ck) = r(22:47,cc,ck) + kcd(4+4*(ck-1),kq)*t(22:47)
               r(51:61,cc,ck) = r(51:61,cc,ck) + kcd(4+4*(ck-1),kq)*t(51:61)
               r(65:75,cc,ck) = r(65:75,cc,ck) + kcd(4+4*(ck-1),kq)*t(65:75)
            end do
         end do
      end do
      res = 0.0_dp
      if (.not. any) return
      cm(1) = 1.0_dp
      cm(2) = cy
      cm(3) = Rs
      cm(4) = Rs*cy
      cm(5) = cy*cy
      cm(6) = Rc
      cm(7) = Rc*cy
      cm(8) = Rs*Rs
      cm(9) = Rs*Rs*cy
      cm(10) = Rs*cy*cy
      cm(11) = Rs*Rc
      cm(12) = Rs*Rc*cy
      cm(13) = cy*cy*cy
      cm(14) = Rc*cy*cy
      cm(15) = Rc*Rc
      cm(16) = Rc*Rc*cy
      do ck = 1, nck
         do cc = 1, ncb
            res(1,cc+ncb*(ck-1)) = -r(1,cc,ck)
            res(2,cc+ncb*(ck-1)) = -cm(2)*r(2,cc,ck)
            res(3,cc+ncb*(ck-1)) = r(3,cc,ck)
            res(4,cc+ncb*(ck-1)) = -r(4,cc,ck) - cm(3)*r(5,cc,ck)
            res(5,cc+ncb*(ck-1)) = -cm(2)*r(6,cc,ck) - cm(4)*r(7,cc,ck)
            res(6,cc+ncb*(ck-1)) = r(8,cc,ck) + cm(3)*r(9,cc,ck)
            res(7,cc+ncb*(ck-1)) = -cm(2)*r(6,cc,ck)
            res(8,cc+ncb*(ck-1)) = -r(10,cc,ck) - cm(5)*r(11,cc,ck)
            res(9,cc+ncb*(ck-1)) = cm(2)*r(12,cc,ck)
            res(10,cc+ncb*(ck-1)) = r(13,cc,ck) - cm(6)*r(5,cc,ck)
            res(11,cc+ncb*(ck-1)) = cm(2)*r(14,cc,ck) - cm(7)*r(7,cc,ck)
            res(12,cc+ncb*(ck-1)) = -r(15,cc,ck) + cm(6)*r(9,cc,ck)
            res(13,cc+ncb*(ck-1)) = -r(16,cc,ck) + cm(3)*r(17,cc,ck)
            res(14,cc+ncb*(ck-1)) = -cm(2)*r(18,cc,ck) + cm(4)*r(19,cc,ck)
            res(15,cc+ncb*(ck-1)) = r(20,cc,ck) - cm(3)*r(21,cc,ck)
            res(16,cc+ncb*(ck-1)) = -r(22,cc,ck) + cm(3)*r(23,cc,ck) + cm(8)*r(24,cc,ck)
            res(17,cc+ncb*(ck-1)) = -cm(2)*r(25,cc,ck) + cm(4)*r(26,cc,ck) + cm(9)*r(27,cc,ck)
            res(18,cc+ncb*(ck-1)) = r(28,cc,ck) - cm(3)*r(29,cc,ck) - cm(8)*r(30,cc,ck)
            res(19,cc+ncb*(ck-1)) = -cm(2)*r(31,cc,ck) + cm(4)*r(32,cc,ck)
            res(20,cc+ncb*(ck-1)) = -r(33,cc,ck) + cm(3)*r(34,cc,ck) - cm(5)*r(35,cc,ck) + &
               cm(10)*r(36,cc,ck)
            res(21,cc+ncb*(ck-1)) = cm(2)*r(37,cc,ck) - cm(4)*r(38,cc,ck)
            res(22,cc+ncb*(ck-1)) = r(39,cc,ck) - cm(3)*r(40,cc,ck) - cm(6)*r(41,cc,ck) + &
               cm(11)*r(24,cc,ck)
            res(23,cc+ncb*(ck-1)) = cm(2)*r(42,cc,ck) - cm(4)*r(43,cc,ck) - cm(7)*r(44,cc,ck) + &
               cm(12)*r(27,cc,ck)
            res(24,cc+ncb*(ck-1)) = -r(45,cc,ck) + cm(3)*r(46,cc,ck) + cm(6)*r(47,cc,ck) - &
               cm(11)*r(30,cc,ck)
            res(25,cc+ncb*(ck-1)) = -cm(2)*r(18,cc,ck)
            res(26,cc+ncb*(ck-1)) = -r(48,cc,ck) - cm(5)*r(49,cc,ck)
            res(27,cc+ncb*(ck-1)) = cm(2)*r(50,cc,ck)
            res(28,cc+ncb*(ck-1)) = -cm(2)*r(31,cc,ck) - cm(4)*r(44,cc,ck)
            res(29,cc+ncb*(ck-1)) = -r(33,cc,ck) - cm(3)*r(51,cc,ck) - cm(5)*r(35,cc,ck) - &
               cm(10)*r(52,cc,ck)
            res(30,cc+ncb*(ck-1)) = cm(2)*r(37,cc,ck) + cm(4)*r(53,cc,ck)
            res(31,cc+ncb*(ck-1)) = -r(54,cc,ck) - cm(5)*r(35,cc,ck)
            res(32,cc+ncb*(ck-1)) = -cm(2)*r(55,cc,ck) - cm(13)*r(56,cc,ck)
            res(33,cc+ncb*(ck-1)) = r(57,cc,ck) + cm(5)*r(58,cc,ck)
            res(34,cc+ncb*(ck-1)) = cm(2)*r(42,cc,ck) - cm(7)*r(44,cc,ck)
            res(35,cc+ncb*(ck-1)) = r(59,cc,ck) + cm(5)*r(60,cc,ck) - cm(6)*r(51,cc,ck) - &
               cm(14)*r(52,cc,ck)
            res(36,cc+ncb*(ck-1)) = -cm(2)*r(61,cc,ck) + cm(7)*r(53,cc,ck)
            res(37,cc+ncb*(ck-1)) = r(62,cc,ck) + cm(6)*r(17,cc,ck)
            res(38,cc+ncb*(ck-1)) = cm(2)*r(63,cc,ck) + cm(7)*r(19,cc,ck)
            res(39,cc+ncb*(ck-1)) = -r(64,cc,ck) - cm(6)*r(21,cc,ck)
            res(40,cc+ncb*(ck-1)) = r(39,cc,ck) + cm(3)*r(65,cc,ck) + cm(6)*r(66,cc,ck) + &
               cm(11)*r(24,cc,ck)
            res(41,cc+ncb*(ck-1)) = cm(2)*r(42,cc,ck) + cm(4)*r(67,cc,ck) + cm(7)*r(32,cc,ck) + &
               cm(12)*r(27,cc,ck)
            res(42,cc+ncb*(ck-1)) = -r(45,cc,ck) - cm(3)*r(68,cc,ck) - cm(6)*r(69,cc,ck) - &
               cm(11)*r(30,cc,ck)
            res(43,cc+ncb*(ck-1)) = cm(2)*r(42,cc,ck) + cm(7)*r(32,cc,ck)
            res(44,cc+ncb*(ck-1)) = r(59,cc,ck) + cm(5)*r(60,cc,ck) + cm(6)*r(34,cc,ck) + &
               cm(14)*r(36,cc,ck)
            res(45,cc+ncb*(ck-1)) = -cm(2)*r(61,cc,ck) - cm(7)*r(38,cc,ck)
            res(46,cc+ncb*(ck-1)) = -r(70,cc,ck) - cm(6)*r(71,cc,ck) + cm(15)*r(24,cc,ck)
            res(47,cc+ncb*(ck-1)) = -cm(2)*r(72,cc,ck) - cm(7)*r(73,cc,ck) + cm(16)*r(27,cc,ck)
            res(48,cc+ncb*(ck-1)) = r(74,cc,ck) + cm(6)*r(75,cc,ck) - cm(15)*r(30,cc,ck)
         end do
      end do
   end subroutine rotaxis_spLL

end module rotaxis_spLL_m
