! GENERATED by scripts/rotaxis_mmd -- do not edit.
! sssL: L=1 comps=4 S=3 g=1 r=5 (terms 5) km=4 cm=4 assembly terms=6
module rotaxis_sssL_m
   use cint_const, only: dp
   use cint_rotaxis_boys, only: boys
   implicit none
   private
   public :: rotaxis_sssL
contains
   ! (ss|sL)  L=1: 3 bra accumulators, 5 ket accumulators, 4 components
   subroutine rotaxis_sssL(nbra, ncb, bp, kab, nket, nck, kp, kcd, gc, cutoff, res, any)
      integer,  intent(in)  :: nbra, ncb, nket, nck
      real(dp), intent(in)  :: bp(5, nbra), kab(1*ncb, nbra)
      real(dp), intent(in)  :: kp(7, nket), kcd(2*nck, nket), gc(3), cutoff
      real(dp), intent(out) :: res(4, ncb*nck)
      logical,  intent(out) :: any
      real(dp) :: s(3, ncb), r(5, ncb, nck), t(5)
      real(dp) :: f(0:1), b(0:1)
      real(dp) :: p, ip, za, zb, eab, q, iq, yc, yd, ax, az, ecd
      real(dp) :: zq, alpha, tt, w, m2a, Rs, Rc, cy
      real(dp) :: g(1), km(4), cm(4)
      integer :: kq, bq, cc, ck, n

      Rs = gc(1); Rc = gc(2); cy = gc(3)
      any = .false.
      r = 0.0_dp
      do kq = 1, nket
         q = kp(1,kq); iq = kp(2,kq); yc = kp(3,kq); yd = kp(4,kq)
         ax = kp(5,kq); az = kp(6,kq); ecd = kp(7,kq)
         s = 0.0_dp
         do bq = 1, nbra
            eab = bp(5,bq)
            if (eab + ecd > cutoff) cycle
            any = .true.
            p = bp(1,bq); ip = bp(2,bq); za = bp(3,bq); zb = bp(4,bq)
            zq = za - az
            alpha = p*q/(p + q)
            tt = alpha*(ax*ax + cy*cy + zq*zq)
            call boys(f, tt, 1)
            w = 1.0_dp/sqrt(p + q)
            m2a = -2.0_dp*alpha
            do n = 0, 1
               b(n) = w*f(n)
               w = w*m2a
            end do
            g(1) = 1.0_dp
            do cc = 1, ncb
               s(1,cc) = s(1,cc) + kab(cc,bq)*b(0)
               s(2,cc) = s(2,cc) + kab(cc,bq)*b(1)
               s(3,cc) = s(3,cc) + kab(cc,bq)*b(1)*zq
            end do
         end do
         if (.not. any) cycle
         km(1) = 1.0_dp
         km(2) = yc
         km(3) = iq*ax
         km(4) = iq
         do cc = 1, ncb
            t(1) = s(1,cc)
            t(2) = km(3)*s(2,cc)
            t(3) = km(2)*s(1,cc)
            t(4) = km(4)*s(2,cc)
            t(5) = km(4)*s(3,cc)
            do ck = 1, nck
               r(1:1,cc,ck) = r(1:1,cc,ck) + kcd(1+2*(ck-1),kq)*t(1:1)
               r(2:5,cc,ck) = r(2:5,cc,ck) + kcd(2+2*(ck-1),kq)*t(2:5)
            end do
         end do
      end do
      res = 0.0_dp
      if (.not. any) return
      cm(1) = 1.0_dp
      cm(2) = Rs
      cm(3) = cy
      cm(4) = Rc
      do ck = 1, nck
         do cc = 1, ncb
            res(1,cc+ncb*(ck-1)) = r(1,cc,ck)
            res(2,cc+ncb*(ck-1)) = r(2,cc,ck) - cm(2)*r(3,cc,ck)
            res(3,cc+ncb*(ck-1)) = cm(3)*r(4,cc,ck)
            res(4,cc+ncb*(ck-1)) = -r(5,cc,ck) - cm(4)*r(3,cc,ck)
         end do
      end do
   end subroutine rotaxis_sssL

end module rotaxis_sssL_m
