! GENERATED by scripts/hgp -- do not edit.
! ssss: vrr=1 carried=1 hrr=1 in 1 block(s) comps=1
module hgp_ssss_m
   use cint_const, only: dp
   ! the same guarded Boys the rotated-axis kernels use: libcint's
   ! closed form cancels for F_1 at a tiny argument.
   use cint_rotaxis_boys, only: boys
   implicit none
   private
   public :: hgp_ssss
   real(dp), parameter :: PI = 3.14159265358979323846_dp
   real(dp), parameter :: TWO_PI_52 = 2.0_dp*PI**2*sqrt(PI)
contains
   ! (ss|ss)  ssss: vrr=1 carried=1 hrr=1 in 1 block(s) comps=1
   subroutine hgp_ssss(nbra, ncb, bp, kab, nket, nck, kp, kcd, ab, cd, cutoff, res, any)
      integer,  intent(in)  :: nbra, ncb, nket, nck
      real(dp), intent(in)  :: bp(10, nbra), kab(1*ncb, nbra)
      real(dp), intent(in)  :: kp(10, nket), kcd(1*nck, nket)
      real(dp), intent(in)  :: ab(3), cd(3), cutoff
      real(dp), intent(out) :: res(1, ncb*nck)
      logical,  intent(out) :: any
      real(dp) :: c(1, 1*ncb, 1*nck)
      real(dp) :: t(1), tv(1), f(0:0), b(0:0)
      real(dp) :: p, q, pq, rho, oo2p, oo2q, oo2pq, rp, rq, tt, w, eab, ecd
      real(dp) :: PA0, PA1, PA2, QC0, QC1, QC2, WP0, WP1, WP2, WQ0, WQ1, WQ2
      real(dp) :: PQ0, PQ1, PQ2, AB0, AB1, AB2, CD0, CD1, CD2, wq_, wp_
      real(dp) :: h(1)
      integer  :: kq, bq, bc, kc, cc, ck, n, col

      AB0 = ab(1); AB1 = ab(2); AB2 = ab(3)
      CD0 = cd(1); CD1 = cd(2); CD2 = cd(3)
      any = .false.
      c = 0.0_dp
      do kq = 1, nket
         q = kp(1,kq); oo2q = kp(2,kq)
         QC0 = kp(3,kq); QC1 = kp(4,kq); QC2 = kp(5,kq)
         ecd = kp(10,kq)
         do bq = 1, nbra
            eab = bp(10,bq)
            if (eab + ecd > cutoff) cycle
            any = .true.
            p = bp(1,bq); oo2p = bp(2,bq)
            PA0 = bp(3,bq); PA1 = bp(4,bq); PA2 = bp(5,bq)
            PQ0 = bp(6,bq) - kp(6,kq)
            PQ1 = bp(7,bq) - kp(7,kq)
            PQ2 = bp(8,bq) - kp(8,kq)
            pq = p + q
            rho = p*q/pq
            oo2pq = 0.5_dp/pq
            rp = rho/p; rq = rho/q
            ! W - P = (q/(p+q)) (Q - P), W - Q = (p/(p+q)) (P - Q)
            wp_ = -q/pq; wq_ = p/pq
            WP0 = wp_*PQ0; WP1 = wp_*PQ1; WP2 = wp_*PQ2
            WQ0 = wq_*PQ0; WQ1 = wq_*PQ1; WQ2 = wq_*PQ2
            tt = rho*(PQ0*PQ0 + PQ1*PQ1 + PQ2*PQ2)
            call boys(f, tt, 0)
            w = TWO_PI_52*bp(9,bq)*kp(9,kq)/sqrt(pq)
            do n = 0, 0
               b(n) = w*f(n)
            end do
            t(1) = b(0)
            tv(1) = t(1)
            do kc = 1, 1*nck
               do bc = 1, 1*ncb
                  c(1:1,bc,kc) = c(1:1,bc,kc) + kab(bc,bq)*kcd(kc,kq)*tv(1:1)
               end do
            end do
         end do
      end do
      res = 0.0_dp
      if (.not. any) return
      do ck = 1, nck
         do cc = 1, ncb
            col = cc + ncb*(ck-1)
            bc = cc; kc = ck
            h(1) = c(1,bc,kc)
            res(1,col) = h(1)
         end do
      end do
   end subroutine hgp_ssss
end module hgp_ssss_m
