! GENERATED by scripts/hgp -- do not edit.
! ppss: vrr=15 carried=9 hrr=18 in 1 block(s) comps=9
module hgp_ppss_m
   use cint_const, only: dp
   ! the same guarded Boys the rotated-axis kernels use: libcint's
   ! closed form cancels for F_1 at a tiny argument.
   use cint_rotaxis_boys, only: boys
   implicit none
   private
   public :: hgp_ppss
   real(dp), parameter :: PI = 3.14159265358979323846_dp
   real(dp), parameter :: TWO_PI_52 = 2.0_dp*PI**2*sqrt(PI)
contains
   ! (pp|ss)  ppss: vrr=15 carried=9 hrr=18 in 1 block(s) comps=9
   subroutine hgp_ppss(nbra, ncb, bp, kab, nket, nck, kp, kcd, ab, cd, cutoff, res, any)
      integer,  intent(in)  :: nbra, ncb, nket, nck
      real(dp), intent(in)  :: bp(10, nbra), kab(1*ncb, nbra)
      real(dp), intent(in)  :: kp(10, nket), kcd(1*nck, nket)
      real(dp), intent(in)  :: ab(3), cd(3), cutoff
      real(dp), intent(out) :: res(9, ncb*nck)
      logical,  intent(out) :: any
      real(dp) :: c(9, 1*ncb, 1*nck)
      real(dp) :: cb(9, 1*ncb)
      real(dp) :: t(15), tv(9), f(0:2), b(0:2)
      real(dp) :: p, q, pq, rho, oo2p, oo2q, oo2pq, rp, rq, tt, w, eab, ecd
      real(dp) :: PA0, PA1, PA2, QC0, QC1, QC2, WP0, WP1, WP2, WQ0, WQ1, WQ2
      real(dp) :: PQ0, PQ1, PQ2, AB0, AB1, AB2, CD0, CD1, CD2, wq_, wp_
      logical  :: hit
      real(dp) :: h(18)
      integer  :: kq, bq, bc, kc, cc, ck, n, col

      AB0 = ab(1); AB1 = ab(2); AB2 = ab(3)
      CD0 = cd(1); CD1 = cd(2); CD2 = cd(3)
      any = .false.
      c = 0.0_dp
      do kq = 1, nket
         q = kp(1,kq); oo2q = kp(2,kq)
         QC0 = kp(3,kq); QC1 = kp(4,kq); QC2 = kp(5,kq)
         ecd = kp(10,kq)
         ! THE CONTRACTION IS STAGED, and that is not a detail: done
         ! flat -- every (bra column, ket column) pair touched at every
         ! primitive quartet -- it costs the product of the two
         ! contraction counts per quartet, which on a generally
         ! contracted shell (cc-pVDZ carbon s: 9 primitives, 3
         ! contractions) is 81 accumulations of the whole target vector
         ! 6561 times over.  Summing the bra columns first and folding
         ! in the ket ones once per ket primitive turns a product into
         ! a sum, which is what libcint's prim_to_ctr staging does.
         cb = 0.0_dp
         hit = .false.
         do bq = 1, nbra
            eab = bp(10,bq)
            if (eab + ecd > cutoff) cycle
            hit = .true.
            p = bp(1,bq); oo2p = bp(2,bq)
            PA0 = bp(3,bq); PA1 = bp(4,bq); PA2 = bp(5,bq)
            PQ0 = bp(6,bq) - kp(6,kq)
            PQ1 = bp(7,bq) - kp(7,kq)
            PQ2 = bp(8,bq) - kp(8,kq)
            pq = p + q
            rho = p*q/pq
            oo2pq = 0.5_dp/pq
            rp = rho/p; rq = rho/q
            ! W - P = (q/(p+q)) (Q - P), W - Q = (p/(p+q)) (P - Q)
            wp_ = -q/pq; wq_ = p/pq
            WP0 = wp_*PQ0; WP1 = wp_*PQ1; WP2 = wp_*PQ2
            WQ0 = wq_*PQ0; WQ1 = wq_*PQ1; WQ2 = wq_*PQ2
            tt = rho*(PQ0*PQ0 + PQ1*PQ1 + PQ2*PQ2)
            call boys(f, tt, 2)
            w = TWO_PI_52*bp(9,bq)*kp(9,kq)/sqrt(pq)
            do n = 0, 2
               b(n) = w*f(n)
            end do
            t(1) = b(0)
            t(2) = b(1)
            t(3) = PA0*t(1) + WP0*t(2)
            t(4) = PA1*t(1) + WP1*t(2)
            t(5) = PA2*t(1) + WP2*t(2)
            t(6) = b(2)
            t(7) = PA0*t(2) + WP0*t(6)
            t(8) = PA0*t(3) + WP0*t(7) + oo2p*t(1) - oo2p*rp*t(2)
            t(9) = PA1*t(2) + WP1*t(6)
            t(10) = PA0*t(4) + WP0*t(9)
            t(11) = PA2*t(2) + WP2*t(6)
            t(12) = PA0*t(5) + WP0*t(11)
            t(13) = PA1*t(4) + WP1*t(9) + oo2p*t(1) - oo2p*rp*t(2)
            t(14) = PA1*t(5) + WP1*t(11)
            t(15) = PA2*t(5) + WP2*t(11) + oo2p*t(1) - oo2p*rp*t(2)
            tv(1) = t(3)
            tv(2) = t(4)
            tv(3) = t(5)
            tv(4) = t(8)
            tv(5) = t(10)
            tv(6) = t(12)
            tv(7) = t(13)
            tv(8) = t(14)
            tv(9) = t(15)
            do bc = 1, 1*ncb
               cb(1:9,bc) = cb(1:9,bc) + kab(bc,bq)*tv(1:9)
            end do
         end do
         if (.not. hit) cycle
         any = .true.
         do kc = 1, 1*nck
            do bc = 1, 1*ncb
               c(1:9,bc,kc) = c(1:9,bc,kc) + kcd(kc,kq)*cb(1:9,bc)
            end do
         end do
      end do
      res = 0.0_dp
      if (.not. any) return
      do ck = 1, nck
         do cc = 1, ncb
            col = cc + ncb*(ck-1)
            bc = cc; kc = ck
            h(1) = c(4,bc,kc)
            h(2) = c(1,bc,kc)
            h(3) = h(1) + AB0*h(2)
            h(4) = c(5,bc,kc)
            h(5) = c(2,bc,kc)
            h(6) = h(4) + AB0*h(5)
            h(7) = c(6,bc,kc)
            h(8) = c(3,bc,kc)
            h(9) = h(7) + AB0*h(8)
            h(10) = h(4) + AB1*h(2)
            h(11) = c(7,bc,kc)
            h(12) = h(11) + AB1*h(5)
            h(13) = c(8,bc,kc)
            h(14) = h(13) + AB1*h(8)
            h(15) = h(7) + AB2*h(2)
            h(16) = h(13) + AB2*h(5)
            h(17) = c(9,bc,kc)
            h(18) = h(17) + AB2*h(8)
            res(1,col) = h(3)
            res(2,col) = h(6)
            res(3,col) = h(9)
            res(4,col) = h(10)
            res(5,col) = h(12)
            res(6,col) = h(14)
            res(7,col) = h(15)
            res(8,col) = h(16)
            res(9,col) = h(18)
         end do
      end do
   end subroutine hgp_ppss
end module hgp_ppss_m
