#!/usr/bin/env python3
"""Generate the Cartesian-to-spherical transforms from libcint's C.

    python3 scripts/c_cart2sph_to_fortran.py --out fortran/src/cint_cart2sph.f90

libcint hand-unrolls these for l = 0..4 and falls back to a small matrix
multiply above that.  The unrolled forms matter: they are what every ordinary
basis set actually uses, and they fix the summation order, so reproducing them
is what lets the spherical integrals agree with the C to the last bit rather
than merely closely.

Each l has the same sparse pattern written out twice in the C -- once walking
pointers over the bra index, once strided over the ket index.  Rather than
transcribe both, this reads the pattern out of the bra form

    gsph[K] = coeff_c2s[I] * gcart[J] + coeff_c2s[I2] * gcart[J2];

and emits both loops from it.  One source of truth, and the ket form cannot
drift from the bra form the way two hand-written copies can.

THE POINTER RETURN.  The C's transforms return `double *`: for s and p (in the
default px,py,pz ordering) the transform is the identity and the function
returns `gcart` untouched, avoiding a copy on the commonest shells.  Fortran
has no comfortable equivalent, so the generated routines return a flag saying
which buffer holds the result, and the caller reads that one.  The `_copy`
variants, which the C provides for callers that need the data moved
regardless, always write to gsph.
"""

import argparse
import re

# Offsets of each l's block within g_trans_cart2sph, read off g_c2s[] in
# src/cart2sph.c.
C2S_OFFSET = [0, 1, 10, 40, 110, 245, 476, 840, 1380, 2145,
              3190, 4576, 6370, 8645, 11480, 14960]

UNROLLED = ["s", "p", "d", "f", "g"]


def extract_pattern(src, letter):
    """Pull the sparse (out, [(coef, cart)]) pattern out of a bra transform."""
    m = re.search(r"static double \*%s_bra_cart2spheric\([^)]*\)\s*\n\{(.*?)\n\}"
                  % letter, src, re.S)
    if not m:
        raise SystemExit("cannot find %s_bra_cart2spheric" % letter)
    body = m.group(1)
    # drop commented-out bodies
    body = re.sub(r"/\*.*?\*/", " ", body, flags=re.S)
    body = re.sub(r"//[^\n]*", " ", body)

    rows = {}
    for stmt in re.findall(r"gsph\[\s*(\d+)\s*\]\s*=(.*?);", body, re.S):
        out = int(stmt[0])
        terms = re.findall(r"coeff_c2s\[\s*(\d+)\s*\]\s*\*\s*gcart\[\s*(\d+)\s*\]",
                           stmt[1])
        if not terms:
            continue
        rows[out] = [(int(c), int(g)) for c, g in terms]
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="src/cart2sph.c")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    src = open(args.src).read()
    patterns = {}
    for i, letter in enumerate(UNROLLED):
        patterns[i] = extract_pattern(src, letter)

    with open(args.out, "w") as fh:
        fh.write('''!
! Cartesian-to-spherical transforms.
!
! Generated by scripts/c_cart2sph_to_fortran.py from src/cart2sph.c -- do not
! edit.  The sparse coefficient pattern is read out of the C's hand-unrolled
! bra transforms, and both the bra and the ket loops are emitted from it, so
! the two cannot drift apart.
!
! l = 0..4 are unrolled, as in the C, which is what ordinary basis sets use.
! Above that the general form applies the transform as a small matrix product
! -- see cint_c2s_general below.
!
! The spinor transforms are NOT here; they belong with the rest of the
! relativistic runtime in D9.
!
module cint_cart2sph
   use cint_const,       only: dp
   use cint_tab_cart2sph, only: g_trans_cart2sph
   use cint_bas,         only: cint_len_cart
   implicit none
   private

   public :: cint_c2s_bra_sph, cint_c2s_ket_sph, cint_c2s_ket_sph_copy
   public :: RESULT_IN_GCART, RESULT_IN_GSPH

   ! The C returns a pointer, and for s and p in the default px,py,pz order it
   ! returns the input buffer so no copy happens on the commonest shells.
   ! These flags carry that information instead: the caller reads whichever
   ! buffer is named.
   integer, parameter :: RESULT_IN_GCART = 0
   integer, parameter :: RESULT_IN_GSPH  = 1

   ! Start of each l's coefficient block within g_trans_cart2sph.
   integer, parameter :: C2S_OFFSET(0:15) = [ &
''')
        fh.write("      " + ", ".join(str(v) for v in C2S_OFFSET) + " ]\n")
        fh.write('''
contains

   ! Transform a bra-side block: nket columns, each of nf Cartesian
   ! components, into 2l+1 spherical ones.
   function cint_c2s_bra_sph(gsph, nket, gcart, l) result(loc)
      real(dp), intent(inout) :: gsph(0:)
      real(dp), intent(in)    :: gcart(0:)
      integer,  intent(in)    :: nket, l
      integer :: loc
      integer :: i, o, nf, nd, co

      nf = cint_len_cart(l)
      nd = 2*l + 1
      co = C2S_OFFSET(l)
      loc = RESULT_IN_GSPH

      select case (l)
''')
        for l in (0, 1):
            fh.write("      case (%d)\n" % l)
            fh.write("         ! identity in the default p ordering; the C returns gcart here\n")
            fh.write("         loc = RESULT_IN_GCART\n")
        for l in (2, 3, 4):
            rows = patterns[l]
            fh.write("      case (%d)\n" % l)
            fh.write("         do i = 0, nket - 1\n")
            fh.write("            o = i * %d\n" % (2*l+1))
            for out in sorted(rows):
                terms = rows[out]
                expr = " &\n                 + ".join(
                    "g_trans_cart2sph(co+%d) * gcart(i*%d+%d)" % (c, cint_len_cart_py(l), g)
                    for c, g in terms)
                fh.write("            gsph(o+%d) = %s\n" % (out, expr))
            fh.write("         end do\n")
        fh.write('''      case default
         call cint_c2s_general_bra(gsph, nket, gcart, nf, nd, co)
      end select
   end function cint_c2s_bra_sph

   ! Transform a ket-side block: nbra rows, strided by lds on output.
   function cint_c2s_ket_sph(gsph, gcart, lds, nbra, l) result(loc)
      real(dp), intent(inout) :: gsph(0:)
      real(dp), intent(in)    :: gcart(0:)
      integer,  intent(in)    :: lds, nbra, l
      integer :: loc
      integer :: i, nf, nd, co

      nf = cint_len_cart(l)
      nd = 2*l + 1
      co = C2S_OFFSET(l)
      loc = RESULT_IN_GSPH

      select case (l)
''')
        for l in (0, 1):
            fh.write("      case (%d)\n" % l)
            fh.write("         loc = RESULT_IN_GCART\n")
        for l in (2, 3, 4):
            rows = patterns[l]
            fh.write("      case (%d)\n" % l)
            fh.write("         do i = 0, nbra - 1\n")
            for out in sorted(rows):
                terms = rows[out]
                expr = " &\n                 + ".join(
                    "g_trans_cart2sph(co+%d) * gcart(%d*nbra+i)" % (c, g)
                    for c, g in terms)
                fh.write("            gsph(%d*lds+i) = %s\n" % (out, expr))
            fh.write("         end do\n")
        fh.write('''      case default
         call cint_c2s_general_ket(gsph, gcart, lds, nbra, nf, nd, co)
      end select
   end function cint_c2s_ket_sph

   ! As above, but always writes to gsph even when the transform is the
   ! identity.  The C keeps these separate for callers that need the move.
   function cint_c2s_ket_sph_copy(gsph, gcart, lds, nbra, l) result(loc)
      real(dp), intent(inout) :: gsph(0:)
      real(dp), intent(in)    :: gcart(0:)
      integer,  intent(in)    :: lds, nbra, l
      integer :: loc
      integer :: i, j

      if (l <= 1) then
         do j = 0, 2*l
            do i = 0, nbra - 1
               gsph(j*lds+i) = gcart(j*nbra+i)
            end do
         end do
         loc = RESULT_IN_GSPH
      else
         loc = cint_c2s_ket_sph(gsph, gcart, lds, nbra, l)
      end if
   end function cint_c2s_ket_sph_copy

   ! General l: the transform as a small matrix product.  The C reaches this
   ! only for l >= 5 and spells it CINTdgemm_*; those are 15x9 to 28x13 blocks,
   ! where a BLAS call and a plain loop measure within a few percent of each
   ! other, so the loop stays here and the dependency does not.
   subroutine cint_c2s_general_bra(gsph, nket, gcart, nf, nd, co)
      real(dp), intent(inout) :: gsph(0:)
      real(dp), intent(in)    :: gcart(0:)
      integer,  intent(in)    :: nket, nf, nd, co
      integer  :: i, j, k
      real(dp) :: s
      do i = 0, nket - 1
         do j = 0, nd - 1
            s = 0.0_dp
            do k = 0, nf - 1
               s = s + g_trans_cart2sph(co + j*nf + k) * gcart(i*nf + k)
            end do
            gsph(i*nd + j) = s
         end do
      end do
   end subroutine cint_c2s_general_bra

   subroutine cint_c2s_general_ket(gsph, gcart, lds, nbra, nf, nd, co)
      real(dp), intent(inout) :: gsph(0:)
      real(dp), intent(in)    :: gcart(0:)
      integer,  intent(in)    :: lds, nbra, nf, nd, co
      integer  :: i, j, k
      real(dp) :: s
      do j = 0, nd - 1
         do i = 0, nbra - 1
            s = 0.0_dp
            do k = 0, nf - 1
               s = s + g_trans_cart2sph(co + j*nf + k) * gcart(k*nbra + i)
            end do
            gsph(j*lds + i) = s
         end do
      end do
   end subroutine cint_c2s_general_ket

end module cint_cart2sph
''')
    print("wrote", args.out)


def cint_len_cart_py(l):
    return (l + 1) * (l + 2) // 2


if __name__ == "__main__":
    main()
