#!/usr/bin/env python3
"""Translate libcint's unrolled 2D-to-4D kernels from C to Fortran.

    python3 scripts/c_g2e_unrolled_to_fortran.py --out fortran/src/cint_g2e_unrolled.f90

`CINTg0_2e_2d4d_unrolled` dispatches on the four angular momenta to one of
about seventy `_g0_2d4d_XXXX` routines, each a few dozen lines of straight-line
assignments into the g array.  They are not optional: the dispatcher has no
fallback and errors out on an unhandled combination, and it is selected
whenever the Rys order is two or less -- which is most of chemistry.

Unlike the autocode, these are **hand-written in upstream libcint**: g2e.c
carries no "generated by" header and no script in scripts/ produces them.  So
"put them under the generator" would mean writing a generator that does not
exist.  Translating them mechanically is the smaller and safer job, and unlike
copying by hand it cannot quietly move a coefficient.

The C subset here is narrower than the one c_rysroot_to_fortran.py handles --
no control flow at all, only declarations and assignments -- so the translator
is correspondingly simpler.  It stops rather than guessing on anything it does
not recognise.
"""

import argparse
import re

# The pointer aliases each kernel opens with, and what they become.
ALIASES = {
    "c00x": "bc%c00x", "c00y": "bc%c00y", "c00z": "bc%c00z",
    "c0px": "bc%c0px", "c0py": "bc%c0py", "c0pz": "bc%c0pz",
    "b00": "bc%b00", "b01": "bc%b01", "b10": "bc%b10",
}

NUM = re.compile(r"""(?<![A-Za-z0-9_.])(\d+\.\d*(?:[Ee][-+]?\d+)?|\.\d+(?:[Ee][-+]?\d+)?)""")


def kindify(e):
    return NUM.sub(lambda m: m.group(1) + "_dp", e)


def translate_body(body, name, locals_seen):
    """One kernel body -> a list of Fortran statements."""
    out = []
    body = re.sub(r"/\*.*?\*/", " ", body, flags=re.S)
    body = re.sub(r"//[^\n]*", " ", body)

    for raw in body.split(";"):
        stmt = " ".join(raw.split())
        if not stmt:
            continue

        # `double *cpx = bc->c00x;`  -- a local alias for one of the coefficient
        # arrays.  Recorded and substituted rather than emitted.
        m = re.match(r"^double \*(\w+) = bc->(\w+)$", stmt)
        if m:
            locals_seen[m.group(1)] = "bc%" + m.group(2)
            continue

        # `double sN = ...;` / `double xN;`
        m = re.match(r"^double (.+)$", stmt)
        if m:
            for part in m.group(1).split(","):
                part = part.strip()
                if "=" in part:
                    lhs, rhs = part.split("=", 1)
                    locals_seen.setdefault("__decl__", set()).add(lhs.strip())
                    out.append("%s = %s" % (lhs.strip(), conv(rhs, locals_seen)))
                else:
                    locals_seen.setdefault("__decl__", set()).add(part)
            continue

        if "=" not in stmt:
            raise SystemExit("%s: unhandled statement %r" % (name, stmt))

        lhs, rhs = stmt.split("=", 1)
        out.append("%s = %s" % (conv(lhs, locals_seen), conv(rhs, locals_seen)))
    return out


def conv(e, locals_seen):
    e = " ".join(e.split())
    # alias[i] -> array(i);  g[i] -> g(i)
    for alias, target in sorted(locals_seen.items(), key=lambda kv: -len(kv[0])):
        if alias == "__decl__":
            continue
        e = re.sub(r"\b%s\[([^\]]+)\]" % re.escape(alias), r"%s(\1)" % target, e)
    e = re.sub(r"\bg\[([^\]]+)\]", r"g(\1)", e)
    # the only envs fields these kernels touch are the two centre separations
    e = re.sub(r"envs->(\w+)\[([0-9])\]", r"envs%\1(\2)", e)
    # Bare integer literals (the kernels assign g[k] = 1 in places) are left
    # alone: Fortran converts them on assignment, and rewriting them would
    # have to distinguish a literal from an array subscript.
    return kindify(e)


def extract_kernels(src):
    """Every unrolled kernel in source order.

    Two families: _g0_2d4d_* for the ordinary Coulomb kernel and _srg0_2d4d_*
    for the short-range one, which carries twice the roots and so writes twice
    as many entries.  Thirty-five of each.
    """
    out = []
    for m in re.finditer(r"static inline void ((?:_srg0|_g0)_2d4d_(\w+))\("
                         r"double \* g, Rys2eT \*bc, CINTEnvVars \*envs\)\s*\n\{", src):
        name, tag = m.group(1), m.group(2)
        i = src.index("{", m.start())
        depth = 0
        for j in range(i, len(src)):
            if src[j] == "{":
                depth += 1
            elif src[j] == "}":
                depth -= 1
                if depth == 0:
                    out.append((name, tag, src[i+1:j]))
                    break
    return out


def extract_dispatch(src, fname):
    """The switch table: bit pattern -> kernel name."""
    m = re.search(r"void %s\(double \* g, Rys2eT \*bc, CINTEnvVars \*envs\)\s*\n\{(.*?)\n\}"
                  % fname, src, re.S)
    if not m:
        raise SystemExit("cannot find %s" % fname)
    cases = re.findall(r"case (0b[01]+): ((?:_srg0|_g0)_2d4d_\w+)\(g, bc, envs\); return;",
                       m.group(1))
    return [(int(b, 2), k) for b, k in cases]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="src/g2e.c")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    src = open(args.src).read()
    kernels = extract_kernels(src)
    disp = extract_dispatch(src, "CINTg0_2e_2d4d_unrolled")
    sdisp = extract_dispatch(src, "CINTsrg0_2e_2d4d_unrolled")

    with open(args.out, "w") as fh:
        fh.write('''!
! Unrolled 2D-to-4D transfers for low angular momentum.
!
! Generated by scripts/c_g2e_unrolled_to_fortran.py from src/g2e.c -- do not
! edit.  These are hand-written in the C (g2e.c is not autocode), and are
! selected whenever the Rys order is two or less, which covers most ordinary
! basis sets.  The dispatcher has no general fallback: an unhandled
! combination of angular momenta is an error, there as here.
!
module cint_g2e_unrolled
   use cint_const, only: dp
   use cint_envs,  only: cint_env_vars, rys_2e_t
   use iso_fortran_env, only: error_unit
   implicit none
   private

   public :: cint_g0_2e_2d4d_unrolled, cint_srg0_2e_2d4d_unrolled

contains

''')
        for name, tag, body in kernels:
            locals_seen = {}
            stmts = translate_body(body, name, locals_seen)
            decls = sorted(locals_seen.get("__decl__", set()))
            fh.write("   subroutine %s(g, bc, envs)\n" % name[1:])
            fh.write("      real(dp), intent(inout) :: g(0:)\n")
            fh.write("      type(rys_2e_t), intent(in) :: bc\n")
            fh.write("      type(cint_env_vars), intent(in) :: envs\n")
            if decls:
                for k in range(0, len(decls), 8):
                    fh.write("      real(dp) :: %s\n" % ", ".join(decls[k:k+8]))
            fh.write("\n")
            for st in stmts:
                for line in wrap(st):
                    fh.write("      " + line + "\n")
            fh.write("   end subroutine %s\n\n" % name[1:])

        for fname, table in (("cint_g0_2e_2d4d_unrolled", disp),
                             ("cint_srg0_2e_2d4d_unrolled", sdisp)):
            fh.write("   subroutine %s(g, bc, envs)\n" % fname)
            fh.write("      real(dp), intent(inout) :: g(0:)\n")
            fh.write("      type(rys_2e_t), intent(in) :: bc\n")
            fh.write("      type(cint_env_vars), intent(in) :: envs\n")
            fh.write("      integer :: type_ijkl\n\n")
            fh.write("      ! the C packs the four angular momenta two bits each\n")
            fh.write("      type_ijkl = ishft(envs%li_ceil, 6) + ishft(envs%lj_ceil, 4) &\n")
            fh.write("                + ishft(envs%lk_ceil, 2) + envs%ll_ceil\n")
            fh.write("      select case (type_ijkl)\n")
            for bits, kern in table:
                fh.write("      case (%d); call %s(g, bc, envs); return\n" % (bits, kern[1:]))
            fh.write("      end select\n")
            fh.write("      write(error_unit,'(A,4I3)') &\n")
            fh.write("         \"cint: no unrolled 2d4d kernel for l = \", &\n")
            fh.write("         envs%li_ceil, envs%lk_ceil, envs%ll_ceil, envs%lj_ceil\n")
            fh.write("   end subroutine %s\n\n" % fname)

        fh.write("end module cint_g2e_unrolled\n")
    print("wrote %s: %d kernels, %d + %d dispatch entries"
          % (args.out, len(kernels), len(disp), len(sdisp)))


def wrap(line, limit=118):
    if len(line) <= limit:
        return [line]
    indent = "     "
    out = []
    while len(line) > limit:
        cut = -1
        for i in range(8, min(limit, len(line))):
            if line[i] in "+-*/" and line[i-1] not in "eEdD(+-*/ " and line[i+1] != " ":
                cut = i
            elif line[i] == " " and i > 8:
                cut = i
        if cut < 0:
            break
        out.append(line[:cut].rstrip() + " &")
        line = indent + line[cut:].lstrip()
    out.append(line)
    return out


if __name__ == "__main__":
    main()
