!
! Generated by scripts/f90-backend.cl from the integral
! descriptions in scripts/auto_intor.cl -- do not edit.
!
! The symbolic layer that produced these is the same one that
! produces libcint's C: only the emitter differs.  The _spinor
! entry points come out of the same description as _cart and
! _sph, which is the whole argument for owning the generator.
!
module cint_gen_intor2
   use cint_const,     only: dp
   use cint_envs
   use cint_workspace, only: cint_ws
   use cint_g1e
   use cint_g2e
   use cint_g2e_ops
   use cint_1e,        only: cint_1e_drv
   use cint_1e_spinor, only: cint_1e_spinor_drv
   use cint_2e,        only: cint_2e_drv
   use cint_2e_spinor, only: cint_2e_spinor_drv
   use cint_3c2e,      only: cint_3c2e_drv, cint_2c2e_drv
   use cint_3c2e_spinor, only: cint_3c2e_spinor_drv
   use cint_opt,       only: cint_del_optimizer
   use cint_3c1e,      only: cint_all_3c1e_optimizer
   use cint_1e_grids,  only: cint_all_1e_grids_optimizer
   use cint_1e_grids_spinor, only: cint_1e_grids_spinor_drv
   use cint_1e_grids,  only: cint_1e_grids_drv, GRID_BLKSIZE, &
                             cint_init_int1e_grids_envvars, &
                             cint_nabla1i_grids, cint_nabla1j_grids, &
                             cint_x1i_grids, cint_x1j_grids
   use cint_3c1e,      only: cint_3c1e_drv, cint_init_int3c1e_envvars, &
                             INT3C1E_OVLP, INT3C1E_RINV, INT3C1E_NUC
   implicit none
   private

   public :: int2e_ig1_cart, int2e_ig1_sph, int2e_ig1_spinor
   public :: int2e_ig1_optimizer
   public :: int2e_gg1_cart, int2e_gg1_sph, int2e_gg1_spinor
   public :: int2e_gg1_optimizer
   public :: int2e_g1g2_cart, int2e_g1g2_sph, int2e_g1g2_spinor
   public :: int2e_g1g2_optimizer
   public :: int2e_p1vxp1_cart, int2e_p1vxp1_sph, int2e_p1vxp1_spinor
   public :: int2e_p1vxp1_optimizer
   public :: int2e_ip1v_rc1_cart, int2e_ip1v_rc1_sph, int2e_ip1v_rc1_spinor
   public :: int2e_ip1v_rc1_optimizer
   public :: int2e_ip1v_r1_cart, int2e_ip1v_r1_sph, int2e_ip1v_r1_spinor
   public :: int2e_ip1v_r1_optimizer
   public :: int2e_ipvg1_xp1_cart, int2e_ipvg1_xp1_sph, int2e_ipvg1_xp1_spinor
   public :: int2e_ipvg1_xp1_optimizer
   public :: int2e_ipvg2_xp1_cart, int2e_ipvg2_xp1_sph, int2e_ipvg2_xp1_spinor
   public :: int2e_ipvg2_xp1_optimizer
   public :: int1e_inuc_rcxp_cart, int1e_inuc_rcxp_sph, int1e_inuc_rcxp_spinor
   public :: int1e_inuc_rcxp_optimizer
   public :: int1e_inuc_rxp_cart, int1e_inuc_rxp_sph, int1e_inuc_rxp_spinor
   public :: int1e_inuc_rxp_optimizer

contains

   ! (G i j|R12 |k l)
   subroutine int2e_ig1_optimizer(opt, atm, natm, bas, nbas, env)
      type(cint_opt_t), intent(inout) :: opt
      integer,  intent(in) :: natm, nbas
      integer,  intent(in) :: atm(0:), bas(0:)
      real(dp), intent(in) :: env(0:)
      integer, parameter :: ng(0:7) = [1, 0, 0, 0, 1, 1, 1, 3]
      call cint_all_2e_optimizer(opt, ng, atm, natm, bas, nbas, env)
   end subroutine int2e_ig1_optimizer

   subroutine CINTgout2e_int2e_ig1(gout, g, idx, envs, gout_empty)
      real(dp), intent(inout) :: gout(0:*)
      real(dp), intent(inout), target :: g(0:)
      integer,  intent(in)    :: idx(0:*)
      type(cint_env_vars), intent(in) :: envs
      integer,  intent(in)    :: gout_empty
      integer  :: nf, nroots, ix, iy, iz, i, n
      integer  :: g0, g1
      real(dp), pointer, contiguous :: g0p(:), g1p(:)
      real(dp) :: s(0:2)
      real(dp) :: rirj(0:2)
      real(dp) :: c(0:2)

      rirj = envs%ri - envs%rj
      c(0) = 1.0_dp * rirj(0)
      c(1) = 1.0_dp * rirj(1)
      c(2) = 1.0_dp * rirj(2)
      nf = envs%nf
      nroots = envs%nrys_roots
      g0 = 0
      g1 = g0 + envs%g_size * 3
      call cint_x1i_2e(g, g1, g0, envs%ri, envs%i_l+0, envs%j_l, envs%k_l, envs%l_l, envs)
      g0p(0:) => g(g0:)
      g1p(0:) => g(g1:)

      do n = 0, nf - 1
         ix = idx(0+n*3)
         iy = idx(1+n*3)
         iz = idx(2+n*3)
         select case (nroots)
         case (1)
            s(0) = + g1p(ix+0)*g0p(iy+0)*g0p(iz+0)
            s(1) = + g0p(ix+0)*g1p(iy+0)*g0p(iz+0)
            s(2) = + g0p(ix+0)*g0p(iy+0)*g1p(iz+0)
         case (2)
            s(0) = + g1p(ix+0)*g0p(iy+0)*g0p(iz+0) &
                     + g1p(ix+1)*g0p(iy+1)*g0p(iz+1)
            s(1) = + g0p(ix+0)*g1p(iy+0)*g0p(iz+0) &
                     + g0p(ix+1)*g1p(iy+1)*g0p(iz+1)
            s(2) = + g0p(ix+0)*g0p(iy+0)*g1p(iz+0) &
                     + g0p(ix+1)*g0p(iy+1)*g1p(iz+1)
         case (3)
            s(0) = + g1p(ix+0)*g0p(iy+0)*g0p(iz+0) &
                     + g1p(ix+1)*g0p(iy+1)*g0p(iz+1) &
                     + g1p(ix+2)*g0p(iy+2)*g0p(iz+2)
            s(1) = + g0p(ix+0)*g1p(iy+0)*g0p(iz+0) &
                     + g0p(ix+1)*g1p(iy+1)*g0p(iz+1) &
                     + g0p(ix+2)*g1p(iy+2)*g0p(iz+2)
            s(2) = + g0p(ix+0)*g0p(iy+0)*g1p(iz+0) &
                     + g0p(ix+1)*g0p(iy+1)*g1p(iz+1) &
                     + g0p(ix+2)*g0p(iy+2)*g1p(iz+2)
         case (4)
            s(0) = + g1p(ix+0)*g0p(iy+0)*g0p(iz+0) &
                     + g1p(ix+1)*g0p(iy+1)*g0p(iz+1) &
                     + g1p(ix+2)*g0p(iy+2)*g0p(iz+2) &
                     + g1p(ix+3)*g0p(iy+3)*g0p(iz+3)
            s(1) = + g0p(ix+0)*g1p(iy+0)*g0p(iz+0) &
                     + g0p(ix+1)*g1p(iy+1)*g0p(iz+1) &
                     + g0p(ix+2)*g1p(iy+2)*g0p(iz+2) &
                     + g0p(ix+3)*g1p(iy+3)*g0p(iz+3)
            s(2) = + g0p(ix+0)*g0p(iy+0)*g1p(iz+0) &
                     + g0p(ix+1)*g0p(iy+1)*g1p(iz+1) &
                     + g0p(ix+2)*g0p(iy+2)*g1p(iz+2) &
                     + g0p(ix+3)*g0p(iy+3)*g1p(iz+3)
         case default
            s = 0.0_dp
            do i = 0, nroots - 1
               s(0) = s(0) + g1p(ix+i) * g0p(iy+i) * g0p(iz+i)
               s(1) = s(1) + g0p(ix+i) * g1p(iy+i) * g0p(iz+i)
               s(2) = s(2) + g0p(ix+i) * g0p(iy+i) * g1p(iz+i)
            end do
         end select
         if (gout_empty /= 0) then
            gout(n*3+0) = - c(1)*s(2) + c(2)*s(1)
            gout(n*3+1) = - c(2)*s(0) + c(0)*s(2)
            gout(n*3+2) = - c(0)*s(1) + c(1)*s(0)
         else
            gout(n*3+0) = gout(n*3+0) + ( - c(1)*s(2) + c(2)*s(1) )
            gout(n*3+1) = gout(n*3+1) + ( - c(2)*s(0) + c(0)*s(2) )
            gout(n*3+2) = gout(n*3+2) + ( - c(0)*s(1) + c(1)*s(0) )
         end if
      end do
   end subroutine CINTgout2e_int2e_ig1

   function int2e_ig1_cart(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      real(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), natm, nbas
      integer,  target        :: atm(0:), bas(0:)
      real(dp), target        :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [1, 0, 0, 0, 1, 1, 1, 3]

      call cint_init_int2e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout2e_int2e_ig1
      envs%common_factor = envs%common_factor * (0.5_dp)
      has_value = cint_2e_drv(out, dims, envs, ws, C2S_CART_2E1)
   end function int2e_ig1_cart

   function int2e_ig1_sph(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      real(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), natm, nbas
      integer,  target        :: atm(0:), bas(0:)
      real(dp), target        :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [1, 0, 0, 0, 1, 1, 1, 3]

      call cint_init_int2e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout2e_int2e_ig1
      envs%common_factor = envs%common_factor * (0.5_dp)
      has_value = cint_2e_drv(out, dims, envs, ws, C2S_SPH_2E1)
   end function int2e_ig1_sph

   function int2e_ig1_spinor(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      complex(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), natm, nbas
      integer,  target        :: atm(0:), bas(0:)
      real(dp), target        :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [1, 0, 0, 0, 1, 1, 1, 3]

      call cint_init_int2e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout2e_int2e_ig1
      envs%common_factor = envs%common_factor * (0.5_dp)
      has_value = cint_2e_spinor_drv(out, dims, envs, ws, .false., .false., .false., .false.)
   end function int2e_ig1_spinor

   ! (G G i j|R12 |k l)
   subroutine int2e_gg1_optimizer(opt, atm, natm, bas, nbas, env)
      type(cint_opt_t), intent(inout) :: opt
      integer,  intent(in) :: natm, nbas
      integer,  intent(in) :: atm(0:), bas(0:)
      real(dp), intent(in) :: env(0:)
      integer, parameter :: ng(0:7) = [2, 0, 0, 0, 2, 1, 1, 9]
      call cint_all_2e_optimizer(opt, ng, atm, natm, bas, nbas, env)
   end subroutine int2e_gg1_optimizer

   subroutine CINTgout2e_int2e_gg1(gout, g, idx, envs, gout_empty)
      real(dp), intent(inout) :: gout(0:*)
      real(dp), intent(inout), target :: g(0:)
      integer,  intent(in)    :: idx(0:*)
      type(cint_env_vars), intent(in) :: envs
      integer,  intent(in)    :: gout_empty
      integer  :: nf, nroots, ix, iy, iz, i, n
      integer  :: g0, g1, g2, g3
      real(dp), pointer, contiguous :: g0p(:), g1p(:), g2p(:), g3p(:)
      real(dp) :: s(0:8)
      real(dp) :: rirj(0:2)
      real(dp) :: c(0:8)

      rirj = envs%ri - envs%rj
      c(0) = 1.0_dp * rirj(0) * rirj(0)
      c(1) = 1.0_dp * rirj(0) * rirj(1)
      c(2) = 1.0_dp * rirj(0) * rirj(2)
      c(3) = 1.0_dp * rirj(1) * rirj(0)
      c(4) = 1.0_dp * rirj(1) * rirj(1)
      c(5) = 1.0_dp * rirj(1) * rirj(2)
      c(6) = 1.0_dp * rirj(2) * rirj(0)
      c(7) = 1.0_dp * rirj(2) * rirj(1)
      c(8) = 1.0_dp * rirj(2) * rirj(2)
      nf = envs%nf
      nroots = envs%nrys_roots
      g0 = 0
      g1 = g0 + envs%g_size * 3
      g2 = g1 + envs%g_size * 3
      g3 = g2 + envs%g_size * 3
      call cint_x1i_2e(g, g1, g0, envs%ri, envs%i_l+1, envs%j_l, envs%k_l, envs%l_l, envs)
      call cint_x1i_2e(g, g2, g0, envs%ri, envs%i_l+0, envs%j_l, envs%k_l, envs%l_l, envs)
      call cint_x1i_2e(g, g3, g1, envs%ri, envs%i_l+0, envs%j_l, envs%k_l, envs%l_l, envs)
      g0p(0:) => g(g0:)
      g1p(0:) => g(g1:)
      g2p(0:) => g(g2:)
      g3p(0:) => g(g3:)

      do n = 0, nf - 1
         ix = idx(0+n*3)
         iy = idx(1+n*3)
         iz = idx(2+n*3)
         s = 0.0_dp
         do i = 0, nroots - 1
               s(0) = s(0) + g3p(ix+i) * g0p(iy+i) * g0p(iz+i)
               s(1) = s(1) + g2p(ix+i) * g1p(iy+i) * g0p(iz+i)
               s(2) = s(2) + g2p(ix+i) * g0p(iy+i) * g1p(iz+i)
               s(3) = s(3) + g1p(ix+i) * g2p(iy+i) * g0p(iz+i)
               s(4) = s(4) + g0p(ix+i) * g3p(iy+i) * g0p(iz+i)
               s(5) = s(5) + g0p(ix+i) * g2p(iy+i) * g1p(iz+i)
               s(6) = s(6) + g1p(ix+i) * g0p(iy+i) * g2p(iz+i)
               s(7) = s(7) + g0p(ix+i) * g1p(iy+i) * g2p(iz+i)
               s(8) = s(8) + g0p(ix+i) * g0p(iy+i) * g3p(iz+i)
         end do
         if (gout_empty /= 0) then
            gout(n*9+0) = - c(4)*s(8) + 2*c(5)*s(7) - c(8)*s(4)
            gout(n*9+1) = - c(7)*s(2) + c(1)*s(8) + c(8)*s(1) - c(2)*s(7)
            gout(n*9+2) = - c(1)*s(5) + c(4)*s(2) + c(2)*s(4) - c(5)*s(1)
            gout(n*9+3) = - c(5)*s(6) + c(8)*s(3) + c(3)*s(8) - c(6)*s(5)
            gout(n*9+4) = - c(8)*s(0) + 2*c(6)*s(2) - c(0)*s(8)
            gout(n*9+5) = - c(2)*s(3) + c(5)*s(0) + c(0)*s(5) - c(3)*s(2)
            gout(n*9+6) = - c(3)*s(7) + c(6)*s(4) + c(4)*s(6) - c(7)*s(3)
            gout(n*9+7) = - c(6)*s(1) + c(0)*s(7) + c(7)*s(0) - c(1)*s(6)
            gout(n*9+8) = - c(0)*s(4) + 2*c(1)*s(3) - c(4)*s(0)
         else
            gout(n*9+0) = gout(n*9+0) + ( - c(4)*s(8) + 2*c(5)*s(7) - c(8)*s(4) )
            gout(n*9+1) = gout(n*9+1) + ( - c(7)*s(2) + c(1)*s(8) + c(8)*s(1) - c(2)*s(7) )
            gout(n*9+2) = gout(n*9+2) + ( - c(1)*s(5) + c(4)*s(2) + c(2)*s(4) - c(5)*s(1) )
            gout(n*9+3) = gout(n*9+3) + ( - c(5)*s(6) + c(8)*s(3) + c(3)*s(8) - c(6)*s(5) )
            gout(n*9+4) = gout(n*9+4) + ( - c(8)*s(0) + 2*c(6)*s(2) - c(0)*s(8) )
            gout(n*9+5) = gout(n*9+5) + ( - c(2)*s(3) + c(5)*s(0) + c(0)*s(5) - c(3)*s(2) )
            gout(n*9+6) = gout(n*9+6) + ( - c(3)*s(7) + c(6)*s(4) + c(4)*s(6) - c(7)*s(3) )
            gout(n*9+7) = gout(n*9+7) + ( - c(6)*s(1) + c(0)*s(7) + c(7)*s(0) - c(1)*s(6) )
            gout(n*9+8) = gout(n*9+8) + ( - c(0)*s(4) + 2*c(1)*s(3) - c(4)*s(0) )
         end if
      end do
   end subroutine CINTgout2e_int2e_gg1

   function int2e_gg1_cart(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      real(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), natm, nbas
      integer,  target        :: atm(0:), bas(0:)
      real(dp), target        :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [2, 0, 0, 0, 2, 1, 1, 9]

      call cint_init_int2e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout2e_int2e_gg1
      envs%common_factor = envs%common_factor * (0.25_dp)
      has_value = cint_2e_drv(out, dims, envs, ws, C2S_CART_2E1)
   end function int2e_gg1_cart

   function int2e_gg1_sph(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      real(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), natm, nbas
      integer,  target        :: atm(0:), bas(0:)
      real(dp), target        :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [2, 0, 0, 0, 2, 1, 1, 9]

      call cint_init_int2e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout2e_int2e_gg1
      envs%common_factor = envs%common_factor * (0.25_dp)
      has_value = cint_2e_drv(out, dims, envs, ws, C2S_SPH_2E1)
   end function int2e_gg1_sph

   function int2e_gg1_spinor(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      complex(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), natm, nbas
      integer,  target        :: atm(0:), bas(0:)
      real(dp), target        :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [2, 0, 0, 0, 2, 1, 1, 9]

      call cint_init_int2e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout2e_int2e_gg1
      envs%common_factor = envs%common_factor * (0.25_dp)
      has_value = cint_2e_spinor_drv(out, dims, envs, ws, .false., .false., .false., .false.)
   end function int2e_gg1_spinor

   ! (G i j|R12 |G k l)
   subroutine int2e_g1g2_optimizer(opt, atm, natm, bas, nbas, env)
      type(cint_opt_t), intent(inout) :: opt
      integer,  intent(in) :: natm, nbas
      integer,  intent(in) :: atm(0:), bas(0:)
      real(dp), intent(in) :: env(0:)
      integer, parameter :: ng(0:7) = [1, 0, 1, 0, 2, 1, 1, 9]
      call cint_all_2e_optimizer(opt, ng, atm, natm, bas, nbas, env)
   end subroutine int2e_g1g2_optimizer

   subroutine CINTgout2e_int2e_g1g2(gout, g, idx, envs, gout_empty)
      real(dp), intent(inout) :: gout(0:*)
      real(dp), intent(inout), target :: g(0:)
      integer,  intent(in)    :: idx(0:*)
      type(cint_env_vars), intent(in) :: envs
      integer,  intent(in)    :: gout_empty
      integer  :: nf, nroots, ix, iy, iz, i, n
      integer  :: g0, g1, g2, g3
      real(dp), pointer, contiguous :: g0p(:), g1p(:), g2p(:), g3p(:)
      real(dp) :: s(0:8)
      real(dp) :: rirj(0:2)
      real(dp) :: rkrl(0:2)
      real(dp) :: c(0:8)

      rirj = envs%ri - envs%rj
      rkrl = envs%rk - envs%rl
      c(0) = 1.0_dp * rirj(0) * rkrl(0)
      c(1) = 1.0_dp * rirj(0) * rkrl(1)
      c(2) = 1.0_dp * rirj(0) * rkrl(2)
      c(3) = 1.0_dp * rirj(1) * rkrl(0)
      c(4) = 1.0_dp * rirj(1) * rkrl(1)
      c(5) = 1.0_dp * rirj(1) * rkrl(2)
      c(6) = 1.0_dp * rirj(2) * rkrl(0)
      c(7) = 1.0_dp * rirj(2) * rkrl(1)
      c(8) = 1.0_dp * rirj(2) * rkrl(2)
      nf = envs%nf
      nroots = envs%nrys_roots
      g0 = 0
      g1 = g0 + envs%g_size * 3
      g2 = g1 + envs%g_size * 3
      g3 = g2 + envs%g_size * 3
      call cint_x1k_2e(g, g1, g0, envs%rk, envs%i_l+1, envs%j_l+0, envs%k_l+0, envs%l_l, envs)
      call cint_x1i_2e(g, g2, g0, envs%ri, envs%i_l+0, envs%j_l, envs%k_l, envs%l_l, envs)
      call cint_x1i_2e(g, g3, g1, envs%ri, envs%i_l+0, envs%j_l, envs%k_l, envs%l_l, envs)
      g0p(0:) => g(g0:)
      g1p(0:) => g(g1:)
      g2p(0:) => g(g2:)
      g3p(0:) => g(g3:)

      do n = 0, nf - 1
         ix = idx(0+n*3)
         iy = idx(1+n*3)
         iz = idx(2+n*3)
         s = 0.0_dp
         do i = 0, nroots - 1
               s(0) = s(0) + g3p(ix+i) * g0p(iy+i) * g0p(iz+i)
               s(1) = s(1) + g2p(ix+i) * g1p(iy+i) * g0p(iz+i)
               s(2) = s(2) + g2p(ix+i) * g0p(iy+i) * g1p(iz+i)
               s(3) = s(3) + g1p(ix+i) * g2p(iy+i) * g0p(iz+i)
               s(4) = s(4) + g0p(ix+i) * g3p(iy+i) * g0p(iz+i)
               s(5) = s(5) + g0p(ix+i) * g2p(iy+i) * g1p(iz+i)
               s(6) = s(6) + g1p(ix+i) * g0p(iy+i) * g2p(iz+i)
               s(7) = s(7) + g0p(ix+i) * g1p(iy+i) * g2p(iz+i)
               s(8) = s(8) + g0p(ix+i) * g0p(iy+i) * g3p(iz+i)
         end do
         if (gout_empty /= 0) then
            gout(n*9+0) = + c(4)*s(8) - c(7)*s(5) - c(5)*s(7) + c(8)*s(4)
            gout(n*9+1) = + c(5)*s(6) - c(8)*s(3) - c(3)*s(8) + c(6)*s(5)
            gout(n*9+2) = + c(3)*s(7) - c(6)*s(4) - c(4)*s(6) + c(7)*s(3)
            gout(n*9+3) = + c(7)*s(2) - c(1)*s(8) - c(8)*s(1) + c(2)*s(7)
            gout(n*9+4) = + c(8)*s(0) - c(2)*s(6) - c(6)*s(2) + c(0)*s(8)
            gout(n*9+5) = + c(6)*s(1) - c(0)*s(7) - c(7)*s(0) + c(1)*s(6)
            gout(n*9+6) = + c(1)*s(5) - c(4)*s(2) - c(2)*s(4) + c(5)*s(1)
            gout(n*9+7) = + c(2)*s(3) - c(5)*s(0) - c(0)*s(5) + c(3)*s(2)
            gout(n*9+8) = + c(0)*s(4) - c(3)*s(1) - c(1)*s(3) + c(4)*s(0)
         else
            gout(n*9+0) = gout(n*9+0) + ( + c(4)*s(8) - c(7)*s(5) - c(5)*s(7) + c(8)*s(4) )
            gout(n*9+1) = gout(n*9+1) + ( + c(5)*s(6) - c(8)*s(3) - c(3)*s(8) + c(6)*s(5) )
            gout(n*9+2) = gout(n*9+2) + ( + c(3)*s(7) - c(6)*s(4) - c(4)*s(6) + c(7)*s(3) )
            gout(n*9+3) = gout(n*9+3) + ( + c(7)*s(2) - c(1)*s(8) - c(8)*s(1) + c(2)*s(7) )
            gout(n*9+4) = gout(n*9+4) + ( + c(8)*s(0) - c(2)*s(6) - c(6)*s(2) + c(0)*s(8) )
            gout(n*9+5) = gout(n*9+5) + ( + c(6)*s(1) - c(0)*s(7) - c(7)*s(0) + c(1)*s(6) )
            gout(n*9+6) = gout(n*9+6) + ( + c(1)*s(5) - c(4)*s(2) - c(2)*s(4) + c(5)*s(1) )
            gout(n*9+7) = gout(n*9+7) + ( + c(2)*s(3) - c(5)*s(0) - c(0)*s(5) + c(3)*s(2) )
            gout(n*9+8) = gout(n*9+8) + ( + c(0)*s(4) - c(3)*s(1) - c(1)*s(3) + c(4)*s(0) )
         end if
      end do
   end subroutine CINTgout2e_int2e_g1g2

   function int2e_g1g2_cart(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      real(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), natm, nbas
      integer,  target        :: atm(0:), bas(0:)
      real(dp), target        :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [1, 0, 1, 0, 2, 1, 1, 9]

      call cint_init_int2e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout2e_int2e_g1g2
      envs%common_factor = envs%common_factor * (-0.25_dp)
      has_value = cint_2e_drv(out, dims, envs, ws, C2S_CART_2E1)
   end function int2e_g1g2_cart

   function int2e_g1g2_sph(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      real(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), natm, nbas
      integer,  target        :: atm(0:), bas(0:)
      real(dp), target        :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [1, 0, 1, 0, 2, 1, 1, 9]

      call cint_init_int2e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout2e_int2e_g1g2
      envs%common_factor = envs%common_factor * (-0.25_dp)
      has_value = cint_2e_drv(out, dims, envs, ws, C2S_SPH_2E1)
   end function int2e_g1g2_sph

   function int2e_g1g2_spinor(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      complex(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), natm, nbas
      integer,  target        :: atm(0:), bas(0:)
      real(dp), target        :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [1, 0, 1, 0, 2, 1, 1, 9]

      call cint_init_int2e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout2e_int2e_g1g2
      envs%common_factor = envs%common_factor * (-0.25_dp)
      has_value = cint_2e_spinor_drv(out, dims, envs, ws, .false., .true., .false., .true.)
   end function int2e_g1g2_spinor

   ! (P* i CROSS P j|R12 |k l)
   subroutine int2e_p1vxp1_optimizer(opt, atm, natm, bas, nbas, env)
      type(cint_opt_t), intent(inout) :: opt
      integer,  intent(in) :: natm, nbas
      integer,  intent(in) :: atm(0:), bas(0:)
      real(dp), intent(in) :: env(0:)
      integer, parameter :: ng(0:7) = [1, 1, 0, 0, 2, 1, 1, 3]
      call cint_all_2e_optimizer(opt, ng, atm, natm, bas, nbas, env)
   end subroutine int2e_p1vxp1_optimizer

   subroutine CINTgout2e_int2e_p1vxp1(gout, g, idx, envs, gout_empty)
      real(dp), intent(inout) :: gout(0:*)
      real(dp), intent(inout), target :: g(0:)
      integer,  intent(in)    :: idx(0:*)
      type(cint_env_vars), intent(in) :: envs
      integer,  intent(in)    :: gout_empty
      integer  :: nf, nroots, ix, iy, iz, i, n
      integer  :: g0, g1, g2, g3
      real(dp), pointer, contiguous :: g0p(:), g1p(:), g2p(:), g3p(:)
      real(dp) :: s(0:8)

      nf = envs%nf
      nroots = envs%nrys_roots
      g0 = 0
      g1 = g0 + envs%g_size * 3
      g2 = g1 + envs%g_size * 3
      g3 = g2 + envs%g_size * 3
      call cint_nabla1j_2e(g, g1, g0, envs%i_l+1, envs%j_l+0, envs%k_l, envs%l_l, envs)
      call cint_nabla1i_2e(g, g2, g0, envs%i_l+0, envs%j_l, envs%k_l, envs%l_l, envs)
      call cint_nabla1i_2e(g, g3, g1, envs%i_l+0, envs%j_l, envs%k_l, envs%l_l, envs)
      g0p(0:) => g(g0:)
      g1p(0:) => g(g1:)
      g2p(0:) => g(g2:)
      g3p(0:) => g(g3:)

      do n = 0, nf - 1
         ix = idx(0+n*3)
         iy = idx(1+n*3)
         iz = idx(2+n*3)
         s = 0.0_dp
         do i = 0, nroots - 1
               s(0) = s(0) + g3p(ix+i) * g0p(iy+i) * g0p(iz+i)
               s(1) = s(1) + g2p(ix+i) * g1p(iy+i) * g0p(iz+i)
               s(2) = s(2) + g2p(ix+i) * g0p(iy+i) * g1p(iz+i)
               s(3) = s(3) + g1p(ix+i) * g2p(iy+i) * g0p(iz+i)
               s(4) = s(4) + g0p(ix+i) * g3p(iy+i) * g0p(iz+i)
               s(5) = s(5) + g0p(ix+i) * g2p(iy+i) * g1p(iz+i)
               s(6) = s(6) + g1p(ix+i) * g0p(iy+i) * g2p(iz+i)
               s(7) = s(7) + g0p(ix+i) * g1p(iy+i) * g2p(iz+i)
               s(8) = s(8) + g0p(ix+i) * g0p(iy+i) * g3p(iz+i)
         end do
         if (gout_empty /= 0) then
            gout(n*3+0) = + s(5) - s(7)
            gout(n*3+1) = + s(6) - s(2)
            gout(n*3+2) = + s(1) - s(3)
         else
            gout(n*3+0) = gout(n*3+0) + ( + s(5) - s(7) )
            gout(n*3+1) = gout(n*3+1) + ( + s(6) - s(2) )
            gout(n*3+2) = gout(n*3+2) + ( + s(1) - s(3) )
         end if
      end do
   end subroutine CINTgout2e_int2e_p1vxp1

   function int2e_p1vxp1_cart(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      real(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), natm, nbas
      integer,  target        :: atm(0:), bas(0:)
      real(dp), target        :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [1, 1, 0, 0, 2, 1, 1, 3]

      call cint_init_int2e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout2e_int2e_p1vxp1
      has_value = cint_2e_drv(out, dims, envs, ws, C2S_CART_2E1)
   end function int2e_p1vxp1_cart

   function int2e_p1vxp1_sph(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      real(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), natm, nbas
      integer,  target        :: atm(0:), bas(0:)
      real(dp), target        :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [1, 1, 0, 0, 2, 1, 1, 3]

      call cint_init_int2e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout2e_int2e_p1vxp1
      has_value = cint_2e_drv(out, dims, envs, ws, C2S_SPH_2E1)
   end function int2e_p1vxp1_sph

   function int2e_p1vxp1_spinor(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      complex(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), natm, nbas
      integer,  target        :: atm(0:), bas(0:)
      real(dp), target        :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [1, 1, 0, 0, 2, 1, 1, 3]

      call cint_init_int2e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout2e_int2e_p1vxp1
      has_value = cint_2e_spinor_drv(out, dims, envs, ws, .false., .false., .false., .false.)
   end function int2e_p1vxp1_spinor

   ! (i RC j|NABLA-R12 |k l)
   subroutine int2e_ip1v_rc1_optimizer(opt, atm, natm, bas, nbas, env)
      type(cint_opt_t), intent(inout) :: opt
      integer,  intent(in) :: natm, nbas
      integer,  intent(in) :: atm(0:), bas(0:)
      real(dp), intent(in) :: env(0:)
      integer, parameter :: ng(0:7) = [1, 2, 0, 0, 2, 1, 1, 9]
      call cint_all_2e_optimizer(opt, ng, atm, natm, bas, nbas, env)
   end subroutine int2e_ip1v_rc1_optimizer

   subroutine CINTgout2e_int2e_ip1v_rc1(gout, g, idx, envs, gout_empty)
      real(dp), intent(inout) :: gout(0:*)
      real(dp), intent(inout), target :: g(0:)
      integer,  intent(in)    :: idx(0:*)
      type(cint_env_vars), intent(in) :: envs
      integer,  intent(in)    :: gout_empty
      integer  :: nf, nroots, ix, iy, iz, i, n
      integer  :: g0, g1, g2, g3
      real(dp), pointer, contiguous :: g0p(:), g1p(:), g2p(:), g3p(:)
      real(dp) :: s(0:8)
      real(dp) :: drj(0:2)

      drj = envs%rj - envs%env(PTR_COMMON_ORIG:PTR_COMMON_ORIG+2)
      nf = envs%nf
      nroots = envs%nrys_roots
      g0 = 0
      g1 = g0 + envs%g_size * 3
      g2 = g1 + envs%g_size * 3
      g3 = g2 + envs%g_size * 3
      call cint_x1j_2e(g, g1, g0, drj, envs%i_l+0, envs%j_l+0, envs%k_l, envs%l_l, envs)
      call cint_nabla1j_2e(g, g2, g0, envs%i_l+0, envs%j_l+1, envs%k_l, envs%l_l, envs)
      call cint_nabla1i_2e(g, g3, g0, envs%i_l+0, envs%j_l+1, envs%k_l, envs%l_l, envs)
      do ix = 0, envs%g_size*3 - 1
         g(g2+ix) = g(g2+ix) + g(g3+ix)
      end do
      call cint_x1j_2e(g, g3, g2, drj, envs%i_l+0, envs%j_l+0, envs%k_l, envs%l_l, envs)
      g0p(0:) => g(g0:)
      g1p(0:) => g(g1:)
      g2p(0:) => g(g2:)
      g3p(0:) => g(g3:)

      do n = 0, nf - 1
         ix = idx(0+n*3)
         iy = idx(1+n*3)
         iz = idx(2+n*3)
         s = 0.0_dp
         do i = 0, nroots - 1
               s(0) = s(0) + g3p(ix+i) * g0p(iy+i) * g0p(iz+i)
               s(1) = s(1) + g2p(ix+i) * g1p(iy+i) * g0p(iz+i)
               s(2) = s(2) + g2p(ix+i) * g0p(iy+i) * g1p(iz+i)
               s(3) = s(3) + g1p(ix+i) * g2p(iy+i) * g0p(iz+i)
               s(4) = s(4) + g0p(ix+i) * g3p(iy+i) * g0p(iz+i)
               s(5) = s(5) + g0p(ix+i) * g2p(iy+i) * g1p(iz+i)
               s(6) = s(6) + g1p(ix+i) * g0p(iy+i) * g2p(iz+i)
               s(7) = s(7) + g0p(ix+i) * g1p(iy+i) * g2p(iz+i)
               s(8) = s(8) + g0p(ix+i) * g0p(iy+i) * g3p(iz+i)
         end do
         if (gout_empty /= 0) then
            gout(n*9+0) = + s(0)
            gout(n*9+1) = + s(1)
            gout(n*9+2) = + s(2)
            gout(n*9+3) = + s(3)
            gout(n*9+4) = + s(4)
            gout(n*9+5) = + s(5)
            gout(n*9+6) = + s(6)
            gout(n*9+7) = + s(7)
            gout(n*9+8) = + s(8)
         else
            gout(n*9+0) = gout(n*9+0) + ( + s(0) )
            gout(n*9+1) = gout(n*9+1) + ( + s(1) )
            gout(n*9+2) = gout(n*9+2) + ( + s(2) )
            gout(n*9+3) = gout(n*9+3) + ( + s(3) )
            gout(n*9+4) = gout(n*9+4) + ( + s(4) )
            gout(n*9+5) = gout(n*9+5) + ( + s(5) )
            gout(n*9+6) = gout(n*9+6) + ( + s(6) )
            gout(n*9+7) = gout(n*9+7) + ( + s(7) )
            gout(n*9+8) = gout(n*9+8) + ( + s(8) )
         end if
      end do
   end subroutine CINTgout2e_int2e_ip1v_rc1

   function int2e_ip1v_rc1_cart(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      real(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), natm, nbas
      integer,  target        :: atm(0:), bas(0:)
      real(dp), target        :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [1, 2, 0, 0, 2, 1, 1, 9]

      call cint_init_int2e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout2e_int2e_ip1v_rc1
      has_value = cint_2e_drv(out, dims, envs, ws, C2S_CART_2E1)
   end function int2e_ip1v_rc1_cart

   function int2e_ip1v_rc1_sph(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      real(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), natm, nbas
      integer,  target        :: atm(0:), bas(0:)
      real(dp), target        :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [1, 2, 0, 0, 2, 1, 1, 9]

      call cint_init_int2e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout2e_int2e_ip1v_rc1
      has_value = cint_2e_drv(out, dims, envs, ws, C2S_SPH_2E1)
   end function int2e_ip1v_rc1_sph

   function int2e_ip1v_rc1_spinor(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      complex(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), natm, nbas
      integer,  target        :: atm(0:), bas(0:)
      real(dp), target        :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [1, 2, 0, 0, 2, 1, 1, 9]

      call cint_init_int2e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout2e_int2e_ip1v_rc1
      has_value = cint_2e_spinor_drv(out, dims, envs, ws, .false., .false., .false., .false.)
   end function int2e_ip1v_rc1_spinor

   ! (i R j|NABLA-R12 |k l)
   subroutine int2e_ip1v_r1_optimizer(opt, atm, natm, bas, nbas, env)
      type(cint_opt_t), intent(inout) :: opt
      integer,  intent(in) :: natm, nbas
      integer,  intent(in) :: atm(0:), bas(0:)
      real(dp), intent(in) :: env(0:)
      integer, parameter :: ng(0:7) = [1, 2, 0, 0, 2, 1, 1, 9]
      call cint_all_2e_optimizer(opt, ng, atm, natm, bas, nbas, env)
   end subroutine int2e_ip1v_r1_optimizer

   subroutine CINTgout2e_int2e_ip1v_r1(gout, g, idx, envs, gout_empty)
      real(dp), intent(inout) :: gout(0:*)
      real(dp), intent(inout), target :: g(0:)
      integer,  intent(in)    :: idx(0:*)
      type(cint_env_vars), intent(in) :: envs
      integer,  intent(in)    :: gout_empty
      integer  :: nf, nroots, ix, iy, iz, i, n
      integer  :: g0, g1, g2, g3
      real(dp), pointer, contiguous :: g0p(:), g1p(:), g2p(:), g3p(:)
      real(dp) :: s(0:8)

      nf = envs%nf
      nroots = envs%nrys_roots
      g0 = 0
      g1 = g0 + envs%g_size * 3
      g2 = g1 + envs%g_size * 3
      g3 = g2 + envs%g_size * 3
      g1 = g0 + envs%g_stride_j
      call cint_nabla1j_2e(g, g2, g0, envs%i_l+0, envs%j_l+1, envs%k_l, envs%l_l, envs)
      call cint_nabla1i_2e(g, g3, g0, envs%i_l+0, envs%j_l+1, envs%k_l, envs%l_l, envs)
      do ix = 0, envs%g_size*3 - 1
         g(g2+ix) = g(g2+ix) + g(g3+ix)
      end do
      g3 = g2 + envs%g_stride_j
      g0p(0:) => g(g0:)
      g1p(0:) => g(g1:)
      g2p(0:) => g(g2:)
      g3p(0:) => g(g3:)

      do n = 0, nf - 1
         ix = idx(0+n*3)
         iy = idx(1+n*3)
         iz = idx(2+n*3)
         s = 0.0_dp
         do i = 0, nroots - 1
               s(0) = s(0) + g3p(ix+i) * g0p(iy+i) * g0p(iz+i)
               s(1) = s(1) + g2p(ix+i) * g1p(iy+i) * g0p(iz+i)
               s(2) = s(2) + g2p(ix+i) * g0p(iy+i) * g1p(iz+i)
               s(3) = s(3) + g1p(ix+i) * g2p(iy+i) * g0p(iz+i)
               s(4) = s(4) + g0p(ix+i) * g3p(iy+i) * g0p(iz+i)
               s(5) = s(5) + g0p(ix+i) * g2p(iy+i) * g1p(iz+i)
               s(6) = s(6) + g1p(ix+i) * g0p(iy+i) * g2p(iz+i)
               s(7) = s(7) + g0p(ix+i) * g1p(iy+i) * g2p(iz+i)
               s(8) = s(8) + g0p(ix+i) * g0p(iy+i) * g3p(iz+i)
         end do
         if (gout_empty /= 0) then
            gout(n*9+0) = + s(0)
            gout(n*9+1) = + s(1)
            gout(n*9+2) = + s(2)
            gout(n*9+3) = + s(3)
            gout(n*9+4) = + s(4)
            gout(n*9+5) = + s(5)
            gout(n*9+6) = + s(6)
            gout(n*9+7) = + s(7)
            gout(n*9+8) = + s(8)
         else
            gout(n*9+0) = gout(n*9+0) + ( + s(0) )
            gout(n*9+1) = gout(n*9+1) + ( + s(1) )
            gout(n*9+2) = gout(n*9+2) + ( + s(2) )
            gout(n*9+3) = gout(n*9+3) + ( + s(3) )
            gout(n*9+4) = gout(n*9+4) + ( + s(4) )
            gout(n*9+5) = gout(n*9+5) + ( + s(5) )
            gout(n*9+6) = gout(n*9+6) + ( + s(6) )
            gout(n*9+7) = gout(n*9+7) + ( + s(7) )
            gout(n*9+8) = gout(n*9+8) + ( + s(8) )
         end if
      end do
   end subroutine CINTgout2e_int2e_ip1v_r1

   function int2e_ip1v_r1_cart(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      real(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), natm, nbas
      integer,  target        :: atm(0:), bas(0:)
      real(dp), target        :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [1, 2, 0, 0, 2, 1, 1, 9]

      call cint_init_int2e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout2e_int2e_ip1v_r1
      has_value = cint_2e_drv(out, dims, envs, ws, C2S_CART_2E1)
   end function int2e_ip1v_r1_cart

   function int2e_ip1v_r1_sph(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      real(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), natm, nbas
      integer,  target        :: atm(0:), bas(0:)
      real(dp), target        :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [1, 2, 0, 0, 2, 1, 1, 9]

      call cint_init_int2e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout2e_int2e_ip1v_r1
      has_value = cint_2e_drv(out, dims, envs, ws, C2S_SPH_2E1)
   end function int2e_ip1v_r1_sph

   function int2e_ip1v_r1_spinor(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      complex(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), natm, nbas
      integer,  target        :: atm(0:), bas(0:)
      real(dp), target        :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [1, 2, 0, 0, 2, 1, 1, 9]

      call cint_init_int2e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout2e_int2e_ip1v_r1
      has_value = cint_2e_spinor_drv(out, dims, envs, ws, .false., .false., .false., .false.)
   end function int2e_ip1v_r1_spinor

   ! (G i j|NABLA-R12 CROSS P |k l)
   subroutine int2e_ipvg1_xp1_optimizer(opt, atm, natm, bas, nbas, env)
      type(cint_opt_t), intent(inout) :: opt
      integer,  intent(in) :: natm, nbas
      integer,  intent(in) :: atm(0:), bas(0:)
      real(dp), intent(in) :: env(0:)
      integer, parameter :: ng(0:7) = [2, 1, 0, 0, 3, 1, 1, 9]
      call cint_all_2e_optimizer(opt, ng, atm, natm, bas, nbas, env)
   end subroutine int2e_ipvg1_xp1_optimizer

   subroutine CINTgout2e_int2e_ipvg1_xp1(gout, g, idx, envs, gout_empty)
      real(dp), intent(inout) :: gout(0:*)
      real(dp), intent(inout), target :: g(0:)
      integer,  intent(in)    :: idx(0:*)
      type(cint_env_vars), intent(in) :: envs
      integer,  intent(in)    :: gout_empty
      integer  :: nf, nroots, ix, iy, iz, i, n
      integer  :: g0, g1, g2, g3, g4, g5, g6, g7
      real(dp), pointer, contiguous :: g0p(:), g1p(:), g2p(:), g3p(:), g4p(:), g5p(:)
      real(dp), pointer, contiguous :: g6p(:), g7p(:)
      real(dp) :: s(0:26)
      real(dp) :: rirj(0:2)
      real(dp) :: c(0:2)

      rirj = envs%ri - envs%rj
      c(0) = 1.0_dp * rirj(0)
      c(1) = 1.0_dp * rirj(1)
      c(2) = 1.0_dp * rirj(2)
      nf = envs%nf
      nroots = envs%nrys_roots
      g0 = 0
      g1 = g0 + envs%g_size * 3
      g2 = g1 + envs%g_size * 3
      g3 = g2 + envs%g_size * 3
      g4 = g3 + envs%g_size * 3
      g5 = g4 + envs%g_size * 3
      g6 = g5 + envs%g_size * 3
      g7 = g6 + envs%g_size * 3
      call cint_nabla1j_2e(g, g1, g0, envs%i_l+2, envs%j_l+0, envs%k_l, envs%l_l, envs)
      call cint_nabla1j_2e(g, g2, g0, envs%i_l+1, envs%j_l+1, envs%k_l, envs%l_l, envs)
      call cint_nabla1i_2e(g, g3, g0, envs%i_l+1, envs%j_l+1, envs%k_l, envs%l_l, envs)
      do ix = 0, envs%g_size*3 - 1
         g(g2+ix) = g(g2+ix) + g(g3+ix)
      end do
      call cint_nabla1j_2e(g, g3, g2, envs%i_l+2, envs%j_l+0, envs%k_l, envs%l_l, envs)
      call cint_x1i_2e(g, g4, g0, envs%ri, envs%i_l+0, envs%j_l, envs%k_l, envs%l_l, envs)
      call cint_x1i_2e(g, g5, g1, envs%ri, envs%i_l+0, envs%j_l, envs%k_l, envs%l_l, envs)
      call cint_x1i_2e(g, g6, g2, envs%ri, envs%i_l+0, envs%j_l, envs%k_l, envs%l_l, envs)
      call cint_x1i_2e(g, g7, g3, envs%ri, envs%i_l+0, envs%j_l, envs%k_l, envs%l_l, envs)
      g0p(0:) => g(g0:)
      g1p(0:) => g(g1:)
      g2p(0:) => g(g2:)
      g3p(0:) => g(g3:)
      g4p(0:) => g(g4:)
      g5p(0:) => g(g5:)
      g6p(0:) => g(g6:)
      g7p(0:) => g(g7:)

      do n = 0, nf - 1
         ix = idx(0+n*3)
         iy = idx(1+n*3)
         iz = idx(2+n*3)
         s = 0.0_dp
         do i = 0, nroots - 1
               s(0) = s(0) + g7p(ix+i) * g0p(iy+i) * g0p(iz+i)
               s(1) = s(1) + g6p(ix+i) * g1p(iy+i) * g0p(iz+i)
               s(2) = s(2) + g6p(ix+i) * g0p(iy+i) * g1p(iz+i)
               s(3) = s(3) + g5p(ix+i) * g2p(iy+i) * g0p(iz+i)
               s(4) = s(4) + g4p(ix+i) * g3p(iy+i) * g0p(iz+i)
               s(5) = s(5) + g4p(ix+i) * g2p(iy+i) * g1p(iz+i)
               s(6) = s(6) + g5p(ix+i) * g0p(iy+i) * g2p(iz+i)
               s(7) = s(7) + g4p(ix+i) * g1p(iy+i) * g2p(iz+i)
               s(8) = s(8) + g4p(ix+i) * g0p(iy+i) * g3p(iz+i)
               s(9) = s(9) + g3p(ix+i) * g4p(iy+i) * g0p(iz+i)
               s(10) = s(10) + g2p(ix+i) * g5p(iy+i) * g0p(iz+i)
               s(11) = s(11) + g2p(ix+i) * g4p(iy+i) * g1p(iz+i)
               s(12) = s(12) + g1p(ix+i) * g6p(iy+i) * g0p(iz+i)
               s(13) = s(13) + g0p(ix+i) * g7p(iy+i) * g0p(iz+i)
               s(14) = s(14) + g0p(ix+i) * g6p(iy+i) * g1p(iz+i)
               s(15) = s(15) + g1p(ix+i) * g4p(iy+i) * g2p(iz+i)
               s(16) = s(16) + g0p(ix+i) * g5p(iy+i) * g2p(iz+i)
               s(17) = s(17) + g0p(ix+i) * g4p(iy+i) * g3p(iz+i)
               s(18) = s(18) + g3p(ix+i) * g0p(iy+i) * g4p(iz+i)
               s(19) = s(19) + g2p(ix+i) * g1p(iy+i) * g4p(iz+i)
               s(20) = s(20) + g2p(ix+i) * g0p(iy+i) * g5p(iz+i)
               s(21) = s(21) + g1p(ix+i) * g2p(iy+i) * g4p(iz+i)
               s(22) = s(22) + g0p(ix+i) * g3p(iy+i) * g4p(iz+i)
               s(23) = s(23) + g0p(ix+i) * g2p(iy+i) * g5p(iz+i)
               s(24) = s(24) + g1p(ix+i) * g0p(iy+i) * g6p(iz+i)
               s(25) = s(25) + g0p(ix+i) * g1p(iy+i) * g6p(iz+i)
               s(26) = s(26) + g0p(ix+i) * g0p(iy+i) * g7p(iz+i)
         end do
         if (gout_empty /= 0) then
            gout(n*9+0) = + c(1)*s(23) - c(2)*s(14) - c(1)*s(25) + c(2)*s(16)
            gout(n*9+1) = + c(1)*s(24) - c(2)*s(15) - c(1)*s(20) + c(2)*s(11)
            gout(n*9+2) = + c(1)*s(19) - c(2)*s(10) - c(1)*s(21) + c(2)*s(12)
            gout(n*9+3) = + c(2)*s(5) - c(0)*s(23) - c(2)*s(7) + c(0)*s(25)
            gout(n*9+4) = + c(2)*s(6) - c(0)*s(24) - c(2)*s(2) + c(0)*s(20)
            gout(n*9+5) = + c(2)*s(1) - c(0)*s(19) - c(2)*s(3) + c(0)*s(21)
            gout(n*9+6) = + c(0)*s(14) - c(1)*s(5) - c(0)*s(16) + c(1)*s(7)
            gout(n*9+7) = + c(0)*s(15) - c(1)*s(6) - c(0)*s(11) + c(1)*s(2)
            gout(n*9+8) = + c(0)*s(10) - c(1)*s(1) - c(0)*s(12) + c(1)*s(3)
         else
            gout(n*9+0) = gout(n*9+0) + ( + c(1)*s(23) - c(2)*s(14) - c(1)*s(25) + c(2)*s(16) )
            gout(n*9+1) = gout(n*9+1) + ( + c(1)*s(24) - c(2)*s(15) - c(1)*s(20) + c(2)*s(11) )
            gout(n*9+2) = gout(n*9+2) + ( + c(1)*s(19) - c(2)*s(10) - c(1)*s(21) + c(2)*s(12) )
            gout(n*9+3) = gout(n*9+3) + ( + c(2)*s(5) - c(0)*s(23) - c(2)*s(7) + c(0)*s(25) )
            gout(n*9+4) = gout(n*9+4) + ( + c(2)*s(6) - c(0)*s(24) - c(2)*s(2) + c(0)*s(20) )
            gout(n*9+5) = gout(n*9+5) + ( + c(2)*s(1) - c(0)*s(19) - c(2)*s(3) + c(0)*s(21) )
            gout(n*9+6) = gout(n*9+6) + ( + c(0)*s(14) - c(1)*s(5) - c(0)*s(16) + c(1)*s(7) )
            gout(n*9+7) = gout(n*9+7) + ( + c(0)*s(15) - c(1)*s(6) - c(0)*s(11) + c(1)*s(2) )
            gout(n*9+8) = gout(n*9+8) + ( + c(0)*s(10) - c(1)*s(1) - c(0)*s(12) + c(1)*s(3) )
         end if
      end do
   end subroutine CINTgout2e_int2e_ipvg1_xp1

   function int2e_ipvg1_xp1_cart(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      real(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), natm, nbas
      integer,  target        :: atm(0:), bas(0:)
      real(dp), target        :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [2, 1, 0, 0, 3, 1, 1, 9]

      call cint_init_int2e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout2e_int2e_ipvg1_xp1
      envs%common_factor = envs%common_factor * (0.5_dp)
      has_value = cint_2e_drv(out, dims, envs, ws, C2S_CART_2E1)
   end function int2e_ipvg1_xp1_cart

   function int2e_ipvg1_xp1_sph(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      real(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), natm, nbas
      integer,  target        :: atm(0:), bas(0:)
      real(dp), target        :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [2, 1, 0, 0, 3, 1, 1, 9]

      call cint_init_int2e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout2e_int2e_ipvg1_xp1
      envs%common_factor = envs%common_factor * (0.5_dp)
      has_value = cint_2e_drv(out, dims, envs, ws, C2S_SPH_2E1)
   end function int2e_ipvg1_xp1_sph

   function int2e_ipvg1_xp1_spinor(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      complex(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), natm, nbas
      integer,  target        :: atm(0:), bas(0:)
      real(dp), target        :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [2, 1, 0, 0, 3, 1, 1, 9]

      call cint_init_int2e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout2e_int2e_ipvg1_xp1
      envs%common_factor = envs%common_factor * (0.5_dp)
      has_value = cint_2e_spinor_drv(out, dims, envs, ws, .false., .false., .false., .false.)
   end function int2e_ipvg1_xp1_spinor

   ! (i j|NABLA-R12 CROSS P |G k l)
   subroutine int2e_ipvg2_xp1_optimizer(opt, atm, natm, bas, nbas, env)
      type(cint_opt_t), intent(inout) :: opt
      integer,  intent(in) :: natm, nbas
      integer,  intent(in) :: atm(0:), bas(0:)
      real(dp), intent(in) :: env(0:)
      integer, parameter :: ng(0:7) = [1, 1, 1, 0, 3, 1, 1, 9]
      call cint_all_2e_optimizer(opt, ng, atm, natm, bas, nbas, env)
   end subroutine int2e_ipvg2_xp1_optimizer

   subroutine CINTgout2e_int2e_ipvg2_xp1(gout, g, idx, envs, gout_empty)
      real(dp), intent(inout) :: gout(0:*)
      real(dp), intent(inout), target :: g(0:)
      integer,  intent(in)    :: idx(0:*)
      type(cint_env_vars), intent(in) :: envs
      integer,  intent(in)    :: gout_empty
      integer  :: nf, nroots, ix, iy, iz, i, n
      integer  :: g0, g1, g2, g3, g4, g5, g6, g7
      real(dp), pointer, contiguous :: g0p(:), g1p(:), g2p(:), g3p(:), g4p(:), g5p(:)
      real(dp), pointer, contiguous :: g6p(:), g7p(:)
      real(dp) :: s(0:26)
      real(dp) :: rkrl(0:2)
      real(dp) :: c(0:2)

      rkrl = envs%rk - envs%rl
      c(0) = 1.0_dp * rkrl(0)
      c(1) = 1.0_dp * rkrl(1)
      c(2) = 1.0_dp * rkrl(2)
      nf = envs%nf
      nroots = envs%nrys_roots
      g0 = 0
      g1 = g0 + envs%g_size * 3
      g2 = g1 + envs%g_size * 3
      g3 = g2 + envs%g_size * 3
      g4 = g3 + envs%g_size * 3
      g5 = g4 + envs%g_size * 3
      g6 = g5 + envs%g_size * 3
      g7 = g6 + envs%g_size * 3
      call cint_x1k_2e(g, g1, g0, envs%rk, envs%i_l+1, envs%j_l+1, envs%k_l+0, envs%l_l, envs)
      call cint_nabla1j_2e(g, g2, g0, envs%i_l+1, envs%j_l+0, envs%k_l, envs%l_l, envs)
      call cint_nabla1j_2e(g, g3, g1, envs%i_l+1, envs%j_l+0, envs%k_l, envs%l_l, envs)
      call cint_nabla1j_2e(g, g4, g0, envs%i_l+0, envs%j_l+1, envs%k_l, envs%l_l, envs)
      call cint_nabla1i_2e(g, g5, g0, envs%i_l+0, envs%j_l+1, envs%k_l, envs%l_l, envs)
      do ix = 0, envs%g_size*3 - 1
         g(g4+ix) = g(g4+ix) + g(g5+ix)
      end do
      call cint_nabla1j_2e(g, g5, g1, envs%i_l+0, envs%j_l+1, envs%k_l, envs%l_l, envs)
      call cint_nabla1i_2e(g, g6, g1, envs%i_l+0, envs%j_l+1, envs%k_l, envs%l_l, envs)
      do ix = 0, envs%g_size*3 - 1
         g(g5+ix) = g(g5+ix) + g(g6+ix)
      end do
      call cint_nabla1j_2e(g, g6, g4, envs%i_l+1, envs%j_l+0, envs%k_l, envs%l_l, envs)
      call cint_nabla1j_2e(g, g7, g5, envs%i_l+1, envs%j_l+0, envs%k_l, envs%l_l, envs)
      g0p(0:) => g(g0:)
      g1p(0:) => g(g1:)
      g2p(0:) => g(g2:)
      g3p(0:) => g(g3:)
      g4p(0:) => g(g4:)
      g5p(0:) => g(g5:)
      g6p(0:) => g(g6:)
      g7p(0:) => g(g7:)

      do n = 0, nf - 1
         ix = idx(0+n*3)
         iy = idx(1+n*3)
         iz = idx(2+n*3)
         s = 0.0_dp
         do i = 0, nroots - 1
               s(0) = s(0) + g7p(ix+i) * g0p(iy+i) * g0p(iz+i)
               s(1) = s(1) + g6p(ix+i) * g1p(iy+i) * g0p(iz+i)
               s(2) = s(2) + g6p(ix+i) * g0p(iy+i) * g1p(iz+i)
               s(3) = s(3) + g5p(ix+i) * g2p(iy+i) * g0p(iz+i)
               s(4) = s(4) + g4p(ix+i) * g3p(iy+i) * g0p(iz+i)
               s(5) = s(5) + g4p(ix+i) * g2p(iy+i) * g1p(iz+i)
               s(6) = s(6) + g5p(ix+i) * g0p(iy+i) * g2p(iz+i)
               s(7) = s(7) + g4p(ix+i) * g1p(iy+i) * g2p(iz+i)
               s(8) = s(8) + g4p(ix+i) * g0p(iy+i) * g3p(iz+i)
               s(9) = s(9) + g3p(ix+i) * g4p(iy+i) * g0p(iz+i)
               s(10) = s(10) + g2p(ix+i) * g5p(iy+i) * g0p(iz+i)
               s(11) = s(11) + g2p(ix+i) * g4p(iy+i) * g1p(iz+i)
               s(12) = s(12) + g1p(ix+i) * g6p(iy+i) * g0p(iz+i)
               s(13) = s(13) + g0p(ix+i) * g7p(iy+i) * g0p(iz+i)
               s(14) = s(14) + g0p(ix+i) * g6p(iy+i) * g1p(iz+i)
               s(15) = s(15) + g1p(ix+i) * g4p(iy+i) * g2p(iz+i)
               s(16) = s(16) + g0p(ix+i) * g5p(iy+i) * g2p(iz+i)
               s(17) = s(17) + g0p(ix+i) * g4p(iy+i) * g3p(iz+i)
               s(18) = s(18) + g3p(ix+i) * g0p(iy+i) * g4p(iz+i)
               s(19) = s(19) + g2p(ix+i) * g1p(iy+i) * g4p(iz+i)
               s(20) = s(20) + g2p(ix+i) * g0p(iy+i) * g5p(iz+i)
               s(21) = s(21) + g1p(ix+i) * g2p(iy+i) * g4p(iz+i)
               s(22) = s(22) + g0p(ix+i) * g3p(iy+i) * g4p(iz+i)
               s(23) = s(23) + g0p(ix+i) * g2p(iy+i) * g5p(iz+i)
               s(24) = s(24) + g1p(ix+i) * g0p(iy+i) * g6p(iz+i)
               s(25) = s(25) + g0p(ix+i) * g1p(iy+i) * g6p(iz+i)
               s(26) = s(26) + g0p(ix+i) * g0p(iy+i) * g7p(iz+i)
         end do
         if (gout_empty /= 0) then
            gout(n*9+0) = - c(1)*s(17) + c(1)*s(23) + c(2)*s(16) - c(2)*s(22)
            gout(n*9+1) = - c(2)*s(15) + c(2)*s(21) + c(0)*s(17) - c(0)*s(23)
            gout(n*9+2) = - c(0)*s(16) + c(0)*s(22) + c(1)*s(15) - c(1)*s(21)
            gout(n*9+3) = - c(1)*s(20) + c(1)*s(8) + c(2)*s(19) - c(2)*s(7)
            gout(n*9+4) = - c(2)*s(18) + c(2)*s(6) + c(0)*s(20) - c(0)*s(8)
            gout(n*9+5) = - c(0)*s(19) + c(0)*s(7) + c(1)*s(18) - c(1)*s(6)
            gout(n*9+6) = - c(1)*s(5) + c(1)*s(11) + c(2)*s(4) - c(2)*s(10)
            gout(n*9+7) = - c(2)*s(3) + c(2)*s(9) + c(0)*s(5) - c(0)*s(11)
            gout(n*9+8) = - c(0)*s(4) + c(0)*s(10) + c(1)*s(3) - c(1)*s(9)
         else
            gout(n*9+0) = gout(n*9+0) + ( - c(1)*s(17) + c(1)*s(23) + c(2)*s(16) - c(2)*s(22) )
            gout(n*9+1) = gout(n*9+1) + ( - c(2)*s(15) + c(2)*s(21) + c(0)*s(17) - c(0)*s(23) )
            gout(n*9+2) = gout(n*9+2) + ( - c(0)*s(16) + c(0)*s(22) + c(1)*s(15) - c(1)*s(21) )
            gout(n*9+3) = gout(n*9+3) + ( - c(1)*s(20) + c(1)*s(8) + c(2)*s(19) - c(2)*s(7) )
            gout(n*9+4) = gout(n*9+4) + ( - c(2)*s(18) + c(2)*s(6) + c(0)*s(20) - c(0)*s(8) )
            gout(n*9+5) = gout(n*9+5) + ( - c(0)*s(19) + c(0)*s(7) + c(1)*s(18) - c(1)*s(6) )
            gout(n*9+6) = gout(n*9+6) + ( - c(1)*s(5) + c(1)*s(11) + c(2)*s(4) - c(2)*s(10) )
            gout(n*9+7) = gout(n*9+7) + ( - c(2)*s(3) + c(2)*s(9) + c(0)*s(5) - c(0)*s(11) )
            gout(n*9+8) = gout(n*9+8) + ( - c(0)*s(4) + c(0)*s(10) + c(1)*s(3) - c(1)*s(9) )
         end if
      end do
   end subroutine CINTgout2e_int2e_ipvg2_xp1

   function int2e_ipvg2_xp1_cart(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      real(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), natm, nbas
      integer,  target        :: atm(0:), bas(0:)
      real(dp), target        :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [1, 1, 1, 0, 3, 1, 1, 9]

      call cint_init_int2e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout2e_int2e_ipvg2_xp1
      envs%common_factor = envs%common_factor * (0.5_dp)
      has_value = cint_2e_drv(out, dims, envs, ws, C2S_CART_2E1)
   end function int2e_ipvg2_xp1_cart

   function int2e_ipvg2_xp1_sph(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      real(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), natm, nbas
      integer,  target        :: atm(0:), bas(0:)
      real(dp), target        :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [1, 1, 1, 0, 3, 1, 1, 9]

      call cint_init_int2e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout2e_int2e_ipvg2_xp1
      envs%common_factor = envs%common_factor * (0.5_dp)
      has_value = cint_2e_drv(out, dims, envs, ws, C2S_SPH_2E1)
   end function int2e_ipvg2_xp1_sph

   function int2e_ipvg2_xp1_spinor(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      complex(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), natm, nbas
      integer,  target        :: atm(0:), bas(0:)
      real(dp), target        :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [1, 1, 1, 0, 3, 1, 1, 9]

      call cint_init_int2e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout2e_int2e_ipvg2_xp1
      envs%common_factor = envs%common_factor * (0.5_dp)
      has_value = cint_2e_spinor_drv(out, dims, envs, ws, .false., .true., .false., .true.)
   end function int2e_ipvg2_xp1_spinor

   ! <i|NUC |RC CROSS P j>
   subroutine int1e_inuc_rcxp_optimizer(opt, atm, natm, bas, nbas, env)
      type(cint_opt_t), intent(inout) :: opt
      integer,  intent(in) :: natm, nbas
      integer,  intent(in) :: atm(0:), bas(0:)
      real(dp), intent(in) :: env(0:)
      integer, parameter :: ng(0:7) = [0, 2, 0, 0, 2, 1, 0, 3]
      call cint_all_1e_optimizer(opt, ng, atm, natm, bas, nbas, env)
   end subroutine int1e_inuc_rcxp_optimizer

   subroutine CINTgout1e_int1e_inuc_rcxp(gout, g, idx, envs, gout_empty)
      real(dp), intent(inout) :: gout(0:*)
      real(dp), intent(inout), target :: g(0:)
      integer,  intent(in)    :: idx(0:*)
      type(cint_env_vars), intent(in) :: envs
      integer,  intent(in)    :: gout_empty
      integer  :: nf, nroots, ix, iy, iz, i, n
      integer  :: g0, g1, g2, g3
      real(dp), pointer, contiguous :: g0p(:), g1p(:), g2p(:), g3p(:)
      real(dp) :: s(0:8)
      real(dp) :: drj(0:2)

      drj = envs%rj - envs%env(PTR_COMMON_ORIG:PTR_COMMON_ORIG+2)
      nf = envs%nf
      nroots = envs%nrys_roots
      g0 = 0
      g1 = g0 + envs%g_size * 3
      g2 = g1 + envs%g_size * 3
      g3 = g2 + envs%g_size * 3
      call cint_nabla1j_2e(g, g1, g0, envs%i_l+0, envs%j_l+0, 0, 0, envs)
      call cint_x1j_2e(g, g2, g0, drj, envs%i_l+0, envs%j_l+1, 0, 0, envs)
      call cint_nabla1j_2e(g, g3, g2, envs%i_l+0, envs%j_l+0, 0, 0, envs)
      g0p(0:) => g(g0:)
      g1p(0:) => g(g1:)
      g2p(0:) => g(g2:)
      g3p(0:) => g(g3:)

      do n = 0, nf - 1
         ix = idx(0+n*3)
         iy = idx(1+n*3)
         iz = idx(2+n*3)
         s = 0.0_dp
         do i = 0, nroots - 1
               s(0) = s(0) + g3p(ix+i) * g0p(iy+i) * g0p(iz+i)
               s(1) = s(1) + g2p(ix+i) * g1p(iy+i) * g0p(iz+i)
               s(2) = s(2) + g2p(ix+i) * g0p(iy+i) * g1p(iz+i)
               s(3) = s(3) + g1p(ix+i) * g2p(iy+i) * g0p(iz+i)
               s(4) = s(4) + g0p(ix+i) * g3p(iy+i) * g0p(iz+i)
               s(5) = s(5) + g0p(ix+i) * g2p(iy+i) * g1p(iz+i)
               s(6) = s(6) + g1p(ix+i) * g0p(iy+i) * g2p(iz+i)
               s(7) = s(7) + g0p(ix+i) * g1p(iy+i) * g2p(iz+i)
               s(8) = s(8) + g0p(ix+i) * g0p(iy+i) * g3p(iz+i)
         end do
         if (gout_empty /= 0) then
            gout(n*3+0) = + s(5) - s(7)
            gout(n*3+1) = + s(6) - s(2)
            gout(n*3+2) = + s(1) - s(3)
         else
            gout(n*3+0) = gout(n*3+0) + ( + s(5) - s(7) )
            gout(n*3+1) = gout(n*3+1) + ( + s(6) - s(2) )
            gout(n*3+2) = gout(n*3+2) + ( + s(1) - s(3) )
         end if
      end do
   end subroutine CINTgout1e_int1e_inuc_rcxp

   function int1e_inuc_rcxp_cart(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      real(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), atm(0:), bas(0:)
      integer,  intent(in)    :: natm, nbas
      real(dp), intent(in)    :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [0, 2, 0, 0, 2, 1, 0, 3]

      call cint_init_int1e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout1e_int1e_inuc_rcxp
      has_value = cint_1e_drv(out, dims, envs, ws, C2S_CART_1E, 2)
   end function int1e_inuc_rcxp_cart

   function int1e_inuc_rcxp_sph(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      real(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), atm(0:), bas(0:)
      integer,  intent(in)    :: natm, nbas
      real(dp), intent(in)    :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [0, 2, 0, 0, 2, 1, 0, 3]

      call cint_init_int1e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout1e_int1e_inuc_rcxp
      has_value = cint_1e_drv(out, dims, envs, ws, C2S_SPH_1E, 2)
   end function int1e_inuc_rcxp_sph

   function int1e_inuc_rcxp_spinor(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      complex(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), natm, nbas
      integer,  target        :: atm(0:), bas(0:)
      real(dp), target        :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [0, 2, 0, 0, 2, 1, 0, 3]

      call cint_init_int1e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout1e_int1e_inuc_rcxp
      has_value = cint_1e_spinor_drv(out, dims, envs, ws, .false., .false., 2)
   end function int1e_inuc_rcxp_spinor

   ! <i|NUC |R CROSS P j>
   subroutine int1e_inuc_rxp_optimizer(opt, atm, natm, bas, nbas, env)
      type(cint_opt_t), intent(inout) :: opt
      integer,  intent(in) :: natm, nbas
      integer,  intent(in) :: atm(0:), bas(0:)
      real(dp), intent(in) :: env(0:)
      integer, parameter :: ng(0:7) = [0, 2, 0, 0, 2, 1, 0, 3]
      call cint_all_1e_optimizer(opt, ng, atm, natm, bas, nbas, env)
   end subroutine int1e_inuc_rxp_optimizer

   subroutine CINTgout1e_int1e_inuc_rxp(gout, g, idx, envs, gout_empty)
      real(dp), intent(inout) :: gout(0:*)
      real(dp), intent(inout), target :: g(0:)
      integer,  intent(in)    :: idx(0:*)
      type(cint_env_vars), intent(in) :: envs
      integer,  intent(in)    :: gout_empty
      integer  :: nf, nroots, ix, iy, iz, i, n
      integer  :: g0, g1, g2, g3
      real(dp), pointer, contiguous :: g0p(:), g1p(:), g2p(:), g3p(:)
      real(dp) :: s(0:8)

      nf = envs%nf
      nroots = envs%nrys_roots
      g0 = 0
      g1 = g0 + envs%g_size * 3
      g2 = g1 + envs%g_size * 3
      g3 = g2 + envs%g_size * 3
      call cint_nabla1j_2e(g, g1, g0, envs%i_l+0, envs%j_l+0, 0, 0, envs)
      g2 = g0 + envs%g_stride_j
      call cint_nabla1j_2e(g, g3, g2, envs%i_l+0, envs%j_l+0, 0, 0, envs)
      g0p(0:) => g(g0:)
      g1p(0:) => g(g1:)
      g2p(0:) => g(g2:)
      g3p(0:) => g(g3:)

      do n = 0, nf - 1
         ix = idx(0+n*3)
         iy = idx(1+n*3)
         iz = idx(2+n*3)
         s = 0.0_dp
         do i = 0, nroots - 1
               s(0) = s(0) + g3p(ix+i) * g0p(iy+i) * g0p(iz+i)
               s(1) = s(1) + g2p(ix+i) * g1p(iy+i) * g0p(iz+i)
               s(2) = s(2) + g2p(ix+i) * g0p(iy+i) * g1p(iz+i)
               s(3) = s(3) + g1p(ix+i) * g2p(iy+i) * g0p(iz+i)
               s(4) = s(4) + g0p(ix+i) * g3p(iy+i) * g0p(iz+i)
               s(5) = s(5) + g0p(ix+i) * g2p(iy+i) * g1p(iz+i)
               s(6) = s(6) + g1p(ix+i) * g0p(iy+i) * g2p(iz+i)
               s(7) = s(7) + g0p(ix+i) * g1p(iy+i) * g2p(iz+i)
               s(8) = s(8) + g0p(ix+i) * g0p(iy+i) * g3p(iz+i)
         end do
         if (gout_empty /= 0) then
            gout(n*3+0) = + s(5) - s(7)
            gout(n*3+1) = + s(6) - s(2)
            gout(n*3+2) = + s(1) - s(3)
         else
            gout(n*3+0) = gout(n*3+0) + ( + s(5) - s(7) )
            gout(n*3+1) = gout(n*3+1) + ( + s(6) - s(2) )
            gout(n*3+2) = gout(n*3+2) + ( + s(1) - s(3) )
         end if
      end do
   end subroutine CINTgout1e_int1e_inuc_rxp

   function int1e_inuc_rxp_cart(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      real(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), atm(0:), bas(0:)
      integer,  intent(in)    :: natm, nbas
      real(dp), intent(in)    :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [0, 2, 0, 0, 2, 1, 0, 3]

      call cint_init_int1e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout1e_int1e_inuc_rxp
      has_value = cint_1e_drv(out, dims, envs, ws, C2S_CART_1E, 2)
   end function int1e_inuc_rxp_cart

   function int1e_inuc_rxp_sph(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      real(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), atm(0:), bas(0:)
      integer,  intent(in)    :: natm, nbas
      real(dp), intent(in)    :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [0, 2, 0, 0, 2, 1, 0, 3]

      call cint_init_int1e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout1e_int1e_inuc_rxp
      has_value = cint_1e_drv(out, dims, envs, ws, C2S_SPH_1E, 2)
   end function int1e_inuc_rxp_sph

   function int1e_inuc_rxp_spinor(out, dims, shls, atm, natm, bas, nbas, env, ws) &
         result(has_value)
      complex(dp), intent(inout) :: out(0:)
      integer,  intent(in)    :: dims(0:), shls(0:), natm, nbas
      integer,  target        :: atm(0:), bas(0:)
      real(dp), target        :: env(0:)
      type(cint_ws), intent(inout) :: ws
      logical :: has_value
      type(cint_env_vars) :: envs
      integer, parameter :: ng(0:7) = [0, 2, 0, 0, 2, 1, 0, 3]

      call cint_init_int1e_envvars(envs, ng, shls, atm, natm, bas, nbas, env)
      envs%f_gout => CINTgout1e_int1e_inuc_rxp
      has_value = cint_1e_spinor_drv(out, dims, envs, ws, .false., .false., 2)
   end function int1e_inuc_rxp_spinor

end module cint_gen_intor2
